In [ ]:

from pathlib import Path
import pandas as pd

from adaptive_reward_checkpoint_fresh import (
    build_adaptive_reward_snapshot,
    run_adaptive_reward_from_snapshot,
)
from adaptive_trade_extensions import RollingThresholdConfig, make_threshold_grid

snapshot_path = Path("checkpoints") / "QQQ_adaptive_reward_fresh_start_252days_at_2020.joblib"

common_kwargs = dict(
    daily_csv_path="DataAPI/data/QQQ_day.csv",
    k5m_csv_path="DataAPI/data/QQQ_5M.csv",
    code="QQQ",
    daily_chan_start="2010-02-11",
    accumulation_start="2012-02-11",
    N_confirm=5,
    min_labeled_days_to_train=200,
    retrain_every_new_labels=25,
    dp_lookback=5,
    lookahead_days_5m=2.0,
    retrain_every_days_5m=5,
    min_samples_total_5m=300,
    threshold_window_days=2.0,
    threshold_ret_grid=None,
    threshold_min_open_signals=10,
    initial_capital=100000.0,
    fee_pct=0.0,
    daily_chan_max_klines=500,
    five_chan_max_klines=500,
    macro_files={
        "vix_": "VIX.csv",
    },
    static_buy_level=0.20,
    static_sell_level=0.30,
    daily_threshold_config=RollingThresholdConfig(
        lookback_days=252,
        buy_grid=make_threshold_grid(0.05, 0.35, 0.005),
        sell_grid=make_threshold_grid(0.15, 0.60, 0.005),
        min_gap=0.02,
        min_obs=60,
        switch_penalty=0.0,
    ),
    verbose=True,
)

snapshot_res = build_adaptive_reward_snapshot(
    snapshot_path=str(snapshot_path),
    snapshot_end_time="2019-12-31",
    output_dir="output_adaptive_reward_snapshot_build_QQQ_252days_at_2020",
    **common_kwargs,
)

print(snapshot_res["snapshot_path"])
display(snapshot_res["daily_reward_df"].tail())
display(snapshot_res["daily_log_df"].tail())

resume_res = run_adaptive_reward_from_snapshot(
    #dp_lookback_override=5,
    snapshot_path=str(snapshot_path),
    end_time="2026-12-31",
    sim_start="2020-01-01",
    initial_capital=100000.0,
    fee_pct=0.0,
    output_dir="output_adaptive_reward_resumed_fresh_QQQ_252days_at_2020",
    # Optional. If omitted, the code saves next to the source snapshot as
    # checkpoints/QQQ_adaptive_reward_fresh_start__continued.joblib
    #save_snapshot_path="output_adaptive_reward_resumed_fresh_QQQ_252days_at_2020/final_checkpoint.joblib",
    autosave_year_start_checkpoints=True,
    verbose=True,
)

print("continued snapshot:", resume_res["continued_snapshot_path"])

display(resume_res["daily_reward_df"].tail())
display(resume_res["daily_log_df"].tail())
display(resume_res["trades_df"].head())

[TRAIN][DAILY-PROB] n=200 pos=42 (21.00%)
[TRAIN][DAILY-PROB] n=225 pos=50 (22.22%)
[TRAIN][DAILY-PROB] n=250 pos=55 (22.00%)
[TRAIN][DAILY-PROB] n=275 pos=59 (21.45%)
[TRAIN][DAILY-PROB] n=300 pos=69 (23.00%)
[TRAIN][DAILY-PROB] n=325 pos=69 (21.23%)
[TRAIN][DAILY-PROB] n=350 pos=69 (19.71%)
[TRAIN][DAILY-PROB] n=375 pos=72 (19.20%)
[TRAIN][DAILY-PROB] n=400 pos=81 (20.25%)
[TRAIN][DAILY-PROB] n=425 pos=91 (21.41%)
[TRAIN][DAILY-PROB] n=450 pos=100 (22.22%)
[TRAIN][DAILY-PROB] n=475 pos=103 (21.68%)
[TRAIN][DAILY-PROB] n=500 pos=106 (21.20%)
[TRAIN][DAILY-PROB] n=525 pos=115 (21.90%)
[TRAIN][DAILY-PROB] n=550 pos=121 (22.00%)
[TRAIN][DAILY-PROB] n=575 pos=125 (21.74%)
[TRAIN][DAILY-PROB] n=600 pos=132 (22.00%)
[TRAIN][DAILY-PROB] n=625 pos=137 (21.92%)
[TRAIN][DAILY-PROB] n=650 pos=147 (22.62%)
[TRAIN][DAILY-PROB] n=675 pos=152 (22.52%)
[TRAIN][DAILY-PROB] n=700 pos=157 (22.43%)
[TRAIN][DAILY-PROB] n=725 pos=161 (22.21%)
[TRAIN][DAILY-PROB] n=750 pos=167 (22.27%)
[TRAIN][DAILY-PROB] n=775 pos=168 (21.68%)
[TRAIN][DAILY-PROB] n=800 pos=171 (21.38%)
[TRAIN][DAILY-PROB] n=825 pos=174 (21.09%)
[TRAIN][DAILY-PROB] n=850 pos=177 (20.82%)
[TRAIN][DAILY-PROB] n=875 pos=185 (21.14%)
[TRAIN][DAILY-PROB] n=900 pos=189 (21.00%)
[TRAIN][DAILY-PROB] n=925 pos=190 (20.54%)
[TRAIN][DAILY-PROB] n=950 pos=190 (20.00%)
[TRAIN][DAILY-PROB] n=975 pos=193 (19.79%)
[TRAIN][DAILY-PROB] n=1000 pos=199 (19.90%)
[TRAIN][DAILY-PROB] n=1025 pos=203 (19.80%)
[TRAIN][DAILY-PROB] n=1050 pos=209 (19.90%)
[TRAIN][DAILY-PROB] n=1075 pos=216 (20.09%)
[TRAIN][DAILY-PROB] n=1100 pos=218 (19.82%)
[TRAIN][DAILY-PROB] n=1125 pos=227 (20.18%)
[TRAIN][DAILY-PROB] n=1150 pos=233 (20.26%)
[TRAIN][DAILY-PROB] n=1175 pos=237 (20.17%)
[TRAIN][DAILY-PROB] n=1200 pos=247 (20.58%)
[TRAIN][DAILY-PROB] n=1225 pos=254 (20.73%)
[TRAIN][DAILY-PROB] n=1250 pos=264 (21.12%)
[TRAIN][DAILY-PROB] n=1275 pos=271 (21.25%)
[TRAIN][DAILY-PROB] n=1300 pos=280 (21.54%)
[TRAIN][DAILY-PROB] n=1325 pos=285 (21.51%)
[TRAIN][DAILY-PROB] n=1350 pos=293 (21.70%)
[TRAIN][DAILY-PROB] n=1375 pos=302 (21.96%)
[TRAIN][DAILY-PROB] n=1400 pos=304 (21.71%)
[TRAIN][DAILY-PROB] n=1425 pos=311 (21.82%)
[TRAIN][DAILY-PROB] n=1450 pos=318 (21.93%)
[TRAIN][DAILY-PROB] n=1475 pos=319 (21.63%)
[TRAIN][DAILY-PROB] n=1500 pos=329 (21.93%)
[TRAIN][DAILY-PROB] n=1525 pos=336 (22.03%)
[TRAIN][DAILY-PROB] n=1550 pos=339 (21.87%)
[TRAIN][DAILY-PROB] n=1575 pos=342 (21.71%)
[TRAIN][DAILY-PROB] n=1600 pos=343 (21.44%)
[TRAIN][DAILY-PROB] n=1625 pos=346 (21.29%)
[TRAIN][DAILY-PROB] n=1650 pos=348 (21.09%)
[TRAIN][DAILY-PROB] n=1675 pos=349 (20.84%)
[TRAIN][DAILY-PROB] n=1700 pos=355 (20.88%)
[TRAIN][DAILY-PROB] n=1725 pos=359 (20.81%)
[TRAIN][DAILY-PROB] n=1750 pos=366 (20.91%)
[TRAIN][DAILY-PROB] n=1775 pos=367 (20.68%)
[TRAIN][DAILY-PROB] n=1800 pos=370 (20.56%)
[TRAIN][DAILY-PROB] n=1825 pos=374 (20.49%)
[TRAIN][DAILY-PROB] n=1850 pos=381 (20.59%)
[TRAIN][DAILY-PROB] n=1875 pos=390 (20.80%)
[TRAIN][DAILY-PROB] n=1900 pos=395 (20.79%)
[TRAIN][DAILY-PROB] n=1925 pos=396 (20.57%)
[TRAIN][DAILY-PROB] n=1950 pos=401 (20.56%)
[TRAIN][DAILY-PROB] n=1975 pos=406 (20.56%)
[TRAIN][DAILY-PROB] n=2000 pos=410 (20.50%)
[TRAIN][DAILY-PROB] n=2025 pos=423 (20.89%)
[TRAIN][DAILY-PROB] n=2050 pos=437 (21.32%)
[TRAIN][DAILY-PROB] n=2075 pos=445 (21.45%)
[TRAIN][DAILY-PROB] n=2100 pos=446 (21.24%)
[TRAIN][DAILY-PROB] n=2125 pos=449 (21.13%)
[TRAIN][DAILY-PROB] n=2150 pos=454 (21.12%)
[TRAIN][DAILY-PROB] n=2175 pos=465 (21.38%)
[TRAIN][DAILY-PROB] n=2200 pos=467 (21.23%)
[TRAIN][DAILY-PROB] n=2225 pos=475 (21.35%)
[TRAIN][DAILY-PROB] n=2250 pos=479 (21.29%)
[TRAIN][DAILY-PROB] n=2275 pos=486 (21.36%)
[TRAIN][DAILY-PROB] n=2300 pos=488 (21.22%)
[TRAIN][5M] asof=2012-03-07 feats=114 buy=NO sell=YES rows=550
[TRAIN][5M] asof=2012-03-12 feats=114 buy=NO sell=YES rows=640
[TRAIN][5M] asof=2012-03-19 feats=114 buy=NO sell=YES rows=750
[TRAIN][5M] asof=2012-03-26 feats=114 buy=NO sell=YES rows=938
[TRAIN][5M] asof=2012-04-02 feats=114 buy=NO sell=YES rows=1055
[TRAIN][5M] asof=2012-04-09 feats=114 buy=YES sell=YES rows=1155
[TRAIN][5M] asof=2012-04-16 feats=114 buy=YES sell=YES rows=1298
[TRAIN][5M] asof=2012-04-23 feats=114 buy=YES sell=YES rows=1439
[TRAIN][5M] asof=2012-04-30 feats=114 buy=YES sell=YES rows=1607
[TRAIN][5M] asof=2012-05-07 feats=114 buy=YES sell=YES rows=1777
[TRAIN][5M] asof=2012-05-14 feats=114 buy=YES sell=YES rows=1977
[TRAIN][5M] asof=2012-05-21 feats=114 buy=YES sell=YES rows=2124
[TRAIN][5M] asof=2012-05-29 feats=114 buy=YES sell=YES rows=2294
[TRAIN][5M] asof=2012-06-04 feats=114 buy=YES sell=YES rows=2378
[TRAIN][5M] asof=2012-06-11 feats=114 buy=YES sell=YES rows=2550
[TRAIN][5M] asof=2012-06-18 feats=114 buy=YES sell=YES rows=2680
[TRAIN][5M] asof=2012-06-25 feats=114 buy=YES sell=YES rows=2799
[TRAIN][5M] asof=2012-07-02 feats=114 buy=YES sell=YES rows=2915
[TRAIN][5M] asof=2012-07-09 feats=114 buy=YES sell=YES rows=3012
[TRAIN][5M] asof=2012-07-16 feats=114 buy=YES sell=YES rows=3122
[TRAIN][5M] asof=2012-07-23 feats=114 buy=YES sell=YES rows=3260
[TRAIN][5M] asof=2012-07-30 feats=114 buy=YES sell=YES rows=3379
[TRAIN][5M] asof=2012-08-06 feats=114 buy=YES sell=YES rows=3541
[TRAIN][5M] asof=2012-08-13 feats=114 buy=YES sell=YES rows=3660
[TRAIN][5M] asof=2012-08-20 feats=114 buy=YES sell=YES rows=3807
[TRAIN][5M] asof=2012-08-27 feats=114 buy=YES sell=YES rows=3990
[TRAIN][5M] asof=2012-09-04 feats=114 buy=YES sell=YES rows=4130
[TRAIN][5M] asof=2012-09-10 feats=114 buy=YES sell=YES rows=4253
[TRAIN][5M] asof=2012-09-17 feats=114 buy=YES sell=YES rows=4409
[TRAIN][5M] asof=2012-09-24 feats=114 buy=YES sell=YES rows=4524
[TRAIN][5M] asof=2012-10-01 feats=114 buy=YES sell=YES rows=4666
[TRAIN][5M] asof=2012-10-08 feats=114 buy=YES sell=YES rows=4837
[TRAIN][5M] asof=2012-10-15 feats=114 buy=YES sell=YES rows=5010
[TRAIN][5M] asof=2012-10-22 feats=114 buy=YES sell=YES rows=5111
[TRAIN][5M] asof=2012-10-31 feats=114 buy=YES sell=YES rows=5258
[TRAIN][5M] asof=2012-11-05 feats=114 buy=YES sell=YES rows=5347
[TRAIN][5M] asof=2012-11-12 feats=114 buy=YES sell=YES rows=5512
[TRAIN][5M] asof=2012-11-19 feats=114 buy=YES sell=YES rows=5638
[TRAIN][5M] asof=2012-11-26 feats=114 buy=YES sell=YES rows=5753
[TRAIN][5M] asof=2012-12-03 feats=114 buy=YES sell=YES rows=5886
[TRAIN][5M] asof=2012-12-10 feats=114 buy=YES sell=YES rows=6029
[TRAIN][5M] asof=2012-12-17 feats=114 buy=YES sell=YES rows=6151
[TRAIN][5M] asof=2012-12-24 feats=114 buy=YES sell=YES rows=6255
[TRAIN][5M] asof=2012-12-31 feats=114 buy=YES sell=YES rows=6330
[TRAIN][5M] asof=2013-01-07 feats=114 buy=YES sell=YES rows=6413
[TRAIN][5M] asof=2013-01-14 feats=114 buy=YES sell=YES rows=6525
[TRAIN][5M] asof=2013-01-22 feats=114 buy=YES sell=YES rows=6632
[TRAIN][5M] asof=2013-01-28 feats=114 buy=YES sell=YES rows=6782
[TRAIN][5M] asof=2013-02-04 feats=114 buy=YES sell=YES rows=6946
[TRAIN][5M] asof=2013-02-11 feats=114 buy=YES sell=YES rows=7098
[TRAIN][5M] asof=2013-02-19 feats=114 buy=YES sell=YES rows=7255
[TRAIN][5M] asof=2013-02-25 feats=114 buy=YES sell=YES rows=7393
[TRAIN][5M] asof=2013-03-04 feats=114 buy=YES sell=YES rows=7536
[TRAIN][5M] asof=2013-03-11 feats=114 buy=YES sell=YES rows=7693
[TRAIN][5M] asof=2013-03-18 feats=114 buy=YES sell=YES rows=7817
[TRAIN][5M] asof=2013-03-25 feats=114 buy=YES sell=YES rows=7933
[TRAIN][5M] asof=2013-04-01 feats=114 buy=YES sell=YES rows=8067
[TRAIN][5M] asof=2013-04-08 feats=114 buy=YES sell=YES rows=8144
[TRAIN][5M] asof=2013-04-15 feats=114 buy=YES sell=YES rows=8261
[TRAIN][5M] asof=2013-04-22 feats=114 buy=YES sell=YES rows=8385
[TRAIN][5M] asof=2013-04-29 feats=114 buy=YES sell=YES rows=8465
[TRAIN][5M] asof=2013-05-06 feats=114 buy=YES sell=YES rows=8601
[TRAIN][5M] asof=2013-05-13 feats=114 buy=YES sell=YES rows=8737
[TRAIN][5M] asof=2013-05-20 feats=114 buy=YES sell=YES rows=8865
[TRAIN][5M] asof=2013-05-28 feats=114 buy=YES sell=YES rows=9020
[TRAIN][5M] asof=2013-06-03 feats=114 buy=YES sell=YES rows=9181
[TRAIN][5M] asof=2013-06-10 feats=114 buy=YES sell=YES rows=9300
[TRAIN][5M] asof=2013-06-17 feats=114 buy=YES sell=YES rows=9437
[TRAIN][5M] asof=2013-06-24 feats=114 buy=YES sell=YES rows=9617
[TRAIN][5M] asof=2013-07-01 feats=114 buy=YES sell=YES rows=9791
[TRAIN][5M] asof=2013-07-08 feats=114 buy=YES sell=YES rows=9875
[TRAIN][5M] asof=2013-07-15 feats=114 buy=YES sell=YES rows=10015
[TRAIN][5M] asof=2013-07-22 feats=114 buy=YES sell=YES rows=10134
[TRAIN][5M] asof=2013-07-29 feats=114 buy=YES sell=YES rows=10303
[TRAIN][5M] asof=2013-08-05 feats=114 buy=YES sell=YES rows=10440
[TRAIN][5M] asof=2013-08-12 feats=114 buy=YES sell=YES rows=10585
[TRAIN][5M] asof=2013-08-19 feats=114 buy=YES sell=YES rows=10810
[TRAIN][5M] asof=2013-08-26 feats=114 buy=YES sell=YES rows=10936
[TRAIN][5M] asof=2013-09-03 feats=114 buy=YES sell=YES rows=11112
[TRAIN][5M] asof=2013-09-09 feats=114 buy=YES sell=YES rows=11246
[TRAIN][5M] asof=2013-09-16 feats=114 buy=YES sell=YES rows=11433
[TRAIN][5M] asof=2013-09-23 feats=114 buy=YES sell=YES rows=11548
[TRAIN][5M] asof=2013-09-30 feats=114 buy=YES sell=YES rows=11749
[TRAIN][5M] asof=2013-10-07 feats=114 buy=YES sell=YES rows=11885
[TRAIN][5M] asof=2013-10-14 feats=114 buy=YES sell=YES rows=12075
[TRAIN][5M] asof=2013-10-21 feats=114 buy=YES sell=YES rows=12237
[TRAIN][5M] asof=2013-10-28 feats=114 buy=YES sell=YES rows=12373
[TRAIN][5M] asof=2013-11-04 feats=114 buy=YES sell=YES rows=12575
[TRAIN][5M] asof=2013-11-11 feats=114 buy=YES sell=YES rows=12752
[TRAIN][5M] asof=2013-11-18 feats=114 buy=YES sell=YES rows=12888
[TRAIN][5M] asof=2013-11-25 feats=114 buy=YES sell=YES rows=13047
[TRAIN][5M] asof=2013-12-02 feats=114 buy=YES sell=YES rows=13146
[TRAIN][5M] asof=2013-12-09 feats=114 buy=YES sell=YES rows=13322
[TRAIN][5M] asof=2013-12-16 feats=114 buy=YES sell=YES rows=13502
[TRAIN][5M] asof=2013-12-23 feats=114 buy=YES sell=YES rows=13707
[TRAIN][5M] asof=2013-12-30 feats=114 buy=YES sell=YES rows=13833
[TRAIN][5M] asof=2014-01-06 feats=114 buy=YES sell=YES rows=13924
[TRAIN][5M] asof=2014-01-13 feats=114 buy=YES sell=YES rows=14034
[TRAIN][5M] asof=2014-01-21 feats=114 buy=YES sell=YES rows=14173
[TRAIN][5M] asof=2014-01-27 feats=114 buy=YES sell=YES rows=14310
[TRAIN][5M] asof=2014-02-03 feats=114 buy=YES sell=YES rows=14487
[TRAIN][5M] asof=2014-02-10 feats=114 buy=YES sell=YES rows=14614
[TRAIN][5M] asof=2014-02-18 feats=114 buy=YES sell=YES rows=14792
[TRAIN][5M] asof=2014-02-24 feats=114 buy=YES sell=YES rows=14894
[TRAIN][5M] asof=2014-03-03 feats=114 buy=YES sell=YES rows=15078
[TRAIN][5M] asof=2014-03-10 feats=114 buy=YES sell=YES rows=15193
[TRAIN][5M] asof=2014-03-17 feats=114 buy=YES sell=YES rows=15359
[TRAIN][5M] asof=2014-03-24 feats=114 buy=YES sell=YES rows=15514
[TRAIN][5M] asof=2014-03-31 feats=114 buy=YES sell=YES rows=15666
[TRAIN][5M] asof=2014-04-07 feats=114 buy=YES sell=YES rows=15807
[TRAIN][5M] asof=2014-04-14 feats=114 buy=YES sell=YES rows=15992
[TRAIN][5M] asof=2014-04-21 feats=114 buy=YES sell=YES rows=16153
[TRAIN][5M] asof=2014-04-28 feats=114 buy=YES sell=YES rows=16333
[TRAIN][5M] asof=2014-05-05 feats=114 buy=YES sell=YES rows=16473
[TRAIN][5M] asof=2014-05-12 feats=114 buy=YES sell=YES rows=16685
[TRAIN][5M] asof=2014-05-19 feats=114 buy=YES sell=YES rows=16831
[TRAIN][5M] asof=2014-05-27 feats=114 buy=YES sell=YES rows=16980
[TRAIN][5M] asof=2014-06-02 feats=114 buy=YES sell=YES rows=17069
[TRAIN][5M] asof=2014-06-09 feats=114 buy=YES sell=YES rows=17228
[TRAIN][5M] asof=2014-06-16 feats=114 buy=YES sell=YES rows=17377
[TRAIN][5M] asof=2014-06-23 feats=114 buy=YES sell=YES rows=17465
[TRAIN][5M] asof=2014-06-30 feats=114 buy=YES sell=YES rows=17587
[TRAIN][5M] asof=2014-07-07 feats=114 buy=YES sell=YES rows=17687
[TRAIN][5M] asof=2014-07-14 feats=114 buy=YES sell=YES rows=17834
[TRAIN][5M] asof=2014-07-21 feats=114 buy=YES sell=YES rows=17971
[TRAIN][5M] asof=2014-07-28 feats=114 buy=YES sell=YES rows=18107
[TRAIN][5M] asof=2014-08-04 feats=114 buy=YES sell=YES rows=18262
[TRAIN][5M] asof=2014-08-11 feats=114 buy=YES sell=YES rows=18438
[TRAIN][5M] asof=2014-08-18 feats=114 buy=YES sell=YES rows=18582
[TRAIN][5M] asof=2014-08-25 feats=114 buy=YES sell=YES rows=18697
[TRAIN][5M] asof=2014-09-02 feats=114 buy=YES sell=YES rows=18842
[TRAIN][5M] asof=2014-09-08 feats=114 buy=YES sell=YES rows=18977
[TRAIN][5M] asof=2014-09-15 feats=114 buy=YES sell=YES rows=19129
[TRAIN][5M] asof=2014-09-22 feats=114 buy=YES sell=YES rows=19292
[TRAIN][5M] asof=2014-09-29 feats=114 buy=YES sell=YES rows=19413
[TRAIN][5M] asof=2014-10-06 feats=114 buy=YES sell=YES rows=19515
[TRAIN][5M] asof=2014-10-13 feats=114 buy=YES sell=YES rows=19701
[TRAIN][5M] asof=2014-10-20 feats=114 buy=YES sell=YES rows=19894
[TRAIN][5M] asof=2014-10-27 feats=114 buy=YES sell=YES rows=20044
[TRAIN][5M] asof=2014-11-03 feats=114 buy=YES sell=YES rows=20183
[TRAIN][5M] asof=2014-11-10 feats=114 buy=YES sell=YES rows=20344
[TRAIN][5M] asof=2014-11-17 feats=114 buy=YES sell=YES rows=20511
[TRAIN][5M] asof=2014-11-24 feats=114 buy=YES sell=YES rows=20654
[TRAIN][5M] asof=2014-12-01 feats=114 buy=YES sell=YES rows=20698
[TRAIN][5M] asof=2014-12-08 feats=114 buy=YES sell=YES rows=20756
[TRAIN][5M] asof=2014-12-15 feats=114 buy=YES sell=YES rows=20942
[TRAIN][5M] asof=2014-12-22 feats=114 buy=YES sell=YES rows=21120
[TRAIN][5M] asof=2014-12-29 feats=114 buy=YES sell=YES rows=21243
[TRAIN][5M] asof=2015-01-05 feats=114 buy=YES sell=YES rows=21326
[TRAIN][5M] asof=2015-01-12 feats=114 buy=YES sell=YES rows=21456
[TRAIN][5M] asof=2015-01-20 feats=114 buy=YES sell=YES rows=21623
[TRAIN][5M] asof=2015-01-26 feats=114 buy=YES sell=YES rows=21734
[TRAIN][5M] asof=2015-02-02 feats=114 buy=YES sell=YES rows=21924
[TRAIN][5M] asof=2015-02-09 feats=114 buy=YES sell=YES rows=22055
[TRAIN][5M] asof=2015-02-17 feats=114 buy=YES sell=YES rows=22156
[TRAIN][5M] asof=2015-02-23 feats=114 buy=YES sell=YES rows=22240
[TRAIN][5M] asof=2015-03-02 feats=114 buy=YES sell=YES rows=22358
[TRAIN][5M] asof=2015-03-09 feats=114 buy=YES sell=YES rows=22477
[TRAIN][5M] asof=2015-03-16 feats=114 buy=YES sell=YES rows=22628
[TRAIN][5M] asof=2015-03-23 feats=114 buy=YES sell=YES rows=22757
[TRAIN][5M] asof=2015-03-30 feats=114 buy=YES sell=YES rows=22907
[TRAIN][5M] asof=2015-04-06 feats=114 buy=YES sell=YES rows=23032
[TRAIN][5M] asof=2015-04-13 feats=114 buy=YES sell=YES rows=23148
[TRAIN][5M] asof=2015-04-20 feats=114 buy=YES sell=YES rows=23255
[TRAIN][5M] asof=2015-04-27 feats=114 buy=YES sell=YES rows=23456
[TRAIN][5M] asof=2015-05-04 feats=114 buy=YES sell=YES rows=23594
[TRAIN][5M] asof=2015-05-11 feats=114 buy=YES sell=YES rows=23726
[TRAIN][5M] asof=2015-05-18 feats=114 buy=YES sell=YES rows=23886
[TRAIN][5M] asof=2015-05-26 feats=114 buy=YES sell=YES rows=24027
[TRAIN][5M] asof=2015-06-01 feats=114 buy=YES sell=YES rows=24140
[TRAIN][5M] asof=2015-06-08 feats=114 buy=YES sell=YES rows=24333
[TRAIN][5M] asof=2015-06-15 feats=114 buy=YES sell=YES rows=24450
[TRAIN][5M] asof=2015-06-22 feats=114 buy=YES sell=YES rows=24607
[TRAIN][5M] asof=2015-06-29 feats=114 buy=YES sell=YES rows=24780
[TRAIN][5M] asof=2015-07-06 feats=114 buy=YES sell=YES rows=24901
[TRAIN][5M] asof=2015-07-13 feats=114 buy=YES sell=YES rows=25047
[TRAIN][5M] asof=2015-07-20 feats=114 buy=YES sell=YES rows=25215
[TRAIN][5M] asof=2015-07-27 feats=114 buy=YES sell=YES rows=25452
[TRAIN][5M] asof=2015-08-03 feats=114 buy=YES sell=YES rows=25594
[TRAIN][5M] asof=2015-08-10 feats=114 buy=YES sell=YES rows=25777
[TRAIN][5M] asof=2015-08-17 feats=114 buy=YES sell=YES rows=25930
[TRAIN][5M] asof=2015-08-24 feats=114 buy=YES sell=YES rows=26085
[TRAIN][5M] asof=2015-08-31 feats=114 buy=YES sell=YES rows=26269
[TRAIN][5M] asof=2015-09-08 feats=114 buy=YES sell=YES rows=26410
[TRAIN][5M] asof=2015-09-14 feats=114 buy=YES sell=YES rows=26518
[TRAIN][5M] asof=2015-09-21 feats=114 buy=YES sell=YES rows=26712
[TRAIN][5M] asof=2015-09-28 feats=114 buy=YES sell=YES rows=26911
[TRAIN][5M] asof=2015-10-05 feats=114 buy=YES sell=YES rows=27105
[TRAIN][5M] asof=2015-10-12 feats=114 buy=YES sell=YES rows=27295
[TRAIN][5M] asof=2015-10-19 feats=114 buy=YES sell=YES rows=27494
[TRAIN][5M] asof=2015-10-26 feats=114 buy=YES sell=YES rows=27711
[TRAIN][5M] asof=2015-11-02 feats=114 buy=YES sell=YES rows=27884
[TRAIN][5M] asof=2015-11-09 feats=114 buy=YES sell=YES rows=28056
[TRAIN][5M] asof=2015-11-16 feats=114 buy=YES sell=YES rows=28269
[TRAIN][5M] asof=2015-11-23 feats=114 buy=YES sell=YES rows=28447
[TRAIN][5M] asof=2015-11-30 feats=114 buy=YES sell=YES rows=28538
[TRAIN][5M] asof=2015-12-07 feats=114 buy=YES sell=YES rows=28687
[TRAIN][5M] asof=2015-12-14 feats=114 buy=YES sell=YES rows=28877
[TRAIN][5M] asof=2015-12-21 feats=114 buy=YES sell=YES rows=29072
[TRAIN][5M] asof=2015-12-28 feats=114 buy=YES sell=YES rows=29176
[TRAIN][5M] asof=2016-01-04 feats=114 buy=YES sell=YES rows=29288
[TRAIN][5M] asof=2016-01-11 feats=114 buy=YES sell=YES rows=29443
[TRAIN][5M] asof=2016-01-19 feats=114 buy=YES sell=YES rows=29658
[TRAIN][5M] asof=2016-01-25 feats=114 buy=YES sell=YES rows=29805
[TRAIN][5M] asof=2016-02-01 feats=114 buy=YES sell=YES rows=30050
[TRAIN][5M] asof=2016-02-08 feats=114 buy=YES sell=YES rows=30246
[TRAIN][5M] asof=2016-02-16 feats=114 buy=YES sell=YES rows=30451
[TRAIN][5M] asof=2016-02-22 feats=114 buy=YES sell=YES rows=30617
[TRAIN][5M] asof=2016-02-29 feats=114 buy=YES sell=YES rows=30794
[TRAIN][5M] asof=2016-03-07 feats=114 buy=YES sell=YES rows=30993
[TRAIN][5M] asof=2016-03-14 feats=114 buy=YES sell=YES rows=31128
[TRAIN][5M] asof=2016-03-21 feats=114 buy=YES sell=YES rows=31263
[TRAIN][5M] asof=2016-03-28 feats=114 buy=YES sell=YES rows=31377
[TRAIN][5M] asof=2016-04-04 feats=114 buy=YES sell=YES rows=31551
[TRAIN][5M] asof=2016-04-11 feats=114 buy=YES sell=YES rows=31677
[TRAIN][5M] asof=2016-04-18 feats=114 buy=YES sell=YES rows=31842
[TRAIN][5M] asof=2016-04-25 feats=114 buy=YES sell=YES rows=32001
[TRAIN][5M] asof=2016-05-02 feats=114 buy=YES sell=YES rows=32177
[TRAIN][5M] asof=2016-05-09 feats=114 buy=YES sell=YES rows=32365
[TRAIN][5M] asof=2016-05-16 feats=114 buy=YES sell=YES rows=32529
[TRAIN][5M] asof=2016-05-23 feats=114 buy=YES sell=YES rows=32690
[TRAIN][5M] asof=2016-05-31 feats=114 buy=YES sell=YES rows=32846
[TRAIN][5M] asof=2016-06-06 feats=114 buy=YES sell=YES rows=32960
[TRAIN][5M] asof=2016-06-13 feats=114 buy=YES sell=YES rows=33103
[TRAIN][5M] asof=2016-06-20 feats=114 buy=YES sell=YES rows=33282
[TRAIN][5M] asof=2016-06-27 feats=114 buy=YES sell=YES rows=33489
[TRAIN][5M] asof=2016-07-05 feats=114 buy=YES sell=YES rows=33661
[TRAIN][5M] asof=2016-07-11 feats=114 buy=YES sell=YES rows=33785
[TRAIN][5M] asof=2016-07-18 feats=114 buy=YES sell=YES rows=33942
[TRAIN][5M] asof=2016-07-25 feats=114 buy=YES sell=YES rows=34084
[TRAIN][5M] asof=2016-08-01 feats=114 buy=YES sell=YES rows=34217
[TRAIN][5M] asof=2016-08-08 feats=114 buy=YES sell=YES rows=34387
[TRAIN][5M] asof=2016-08-15 feats=114 buy=YES sell=YES rows=34527
[TRAIN][5M] asof=2016-08-22 feats=114 buy=YES sell=YES rows=34646
[TRAIN][5M] asof=2016-08-29 feats=114 buy=YES sell=YES rows=34753
[TRAIN][5M] asof=2016-09-06 feats=114 buy=YES sell=YES rows=34915
[TRAIN][5M] asof=2016-09-12 feats=114 buy=YES sell=YES rows=35032
[TRAIN][5M] asof=2016-09-19 feats=114 buy=YES sell=YES rows=35198
[TRAIN][5M] asof=2016-09-26 feats=114 buy=YES sell=YES rows=35336
[TRAIN][5M] asof=2016-10-03 feats=114 buy=YES sell=YES rows=35492
[TRAIN][5M] asof=2016-10-10 feats=114 buy=YES sell=YES rows=35628
[TRAIN][5M] asof=2016-10-17 feats=114 buy=YES sell=YES rows=35764
[TRAIN][5M] asof=2016-10-24 feats=114 buy=YES sell=YES rows=35937
[TRAIN][5M] asof=2016-10-31 feats=114 buy=YES sell=YES rows=36104
[TRAIN][5M] asof=2016-11-07 feats=114 buy=YES sell=YES rows=36268
[TRAIN][5M] asof=2016-11-14 feats=114 buy=YES sell=YES rows=36438
[TRAIN][5M] asof=2016-11-21 feats=114 buy=YES sell=YES rows=36611
[TRAIN][5M] asof=2016-11-28 feats=114 buy=YES sell=YES rows=36720

,date,decision_date,result_date,p_day,p_day_source_date,daily_gate_mode,daily_reward_mode,direct_gate_confidence,direct_gate_prob_force_buy,direct_gate_prob_free,...,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
1978,2019-12-20,2019-12-20,2019-12-23,0.244201,2019-12-20,threshold,counterfactual_5m,NaN,NaN,NaN,...,FORCE_BUY,0.000851,0.000851,0.000851,0.000851,FORCE_BUY,1.353974e+07,211.81,-0.5,1.785
1979,2019-12-23,2019-12-23,2019-12-24,0.196344,2019-12-23,threshold,counterfactual_5m,NaN,NaN,NaN,...,FORCE_BUY,0.000142,0.000142,0.000142,0.000142,FORCE_BUY,1.354166e+07,211.95,-0.5,1.785
1980,2019-12-24,2019-12-24,2019-12-26,0.134960,2019-12-24,threshold,counterfactual_5m,NaN,NaN,NaN,...,FORCE_BUY,0.009995,0.009995,0.009995,0.009995,FORCE_BUY,1.367701e+07,214.22,-0.5,1.785
1981,2019-12-26,2019-12-26,2019-12-27,0.149960,2019-12-26,threshold,counterfactual_5m,NaN,NaN,NaN,...,FORCE_BUY,-0.005550,-0.005550,-0.005550,-0.005550,FORCE_BUY,1.360111e+07,213.23,-0.5,1.785
1982,2019-12-27,2019-12-27,2019-12-30,0.330249,2019-12-27,threshold,counterfactual_5m,NaN,NaN,NaN,...,FORCE_BUY,-0.007248,-0.007248,-0.007248,-0.007248,FORCE_BUY,1.350253e+07,212.31,-0.5,1.785

,date,equity,cash,pos,qty,entry_px,decision_date,result_date,buy_th,sell_th,...,daily_buy_level,daily_sell_level,decision_extreme_base_dir,decision_extreme_region,decision_extreme_label,decision_extreme_window_end_date,decision_extreme_ref_high,decision_extreme_ref_low,decision_extreme_future_max_high,decision_extreme_future_min_low
1978,2019-12-23,182391.671811,0.0,1,861.109824,204.82,2019-12-20,2019-12-23,-0.500,1.785,...,0.34,0.39,sell,sell_high_broken,0.0,2019-12-30,212.52,211.27,214.56,211.16
1979,2019-12-24,182512.227186,0.0,1,861.109824,204.82,2019-12-23,2019-12-24,-0.500,1.785,...,0.34,0.39,sell,sell_high_broken,0.0,2019-12-31,212.15,211.63,214.56,211.16
1980,2019-12-26,184466.946486,0.0,1,861.109824,204.82,2019-12-24,2019-12-26,-0.500,1.785,...,0.34,0.39,sell,pending,NaN,NaT,NaN,NaN,NaN,NaN
1981,2019-12-27,183614.447761,0.0,1,861.109824,204.82,2019-12-26,2019-12-27,-0.500,1.785,...,0.34,0.39,sell,pending,NaN,NaT,NaN,NaN,NaN,NaN
1982,2019-12-30,182822.226723,0.0,1,861.109824,204.82,2019-12-27,2019-12-30,1.335,1.290,...,0.34,0.39,sell,pending,NaN,NaT,NaN,NaN,NaN,NaN

[TRAIN][DAILY-PROB] n=2340 pos=489 (20.90%)
[TRAIN][DAILY-PROB] n=2365 pos=494 (20.89%)
[TRAIN][DAILY-PROB] n=2390 pos=497 (20.79%)
[TRAIN][DAILY-PROB] n=2415 pos=498 (20.62%)
[TRAIN][DAILY-PROB] n=2440 pos=500 (20.49%)
[TRAIN][DAILY-PROB] n=2465 pos=508 (20.61%)
[TRAIN][DAILY-PROB] n=2490 pos=511 (20.52%)
[TRAIN][DAILY-PROB] n=2515 pos=518 (20.60%)
[TRAIN][DAILY-PROB] n=2540 pos=529 (20.83%)
[TRAIN][DAILY-PROB] n=2565 pos=530 (20.66%)
[TRAIN][DAILY-PROB] n=2590 pos=533 (20.58%)
[TRAIN][DAILY-PROB] n=2615 pos=540 (20.65%)
[TRAIN][DAILY-PROB] n=2640 pos=543 (20.57%)
[TRAIN][DAILY-PROB] n=2665 pos=549 (20.60%)
[TRAIN][DAILY-PROB] n=2690 pos=549 (20.41%)
[TRAIN][DAILY-PROB] n=2715 pos=552 (20.33%)
[TRAIN][DAILY-PROB] n=2740 pos=555 (20.26%)
[TRAIN][DAILY-PROB] n=2765 pos=566 (20.47%)
[TRAIN][DAILY-PROB] n=2790 pos=569 (20.39%)
[TRAIN][DAILY-PROB] n=2815 pos=574 (20.39%)
[TRAIN][DAILY-PROB] n=2840 pos=580 (20.42%)
[TRAIN][DAILY-PROB] n=2865 pos=583 (20.35%)
[TRAIN][DAILY-PROB] n=2890 pos=593 (20.52%)
[TRAIN][DAILY-PROB] n=2915 pos=593 (20.34%)
[TRAIN][DAILY-PROB] n=2940 pos=602 (20.48%)
[TRAIN][DAILY-PROB] n=2965 pos=610 (20.57%)
[TRAIN][DAILY-PROB] n=2990 pos=616 (20.60%)
[TRAIN][DAILY-PROB] n=3015 pos=625 (20.73%)
[TRAIN][DAILY-PROB] n=3040 pos=631 (20.76%)
[TRAIN][DAILY-PROB] n=3065 pos=637 (20.78%)
[TRAIN][DAILY-PROB] n=3090 pos=640 (20.71%)
[TRAIN][DAILY-PROB] n=3115 pos=649 (20.83%)
[TRAIN][DAILY-PROB] n=3140 pos=656 (20.89%)
[TRAIN][DAILY-PROB] n=3165 pos=658 (20.79%)
[TRAIN][DAILY-PROB] n=3190 pos=658 (20.63%)
[TRAIN][DAILY-PROB] n=3215 pos=661 (20.56%)
[TRAIN][DAILY-PROB] n=3240 pos=669 (20.65%)
[TRAIN][DAILY-PROB] n=3265 pos=679 (20.80%)
[TRAIN][DAILY-PROB] n=3290 pos=689 (20.94%)
[TRAIN][DAILY-PROB] n=3315 pos=690 (20.81%)
[TRAIN][DAILY-PROB] n=3340 pos=696 (20.84%)
[TRAIN][DAILY-PROB] n=3365 pos=699 (20.77%)
[TRAIN][DAILY-PROB] n=3390 pos=703 (20.74%)
[TRAIN][DAILY-PROB] n=3415 pos=709 (20.76%)
[TRAIN][DAILY-PROB] n=3440 pos=711 (20.67%)
[TRAIN][DAILY-PROB] n=3465 pos=717 (20.69%)
[TRAIN][DAILY-PROB] n=3490 pos=725 (20.77%)
[TRAIN][DAILY-PROB] n=3515 pos=731 (20.80%)
[TRAIN][DAILY-PROB] n=3540 pos=734 (20.73%)
[TRAIN][DAILY-PROB] n=3565 pos=737 (20.67%)
[TRAIN][DAILY-PROB] n=3590 pos=743 (20.70%)
[TRAIN][DAILY-PROB] n=3615 pos=750 (20.75%)
[TRAIN][DAILY-PROB] n=3640 pos=760 (20.88%)
[TRAIN][DAILY-PROB] n=3665 pos=768 (20.95%)
[TRAIN][DAILY-PROB] n=3690 pos=769 (20.84%)
[TRAIN][DAILY-PROB] n=3715 pos=770 (20.73%)
[TRAIN][DAILY-PROB] n=3740 pos=778 (20.80%)
[TRAIN][DAILY-PROB] n=3765 pos=785 (20.85%)
[TRAIN][DAILY-PROB] n=3790 pos=790 (20.84%)
[TRAIN][DAILY-PROB] n=3815 pos=798 (20.92%)
[TRAIN][DAILY-PROB] n=3840 pos=801 (20.86%)
[TRAIN][DAILY-PROB] n=3865 pos=807 (20.88%)
[TRAIN][DAILY-PROB] n=3890 pos=811 (20.85%)
[TRAIN][DAILY-PROB] n=3915 pos=812 (20.74%)
[TRAIN][5M] asof=2019-12-31 feats=114 buy=YES sell=YES rows=63348
[TRAIN][5M] asof=2020-01-06 feats=114 buy=YES sell=YES rows=63491
[TRAIN][5M] asof=2020-01-13 feats=114 buy=YES sell=YES rows=63724
[TRAIN][5M] asof=2020-01-21 feats=114 buy=YES sell=YES rows=63922
[TRAIN][5M] asof=2020-01-27 feats=114 buy=YES sell=YES rows=64099
[TRAIN][5M] asof=2020-02-03 feats=114 buy=YES sell=YES rows=64320
[TRAIN][5M] asof=2020-02-10 feats=114 buy=YES sell=YES rows=64544
[TRAIN][5M] asof=2020-02-18 feats=114 buy=YES sell=YES rows=64708
[TRAIN][5M] asof=2020-02-24 feats=114 buy=YES sell=YES rows=64838
[TRAIN][5M] asof=2020-03-02 feats=114 buy=YES sell=YES rows=65071
[TRAIN][5M] asof=2020-03-09 feats=114 buy=YES sell=YES rows=65267
[TRAIN][5M] asof=2020-03-16 feats=114 buy=YES sell=YES rows=65422
[TRAIN][5M] asof=2020-03-23 feats=114 buy=YES sell=YES rows=65670
[TRAIN][5M] asof=2020-03-30 feats=114 buy=YES sell=YES rows=65879
[TRAIN][5M] asof=2020-04-06 feats=114 buy=YES sell=YES rows=66047
[TRAIN][5M] asof=2020-04-13 feats=114 buy=YES sell=YES rows=66188
[TRAIN][5M] asof=2020-04-20 feats=114 buy=YES sell=YES rows=66389
[TRAIN][5M] asof=2020-04-27 feats=114 buy=YES sell=YES rows=66658
[TRAIN][5M] asof=2020-05-04 feats=114 buy=YES sell=YES rows=66852
[TRAIN][5M] asof=2020-05-11 feats=114 buy=YES sell=YES rows=67057
[TRAIN][5M] asof=2020-05-18 feats=114 buy=YES sell=YES rows=67279
[TRAIN][5M] asof=2020-05-26 feats=114 buy=YES sell=YES rows=67493
[TRAIN][5M] asof=2020-06-01 feats=114 buy=YES sell=YES rows=67654
[TRAIN][5M] asof=2020-06-08 feats=114 buy=YES sell=YES rows=67880
[TRAIN][5M] asof=2020-06-15 feats=114 buy=YES sell=YES rows=68051
[TRAIN][5M] asof=2020-06-22 feats=114 buy=YES sell=YES rows=68273
[TRAIN][5M] asof=2020-06-29 feats=114 buy=YES sell=YES rows=68470
[TRAIN][5M] asof=2020-07-06 feats=114 buy=YES sell=YES rows=68619
[TRAIN][5M] asof=2020-07-13 feats=114 buy=YES sell=YES rows=68856
[TRAIN][5M] asof=2020-07-20 feats=114 buy=YES sell=YES rows=69056
[TRAIN][5M] asof=2020-07-27 feats=114 buy=YES sell=YES rows=69255
[TRAIN][5M] asof=2020-08-03 feats=114 buy=YES sell=YES rows=69448
[TRAIN][5M] asof=2020-08-10 feats=114 buy=YES sell=YES rows=69638
[TRAIN][5M] asof=2020-08-17 feats=114 buy=YES sell=YES rows=69828
[TRAIN][5M] asof=2020-08-24 feats=114 buy=YES sell=YES rows=70010
[TRAIN][5M] asof=2020-08-31 feats=114 buy=YES sell=YES rows=70221
[TRAIN][5M] asof=2020-09-08 feats=114 buy=YES sell=YES rows=70412
[TRAIN][5M] asof=2020-09-14 feats=114 buy=YES sell=YES rows=70595
[TRAIN][5M] asof=2020-09-21 feats=114 buy=YES sell=YES rows=70807
[TRAIN][5M] asof=2020-09-28 feats=114 buy=YES sell=YES rows=71002
[TRAIN][5M] asof=2020-10-05 feats=114 buy=YES sell=YES rows=71208
[TRAIN][5M] asof=2020-10-12 feats=114 buy=YES sell=YES rows=71413
[TRAIN][5M] asof=2020-10-19 feats=114 buy=YES sell=YES rows=71625
[TRAIN][5M] asof=2020-10-26 feats=114 buy=YES sell=YES rows=71806
[TRAIN][5M] asof=2020-11-02 feats=114 buy=YES sell=YES rows=72034
[TRAIN][5M] asof=2020-11-09 feats=114 buy=YES sell=YES rows=72198
[TRAIN][5M] asof=2020-11-16 feats=114 buy=YES sell=YES rows=72380
[TRAIN][5M] asof=2020-11-23 feats=114 buy=YES sell=YES rows=72557
[TRAIN][5M] asof=2020-11-30 feats=114 buy=YES sell=YES rows=72685
[TRAIN][5M] asof=2020-12-07 feats=114 buy=YES sell=YES rows=72893
[TRAIN][5M] asof=2020-12-14 feats=114 buy=YES sell=YES rows=73036
[TRAIN][5M] asof=2020-12-21 feats=114 buy=YES sell=YES rows=73207
[TRAIN][5M] asof=2020-12-28 feats=114 buy=YES sell=YES rows=73364
[TRAIN][5M] asof=2021-01-04 feats=114 buy=YES sell=YES rows=73508
[TRAIN][5M] asof=2021-01-11 feats=114 buy=YES sell=YES rows=73706
[TRAIN][5M] asof=2021-01-19 feats=114 buy=YES sell=YES rows=73905
[TRAIN][5M] asof=2021-01-25 feats=114 buy=YES sell=YES rows=74092
[TRAIN][5M] asof=2021-02-01 feats=114 buy=YES sell=YES rows=74302
[TRAIN][5M] asof=2021-02-08 feats=114 buy=YES sell=YES rows=74486
[TRAIN][5M] asof=2021-02-16 feats=114 buy=YES sell=YES rows=74663
[TRAIN][5M] asof=2021-02-22 feats=114 buy=YES sell=YES rows=74836
[TRAIN][5M] asof=2021-03-01 feats=114 buy=YES sell=YES rows=75066
[TRAIN][5M] asof=2021-03-08 feats=114 buy=YES sell=YES rows=75280
[TRAIN][5M] asof=2021-03-15 feats=114 buy=YES sell=YES rows=75456
[TRAIN][5M] asof=2021-03-22 feats=114 buy=YES sell=YES rows=75613
[TRAIN][5M] asof=2021-03-29 feats=114 buy=YES sell=YES rows=75814
[TRAIN][5M] asof=2021-04-05 feats=114 buy=YES sell=YES rows=75990
[TRAIN][5M] asof=2021-04-12 feats=114 buy=YES sell=YES rows=76194
[TRAIN][5M] asof=2021-04-19 feats=114 buy=YES sell=YES rows=76374
[TRAIN][5M] asof=2021-04-26 feats=114 buy=YES sell=YES rows=76588
[TRAIN][5M] asof=2021-05-03 feats=114 buy=YES sell=YES rows=76783
[TRAIN][5M] asof=2021-05-10 feats=114 buy=YES sell=YES rows=76974
[TRAIN][5M] asof=2021-05-17 feats=114 buy=YES sell=YES rows=77166
[TRAIN][5M] asof=2021-05-24 feats=114 buy=YES sell=YES rows=77355
[TRAIN][5M] asof=2021-06-01 feats=114 buy=YES sell=YES rows=77504
[TRAIN][5M] asof=2021-06-07 feats=114 buy=YES sell=YES rows=77670
[TRAIN][5M] asof=2021-06-14 feats=114 buy=YES sell=YES rows=77845
[TRAIN][5M] asof=2021-06-21 feats=114 buy=YES sell=YES rows=78042
[TRAIN][5M] asof=2021-06-28 feats=114 buy=YES sell=YES rows=78191
[TRAIN][5M] asof=2021-07-06 feats=114 buy=YES sell=YES rows=78429
[TRAIN][5M] asof=2021-07-12 feats=114 buy=YES sell=YES rows=78570
[TRAIN][5M] asof=2021-07-19 feats=114 buy=YES sell=YES rows=78772
[TRAIN][5M] asof=2021-07-26 feats=114 buy=YES sell=YES rows=78972
[TRAIN][5M] asof=2021-08-02 feats=114 buy=YES sell=YES rows=79191
[TRAIN][5M] asof=2021-08-09 feats=114 buy=YES sell=YES rows=79355
[TRAIN][5M] asof=2021-08-16 feats=114 buy=YES sell=YES rows=79534
[TRAIN][5M] asof=2021-08-23 feats=114 buy=YES sell=YES rows=79758
[TRAIN][5M] asof=2021-08-30 feats=114 buy=YES sell=YES rows=79951
[TRAIN][5M] asof=2021-09-07 feats=114 buy=YES sell=YES rows=80136
[TRAIN][5M] asof=2021-09-13 feats=114 buy=YES sell=YES rows=80271
[TRAIN][5M] asof=2021-09-20 feats=114 buy=YES sell=YES rows=80482
[TRAIN][5M] asof=2021-09-27 feats=114 buy=YES sell=YES rows=80644
[TRAIN][5M] asof=2021-10-04 feats=114 buy=YES sell=YES rows=80823
[TRAIN][5M] asof=2021-10-11 feats=114 buy=YES sell=YES rows=80975
[TRAIN][5M] asof=2021-10-18 feats=114 buy=YES sell=YES rows=81177
[TRAIN][5M] asof=2021-10-25 feats=114 buy=YES sell=YES rows=81371
[TRAIN][5M] asof=2021-11-01 feats=114 buy=YES sell=YES rows=81522
[TRAIN][5M] asof=2021-11-08 feats=114 buy=YES sell=YES rows=81709
[TRAIN][5M] asof=2021-11-15 feats=114 buy=YES sell=YES rows=81908
[TRAIN][5M] asof=2021-11-22 feats=114 buy=YES sell=YES rows=82061
[TRAIN][5M] asof=2021-11-29 feats=114 buy=YES sell=YES rows=82223
[TRAIN][5M] asof=2021-12-06 feats=114 buy=YES sell=YES rows=82404
[TRAIN][5M] asof=2021-12-13 feats=114 buy=YES sell=YES rows=82556
[TRAIN][5M] asof=2021-12-20 feats=114 buy=YES sell=YES rows=82732
[TRAIN][5M] asof=2021-12-27 feats=114 buy=YES sell=YES rows=82912
[TRAIN][5M] asof=2022-01-03 feats=114 buy=YES sell=YES rows=83088
[TRAIN][5M] asof=2022-01-10 feats=114 buy=YES sell=YES rows=83264
[TRAIN][5M] asof=2022-01-18 feats=114 buy=YES sell=YES rows=83484
[TRAIN][5M] asof=2022-01-24 feats=114 buy=YES sell=YES rows=83646
[TRAIN][5M] asof=2022-01-31 feats=114 buy=YES sell=YES rows=83792
[TRAIN][5M] asof=2022-02-07 feats=114 buy=YES sell=YES rows=83975
[TRAIN][5M] asof=2022-02-14 feats=114 buy=YES sell=YES rows=84144
[TRAIN][5M] asof=2022-02-22 feats=114 buy=YES sell=YES rows=84320

In [1]:
from adaptive_reward_checkpoint_fresh import run_adaptive_reward_from_snapshot

checkpoint_path = r"output_adaptive_reward_snapshot_build_QQQ_252days_at_2020\year_start_checkpoints\QQQ_adaptive_reward_fresh_start_252days_at_2020__continued__start_2020.joblib"

res = run_adaptive_reward_from_snapshot(
    snapshot_path=checkpoint_path,

    # Simulate through this local-data timestamp.
    end_time="2026-06-12 16:00:00",

    # Actual trading begins here.
    # The first trading day will use the latest prior p_day/gate from the checkpoint/history.
    trade_start="2020-01-01 09:30:00",

    # Optional; defaults to checkpoint_time + 1 day.
    # Keep this at or before trade_start if you want all trade_start signals considered.
    sim_start="2020-01-01 09:30:00",

    output_dir=r"output_prev_checkpoint_local_QQQ_20200101_20260612",
    save_snapshot_path=r"output_prev_checkpoint_local_QQQ_20200101_20260612\continued_checkpoint.joblib",

    # Start clean/flat from this capital.
    reset_execution_state=True,
    initial_capital=100000.0,
    fee_pct=0.0,

    # Keep saved model/checkpoint logic.
    autosave_year_start_checkpoints=False,
    verbose=True,
)

print("Output dir:", res["output_dir"])
print("Continued checkpoint:", res["continued_snapshot_path"])
print(res["daily_reward_df"].tail())
print(res["signal_decisions_all_df"].tail())

[TRAIN][DAILY-PROB] n=5531 pos=1138 (20.57%)
[TRAIN][5M] asof=2020-01-02 feats=69 buy=YES sell=YES rows=63437
[TRAIN][5M] asof=2020-01-07 feats=69 buy=YES sell=YES rows=63541
[TRAIN][5M] asof=2020-01-13 feats=69 buy=YES sell=YES rows=63738
[TRAIN][5M] asof=2020-01-21 feats=69 buy=YES sell=YES rows=63936
[TRAIN][5M] asof=2020-01-27 feats=69 buy=YES sell=YES rows=64113
[TRAIN][5M] asof=2020-02-03 feats=69 buy=YES sell=YES rows=64334
[TRAIN][5M] asof=2020-02-10 feats=69 buy=YES sell=YES rows=64558
[TRAIN][5M] asof=2020-02-18 feats=69 buy=YES sell=YES rows=64722
[TRAIN][5M] asof=2020-02-24 feats=69 buy=YES sell=YES rows=64852
[TRAIN][5M] asof=2020-03-02 feats=69 buy=YES sell=YES rows=65085
[TRAIN][5M] asof=2020-03-09 feats=69 buy=YES sell=YES rows=65281
[TRAIN][5M] asof=2020-03-16 feats=69 buy=YES sell=YES rows=65436
[TRAIN][5M] asof=2020-03-23 feats=69 buy=YES sell=YES rows=65684
[TRAIN][5M] asof=2020-03-30 feats=69 buy=YES sell=YES rows=65893
[TRAIN][5M] asof=2020-04-06 feats=69 buy=YES sell=YES rows=66061
[TRAIN][5M] asof=2020-04-13 feats=69 buy=YES sell=YES rows=66202
[TRAIN][5M] asof=2020-04-20 feats=69 buy=YES sell=YES rows=66403
[TRAIN][5M] asof=2020-04-27 feats=69 buy=YES sell=YES rows=66672
[TRAIN][5M] asof=2020-05-04 feats=69 buy=YES sell=YES rows=66866
[TRAIN][5M] asof=2020-05-11 feats=69 buy=YES sell=YES rows=67071
[TRAIN][5M] asof=2020-05-18 feats=69 buy=YES sell=YES rows=67293
[TRAIN][5M] asof=2020-05-26 feats=69 buy=YES sell=YES rows=67507
[TRAIN][5M] asof=2020-06-01 feats=69 buy=YES sell=YES rows=67668
[TRAIN][5M] asof=2020-06-08 feats=69 buy=YES sell=YES rows=67894
[TRAIN][5M] asof=2020-06-15 feats=69 buy=YES sell=YES rows=68065
[TRAIN][5M] asof=2020-06-22 feats=69 buy=YES sell=YES rows=68287
[TRAIN][5M] asof=2020-06-29 feats=69 buy=YES sell=YES rows=68484
[TRAIN][5M] asof=2020-07-06 feats=69 buy=YES sell=YES rows=68633
[TRAIN][5M] asof=2020-07-13 feats=69 buy=YES sell=YES rows=68870
[TRAIN][5M] asof=2020-07-20 feats=69 buy=YES sell=YES rows=69070
[TRAIN][5M] asof=2020-07-27 feats=69 buy=YES sell=YES rows=69269
[TRAIN][5M] asof=2020-08-03 feats=69 buy=YES sell=YES rows=69462
[TRAIN][5M] asof=2020-08-10 feats=69 buy=YES sell=YES rows=69652
[TRAIN][5M] asof=2020-08-17 feats=69 buy=YES sell=YES rows=69842
[TRAIN][5M] asof=2020-08-24 feats=69 buy=YES sell=YES rows=70024
[TRAIN][5M] asof=2020-08-31 feats=69 buy=YES sell=YES rows=70235
[TRAIN][5M] asof=2020-09-08 feats=69 buy=YES sell=YES rows=70426
[TRAIN][5M] asof=2020-09-14 feats=69 buy=YES sell=YES rows=70609
[TRAIN][5M] asof=2020-09-21 feats=69 buy=YES sell=YES rows=70821
[TRAIN][5M] asof=2020-09-28 feats=69 buy=YES sell=YES rows=71016
[TRAIN][5M] asof=2020-10-05 feats=69 buy=YES sell=YES rows=71222
[TRAIN][5M] asof=2020-10-12 feats=69 buy=YES sell=YES rows=71427
[TRAIN][5M] asof=2020-10-19 feats=69 buy=YES sell=YES rows=71639
[TRAIN][5M] asof=2020-10-26 feats=69 buy=YES sell=YES rows=71820
[TRAIN][5M] asof=2020-11-02 feats=69 buy=YES sell=YES rows=72048
[TRAIN][5M] asof=2020-11-09 feats=69 buy=YES sell=YES rows=72212
[TRAIN][5M] asof=2020-11-16 feats=69 buy=YES sell=YES rows=72394
[TRAIN][5M] asof=2020-11-23 feats=69 buy=YES sell=YES rows=72571
[TRAIN][5M] asof=2020-11-30 feats=69 buy=YES sell=YES rows=72699
[TRAIN][5M] asof=2020-12-07 feats=69 buy=YES sell=YES rows=72907
[TRAIN][5M] asof=2020-12-14 feats=69 buy=YES sell=YES rows=73050
[TRAIN][5M] asof=2020-12-21 feats=69 buy=YES sell=YES rows=73221
[TRAIN][5M] asof=2020-12-28 feats=69 buy=YES sell=YES rows=73378
[TRAIN][5M] asof=2021-01-04 feats=69 buy=YES sell=YES rows=73522
[TRAIN][5M] asof=2021-01-11 feats=69 buy=YES sell=YES rows=73720
[TRAIN][5M] asof=2021-01-19 feats=69 buy=YES sell=YES rows=73919
[TRAIN][5M] asof=2021-01-25 feats=69 buy=YES sell=YES rows=74106
[TRAIN][5M] asof=2021-02-01 feats=69 buy=YES sell=YES rows=74316
[TRAIN][5M] asof=2021-02-08 feats=69 buy=YES sell=YES rows=74500
[TRAIN][5M] asof=2021-02-16 feats=69 buy=YES sell=YES rows=74677
[TRAIN][5M] asof=2021-02-22 feats=69 buy=YES sell=YES rows=74850
[TRAIN][5M] asof=2021-03-01 feats=69 buy=YES sell=YES rows=75080
[TRAIN][5M] asof=2021-03-08 feats=69 buy=YES sell=YES rows=75294
[TRAIN][5M] asof=2021-03-15 feats=69 buy=YES sell=YES rows=75470
[TRAIN][5M] asof=2021-03-22 feats=69 buy=YES sell=YES rows=75627
[TRAIN][5M] asof=2021-03-29 feats=69 buy=YES sell=YES rows=75828
[TRAIN][5M] asof=2021-04-05 feats=69 buy=YES sell=YES rows=76004
[TRAIN][5M] asof=2021-04-12 feats=69 buy=YES sell=YES rows=76208
[TRAIN][5M] asof=2021-04-19 feats=69 buy=YES sell=YES rows=76388
[TRAIN][5M] asof=2021-04-26 feats=69 buy=YES sell=YES rows=76602
[TRAIN][5M] asof=2021-05-03 feats=69 buy=YES sell=YES rows=76797
[TRAIN][5M] asof=2021-05-10 feats=69 buy=YES sell=YES rows=76988
[TRAIN][5M] asof=2021-05-17 feats=69 buy=YES sell=YES rows=77180
[TRAIN][5M] asof=2021-05-24 feats=69 buy=YES sell=YES rows=77369
[TRAIN][5M] asof=2021-06-01 feats=69 buy=YES sell=YES rows=77518
[TRAIN][5M] asof=2021-06-07 feats=69 buy=YES sell=YES rows=77684
[TRAIN][5M] asof=2021-06-14 feats=69 buy=YES sell=YES rows=77859
[TRAIN][5M] asof=2021-06-21 feats=69 buy=YES sell=YES rows=78056
[TRAIN][5M] asof=2021-06-28 feats=69 buy=YES sell=YES rows=78205
[TRAIN][5M] asof=2021-07-06 feats=69 buy=YES sell=YES rows=78443
[TRAIN][5M] asof=2021-07-12 feats=69 buy=YES sell=YES rows=78584
[TRAIN][5M] asof=2021-07-19 feats=69 buy=YES sell=YES rows=78786
[TRAIN][5M] asof=2021-07-26 feats=69 buy=YES sell=YES rows=78986
[TRAIN][5M] asof=2021-08-02 feats=69 buy=YES sell=YES rows=79205
[TRAIN][5M] asof=2021-08-09 feats=69 buy=YES sell=YES rows=79369
[TRAIN][5M] asof=2021-08-16 feats=69 buy=YES sell=YES rows=79548
[TRAIN][5M] asof=2021-08-23 feats=69 buy=YES sell=YES rows=79772
[TRAIN][5M] asof=2021-08-30 feats=69 buy=YES sell=YES rows=79965
[TRAIN][5M] asof=2021-09-07 feats=69 buy=YES sell=YES rows=80150
[TRAIN][5M] asof=2021-09-13 feats=69 buy=YES sell=YES rows=80285
[TRAIN][5M] asof=2021-09-20 feats=69 buy=YES sell=YES rows=80496
[TRAIN][5M] asof=2021-09-27 feats=69 buy=YES sell=YES rows=80658
[TRAIN][5M] asof=2021-10-04 feats=69 buy=YES sell=YES rows=80837
[TRAIN][5M] asof=2021-10-11 feats=69 buy=YES sell=YES rows=80989
[TRAIN][5M] asof=2021-10-18 feats=69 buy=YES sell=YES rows=81191
[TRAIN][5M] asof=2021-10-25 feats=69 buy=YES sell=YES rows=81385
[TRAIN][5M] asof=2021-11-01 feats=69 buy=YES sell=YES rows=81536
[TRAIN][5M] asof=2021-11-08 feats=69 buy=YES sell=YES rows=81723
[TRAIN][5M] asof=2021-11-15 feats=69 buy=YES sell=YES rows=81922
[TRAIN][5M] asof=2021-11-22 feats=69 buy=YES sell=YES rows=82075
[TRAIN][5M] asof=2021-11-29 feats=69 buy=YES sell=YES rows=82237
[TRAIN][5M] asof=2021-12-06 feats=69 buy=YES sell=YES rows=82418
[TRAIN][5M] asof=2021-12-13 feats=69 buy=YES sell=YES rows=82570
[TRAIN][5M] asof=2021-12-20 feats=69 buy=YES sell=YES rows=82746
[TRAIN][5M] asof=2021-12-27 feats=69 buy=YES sell=YES rows=82926
[TRAIN][5M] asof=2022-01-03 feats=69 buy=YES sell=YES rows=83102
[TRAIN][5M] asof=2022-01-10 feats=69 buy=YES sell=YES rows=83278
[TRAIN][5M] asof=2022-01-18 feats=69 buy=YES sell=YES rows=83498
[TRAIN][5M] asof=2022-01-24 feats=69 buy=YES sell=YES rows=83660
[TRAIN][5M] asof=2022-01-31 feats=69 buy=YES sell=YES rows=83806
[TRAIN][5M] asof=2022-02-07 feats=69 buy=YES sell=YES rows=83989
[TRAIN][5M] asof=2022-02-14 feats=69 buy=YES sell=YES rows=84158
[TRAIN][5M] asof=2022-02-22 feats=69 buy=YES sell=YES rows=84334
[TRAIN][5M] asof=2022-02-28 feats=69 buy=YES sell=YES rows=84510
[TRAIN][5M] asof=2022-03-07 feats=69 buy=YES sell=YES rows=84728
[TRAIN][5M] asof=2022-03-14 feats=69 buy=YES sell=YES rows=84883
[TRAIN][5M] asof=2022-03-21 feats=69 buy=YES sell=YES rows=85089
[TRAIN][5M] asof=2022-03-28 feats=69 buy=YES sell=YES rows=85299
[TRAIN][5M] asof=2022-04-04 feats=69 buy=YES sell=YES rows=85510
[TRAIN][5M] asof=2022-04-11 feats=69 buy=YES sell=YES rows=85732
[TRAIN][5M] asof=2022-04-18 feats=69 buy=YES sell=YES rows=85897
[TRAIN][5M] asof=2022-04-25 feats=69 buy=YES sell=YES rows=86076
[TRAIN][5M] asof=2022-05-02 feats=69 buy=YES sell=YES rows=86240
[TRAIN][5M] asof=2022-05-09 feats=69 buy=YES sell=YES rows=86429
[TRAIN][5M] asof=2022-05-16 feats=69 buy=YES sell=YES rows=86620
[TRAIN][5M] asof=2022-05-23 feats=69 buy=YES sell=YES rows=86847
[TRAIN][5M] asof=2022-05-31 feats=69 buy=YES sell=YES rows=87073
[TRAIN][5M] asof=2022-06-06 feats=69 buy=YES sell=YES rows=87241
[TRAIN][5M] asof=2022-06-13 feats=69 buy=YES sell=YES rows=87466
[TRAIN][5M] asof=2022-06-21 feats=69 buy=YES sell=YES rows=87658
[TRAIN][5M] asof=2022-06-27 feats=69 buy=YES sell=YES rows=87789
[TRAIN][5M] asof=2022-07-05 feats=69 buy=YES sell=YES rows=87987
[TRAIN][5M] asof=2022-07-11 feats=69 buy=YES sell=YES rows=88117
[TRAIN][5M] asof=2022-07-18 feats=69 buy=YES sell=YES rows=88219
[TRAIN][5M] asof=2022-07-25 feats=69 buy=YES sell=YES rows=88423
[TRAIN][5M] asof=2022-08-01 feats=69 buy=YES sell=YES rows=88577
[TRAIN][5M] asof=2022-08-08 feats=69 buy=YES sell=YES rows=88764
[TRAIN][5M] asof=2022-08-15 feats=69 buy=YES sell=YES rows=88955
[TRAIN][5M] asof=2022-08-22 feats=69 buy=YES sell=YES rows=89224
[TRAIN][5M] asof=2022-08-29 feats=69 buy=YES sell=YES rows=89424
[TRAIN][5M] asof=2022-09-06 feats=69 buy=YES sell=YES rows=89627
[TRAIN][5M] asof=2022-09-12 feats=69 buy=YES sell=YES rows=89798
[TRAIN][5M] asof=2022-09-19 feats=69 buy=YES sell=YES rows=89985
[TRAIN][5M] asof=2022-09-26 feats=69 buy=YES sell=YES rows=90189
[TRAIN][5M] asof=2022-10-03 feats=69 buy=YES sell=YES rows=90383
[TRAIN][5M] asof=2022-10-10 feats=69 buy=YES sell=YES rows=90550
[TRAIN][5M] asof=2022-10-17 feats=69 buy=YES sell=YES rows=90724
[TRAIN][5M] asof=2022-10-24 feats=69 buy=YES sell=YES rows=90966
[TRAIN][5M] asof=2022-10-31 feats=69 buy=YES sell=YES rows=91148
[TRAIN][5M] asof=2022-11-07 feats=69 buy=YES sell=YES rows=91286
[TRAIN][5M] asof=2022-11-14 feats=69 buy=YES sell=YES rows=91498
[TRAIN][5M] asof=2022-11-21 feats=69 buy=YES sell=YES rows=91696
[TRAIN][5M] asof=2022-11-28 feats=69 buy=YES sell=YES rows=91876
[TRAIN][5M] asof=2022-12-05 feats=69 buy=YES sell=YES rows=92010
[TRAIN][5M] asof=2022-12-12 feats=69 buy=YES sell=YES rows=92121
[TRAIN][5M] asof=2022-12-19 feats=69 buy=YES sell=YES rows=92265
[TRAIN][5M] asof=2022-12-27 feats=69 buy=YES sell=YES rows=92493
[TRAIN][5M] asof=2023-01-03 feats=69 buy=YES sell=YES rows=92654
[TRAIN][5M] asof=2023-01-09 feats=69 buy=YES sell=YES rows=92766
[TRAIN][5M] asof=2023-01-17 feats=69 buy=YES sell=YES rows=92942
[TRAIN][5M] asof=2023-01-23 feats=69 buy=YES sell=YES rows=93102
[TRAIN][5M] asof=2023-01-30 feats=69 buy=YES sell=YES rows=93286
[TRAIN][5M] asof=2023-02-06 feats=69 buy=YES sell=YES rows=93507
[TRAIN][5M] asof=2023-02-13 feats=69 buy=YES sell=YES rows=93723
[TRAIN][5M] asof=2023-02-21 feats=69 buy=YES sell=YES rows=93870
[TRAIN][5M] asof=2023-02-27 feats=69 buy=YES sell=YES rows=94003
[TRAIN][5M] asof=2023-03-06 feats=69 buy=YES sell=YES rows=94236
[TRAIN][5M] asof=2023-03-13 feats=69 buy=YES sell=YES rows=94409
[TRAIN][5M] asof=2023-03-20 feats=69 buy=YES sell=YES rows=94596
[TRAIN][5M] asof=2023-03-27 feats=69 buy=YES sell=YES rows=94786
[TRAIN][5M] asof=2023-04-03 feats=69 buy=YES sell=YES rows=94997
[TRAIN][5M] asof=2023-04-10 feats=69 buy=YES sell=YES rows=95147
[TRAIN][5M] asof=2023-04-17 feats=69 buy=YES sell=YES rows=95352
[TRAIN][5M] asof=2023-04-24 feats=69 buy=YES sell=YES rows=95536
[TRAIN][5M] asof=2023-05-01 feats=69 buy=YES sell=YES rows=95729
[TRAIN][5M] asof=2023-05-08 feats=69 buy=YES sell=YES rows=95932
[TRAIN][5M] asof=2023-05-15 feats=69 buy=YES sell=YES rows=96100
[TRAIN][5M] asof=2023-05-22 feats=69 buy=YES sell=YES rows=96235
[TRAIN][5M] asof=2023-05-30 feats=69 buy=YES sell=YES rows=96479
[TRAIN][5M] asof=2023-06-05 feats=69 buy=YES sell=YES rows=96621
[TRAIN][5M] asof=2023-06-12 feats=69 buy=YES sell=YES rows=96826
[TRAIN][5M] asof=2023-06-20 feats=69 buy=YES sell=YES rows=97001
[TRAIN][5M] asof=2023-06-26 feats=69 buy=YES sell=YES rows=97203
[TRAIN][5M] asof=2023-07-03 feats=69 buy=YES sell=YES rows=97408
[TRAIN][5M] asof=2023-07-10 feats=69 buy=YES sell=YES rows=97564
[TRAIN][5M] asof=2023-07-17 feats=69 buy=YES sell=YES rows=97767
[TRAIN][5M] asof=2023-07-24 feats=69 buy=YES sell=YES rows=97922
[TRAIN][5M] asof=2023-07-31 feats=69 buy=YES sell=YES rows=98138
[TRAIN][5M] asof=2023-08-07 feats=69 buy=YES sell=YES rows=98328
[TRAIN][5M] asof=2023-08-14 feats=69 buy=YES sell=YES rows=98522
[TRAIN][5M] asof=2023-08-21 feats=69 buy=YES sell=YES rows=98738
[TRAIN][5M] asof=2023-08-28 feats=69 buy=YES sell=YES rows=98979
[TRAIN][5M] asof=2023-09-05 feats=69 buy=YES sell=YES rows=99155
[TRAIN][5M] asof=2023-09-11 feats=69 buy=YES sell=YES rows=99292
[TRAIN][5M] asof=2023-09-18 feats=69 buy=YES sell=YES rows=99474
[TRAIN][5M] asof=2023-09-25 feats=69 buy=YES sell=YES rows=99679
[TRAIN][5M] asof=2023-10-02 feats=69 buy=YES sell=YES rows=99873
[TRAIN][5M] asof=2023-10-09 feats=69 buy=YES sell=YES rows=100066
[TRAIN][5M] asof=2023-10-16 feats=69 buy=YES sell=YES rows=100239
[TRAIN][5M] asof=2023-10-23 feats=69 buy=YES sell=YES rows=100474
[TRAIN][5M] asof=2023-10-30 feats=69 buy=YES sell=YES rows=100681
[TRAIN][5M] asof=2023-11-06 feats=69 buy=YES sell=YES rows=100856
[TRAIN][5M] asof=2023-11-13 feats=69 buy=YES sell=YES rows=101048
[TRAIN][5M] asof=2023-11-20 feats=69 buy=YES sell=YES rows=101246
[TRAIN][5M] asof=2023-11-27 feats=69 buy=YES sell=YES rows=101406
[TRAIN][5M] asof=2023-12-04 feats=69 buy=YES sell=YES rows=101648
[TRAIN][5M] asof=2023-12-11 feats=69 buy=YES sell=YES rows=101850
[TRAIN][5M] asof=2023-12-18 feats=69 buy=YES sell=YES rows=102077
[TRAIN][5M] asof=2023-12-26 feats=69 buy=YES sell=YES rows=102226
[TRAIN][5M] asof=2024-01-02 feats=69 buy=YES sell=YES rows=102339
[TRAIN][5M] asof=2024-01-08 feats=69 buy=YES sell=YES rows=102485
[TRAIN][5M] asof=2024-01-16 feats=69 buy=YES sell=YES rows=102769
[TRAIN][5M] asof=2024-01-22 feats=69 buy=YES sell=YES rows=102957
[TRAIN][5M] asof=2024-01-29 feats=69 buy=YES sell=YES rows=103112
[TRAIN][5M] asof=2024-02-05 feats=69 buy=YES sell=YES rows=103281
[TRAIN][5M] asof=2024-02-12 feats=69 buy=YES sell=YES rows=103436
[TRAIN][5M] asof=2024-02-20 feats=69 buy=YES sell=YES rows=103612
[TRAIN][5M] asof=2024-02-26 feats=69 buy=YES sell=YES rows=103770
[TRAIN][5M] asof=2024-03-04 feats=69 buy=YES sell=YES rows=103979
[TRAIN][5M] asof=2024-03-11 feats=69 buy=YES sell=YES rows=104200
[TRAIN][5M] asof=2024-03-18 feats=69 buy=YES sell=YES rows=104361
[TRAIN][5M] asof=2024-03-25 feats=69 buy=YES sell=YES rows=104554
[TRAIN][5M] asof=2024-04-01 feats=69 buy=YES sell=YES rows=104675
[TRAIN][5M] asof=2024-04-08 feats=69 buy=YES sell=YES rows=104801
[TRAIN][5M] asof=2024-04-15 feats=69 buy=YES sell=YES rows=104992
[TRAIN][5M] asof=2024-04-22 feats=69 buy=YES sell=YES rows=105127
[TRAIN][5M] asof=2024-04-29 feats=69 buy=YES sell=YES rows=105348
[TRAIN][5M] asof=2024-05-06 feats=69 buy=YES sell=YES rows=105510
[TRAIN][5M] asof=2024-05-13 feats=69 buy=YES sell=YES rows=105648
[TRAIN][5M] asof=2024-05-20 feats=69 buy=YES sell=YES rows=105792
[TRAIN][5M] asof=2024-05-28 feats=69 buy=YES sell=YES rows=105986
[TRAIN][5M] asof=2024-06-03 feats=69 buy=YES sell=YES rows=106160
[TRAIN][5M] asof=2024-06-10 feats=69 buy=YES sell=YES rows=106335
[TRAIN][5M] asof=2024-06-17 feats=69 buy=YES sell=YES rows=106513
[TRAIN][5M] asof=2024-06-24 feats=69 buy=YES sell=YES rows=106647
[TRAIN][5M] asof=2024-07-01 feats=69 buy=YES sell=YES rows=106795
[TRAIN][5M] asof=2024-07-08 feats=69 buy=YES sell=YES rows=106914
[TRAIN][5M] asof=2024-07-15 feats=69 buy=YES sell=YES rows=107095
[TRAIN][5M] asof=2024-07-22 feats=69 buy=YES sell=YES rows=107328
[TRAIN][5M] asof=2024-07-29 feats=69 buy=YES sell=YES rows=107585
[TRAIN][5M] asof=2024-08-05 feats=69 buy=YES sell=YES rows=107826
[TRAIN][5M] asof=2024-08-12 feats=69 buy=YES sell=YES rows=107979
[TRAIN][5M] asof=2024-08-19 feats=69 buy=YES sell=YES rows=108168
[TRAIN][5M] asof=2024-08-26 feats=69 buy=YES sell=YES rows=108370
[TRAIN][5M] asof=2024-09-03 feats=69 buy=YES sell=YES rows=108533
[TRAIN][5M] asof=2024-09-09 feats=69 buy=YES sell=YES rows=108696
[TRAIN][5M] asof=2024-09-16 feats=69 buy=YES sell=YES rows=108907
[TRAIN][5M] asof=2024-09-23 feats=69 buy=YES sell=YES rows=109109
[TRAIN][5M] asof=2024-09-30 feats=69 buy=YES sell=YES rows=109265
[TRAIN][5M] asof=2024-10-07 feats=69 buy=YES sell=YES rows=109408
[TRAIN][5M] asof=2024-10-14 feats=69 buy=YES sell=YES rows=109578
[TRAIN][5M] asof=2024-10-21 feats=69 buy=YES sell=YES rows=109786
[TRAIN][5M] asof=2024-10-28 feats=69 buy=YES sell=YES rows=110001
[TRAIN][5M] asof=2024-11-04 feats=69 buy=YES sell=YES rows=110194
[TRAIN][5M] asof=2024-11-11 feats=69 buy=YES sell=YES rows=110362
[TRAIN][5M] asof=2024-11-18 feats=69 buy=YES sell=YES rows=110542
[TRAIN][5M] asof=2024-11-25 feats=69 buy=YES sell=YES rows=110733
[TRAIN][5M] asof=2024-12-02 feats=69 buy=YES sell=YES rows=110850
[TRAIN][5M] asof=2024-12-09 feats=69 buy=YES sell=YES rows=111027
[TRAIN][5M] asof=2024-12-16 feats=69 buy=YES sell=YES rows=111220
[TRAIN][5M] asof=2024-12-23 feats=69 buy=YES sell=YES rows=111403
[TRAIN][5M] asof=2024-12-30 feats=69 buy=YES sell=YES rows=111572
[TRAIN][5M] asof=2025-01-06 feats=69 buy=YES sell=YES rows=111707
[TRAIN][5M] asof=2025-01-13 feats=69 buy=YES sell=YES rows=111888
[TRAIN][5M] asof=2025-01-21 feats=69 buy=YES sell=YES rows=112099
[TRAIN][5M] asof=2025-01-27 feats=69 buy=YES sell=YES rows=112246
[TRAIN][5M] asof=2025-02-03 feats=69 buy=YES sell=YES rows=112455
[TRAIN][5M] asof=2025-02-10 feats=69 buy=YES sell=YES rows=112635
[TRAIN][5M] asof=2025-02-18 feats=69 buy=YES sell=YES rows=112762
[TRAIN][5M] asof=2025-02-24 feats=69 buy=YES sell=YES rows=112932
[TRAIN][5M] asof=2025-03-03 feats=69 buy=YES sell=YES rows=113108
[TRAIN][5M] asof=2025-03-10 feats=69 buy=YES sell=YES rows=113317
[TRAIN][5M] asof=2025-03-17 feats=69 buy=YES sell=YES rows=113501
[TRAIN][5M] asof=2025-03-24 feats=69 buy=YES sell=YES rows=113699
[TRAIN][5M] asof=2025-03-31 feats=69 buy=YES sell=YES rows=113916
[TRAIN][5M] asof=2025-04-07 feats=69 buy=YES sell=YES rows=114114
[TRAIN][5M] asof=2025-04-14 feats=69 buy=YES sell=YES rows=114309
[TRAIN][5M] asof=2025-04-21 feats=69 buy=YES sell=YES rows=114441
[TRAIN][5M] asof=2025-04-28 feats=69 buy=YES sell=YES rows=114692
[TRAIN][5M] asof=2025-05-05 feats=69 buy=YES sell=YES rows=114928
[TRAIN][5M] asof=2025-05-12 feats=69 buy=YES sell=YES rows=115082
[TRAIN][5M] asof=2025-05-19 feats=69 buy=YES sell=YES rows=115263
[TRAIN][5M] asof=2025-05-27 feats=69 buy=YES sell=YES rows=115454
[TRAIN][5M] asof=2025-06-02 feats=69 buy=YES sell=YES rows=115577
[TRAIN][5M] asof=2025-06-09 feats=69 buy=YES sell=YES rows=115738
[TRAIN][5M] asof=2025-06-16 feats=69 buy=YES sell=YES rows=115857
[TRAIN][5M] asof=2025-06-23 feats=69 buy=YES sell=YES rows=115999
[TRAIN][5M] asof=2025-06-30 feats=69 buy=YES sell=YES rows=116146
[TRAIN][5M] asof=2025-07-07 feats=69 buy=YES sell=YES rows=116304
[TRAIN][5M] asof=2025-07-14 feats=69 buy=YES sell=YES rows=116470
[TRAIN][5M] asof=2025-07-21 feats=69 buy=YES sell=YES rows=116682
[TRAIN][5M] asof=2025-07-28 feats=69 buy=YES sell=YES rows=116892
[TRAIN][5M] asof=2025-08-04 feats=69 buy=YES sell=YES rows=117080
[TRAIN][5M] asof=2025-08-11 feats=69 buy=YES sell=YES rows=117254
[TRAIN][5M] asof=2025-08-18 feats=69 buy=YES sell=YES rows=117408
[TRAIN][5M] asof=2025-08-25 feats=69 buy=YES sell=YES rows=117593
[TRAIN][5M] asof=2025-09-02 feats=69 buy=YES sell=YES rows=117750
[TRAIN][5M] asof=2025-09-08 feats=69 buy=YES sell=YES rows=117888
[TRAIN][5M] asof=2025-09-15 feats=69 buy=YES sell=YES rows=118040
[TRAIN][5M] asof=2025-09-22 feats=69 buy=YES sell=YES rows=118267
[TRAIN][5M] asof=2025-09-29 feats=69 buy=YES sell=YES rows=118457
[TRAIN][5M] asof=2025-10-06 feats=69 buy=YES sell=YES rows=118683
[TRAIN][5M] asof=2025-10-13 feats=69 buy=YES sell=YES rows=118879
[TRAIN][5M] asof=2025-10-20 feats=69 buy=YES sell=YES rows=119095
[TRAIN][5M] asof=2025-10-27 feats=69 buy=YES sell=YES rows=119297

MemoryError: Unable to allocate 3.77 MiB for an array with shape (7, 70616) and data type int64

In [ ]:
from adaptive_reward_checkpoint_fresh import (
    build_adaptive_reward_snapshot,
    run_adaptive_reward_from_snapshot_chronological,
    load_joblib,
)
from adaptive_trade_extensions import make_ret_grid

old_checkpoint = r"output_adaptive_reward_snapshot_build_QQQ_252days_at_2020\year_start_checkpoints\final_checkpoint__start_2020.joblib"
old = load_joblib(old_checkpoint)

build_dir = r"output_QQQ_build_direct_gate_open_close_reward_at_2020"
checkpoint = build_dir + r"\direct_gate_checkpoint_before_2020.joblib"

build_res = build_adaptive_reward_snapshot(
    daily_csv_path=old["daily_csv_path"],
    k5m_csv_path=old["k5m_csv_path"],
    snapshot_path=checkpoint,

    code=old.get("code", "QQQ"),
    daily_chan_start=old["original_daily_chan_start"],
    accumulation_start=old["original_accumulation_start"],
    snapshot_end_time="2019-12-31 16:00:00",

    threshold_ret_grid=make_ret_grid(5, 25, 0.5),

    daily_gate_mode="direct",
    daily_reward_mode="open_close_forced",
    daily_direct_gate_min_samples=60,

    output_dir=build_dir,
    autosave_year_start_checkpoints=False,
    verbose=True,
)

res = run_adaptive_reward_from_snapshot_chronological(
    snapshot_path=checkpoint,
    end_time="2026-06-12 16:00:00",
    sim_start="2020-01-01 09:30:00",
    trade_start="2020-01-01 09:30:00",

    output_dir=r"output_QQQ_direct_gate_open_close_reward_2020_20260612",
    save_snapshot_path=r"output_QQQ_direct_gate_open_close_reward_2020_20260612\continued_checkpoint.joblib",

    reset_execution_state=True,
    initial_capital=100000.0,
    fee_pct=0.0,

    threshold_ret_grid_override=make_ret_grid(5, 25, 0.5),

    daily_gate_mode="direct",
    daily_reward_mode="open_close_forced",
    daily_direct_gate_min_samples=60,

    autosave_year_start_checkpoints=False,
    verbose=True,
)

print("Output dir:", res["output_dir"])
print("Continued checkpoint:", res["continued_snapshot_path"])

print(res["daily_log_df"][[
    "date",
    "daily_action",
    "daily_gate_mode",
    "daily_reward_mode",
    "p_day",
    "direct_gate_prob_force_buy",
    "direct_gate_prob_free",
    "direct_gate_prob_force_sell",
]].tail(30))

print(res["daily_reward_df"].groupby("chosen_action")["chosen_reward"].agg(
    ["count", "mean", "median", "sum", "std", "min", "max"]
))

In [1]:
from pathlib import Path
import pandas as pd

from adaptive_reward_checkpoint_fresh import (
    build_adaptive_reward_snapshot,
    run_adaptive_reward_from_snapshot_chronological,
)

from adaptive_trade_extensions import (
    RollingThresholdConfig,
    make_threshold_grid,
    make_ret_grid,
)

five_min_grid = make_ret_grid(0, 25, 0.5)

common_kwargs = dict(
    daily_csv_path="DataAPI/data/QQQ_day.csv",
    k5m_csv_path="DataAPI/data/QQQ_5M.csv",
    code="QQQ",
    daily_chan_start="2010-02-11",
    accumulation_start="2012-02-11",
    N_confirm=5,
    min_labeled_days_to_train=200,
    retrain_every_new_labels=25,
    dp_lookback=252,
    lookahead_days_5m=2.0,
    retrain_every_days_5m=5,
    min_samples_total_5m=300,
    threshold_window_days=2.0,
    threshold_ret_grid=five_min_grid,
    threshold_min_open_signals=10,
    initial_capital=100000.0,
    fee_pct=0.0,
    daily_chan_max_klines=500,
    five_chan_max_klines=500,
    macro_files={"vix_": "VIX.csv"},
    static_buy_level=0.20,
    static_sell_level=0.30,
    daily_threshold_config=RollingThresholdConfig(
        lookback_days=252,
        buy_grid=make_threshold_grid(0.05, 0.35, 0.005),
        sell_grid=make_threshold_grid(0.15, 0.60, 0.005),
        min_gap=0.02,
        min_obs=60,
        switch_penalty=0.0,
    ),
    verbose=True,
)

build_dir = Path("output_QQQ_build_prev_daily_context_at_2020")
checkpoint_path = build_dir / "fresh_checkpoint_prev_daily_context__before_2020.joblib"

# Build the clean pre-2020 checkpoint only if it does not already exist.
if checkpoint_path.exists():
    print("Using existing clean checkpoint:", checkpoint_path)
else:
    build_res = build_adaptive_reward_snapshot(
        snapshot_path=str(checkpoint_path),
        snapshot_end_time="2019-12-31 16:00:00",
        output_dir=str(build_dir),
        autosave_year_start_checkpoints=False,
        **common_kwargs,
    )

    print("Built checkpoint:", build_res["snapshot_path"])
    display(build_res["daily_reward_df"].tail())
    display(build_res["daily_log_df"].tail())

base_output_dir = Path("output_QQQ_chrono_prev_daily_context_wide_5m_resumable")
base_output_dir.mkdir(parents=True, exist_ok=True)

chunks = [
    ("2020", "2020-12-31 16:00:00"),
    ("2021", "2021-12-31 16:00:00"),
    ("2022", "2022-12-31 16:00:00"),
    ("2023", "2023-12-31 16:00:00"),
    ("2024", "2024-12-31 16:00:00"),
    ("2025", "2025-12-31 16:00:00"),
    ("2026", "2026-06-12 16:00:00"),
]

current_checkpoint = checkpoint_path
last_res = None

for year, chunk_end_time in chunks:
    chunk_dir = base_output_dir / f"chunk_{year}"
    chunk_checkpoint = chunk_dir / f"continued_checkpoint__through_{year}.joblib"

    # If this chunk already finished in a previous run, skip it and resume from it.
    if chunk_checkpoint.exists():
        print(f"[SKIP] {year} already completed:", chunk_checkpoint)
        current_checkpoint = chunk_checkpoint
        continue

    print(f"[RUN] {year}: {current_checkpoint} -> {chunk_end_time}")

    is_first_chunk = Path(current_checkpoint) == checkpoint_path

    last_res = run_adaptive_reward_from_snapshot_chronological(
        snapshot_path=str(current_checkpoint),
        end_time=chunk_end_time,

        # Only needed for the first chunk from the clean pre-2020 checkpoint.
        sim_start="2020-01-01 09:30:00" if is_first_chunk else None,
        trade_start="2020-01-01 09:30:00" if is_first_chunk else None,

        output_dir=str(chunk_dir),
        save_snapshot_path=str(chunk_checkpoint),

        # First chunk starts a fresh portfolio. Later chunks preserve state from checkpoint.
        reset_execution_state=True if is_first_chunk else False,
        initial_capital=common_kwargs["initial_capital"],
        fee_pct=common_kwargs["fee_pct"],

        dp_lookback_override=common_kwargs["dp_lookback"],
        daily_threshold_lookback_days_override=252,
        threshold_ret_grid_override=five_min_grid,

        autosave_year_start_checkpoints=True,
        verbose=True,
    )

    print(f"[DONE] {year} checkpoint:", chunk_checkpoint)
    current_checkpoint = chunk_checkpoint

print("Final checkpoint:", current_checkpoint)

[TRAIN][DAILY-PROB] n=200 pos=42 (21.00%)
[TRAIN][DAILY-PROB] n=225 pos=50 (22.22%)
[TRAIN][DAILY-PROB] n=250 pos=55 (22.00%)
[TRAIN][DAILY-PROB] n=275 pos=59 (21.45%)
[TRAIN][DAILY-PROB] n=300 pos=69 (23.00%)
[TRAIN][DAILY-PROB] n=325 pos=69 (21.23%)
[TRAIN][DAILY-PROB] n=350 pos=69 (19.71%)
[TRAIN][DAILY-PROB] n=375 pos=72 (19.20%)
[TRAIN][DAILY-PROB] n=400 pos=81 (20.25%)
[TRAIN][DAILY-PROB] n=425 pos=91 (21.41%)
[TRAIN][DAILY-PROB] n=450 pos=100 (22.22%)
[TRAIN][DAILY-PROB] n=475 pos=103 (21.68%)
[TRAIN][DAILY-PROB] n=500 pos=106 (21.20%)
[TRAIN][DAILY-PROB] n=525 pos=115 (21.90%)
[TRAIN][DAILY-PROB] n=550 pos=121 (22.00%)
[TRAIN][DAILY-PROB] n=575 pos=125 (21.74%)
[TRAIN][DAILY-PROB] n=600 pos=132 (22.00%)
[TRAIN][DAILY-PROB] n=625 pos=137 (21.92%)
[TRAIN][DAILY-PROB] n=650 pos=147 (22.62%)
[TRAIN][DAILY-PROB] n=675 pos=152 (22.52%)
[TRAIN][DAILY-PROB] n=700 pos=157 (22.43%)
[TRAIN][DAILY-PROB] n=725 pos=161 (22.21%)
[TRAIN][DAILY-PROB] n=750 pos=167 (22.27%)
[TRAIN][DAILY-PROB] n=775 pos=168 (21.68%)
[TRAIN][DAILY-PROB] n=800 pos=171 (21.38%)
[TRAIN][DAILY-PROB] n=825 pos=174 (21.09%)
[TRAIN][DAILY-PROB] n=850 pos=177 (20.82%)
[TRAIN][DAILY-PROB] n=875 pos=185 (21.14%)
[TRAIN][DAILY-PROB] n=900 pos=189 (21.00%)
[TRAIN][DAILY-PROB] n=925 pos=190 (20.54%)
[TRAIN][DAILY-PROB] n=950 pos=190 (20.00%)
[TRAIN][DAILY-PROB] n=975 pos=193 (19.79%)
[TRAIN][DAILY-PROB] n=1000 pos=199 (19.90%)
[TRAIN][DAILY-PROB] n=1025 pos=203 (19.80%)
[TRAIN][DAILY-PROB] n=1050 pos=209 (19.90%)
[TRAIN][DAILY-PROB] n=1075 pos=216 (20.09%)
[TRAIN][DAILY-PROB] n=1100 pos=218 (19.82%)
[TRAIN][DAILY-PROB] n=1125 pos=227 (20.18%)
[TRAIN][DAILY-PROB] n=1150 pos=233 (20.26%)
[TRAIN][DAILY-PROB] n=1175 pos=237 (20.17%)
[TRAIN][DAILY-PROB] n=1200 pos=247 (20.58%)
[TRAIN][DAILY-PROB] n=1225 pos=254 (20.73%)
[TRAIN][DAILY-PROB] n=1250 pos=264 (21.12%)
[TRAIN][DAILY-PROB] n=1275 pos=271 (21.25%)
[TRAIN][DAILY-PROB] n=1300 pos=280 (21.54%)
[TRAIN][DAILY-PROB] n=1325 pos=285 (21.51%)
[TRAIN][DAILY-PROB] n=1350 pos=293 (21.70%)
[TRAIN][DAILY-PROB] n=1375 pos=302 (21.96%)
[TRAIN][DAILY-PROB] n=1400 pos=304 (21.71%)
[TRAIN][DAILY-PROB] n=1425 pos=311 (21.82%)
[TRAIN][DAILY-PROB] n=1450 pos=318 (21.93%)
[TRAIN][DAILY-PROB] n=1475 pos=319 (21.63%)
[TRAIN][DAILY-PROB] n=1500 pos=329 (21.93%)
[TRAIN][DAILY-PROB] n=1525 pos=336 (22.03%)
[TRAIN][DAILY-PROB] n=1550 pos=339 (21.87%)
[TRAIN][DAILY-PROB] n=1575 pos=342 (21.71%)
[TRAIN][DAILY-PROB] n=1600 pos=343 (21.44%)
[TRAIN][DAILY-PROB] n=1625 pos=346 (21.29%)
[TRAIN][DAILY-PROB] n=1650 pos=348 (21.09%)
[TRAIN][DAILY-PROB] n=1675 pos=349 (20.84%)
[TRAIN][DAILY-PROB] n=1700 pos=355 (20.88%)
[TRAIN][DAILY-PROB] n=1725 pos=359 (20.81%)
[TRAIN][DAILY-PROB] n=1750 pos=366 (20.91%)
[TRAIN][DAILY-PROB] n=1775 pos=367 (20.68%)
[TRAIN][DAILY-PROB] n=1800 pos=370 (20.56%)
[TRAIN][DAILY-PROB] n=1825 pos=374 (20.49%)
[TRAIN][DAILY-PROB] n=1850 pos=381 (20.59%)
[TRAIN][DAILY-PROB] n=1875 pos=390 (20.80%)
[TRAIN][DAILY-PROB] n=1900 pos=395 (20.79%)
[TRAIN][DAILY-PROB] n=1925 pos=396 (20.57%)
[TRAIN][DAILY-PROB] n=1950 pos=401 (20.56%)
[TRAIN][DAILY-PROB] n=1975 pos=406 (20.56%)
[TRAIN][DAILY-PROB] n=2000 pos=410 (20.50%)
[TRAIN][DAILY-PROB] n=2025 pos=423 (20.89%)
[TRAIN][DAILY-PROB] n=2050 pos=437 (21.32%)
[TRAIN][DAILY-PROB] n=2075 pos=445 (21.45%)
[TRAIN][DAILY-PROB] n=2100 pos=446 (21.24%)
[TRAIN][DAILY-PROB] n=2125 pos=449 (21.13%)
[TRAIN][DAILY-PROB] n=2150 pos=454 (21.12%)
[TRAIN][DAILY-PROB] n=2175 pos=465 (21.38%)
[TRAIN][DAILY-PROB] n=2200 pos=467 (21.23%)
[TRAIN][DAILY-PROB] n=2225 pos=475 (21.35%)
[TRAIN][DAILY-PROB] n=2250 pos=479 (21.29%)
[TRAIN][DAILY-PROB] n=2275 pos=486 (21.36%)
[TRAIN][DAILY-PROB] n=2300 pos=488 (21.22%)
[TRAIN][5M] asof=2012-03-07 feats=114 buy=NO sell=YES rows=550
[TRAIN][5M] asof=2012-03-12 feats=114 buy=NO sell=YES rows=640
[TRAIN][5M] asof=2012-03-19 feats=114 buy=NO sell=YES rows=750
[TRAIN][5M] asof=2012-03-26 feats=114 buy=NO sell=YES rows=938
[TRAIN][5M] asof=2012-04-02 feats=114 buy=NO sell=YES rows=1055
[TRAIN][5M] asof=2012-04-09 feats=114 buy=YES sell=YES rows=1155
[TRAIN][5M] asof=2012-04-16 feats=114 buy=YES sell=YES rows=1298
[TRAIN][5M] asof=2012-04-23 feats=114 buy=YES sell=YES rows=1439
[TRAIN][5M] asof=2012-04-30 feats=114 buy=YES sell=YES rows=1607
[TRAIN][5M] asof=2012-05-07 feats=114 buy=YES sell=YES rows=1777
[TRAIN][5M] asof=2012-05-14 feats=114 buy=YES sell=YES rows=1977
[TRAIN][5M] asof=2012-05-21 feats=114 buy=YES sell=YES rows=2124
[TRAIN][5M] asof=2012-05-29 feats=114 buy=YES sell=YES rows=2294
[TRAIN][5M] asof=2012-06-04 feats=114 buy=YES sell=YES rows=2378
[TRAIN][5M] asof=2012-06-11 feats=114 buy=YES sell=YES rows=2550
[TRAIN][5M] asof=2012-06-18 feats=114 buy=YES sell=YES rows=2680
[TRAIN][5M] asof=2012-06-25 feats=114 buy=YES sell=YES rows=2799
[TRAIN][5M] asof=2012-07-02 feats=114 buy=YES sell=YES rows=2915
[TRAIN][5M] asof=2012-07-09 feats=114 buy=YES sell=YES rows=3012
[TRAIN][5M] asof=2012-07-16 feats=114 buy=YES sell=YES rows=3122
[TRAIN][5M] asof=2012-07-23 feats=114 buy=YES sell=YES rows=3260
[TRAIN][5M] asof=2012-07-30 feats=114 buy=YES sell=YES rows=3379
[TRAIN][5M] asof=2012-08-06 feats=114 buy=YES sell=YES rows=3541
[TRAIN][5M] asof=2012-08-13 feats=114 buy=YES sell=YES rows=3660
[TRAIN][5M] asof=2012-08-20 feats=114 buy=YES sell=YES rows=3807
[TRAIN][5M] asof=2012-08-27 feats=114 buy=YES sell=YES rows=3990
[TRAIN][5M] asof=2012-09-04 feats=114 buy=YES sell=YES rows=4130
[TRAIN][5M] asof=2012-09-10 feats=114 buy=YES sell=YES rows=4253
[TRAIN][5M] asof=2012-09-17 feats=114 buy=YES sell=YES rows=4409
[TRAIN][5M] asof=2012-09-24 feats=114 buy=YES sell=YES rows=4524
[TRAIN][5M] asof=2012-10-01 feats=114 buy=YES sell=YES rows=4666
[TRAIN][5M] asof=2012-10-08 feats=114 buy=YES sell=YES rows=4837
[TRAIN][5M] asof=2012-10-15 feats=114 buy=YES sell=YES rows=5010
[TRAIN][5M] asof=2012-10-22 feats=114 buy=YES sell=YES rows=5111
[TRAIN][5M] asof=2012-10-31 feats=114 buy=YES sell=YES rows=5258
[TRAIN][5M] asof=2012-11-05 feats=114 buy=YES sell=YES rows=5347
[TRAIN][5M] asof=2012-11-12 feats=114 buy=YES sell=YES rows=5512
[TRAIN][5M] asof=2012-11-19 feats=114 buy=YES sell=YES rows=5638
[TRAIN][5M] asof=2012-11-26 feats=114 buy=YES sell=YES rows=5753
[TRAIN][5M] asof=2012-12-03 feats=114 buy=YES sell=YES rows=5886
[TRAIN][5M] asof=2012-12-10 feats=114 buy=YES sell=YES rows=6029
[TRAIN][5M] asof=2012-12-17 feats=114 buy=YES sell=YES rows=6151
[TRAIN][5M] asof=2012-12-24 feats=114 buy=YES sell=YES rows=6255
[TRAIN][5M] asof=2012-12-31 feats=114 buy=YES sell=YES rows=6330
[TRAIN][5M] asof=2013-01-07 feats=114 buy=YES sell=YES rows=6413
[TRAIN][5M] asof=2013-01-14 feats=114 buy=YES sell=YES rows=6525
[TRAIN][5M] asof=2013-01-22 feats=114 buy=YES sell=YES rows=6632
[TRAIN][5M] asof=2013-01-28 feats=114 buy=YES sell=YES rows=6782
[TRAIN][5M] asof=2013-02-04 feats=114 buy=YES sell=YES rows=6946
[TRAIN][5M] asof=2013-02-11 feats=114 buy=YES sell=YES rows=7098
[TRAIN][5M] asof=2013-02-19 feats=114 buy=YES sell=YES rows=7255
[TRAIN][5M] asof=2013-02-25 feats=114 buy=YES sell=YES rows=7393
[TRAIN][5M] asof=2013-03-04 feats=114 buy=YES sell=YES rows=7536
[TRAIN][5M] asof=2013-03-11 feats=114 buy=YES sell=YES rows=7693
[TRAIN][5M] asof=2013-03-18 feats=114 buy=YES sell=YES rows=7817
[TRAIN][5M] asof=2013-03-25 feats=114 buy=YES sell=YES rows=7933
[TRAIN][5M] asof=2013-04-01 feats=114 buy=YES sell=YES rows=8067
[TRAIN][5M] asof=2013-04-08 feats=114 buy=YES sell=YES rows=8144
[TRAIN][5M] asof=2013-04-15 feats=114 buy=YES sell=YES rows=8261
[TRAIN][5M] asof=2013-04-22 feats=114 buy=YES sell=YES rows=8385
[TRAIN][5M] asof=2013-04-29 feats=114 buy=YES sell=YES rows=8465
[TRAIN][5M] asof=2013-05-06 feats=114 buy=YES sell=YES rows=8601
[TRAIN][5M] asof=2013-05-13 feats=114 buy=YES sell=YES rows=8737
[TRAIN][5M] asof=2013-05-20 feats=114 buy=YES sell=YES rows=8865
[TRAIN][5M] asof=2013-05-28 feats=114 buy=YES sell=YES rows=9020
[TRAIN][5M] asof=2013-06-03 feats=114 buy=YES sell=YES rows=9181
[TRAIN][5M] asof=2013-06-10 feats=114 buy=YES sell=YES rows=9300
[TRAIN][5M] asof=2013-06-17 feats=114 buy=YES sell=YES rows=9437
[TRAIN][5M] asof=2013-06-24 feats=114 buy=YES sell=YES rows=9617
[TRAIN][5M] asof=2013-07-01 feats=114 buy=YES sell=YES rows=9791
[TRAIN][5M] asof=2013-07-08 feats=114 buy=YES sell=YES rows=9875
[TRAIN][5M] asof=2013-07-15 feats=114 buy=YES sell=YES rows=10015
[TRAIN][5M] asof=2013-07-22 feats=114 buy=YES sell=YES rows=10134
[TRAIN][5M] asof=2013-07-29 feats=114 buy=YES sell=YES rows=10303
[TRAIN][5M] asof=2013-08-05 feats=114 buy=YES sell=YES rows=10440
[TRAIN][5M] asof=2013-08-12 feats=114 buy=YES sell=YES rows=10585
[TRAIN][5M] asof=2013-08-19 feats=114 buy=YES sell=YES rows=10810
[TRAIN][5M] asof=2013-08-26 feats=114 buy=YES sell=YES rows=10936
[TRAIN][5M] asof=2013-09-03 feats=114 buy=YES sell=YES rows=11112
[TRAIN][5M] asof=2013-09-09 feats=114 buy=YES sell=YES rows=11246
[TRAIN][5M] asof=2013-09-16 feats=114 buy=YES sell=YES rows=11433
[TRAIN][5M] asof=2013-09-23 feats=114 buy=YES sell=YES rows=11548
[TRAIN][5M] asof=2013-09-30 feats=114 buy=YES sell=YES rows=11749
[TRAIN][5M] asof=2013-10-07 feats=114 buy=YES sell=YES rows=11885
[TRAIN][5M] asof=2013-10-14 feats=114 buy=YES sell=YES rows=12075
[TRAIN][5M] asof=2013-10-21 feats=114 buy=YES sell=YES rows=12237
[TRAIN][5M] asof=2013-10-28 feats=114 buy=YES sell=YES rows=12373
[TRAIN][5M] asof=2013-11-04 feats=114 buy=YES sell=YES rows=12575
[TRAIN][5M] asof=2013-11-11 feats=114 buy=YES sell=YES rows=12752
[TRAIN][5M] asof=2013-11-18 feats=114 buy=YES sell=YES rows=12888
[TRAIN][5M] asof=2013-11-25 feats=114 buy=YES sell=YES rows=13047
[TRAIN][5M] asof=2013-12-02 feats=114 buy=YES sell=YES rows=13146
[TRAIN][5M] asof=2013-12-09 feats=114 buy=YES sell=YES rows=13322
[TRAIN][5M] asof=2013-12-16 feats=114 buy=YES sell=YES rows=13502
[TRAIN][5M] asof=2013-12-23 feats=114 buy=YES sell=YES rows=13707
[TRAIN][5M] asof=2013-12-30 feats=114 buy=YES sell=YES rows=13833
[TRAIN][5M] asof=2014-01-06 feats=114 buy=YES sell=YES rows=13924
[TRAIN][5M] asof=2014-01-13 feats=114 buy=YES sell=YES rows=14034
[TRAIN][5M] asof=2014-01-21 feats=114 buy=YES sell=YES rows=14173
[TRAIN][5M] asof=2014-01-27 feats=114 buy=YES sell=YES rows=14310
[TRAIN][5M] asof=2014-02-03 feats=114 buy=YES sell=YES rows=14487
[TRAIN][5M] asof=2014-02-10 feats=114 buy=YES sell=YES rows=14614
[TRAIN][5M] asof=2014-02-18 feats=114 buy=YES sell=YES rows=14792
[TRAIN][5M] asof=2014-02-24 feats=114 buy=YES sell=YES rows=14894
[TRAIN][5M] asof=2014-03-03 feats=114 buy=YES sell=YES rows=15078
[TRAIN][5M] asof=2014-03-10 feats=114 buy=YES sell=YES rows=15193
[TRAIN][5M] asof=2014-03-17 feats=114 buy=YES sell=YES rows=15359
[TRAIN][5M] asof=2014-03-24 feats=114 buy=YES sell=YES rows=15514
[TRAIN][5M] asof=2014-03-31 feats=114 buy=YES sell=YES rows=15666
[TRAIN][5M] asof=2014-04-07 feats=114 buy=YES sell=YES rows=15807
[TRAIN][5M] asof=2014-04-14 feats=114 buy=YES sell=YES rows=15992
[TRAIN][5M] asof=2014-04-21 feats=114 buy=YES sell=YES rows=16153
[TRAIN][5M] asof=2014-04-28 feats=114 buy=YES sell=YES rows=16333
[TRAIN][5M] asof=2014-05-05 feats=114 buy=YES sell=YES rows=16473
[TRAIN][5M] asof=2014-05-12 feats=114 buy=YES sell=YES rows=16685
[TRAIN][5M] asof=2014-05-19 feats=114 buy=YES sell=YES rows=16831
[TRAIN][5M] asof=2014-05-27 feats=114 buy=YES sell=YES rows=16980
[TRAIN][5M] asof=2014-06-02 feats=114 buy=YES sell=YES rows=17069
[TRAIN][5M] asof=2014-06-09 feats=114 buy=YES sell=YES rows=17228
[TRAIN][5M] asof=2014-06-16 feats=114 buy=YES sell=YES rows=17377
[TRAIN][5M] asof=2014-06-23 feats=114 buy=YES sell=YES rows=17465
[TRAIN][5M] asof=2014-06-30 feats=114 buy=YES sell=YES rows=17587
[TRAIN][5M] asof=2014-07-07 feats=114 buy=YES sell=YES rows=17687
[TRAIN][5M] asof=2014-07-14 feats=114 buy=YES sell=YES rows=17834
[TRAIN][5M] asof=2014-07-21 feats=114 buy=YES sell=YES rows=17971
[TRAIN][5M] asof=2014-07-28 feats=114 buy=YES sell=YES rows=18107
[TRAIN][5M] asof=2014-08-04 feats=114 buy=YES sell=YES rows=18262
[TRAIN][5M] asof=2014-08-11 feats=114 buy=YES sell=YES rows=18438
[TRAIN][5M] asof=2014-08-18 feats=114 buy=YES sell=YES rows=18582
[TRAIN][5M] asof=2014-08-25 feats=114 buy=YES sell=YES rows=18697
[TRAIN][5M] asof=2014-09-02 feats=114 buy=YES sell=YES rows=18842
[TRAIN][5M] asof=2014-09-08 feats=114 buy=YES sell=YES rows=18977
[TRAIN][5M] asof=2014-09-15 feats=114 buy=YES sell=YES rows=19129
[TRAIN][5M] asof=2014-09-22 feats=114 buy=YES sell=YES rows=19292
[TRAIN][5M] asof=2014-09-29 feats=114 buy=YES sell=YES rows=19413
[TRAIN][5M] asof=2014-10-06 feats=114 buy=YES sell=YES rows=19515
[TRAIN][5M] asof=2014-10-13 feats=114 buy=YES sell=YES rows=19701
[TRAIN][5M] asof=2014-10-20 feats=114 buy=YES sell=YES rows=19894
[TRAIN][5M] asof=2014-10-27 feats=114 buy=YES sell=YES rows=20044
[TRAIN][5M] asof=2014-11-03 feats=114 buy=YES sell=YES rows=20183
[TRAIN][5M] asof=2014-11-10 feats=114 buy=YES sell=YES rows=20344
[TRAIN][5M] asof=2014-11-17 feats=114 buy=YES sell=YES rows=20511
[TRAIN][5M] asof=2014-11-24 feats=114 buy=YES sell=YES rows=20654
[TRAIN][5M] asof=2014-12-01 feats=114 buy=YES sell=YES rows=20698
[TRAIN][5M] asof=2014-12-08 feats=114 buy=YES sell=YES rows=20756
[TRAIN][5M] asof=2014-12-15 feats=114 buy=YES sell=YES rows=20942
[TRAIN][5M] asof=2014-12-22 feats=114 buy=YES sell=YES rows=21120
[TRAIN][5M] asof=2014-12-29 feats=114 buy=YES sell=YES rows=21243
[TRAIN][5M] asof=2015-01-05 feats=114 buy=YES sell=YES rows=21326
[TRAIN][5M] asof=2015-01-12 feats=114 buy=YES sell=YES rows=21456
[TRAIN][5M] asof=2015-01-20 feats=114 buy=YES sell=YES rows=21623
[TRAIN][5M] asof=2015-01-26 feats=114 buy=YES sell=YES rows=21734
[TRAIN][5M] asof=2015-02-02 feats=114 buy=YES sell=YES rows=21924
[TRAIN][5M] asof=2015-02-09 feats=114 buy=YES sell=YES rows=22055
[TRAIN][5M] asof=2015-02-17 feats=114 buy=YES sell=YES rows=22156
[TRAIN][5M] asof=2015-02-23 feats=114 buy=YES sell=YES rows=22240
[TRAIN][5M] asof=2015-03-02 feats=114 buy=YES sell=YES rows=22358
[TRAIN][5M] asof=2015-03-09 feats=114 buy=YES sell=YES rows=22477
[TRAIN][5M] asof=2015-03-16 feats=114 buy=YES sell=YES rows=22628
[TRAIN][5M] asof=2015-03-23 feats=114 buy=YES sell=YES rows=22757
[TRAIN][5M] asof=2015-03-30 feats=114 buy=YES sell=YES rows=22907
[TRAIN][5M] asof=2015-04-06 feats=114 buy=YES sell=YES rows=23032
[TRAIN][5M] asof=2015-04-13 feats=114 buy=YES sell=YES rows=23148
[TRAIN][5M] asof=2015-04-20 feats=114 buy=YES sell=YES rows=23255
[TRAIN][5M] asof=2015-04-27 feats=114 buy=YES sell=YES rows=23456
[TRAIN][5M] asof=2015-05-04 feats=114 buy=YES sell=YES rows=23594
[TRAIN][5M] asof=2015-05-11 feats=114 buy=YES sell=YES rows=23726
[TRAIN][5M] asof=2015-05-18 feats=114 buy=YES sell=YES rows=23886
[TRAIN][5M] asof=2015-05-26 feats=114 buy=YES sell=YES rows=24027
[TRAIN][5M] asof=2015-06-01 feats=114 buy=YES sell=YES rows=24140
[TRAIN][5M] asof=2015-06-08 feats=114 buy=YES sell=YES rows=24333
[TRAIN][5M] asof=2015-06-15 feats=114 buy=YES sell=YES rows=24450
[TRAIN][5M] asof=2015-06-22 feats=114 buy=YES sell=YES rows=24607
[TRAIN][5M] asof=2015-06-29 feats=114 buy=YES sell=YES rows=24780
[TRAIN][5M] asof=2015-07-06 feats=114 buy=YES sell=YES rows=24901
[TRAIN][5M] asof=2015-07-13 feats=114 buy=YES sell=YES rows=25047
[TRAIN][5M] asof=2015-07-20 feats=114 buy=YES sell=YES rows=25215
[TRAIN][5M] asof=2015-07-27 feats=114 buy=YES sell=YES rows=25452
[TRAIN][5M] asof=2015-08-03 feats=114 buy=YES sell=YES rows=25594
[TRAIN][5M] asof=2015-08-10 feats=114 buy=YES sell=YES rows=25777
[TRAIN][5M] asof=2015-08-17 feats=114 buy=YES sell=YES rows=25930
[TRAIN][5M] asof=2015-08-24 feats=114 buy=YES sell=YES rows=26085
[TRAIN][5M] asof=2015-08-31 feats=114 buy=YES sell=YES rows=26269
[TRAIN][5M] asof=2015-09-08 feats=114 buy=YES sell=YES rows=26410
[TRAIN][5M] asof=2015-09-14 feats=114 buy=YES sell=YES rows=26518
[TRAIN][5M] asof=2015-09-21 feats=114 buy=YES sell=YES rows=26712
[TRAIN][5M] asof=2015-09-28 feats=114 buy=YES sell=YES rows=26911
[TRAIN][5M] asof=2015-10-05 feats=114 buy=YES sell=YES rows=27105
[TRAIN][5M] asof=2015-10-12 feats=114 buy=YES sell=YES rows=27295
[TRAIN][5M] asof=2015-10-19 feats=114 buy=YES sell=YES rows=27494
[TRAIN][5M] asof=2015-10-26 feats=114 buy=YES sell=YES rows=27711
[TRAIN][5M] asof=2015-11-02 feats=114 buy=YES sell=YES rows=27884
[TRAIN][5M] asof=2015-11-09 feats=114 buy=YES sell=YES rows=28056
[TRAIN][5M] asof=2015-11-16 feats=114 buy=YES sell=YES rows=28269
[TRAIN][5M] asof=2015-11-23 feats=114 buy=YES sell=YES rows=28447
[TRAIN][5M] asof=2015-11-30 feats=114 buy=YES sell=YES rows=28538
[TRAIN][5M] asof=2015-12-07 feats=114 buy=YES sell=YES rows=28687
[TRAIN][5M] asof=2015-12-14 feats=114 buy=YES sell=YES rows=28877
[TRAIN][5M] asof=2015-12-21 feats=114 buy=YES sell=YES rows=29072
[TRAIN][5M] asof=2015-12-28 feats=114 buy=YES sell=YES rows=29176
[TRAIN][5M] asof=2016-01-04 feats=114 buy=YES sell=YES rows=29288
[TRAIN][5M] asof=2016-01-11 feats=114 buy=YES sell=YES rows=29443
[TRAIN][5M] asof=2016-01-19 feats=114 buy=YES sell=YES rows=29658
[TRAIN][5M] asof=2016-01-25 feats=114 buy=YES sell=YES rows=29805
[TRAIN][5M] asof=2016-02-01 feats=114 buy=YES sell=YES rows=30050
[TRAIN][5M] asof=2016-02-08 feats=114 buy=YES sell=YES rows=30246
[TRAIN][5M] asof=2016-02-16 feats=114 buy=YES sell=YES rows=30451
[TRAIN][5M] asof=2016-02-22 feats=114 buy=YES sell=YES rows=30617
[TRAIN][5M] asof=2016-02-29 feats=114 buy=YES sell=YES rows=30794
[TRAIN][5M] asof=2016-03-07 feats=114 buy=YES sell=YES rows=30993
[TRAIN][5M] asof=2016-03-14 feats=114 buy=YES sell=YES rows=31128
[TRAIN][5M] asof=2016-03-21 feats=114 buy=YES sell=YES rows=31263
[TRAIN][5M] asof=2016-03-28 feats=114 buy=YES sell=YES rows=31377
[TRAIN][5M] asof=2016-04-04 feats=114 buy=YES sell=YES rows=31551
[TRAIN][5M] asof=2016-04-11 feats=114 buy=YES sell=YES rows=31677
[TRAIN][5M] asof=2016-04-18 feats=114 buy=YES sell=YES rows=31842
[TRAIN][5M] asof=2016-04-25 feats=114 buy=YES sell=YES rows=32001
[TRAIN][5M] asof=2016-05-02 feats=114 buy=YES sell=YES rows=32177
[TRAIN][5M] asof=2016-05-09 feats=114 buy=YES sell=YES rows=32365
[TRAIN][5M] asof=2016-05-16 feats=114 buy=YES sell=YES rows=32529
[TRAIN][5M] asof=2016-05-23 feats=114 buy=YES sell=YES rows=32690
[TRAIN][5M] asof=2016-05-31 feats=114 buy=YES sell=YES rows=32846
[TRAIN][5M] asof=2016-06-06 feats=114 buy=YES sell=YES rows=32960
[TRAIN][5M] asof=2016-06-13 feats=114 buy=YES sell=YES rows=33103
[TRAIN][5M] asof=2016-06-20 feats=114 buy=YES sell=YES rows=33282
[TRAIN][5M] asof=2016-06-27 feats=114 buy=YES sell=YES rows=33489
[TRAIN][5M] asof=2016-07-05 feats=114 buy=YES sell=YES rows=33661
[TRAIN][5M] asof=2016-07-11 feats=114 buy=YES sell=YES rows=33785
[TRAIN][5M] asof=2016-07-18 feats=114 buy=YES sell=YES rows=33942
[TRAIN][5M] asof=2016-07-25 feats=114 buy=YES sell=YES rows=34084
[TRAIN][5M] asof=2016-08-01 feats=114 buy=YES sell=YES rows=34217
[TRAIN][5M] asof=2016-08-08 feats=114 buy=YES sell=YES rows=34387
[TRAIN][5M] asof=2016-08-15 feats=114 buy=YES sell=YES rows=34527
[TRAIN][5M] asof=2016-08-22 feats=114 buy=YES sell=YES rows=34646
[TRAIN][5M] asof=2016-08-29 feats=114 buy=YES sell=YES rows=34753
[TRAIN][5M] asof=2016-09-06 feats=114 buy=YES sell=YES rows=34915
[TRAIN][5M] asof=2016-09-12 feats=114 buy=YES sell=YES rows=35032
[TRAIN][5M] asof=2016-09-19 feats=114 buy=YES sell=YES rows=35198
[TRAIN][5M] asof=2016-09-26 feats=114 buy=YES sell=YES rows=35336
[TRAIN][5M] asof=2016-10-03 feats=114 buy=YES sell=YES rows=35492
[TRAIN][5M] asof=2016-10-10 feats=114 buy=YES sell=YES rows=35628
[TRAIN][5M] asof=2016-10-17 feats=114 buy=YES sell=YES rows=35764
[TRAIN][5M] asof=2016-10-24 feats=114 buy=YES sell=YES rows=35937
[TRAIN][5M] asof=2016-10-31 feats=114 buy=YES sell=YES rows=36104
[TRAIN][5M] asof=2016-11-07 feats=114 buy=YES sell=YES rows=36268
[TRAIN][5M] asof=2016-11-14 feats=114 buy=YES sell=YES rows=36438
[TRAIN][5M] asof=2016-11-21 feats=114 buy=YES sell=YES rows=36611
[TRAIN][5M] asof=2016-11-28 feats=114 buy=YES sell=YES rows=36720

,date,decision_date,result_date,p_day,p_day_source_date,daily_gate_mode,daily_reward_mode,direct_gate_confidence,direct_gate_prob_force_buy,direct_gate_prob_free,...,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
1979,2019-12-23,2019-12-23,2019-12-24,0.174284,2019-12-23,threshold,counterfactual_5m,NaN,NaN,NaN,...,FORCE_BUY,0.000142,0.000142,0.000142,0.000142,FORCE_BUY,7.557172e+06,211.95,0.0,2.0
1980,2019-12-24,2019-12-24,2019-12-26,0.121730,2019-12-24,threshold,counterfactual_5m,NaN,NaN,NaN,...,FORCE_BUY,0.009995,0.009995,0.009995,0.009995,FORCE_BUY,7.632708e+06,214.22,0.0,2.0
1981,2019-12-26,2019-12-26,2019-12-27,0.142004,2019-12-26,threshold,counterfactual_5m,NaN,NaN,NaN,...,FORCE_BUY,-0.005550,-0.005550,-0.005550,-0.005550,FORCE_BUY,7.590348e+06,213.23,0.0,2.0
1982,2019-12-27,2019-12-27,2019-12-30,0.304810,2019-12-27,threshold,counterfactual_5m,NaN,NaN,NaN,...,FORCE_BUY,-0.007248,-0.007248,-0.007248,-0.007248,FORCE_BUY,7.535335e+06,212.31,0.0,2.0
1983,2019-12-30,2019-12-30,2019-12-31,0.302711,2019-12-30,threshold,counterfactual_5m,NaN,NaN,NaN,...,FORCE_BUY,0.002778,0.003752,0.000000,0.002778,FREE,7.563611e+06,212.98,1.5,0.0

,date,equity,cash,pos,qty,entry_px,decision_date,result_date,buy_th,sell_th,...,daily_buy_level,daily_sell_level,decision_extreme_base_dir,decision_extreme_region,decision_extreme_label,decision_extreme_window_end_date,decision_extreme_ref_high,decision_extreme_ref_low,decision_extreme_future_max_high,decision_extreme_future_min_low
1979,2019-12-24,207478.777384,0.0,1,978.904352,204.46,2019-12-23,2019-12-24,0.0,2.0,...,0.335,0.385,sell,sell_high_broken,0.0,2019-12-31,212.15,211.63,214.56,211.16
1980,2019-12-26,209700.890263,0.0,1,978.904352,204.46,2019-12-24,2019-12-26,0.0,2.0,...,0.335,0.385,sell,pending,NaN,NaT,NaN,NaN,NaN,NaN
1981,2019-12-27,208731.774954,0.0,1,978.904352,204.46,2019-12-26,2019-12-27,0.0,2.0,...,0.335,0.385,sell,pending,NaN,NaT,NaN,NaN,NaN,NaN
1982,2019-12-30,207831.182950,0.0,1,978.904352,204.46,2019-12-27,2019-12-30,1.5,0.0,...,0.335,0.385,sell,pending,NaN,NaT,NaN,NaN,NaN,NaN
1983,2019-12-31,208487.048866,0.0,1,978.904352,204.46,2019-12-30,2019-12-31,1.5,1.5,...,0.335,0.385,sell,pending,NaN,NaT,NaN,NaN,NaN,NaN

[RUN] 2020: output_QQQ_build_prev_daily_context_at_2020\fresh_checkpoint_prev_daily_context__before_2020.joblib -> 2020-12-31 16:00:00
[CHRONO] 5m day=2019-12-31 rows=307851:307888
[TRAIN][5M] asof=2019-12-31 feats=114 buy=YES sell=YES rows=63348
[CHECKPOINT] autosaved chronological year-start snapshot for 2020 before 2020-01-02 -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2020\year_start_checkpoints\continued_checkpoint__through_2020__start_2020.joblib
[CHRONO] 5m day=2020-01-02 rows=307888:308074
[CHRONO] daily close=2020-01-02 idx=2489
[CHRONO] 5m day=2020-01-03 rows=308074:308259
[CHRONO] daily close=2020-01-03 idx=2490
[CHRONO] 5m day=2020-01-06 rows=308259:308445
[TRAIN][5M] asof=2020-01-06 feats=114 buy=YES sell=YES rows=63491
[CHRONO] daily close=2020-01-06 idx=2491
[CHRONO] 5m day=2020-01-07 rows=308445:308635
[CHRONO] daily close=2020-01-07 idx=2492
[CHRONO] 5m day=2020-01-08 rows=308635:308822
[CHRONO] daily close=2020-01-08 idx=2493
[CHRONO] 5m day=2020-01-09 rows=308822:309011
[CHRONO] daily close=2020-01-09 idx=2494
[CHRONO] 5m day=2020-01-10 rows=309011:309180
[CHRONO] daily close=2020-01-10 idx=2495
[CHRONO] 5m day=2020-01-13 rows=309180:309367
[TRAIN][5M] asof=2020-01-13 feats=114 buy=YES sell=YES rows=63724
[CHRONO] daily close=2020-01-13 idx=2496
[CHRONO] 5m day=2020-01-14 rows=309367:309552
[CHRONO] daily close=2020-01-14 idx=2497
[CHRONO] 5m day=2020-01-15 rows=309552:309734
[CHRONO] daily close=2020-01-15 idx=2498
[CHRONO] 5m day=2020-01-16 rows=309734:309921
[CHRONO] daily close=2020-01-16 idx=2499
[CHRONO] 5m day=2020-01-17 rows=309921:310093
[CHRONO] daily close=2020-01-17 idx=2500
[CHRONO] 5m day=2020-01-21 rows=310093:310282
[TRAIN][5M] asof=2020-01-21 feats=114 buy=YES sell=YES rows=63922
[CHRONO] daily close=2020-01-21 idx=2501
[CHRONO] 5m day=2020-01-22 rows=310282:310468
[CHRONO] daily close=2020-01-22 idx=2502
[CHRONO] 5m day=2020-01-23 rows=310468:310654
[CHRONO] daily close=2020-01-23 idx=2503
[CHRONO] 5m day=2020-01-24 rows=310654:310839
[CHRONO] daily close=2020-01-24 idx=2504
[CHRONO] 5m day=2020-01-27 rows=310839:311030
[TRAIN][5M] asof=2020-01-27 feats=114 buy=YES sell=YES rows=64099
[CHRONO] daily close=2020-01-27 idx=2505
[CHRONO] 5m day=2020-01-28 rows=311030:311216
[CHRONO] daily close=2020-01-28 idx=2506
[CHRONO] 5m day=2020-01-29 rows=311216:311405
[CHRONO] daily close=2020-01-29 idx=2507
[CHRONO] 5m day=2020-01-30 rows=311405:311596
[CHRONO] daily close=2020-01-30 idx=2508
[CHRONO] 5m day=2020-01-31 rows=311596:311784
[CHRONO] daily close=2020-01-31 idx=2509
[CHRONO] 5m day=2020-02-03 rows=311784:311973
[TRAIN][5M] asof=2020-02-03 feats=114 buy=YES sell=YES rows=64320
[CHRONO] daily close=2020-02-03 idx=2510
[CHRONO] 5m day=2020-02-04 rows=311973:312160
[CHRONO] daily close=2020-02-04 idx=2511
[CHRONO] 5m day=2020-02-05 rows=312160:312352
[CHRONO] daily close=2020-02-05 idx=2512
[CHRONO] 5m day=2020-02-06 rows=312352:312539
[CHRONO] daily close=2020-02-06 idx=2513
[TRAIN][DAILY-PROB] n=2340 pos=489 (20.90%)
[CHRONO] 5m day=2020-02-07 rows=312539:312728
[CHRONO] daily close=2020-02-07 idx=2514
[CHRONO] 5m day=2020-02-10 rows=312728:312919
[TRAIN][5M] asof=2020-02-10 feats=114 buy=YES sell=YES rows=64544
[CHRONO] daily close=2020-02-10 idx=2515
[CHRONO] 5m day=2020-02-11 rows=312919:313108
[CHRONO] daily close=2020-02-11 idx=2516
[CHRONO] 5m day=2020-02-12 rows=313108:313299
[CHRONO] daily close=2020-02-12 idx=2517
[CHRONO] 5m day=2020-02-13 rows=313299:313489
[CHRONO] daily close=2020-02-13 idx=2518
[CHRONO] 5m day=2020-02-14 rows=313489:313665
[CHRONO] daily close=2020-02-14 idx=2519
[CHRONO] 5m day=2020-02-18 rows=313665:313854
[TRAIN][5M] asof=2020-02-18 feats=114 buy=YES sell=YES rows=64708
[CHRONO] daily close=2020-02-18 idx=2520
[CHRONO] 5m day=2020-02-19 rows=313854:314041
[CHRONO] daily close=2020-02-19 idx=2521
[CHRONO] 5m day=2020-02-20 rows=314041:314226
[CHRONO] daily close=2020-02-20 idx=2522
[CHRONO] 5m day=2020-02-21 rows=314226:314412
[CHRONO] daily close=2020-02-21 idx=2523
[CHRONO] 5m day=2020-02-24 rows=314412:314604
[TRAIN][5M] asof=2020-02-24 feats=114 buy=YES sell=YES rows=64838
[CHRONO] daily close=2020-02-24 idx=2524
[CHRONO] 5m day=2020-02-25 rows=314604:314796
[CHRONO] daily close=2020-02-25 idx=2525
[CHRONO] 5m day=2020-02-26 rows=314796:314988
[CHRONO] daily close=2020-02-26 idx=2526
[CHRONO] 5m day=2020-02-27 rows=314988:315180
[CHRONO] daily close=2020-02-27 idx=2527
[CHRONO] 5m day=2020-02-28 rows=315180:315372
[CHRONO] daily close=2020-02-28 idx=2528
[CHRONO] 5m day=2020-03-02 rows=315372:315564
[TRAIN][5M] asof=2020-03-02 feats=114 buy=YES sell=YES rows=65071
[CHRONO] daily close=2020-03-02 idx=2529
[CHRONO] 5m day=2020-03-03 rows=315564:315756
[CHRONO] daily close=2020-03-03 idx=2530
[CHRONO] 5m day=2020-03-04 rows=315756:315948
[CHRONO] daily close=2020-03-04 idx=2531
[CHRONO] 5m day=2020-03-05 rows=315948:316140
[CHRONO] daily close=2020-03-05 idx=2532
[CHRONO] 5m day=2020-03-06 rows=316140:316332
[CHRONO] daily close=2020-03-06 idx=2533
[CHRONO] 5m day=2020-03-09 rows=316332:316522
[TRAIN][5M] asof=2020-03-09 feats=114 buy=YES sell=YES rows=65267
[CHRONO] daily close=2020-03-09 idx=2534
[CHRONO] 5m day=2020-03-10 rows=316522:316714
[CHRONO] daily close=2020-03-10 idx=2535
[CHRONO] 5m day=2020-03-11 rows=316714:316906
[CHRONO] daily close=2020-03-11 idx=2536
[CHRONO] 5m day=2020-03-12 rows=316906:317096
[CHRONO] daily close=2020-03-12 idx=2537
[CHRONO] 5m day=2020-03-13 rows=317096:317288
[CHRONO] daily close=2020-03-13 idx=2538
[TRAIN][DAILY-PROB] n=2365 pos=494 (20.89%)
[CHRONO] 5m day=2020-03-16 rows=317288:317478
[TRAIN][5M] asof=2020-03-16 feats=114 buy=YES sell=YES rows=65422
[CHRONO] daily close=2020-03-16 idx=2539
[CHRONO] 5m day=2020-03-17 rows=317478:317670
[CHRONO] daily close=2020-03-17 idx=2540
[CHRONO] 5m day=2020-03-18 rows=317670:317860
[CHRONO] daily close=2020-03-18 idx=2541
[CHRONO] 5m day=2020-03-19 rows=317860:318052
[CHRONO] daily close=2020-03-19 idx=2542
[CHRONO] 5m day=2020-03-20 rows=318052:318244
[CHRONO] daily close=2020-03-20 idx=2543
[CHRONO] 5m day=2020-03-23 rows=318244:318436
[TRAIN][5M] asof=2020-03-23 feats=114 buy=YES sell=YES rows=65670
[CHRONO] daily close=2020-03-23 idx=2544
[CHRONO] 5m day=2020-03-24 rows=318436:318628
[CHRONO] daily close=2020-03-24 idx=2545
[CHRONO] 5m day=2020-03-25 rows=318628:318819
[CHRONO] daily close=2020-03-25 idx=2546
[CHRONO] 5m day=2020-03-26 rows=318819:319011
[CHRONO] daily close=2020-03-26 idx=2547
[CHRONO] 5m day=2020-03-27 rows=319011:319201
[CHRONO] daily close=2020-03-27 idx=2548
[CHRONO] 5m day=2020-03-30 rows=319201:319393
[TRAIN][5M] asof=2020-03-30 feats=114 buy=YES sell=YES rows=65879
[CHRONO] daily close=2020-03-30 idx=2549
[CHRONO] 5m day=2020-03-31 rows=319393:319585
[CHRONO] daily close=2020-03-31 idx=2550
[CHRONO] 5m day=2020-04-01 rows=319585:319777
[CHRONO] daily close=2020-04-01 idx=2551
[CHRONO] 5m day=2020-04-02 rows=319777:319969
[CHRONO] daily close=2020-04-02 idx=2552
[CHRONO] 5m day=2020-04-03 rows=319969:320159
[CHRONO] daily close=2020-04-03 idx=2553
[CHRONO] 5m day=2020-04-06 rows=320159:320351
[TRAIN][5M] asof=2020-04-06 feats=114 buy=YES sell=YES rows=66047
[CHRONO] daily close=2020-04-06 idx=2554
[CHRONO] 5m day=2020-04-07 rows=320351:320542
[CHRONO] daily close=2020-04-07 idx=2555
[CHRONO] 5m day=2020-04-08 rows=320542:320732
[CHRONO] daily close=2020-04-08 idx=2556
[CHRONO] 5m day=2020-04-09 rows=320732:320923
[CHRONO] daily close=2020-04-09 idx=2557
[CHRONO] 5m day=2020-04-13 rows=320923:321115
[TRAIN][5M] asof=2020-04-13 feats=114 buy=YES sell=YES rows=66188
[CHRONO] daily close=2020-04-13 idx=2558
[CHRONO] 5m day=2020-04-14 rows=321115:321306
[CHRONO] daily close=2020-04-14 idx=2559
[CHRONO] 5m day=2020-04-15 rows=321306:321497
[CHRONO] daily close=2020-04-15 idx=2560
[CHRONO] 5m day=2020-04-16 rows=321497:321688
[CHRONO] daily close=2020-04-16 idx=2561
[CHRONO] 5m day=2020-04-17 rows=321688:321878
[CHRONO] daily close=2020-04-17 idx=2562
[CHRONO] 5m day=2020-04-20 rows=321878:322068
[TRAIN][5M] asof=2020-04-20 feats=114 buy=YES sell=YES rows=66389
[CHRONO] daily close=2020-04-20 idx=2563
[TRAIN][DAILY-PROB] n=2390 pos=497 (20.79%)
[CHRONO] 5m day=2020-04-21 rows=322068:322260
[CHRONO] daily close=2020-04-21 idx=2564
[CHRONO] 5m day=2020-04-22 rows=322260:322452
[CHRONO] daily close=2020-04-22 idx=2565
[CHRONO] 5m day=2020-04-23 rows=322452:322640
[CHRONO] daily close=2020-04-23 idx=2566
[CHRONO] 5m day=2020-04-24 rows=322640:322828
[CHRONO] daily close=2020-04-24 idx=2567
[CHRONO] 5m day=2020-04-27 rows=322828:323020
[TRAIN][5M] asof=2020-04-27 feats=114 buy=YES sell=YES rows=66658
[CHRONO] daily close=2020-04-27 idx=2568
[CHRONO] 5m day=2020-04-28 rows=323020:323210
[CHRONO] daily close=2020-04-28 idx=2569
[CHRONO] 5m day=2020-04-29 rows=323210:323400
[CHRONO] daily close=2020-04-29 idx=2570
[CHRONO] 5m day=2020-04-30 rows=323400:323589
[CHRONO] daily close=2020-04-30 idx=2571
[CHRONO] 5m day=2020-05-01 rows=323589:323777
[CHRONO] daily close=2020-05-01 idx=2572
[CHRONO] 5m day=2020-05-04 rows=323777:323967
[TRAIN][5M] asof=2020-05-04 feats=114 buy=YES sell=YES rows=66852
[CHRONO] daily close=2020-05-04 idx=2573
[CHRONO] 5m day=2020-05-05 rows=323967:324156
[CHRONO] daily close=2020-05-05 idx=2574
[CHRONO] 5m day=2020-05-06 rows=324156:324343
[CHRONO] daily close=2020-05-06 idx=2575
[CHRONO] 5m day=2020-05-07 rows=324343:324535
[CHRONO] daily close=2020-05-07 idx=2576
[CHRONO] 5m day=2020-05-08 rows=324535:324725
[CHRONO] daily close=2020-05-08 idx=2577
[CHRONO] 5m day=2020-05-11 rows=324725:324916
[TRAIN][5M] asof=2020-05-11 feats=114 buy=YES sell=YES rows=67057
[CHRONO] daily close=2020-05-11 idx=2578
[CHRONO] 5m day=2020-05-12 rows=324916:325105
[CHRONO] daily close=2020-05-12 idx=2579
[CHRONO] 5m day=2020-05-13 rows=325105:325297
[CHRONO] daily close=2020-05-13 idx=2580
[CHRONO] 5m day=2020-05-14 rows=325297:325487
[CHRONO] daily close=2020-05-14 idx=2581
[CHRONO] 5m day=2020-05-15 rows=325487:325675
[CHRONO] daily close=2020-05-15 idx=2582
[CHRONO] 5m day=2020-05-18 rows=325675:325865
[TRAIN][5M] asof=2020-05-18 feats=114 buy=YES sell=YES rows=67279
[CHRONO] daily close=2020-05-18 idx=2583
[CHRONO] 5m day=2020-05-19 rows=325865:326055
[CHRONO] daily close=2020-05-19 idx=2584
[CHRONO] 5m day=2020-05-20 rows=326055:326247
[CHRONO] daily close=2020-05-20 idx=2585
[CHRONO] 5m day=2020-05-21 rows=326247:326437
[CHRONO] daily close=2020-05-21 idx=2586
[CHRONO] 5m day=2020-05-22 rows=326437:326624
[CHRONO] daily close=2020-05-22 idx=2587
[CHRONO] 5m day=2020-05-26 rows=326624:326814
[TRAIN][5M] asof=2020-05-26 feats=114 buy=YES sell=YES rows=67493
[CHRONO] daily close=2020-05-26 idx=2588
[TRAIN][DAILY-PROB] n=2415 pos=498 (20.62%)
[CHRONO] 5m day=2020-05-27 rows=326814:327005
[CHRONO] daily close=2020-05-27 idx=2589
[CHRONO] 5m day=2020-05-28 rows=327005:327197
[CHRONO] daily close=2020-05-28 idx=2590
[CHRONO] 5m day=2020-05-29 rows=327197:327387
[CHRONO] daily close=2020-05-29 idx=2591
[CHRONO] 5m day=2020-06-01 rows=327387:327577
[TRAIN][5M] asof=2020-06-01 feats=114 buy=YES sell=YES rows=67654
[CHRONO] daily close=2020-06-01 idx=2592
[CHRONO] 5m day=2020-06-02 rows=327577:327769
[CHRONO] daily close=2020-06-02 idx=2593
[CHRONO] 5m day=2020-06-03 rows=327769:327955
[CHRONO] daily close=2020-06-03 idx=2594
[CHRONO] 5m day=2020-06-04 rows=327955:328140
[CHRONO] daily close=2020-06-04 idx=2595
[CHRONO] 5m day=2020-06-05 rows=328140:328321
[CHRONO] daily close=2020-06-05 idx=2596
[CHRONO] 5m day=2020-06-08 rows=328321:328510
[TRAIN][5M] asof=2020-06-08 feats=114 buy=YES sell=YES rows=67880
[CHRONO] daily close=2020-06-08 idx=2597
[CHRONO] 5m day=2020-06-09 rows=328510:328698
[CHRONO] daily close=2020-06-09 idx=2598
[CHRONO] 5m day=2020-06-10 rows=328698:328889
[CHRONO] daily close=2020-06-10 idx=2599
[CHRONO] 5m day=2020-06-11 rows=328889:329081
[CHRONO] daily close=2020-06-11 idx=2600
[CHRONO] 5m day=2020-06-12 rows=329081:329270
[CHRONO] daily close=2020-06-12 idx=2601
[CHRONO] 5m day=2020-06-15 rows=329270:329461
[TRAIN][5M] asof=2020-06-15 feats=114 buy=YES sell=YES rows=68051
[CHRONO] daily close=2020-06-15 idx=2602
[CHRONO] 5m day=2020-06-16 rows=329461:329652
[CHRONO] daily close=2020-06-16 idx=2603
[CHRONO] 5m day=2020-06-17 rows=329652:329844
[CHRONO] daily close=2020-06-17 idx=2604
[CHRONO] 5m day=2020-06-18 rows=329844:330032
[CHRONO] daily close=2020-06-18 idx=2605
[CHRONO] 5m day=2020-06-19 rows=330032:330218
[CHRONO] daily close=2020-06-19 idx=2606
[CHRONO] 5m day=2020-06-22 rows=330218:330408
[TRAIN][5M] asof=2020-06-22 feats=114 buy=YES sell=YES rows=68273
[CHRONO] daily close=2020-06-22 idx=2607
[CHRONO] 5m day=2020-06-23 rows=330408:330598
[CHRONO] daily close=2020-06-23 idx=2608
[CHRONO] 5m day=2020-06-24 rows=330598:330785
[CHRONO] daily close=2020-06-24 idx=2609
[CHRONO] 5m day=2020-06-25 rows=330785:330975
[CHRONO] daily close=2020-06-25 idx=2610
[CHRONO] 5m day=2020-06-26 rows=330975:331163
[CHRONO] daily close=2020-06-26 idx=2611
[CHRONO] 5m day=2020-06-29 rows=331163:331355
[TRAIN][5M] asof=2020-06-29 feats=114 buy=YES sell=YES rows=68470
[CHRONO] daily close=2020-06-29 idx=2612
[CHRONO] 5m day=2020-06-30 rows=331355:331545
[CHRONO] daily close=2020-06-30 idx=2613
[TRAIN][DAILY-PROB] n=2440 pos=500 (20.49%)
[CHRONO] 5m day=2020-07-01 rows=331545:331731
[CHRONO] daily close=2020-07-01 idx=2614
[CHRONO] 5m day=2020-07-02 rows=331731:331917
[CHRONO] daily close=2020-07-02 idx=2615
[CHRONO] 5m day=2020-07-06 rows=331917:332107
[TRAIN][5M] asof=2020-07-06 feats=114 buy=YES sell=YES rows=68619
[CHRONO] daily close=2020-07-06 idx=2616
[CHRONO] 5m day=2020-07-07 rows=332107:332297
[CHRONO] daily close=2020-07-07 idx=2617
[CHRONO] 5m day=2020-07-08 rows=332297:332489
[CHRONO] daily close=2020-07-08 idx=2618
[CHRONO] 5m day=2020-07-09 rows=332489:332676
[CHRONO] daily close=2020-07-09 idx=2619
[CHRONO] 5m day=2020-07-10 rows=332676:332864
[CHRONO] daily close=2020-07-10 idx=2620
[CHRONO] 5m day=2020-07-13 rows=332864:333056
[TRAIN][5M] asof=2020-07-13 feats=114 buy=YES sell=YES rows=68856
[CHRONO] daily close=2020-07-13 idx=2621
[CHRONO] 5m day=2020-07-14 rows=333056:333248
[CHRONO] daily close=2020-07-14 idx=2622
[CHRONO] 5m day=2020-07-15 rows=333248:333436
[CHRONO] daily close=2020-07-15 idx=2623
[CHRONO] 5m day=2020-07-16 rows=333436:333627
[CHRONO] daily close=2020-07-16 idx=2624
[CHRONO] 5m day=2020-07-17 rows=333627:333808
[CHRONO] daily close=2020-07-17 idx=2625
[CHRONO] 5m day=2020-07-20 rows=333808:333998
[TRAIN][5M] asof=2020-07-20 feats=114 buy=YES sell=YES rows=69056
[CHRONO] daily close=2020-07-20 idx=2626
[CHRONO] 5m day=2020-07-21 rows=333998:334190
[CHRONO] daily close=2020-07-21 idx=2627
[CHRONO] 5m day=2020-07-22 rows=334190:334382
[CHRONO] daily close=2020-07-22 idx=2628
[CHRONO] 5m day=2020-07-23 rows=334382:334573
[CHRONO] daily close=2020-07-23 idx=2629
[CHRONO] 5m day=2020-07-24 rows=334573:334760
[CHRONO] daily close=2020-07-24 idx=2630
[CHRONO] 5m day=2020-07-27 rows=334760:334950
[TRAIN][5M] asof=2020-07-27 feats=114 buy=YES sell=YES rows=69255
[CHRONO] daily close=2020-07-27 idx=2631
[CHRONO] 5m day=2020-07-28 rows=334950:335142
[CHRONO] daily close=2020-07-28 idx=2632
[CHRONO] 5m day=2020-07-29 rows=335142:335329
[CHRONO] daily close=2020-07-29 idx=2633
[CHRONO] 5m day=2020-07-30 rows=335329:335521
[CHRONO] daily close=2020-07-30 idx=2634
[CHRONO] 5m day=2020-07-31 rows=335521:335711
[CHRONO] daily close=2020-07-31 idx=2635
[CHRONO] 5m day=2020-08-03 rows=335711:335902
[TRAIN][5M] asof=2020-08-03 feats=114 buy=YES sell=YES rows=69448
[CHRONO] daily close=2020-08-03 idx=2636
[CHRONO] 5m day=2020-08-04 rows=335902:336092
[CHRONO] daily close=2020-08-04 idx=2637
[CHRONO] 5m day=2020-08-05 rows=336092:336279
[CHRONO] daily close=2020-08-05 idx=2638
[TRAIN][DAILY-PROB] n=2465 pos=508 (20.61%)
[CHRONO] 5m day=2020-08-06 rows=336279:336463
[CHRONO] daily close=2020-08-06 idx=2639
[CHRONO] 5m day=2020-08-07 rows=336463:336649
[CHRONO] daily close=2020-08-07 idx=2640
[CHRONO] 5m day=2020-08-10 rows=336649:336835
[TRAIN][5M] asof=2020-08-10 feats=114 buy=YES sell=YES rows=69638
[CHRONO] daily close=2020-08-10 idx=2641
[CHRONO] 5m day=2020-08-11 rows=336835:337027
[CHRONO] daily close=2020-08-11 idx=2642
[CHRONO] 5m day=2020-08-12 rows=337027:337216
[CHRONO] daily close=2020-08-12 idx=2643
[CHRONO] 5m day=2020-08-13 rows=337216:337407
[CHRONO] daily close=2020-08-13 idx=2644
[CHRONO] 5m day=2020-08-14 rows=337407:337589
[CHRONO] daily close=2020-08-14 idx=2645
[CHRONO] 5m day=2020-08-17 rows=337589:337770
[TRAIN][5M] asof=2020-08-17 feats=114 buy=YES sell=YES rows=69828
[CHRONO] daily close=2020-08-17 idx=2646
[CHRONO] 5m day=2020-08-18 rows=337770:337960
[CHRONO] daily close=2020-08-18 idx=2647
[CHRONO] 5m day=2020-08-19 rows=337960:338149
[CHRONO] daily close=2020-08-19 idx=2648
[CHRONO] 5m day=2020-08-20 rows=338149:338340
[CHRONO] daily close=2020-08-20 idx=2649
[CHRONO] 5m day=2020-08-21 rows=338340:338527
[CHRONO] daily close=2020-08-21 idx=2650
[CHRONO] 5m day=2020-08-24 rows=338527:338719
[TRAIN][5M] asof=2020-08-24 feats=114 buy=YES sell=YES rows=70010
[CHRONO] daily close=2020-08-24 idx=2651
[CHRONO] 5m day=2020-08-25 rows=338719:338904
[CHRONO] daily close=2020-08-25 idx=2652
[CHRONO] 5m day=2020-08-26 rows=338904:339093
[CHRONO] daily close=2020-08-26 idx=2653
[CHRONO] 5m day=2020-08-27 rows=339093:339283
[CHRONO] daily close=2020-08-27 idx=2654
[CHRONO] 5m day=2020-08-28 rows=339283:339467
[CHRONO] daily close=2020-08-28 idx=2655
[CHRONO] 5m day=2020-08-31 rows=339467:339658
[TRAIN][5M] asof=2020-08-31 feats=114 buy=YES sell=YES rows=70221
[CHRONO] daily close=2020-08-31 idx=2656
[CHRONO] 5m day=2020-09-01 rows=339658:339850
[CHRONO] daily close=2020-09-01 idx=2657
[CHRONO] 5m day=2020-09-02 rows=339850:340041
[CHRONO] daily close=2020-09-02 idx=2658
[CHRONO] 5m day=2020-09-03 rows=340041:340233
[CHRONO] daily close=2020-09-03 idx=2659
[CHRONO] 5m day=2020-09-04 rows=340233:340425
[CHRONO] daily close=2020-09-04 idx=2660
[CHRONO] 5m day=2020-09-08 rows=340425:340617
[TRAIN][5M] asof=2020-09-08 feats=114 buy=YES sell=YES rows=70412
[CHRONO] daily close=2020-09-08 idx=2661
[CHRONO] 5m day=2020-09-09 rows=340617:340809
[CHRONO] daily close=2020-09-09 idx=2662
[CHRONO] 5m day=2020-09-10 rows=340809:341000
[CHRONO] daily close=2020-09-10 idx=2663
[TRAIN][DAILY-PROB] n=2490 pos=511 (20.52%)
[CHRONO] 5m day=2020-09-11 rows=341000:341189
[CHRONO] daily close=2020-09-11 idx=2664
[CHRONO] 5m day=2020-09-14 rows=341189:341380
[TRAIN][5M] asof=2020-09-14 feats=114 buy=YES sell=YES rows=70595
[CHRONO] daily close=2020-09-14 idx=2665
[CHRONO] 5m day=2020-09-15 rows=341380:341572
[CHRONO] daily close=2020-09-15 idx=2666
[CHRONO] 5m day=2020-09-16 rows=341572:341764
[CHRONO] daily close=2020-09-16 idx=2667
[CHRONO] 5m day=2020-09-17 rows=341764:341956
[CHRONO] daily close=2020-09-17 idx=2668
[CHRONO] 5m day=2020-09-18 rows=341956:342146
[CHRONO] daily close=2020-09-18 idx=2669
[CHRONO] 5m day=2020-09-21 rows=342146:342338
[TRAIN][5M] asof=2020-09-21 feats=114 buy=YES sell=YES rows=70807
[CHRONO] daily close=2020-09-21 idx=2670
[CHRONO] 5m day=2020-09-22 rows=342338:342528
[CHRONO] daily close=2020-09-22 idx=2671
[CHRONO] 5m day=2020-09-23 rows=342528:342719
[CHRONO] daily close=2020-09-23 idx=2672
[CHRONO] 5m day=2020-09-24 rows=342719:342910
[CHRONO] daily close=2020-09-24 idx=2673
[CHRONO] 5m day=2020-09-25 rows=342910:343097
[CHRONO] daily close=2020-09-25 idx=2674
[CHRONO] 5m day=2020-09-28 rows=343097:343288
[TRAIN][5M] asof=2020-09-28 feats=114 buy=YES sell=YES rows=71002
[CHRONO] daily close=2020-09-28 idx=2675
[CHRONO] 5m day=2020-09-29 rows=343288:343477
[CHRONO] daily close=2020-09-29 idx=2676
[CHRONO] 5m day=2020-09-30 rows=343477:343669
[CHRONO] daily close=2020-09-30 idx=2677
[CHRONO] 5m day=2020-10-01 rows=343669:343861
[CHRONO] daily close=2020-10-01 idx=2678
[CHRONO] 5m day=2020-10-02 rows=343861:344053
[CHRONO] daily close=2020-10-02 idx=2679

c:\Users\TonyTang\Documents\chan.py\adaptive_reward_checkpoint_fresh.py:3132: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  daily_log_df = pd.concat(daily_log_frames, ignore_index=True, sort=False) if daily_log_frames else pd.DataFrame()

[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2020\trades.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2020\signal_decisions.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2020\daily_log.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2020\daily_reward_log.csv
[CHECKPOINT] saved chronological snapshot -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2020\continued_checkpoint__through_2020.joblib
[DONE] 2020 checkpoint: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2020\continued_checkpoint__through_2020.joblib
[RUN] 2021: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2020\continued_checkpoint__through_2020.joblib -> 2021-12-31 16:00:00
[CHRONO] 5m day=2020-12-31 rows=355650:355683
[TRAIN][5M] asof=2020-12-31 feats=114 buy=YES sell=YES rows=73476
[CHECKPOINT] autosaved chronological year-start snapshot for 2021 before 2021-01-04 -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2021\year_start_checkpoints\continued_checkpoint__through_2021__start_2021.joblib
[CHRONO] 5m day=2021-01-04 rows=355683:355872
[CHRONO] daily close=2021-01-04 idx=2742
[CHRONO] 5m day=2021-01-05 rows=355872:356062
[TRAIN][5M] asof=2021-01-05 feats=114 buy=YES sell=YES rows=73571
[CHRONO] daily close=2021-01-05 idx=2743
[CHRONO] 5m day=2021-01-06 rows=356062:356254
[CHRONO] daily close=2021-01-06 idx=2744
[CHRONO] 5m day=2021-01-07 rows=356254:356446
[CHRONO] daily close=2021-01-07 idx=2745
[CHRONO] 5m day=2021-01-08 rows=356446:356634
[CHRONO] daily close=2021-01-08 idx=2746
[CHRONO] 5m day=2021-01-11 rows=356634:356825
[TRAIN][5M] asof=2021-01-11 feats=114 buy=YES sell=YES rows=73712
[CHRONO] daily close=2021-01-11 idx=2747
[CHRONO] 5m day=2021-01-12 rows=356825:357016
[CHRONO] daily close=2021-01-12 idx=2748
[CHRONO] 5m day=2021-01-13 rows=357016:357207
[CHRONO] daily close=2021-01-13 idx=2749
[CHRONO] 5m day=2021-01-14 rows=357207:357397
[CHRONO] daily close=2021-01-14 idx=2750
[CHRONO] 5m day=2021-01-15 rows=357397:357580
[CHRONO] daily close=2021-01-15 idx=2751
[CHRONO] 5m day=2021-01-19 rows=357580:357772
[TRAIN][5M] asof=2021-01-19 feats=114 buy=YES sell=YES rows=73911
[CHRONO] daily close=2021-01-19 idx=2752
[CHRONO] 5m day=2021-01-20 rows=357772:357961
[CHRONO] daily close=2021-01-20 idx=2753
[CHRONO] 5m day=2021-01-21 rows=357961:358153
[CHRONO] daily close=2021-01-21 idx=2754
[CHRONO] 5m day=2021-01-22 rows=358153:358341
[CHRONO] daily close=2021-01-22 idx=2755
[CHRONO] 5m day=2021-01-25 rows=358341:358533
[TRAIN][5M] asof=2021-01-25 feats=114 buy=YES sell=YES rows=74098
[CHRONO] daily close=2021-01-25 idx=2756
[CHRONO] 5m day=2021-01-26 rows=358533:358724
[CHRONO] daily close=2021-01-26 idx=2757
[CHRONO] 5m day=2021-01-27 rows=358724:358915
[CHRONO] daily close=2021-01-27 idx=2758
[CHRONO] 5m day=2021-01-28 rows=358915:359106
[CHRONO] daily close=2021-01-28 idx=2759
[CHRONO] 5m day=2021-01-29 rows=359106:359295
[CHRONO] daily close=2021-01-29 idx=2760
[CHRONO] 5m day=2021-02-01 rows=359295:359487
[TRAIN][5M] asof=2021-02-01 feats=114 buy=YES sell=YES rows=74308
[CHRONO] daily close=2021-02-01 idx=2761
[CHRONO] 5m day=2021-02-02 rows=359487:359679
[CHRONO] daily close=2021-02-02 idx=2762
[CHRONO] 5m day=2021-02-03 rows=359679:359871
[CHRONO] daily close=2021-02-03 idx=2763
[CHRONO] 5m day=2021-02-04 rows=359871:360062
[CHRONO] daily close=2021-02-04 idx=2764
[CHRONO] 5m day=2021-02-05 rows=360062:360248
[CHRONO] daily close=2021-02-05 idx=2765
[CHRONO] 5m day=2021-02-08 rows=360248:360439
[TRAIN][5M] asof=2021-02-08 feats=114 buy=YES sell=YES rows=74492
[CHRONO] daily close=2021-02-08 idx=2766
[TRAIN][DAILY-PROB] n=2593 pos=533 (20.56%)
[CHRONO] 5m day=2021-02-09 rows=360439:360627
[CHRONO] daily close=2021-02-09 idx=2767
[CHRONO] 5m day=2021-02-10 rows=360627:360818
[CHRONO] daily close=2021-02-10 idx=2768
[CHRONO] 5m day=2021-02-11 rows=360818:361005
[CHRONO] daily close=2021-02-11 idx=2769
[CHRONO] 5m day=2021-02-12 rows=361005:361192
[CHRONO] daily close=2021-02-12 idx=2770
[CHRONO] 5m day=2021-02-16 rows=361192:361382
[TRAIN][5M] asof=2021-02-16 feats=114 buy=YES sell=YES rows=74669
[CHRONO] daily close=2021-02-16 idx=2771
[CHRONO] 5m day=2021-02-17 rows=361382:361569
[CHRONO] daily close=2021-02-17 idx=2772
[CHRONO] 5m day=2021-02-18 rows=361569:361761
[CHRONO] daily close=2021-02-18 idx=2773
[CHRONO] 5m day=2021-02-19 rows=361761:361948
[CHRONO] daily close=2021-02-19 idx=2774
[CHRONO] 5m day=2021-02-22 rows=361948:362139
[TRAIN][5M] asof=2021-02-22 feats=114 buy=YES sell=YES rows=74842
[CHRONO] daily close=2021-02-22 idx=2775
[CHRONO] 5m day=2021-02-23 rows=362139:362331
[CHRONO] daily close=2021-02-23 idx=2776
[CHRONO] 5m day=2021-02-24 rows=362331:362523
[CHRONO] daily close=2021-02-24 idx=2777
[CHRONO] 5m day=2021-02-25 rows=362523:362715
[CHRONO] daily close=2021-02-25 idx=2778
[CHRONO] 5m day=2021-02-26 rows=362715:362906
[CHRONO] daily close=2021-02-26 idx=2779
[CHRONO] 5m day=2021-03-01 rows=362906:363098
[TRAIN][5M] asof=2021-03-01 feats=114 buy=YES sell=YES rows=75072
[CHRONO] daily close=2021-03-01 idx=2780
[CHRONO] 5m day=2021-03-02 rows=363098:363290
[CHRONO] daily close=2021-03-02 idx=2781
[CHRONO] 5m day=2021-03-03 rows=363290:363482
[CHRONO] daily close=2021-03-03 idx=2782
[CHRONO] 5m day=2021-03-04 rows=363482:363674
[CHRONO] daily close=2021-03-04 idx=2783
[CHRONO] 5m day=2021-03-05 rows=363674:363865
[CHRONO] daily close=2021-03-05 idx=2784
[CHRONO] 5m day=2021-03-08 rows=363865:364057
[TRAIN][5M] asof=2021-03-08 feats=114 buy=YES sell=YES rows=75286
[CHRONO] daily close=2021-03-08 idx=2785
[CHRONO] 5m day=2021-03-09 rows=364057:364249
[CHRONO] daily close=2021-03-09 idx=2786
[CHRONO] 5m day=2021-03-10 rows=364249:364441
[CHRONO] daily close=2021-03-10 idx=2787
[CHRONO] 5m day=2021-03-11 rows=364441:364633
[CHRONO] daily close=2021-03-11 idx=2788
[CHRONO] 5m day=2021-03-12 rows=364633:364821
[CHRONO] daily close=2021-03-12 idx=2789
[CHRONO] 5m day=2021-03-15 rows=364821:365013
[TRAIN][5M] asof=2021-03-15 feats=114 buy=YES sell=YES rows=75462
[CHRONO] daily close=2021-03-15 idx=2790
[CHRONO] 5m day=2021-03-16 rows=365013:365204
[CHRONO] daily close=2021-03-16 idx=2791
[TRAIN][DAILY-PROB] n=2618 pos=540 (20.63%)
[CHRONO] 5m day=2021-03-17 rows=365204:365395
[CHRONO] daily close=2021-03-17 idx=2792
[CHRONO] 5m day=2021-03-18 rows=365395:365587
[CHRONO] daily close=2021-03-18 idx=2793
[CHRONO] 5m day=2021-03-19 rows=365587:365775
[CHRONO] daily close=2021-03-19 idx=2794
[CHRONO] 5m day=2021-03-22 rows=365775:365965
[TRAIN][5M] asof=2021-03-22 feats=114 buy=YES sell=YES rows=75619
[CHRONO] daily close=2021-03-22 idx=2795
[CHRONO] 5m day=2021-03-23 rows=365965:366157
[CHRONO] daily close=2021-03-23 idx=2796
[CHRONO] 5m day=2021-03-24 rows=366157:366349
[CHRONO] daily close=2021-03-24 idx=2797
[CHRONO] 5m day=2021-03-25 rows=366349:366541
[CHRONO] daily close=2021-03-25 idx=2798
[CHRONO] 5m day=2021-03-26 rows=366541:366728
[CHRONO] daily close=2021-03-26 idx=2799
[CHRONO] 5m day=2021-03-29 rows=366728:366919
[TRAIN][5M] asof=2021-03-29 feats=114 buy=YES sell=YES rows=75820
[CHRONO] daily close=2021-03-29 idx=2800
[CHRONO] 5m day=2021-03-30 rows=366919:367106
[CHRONO] daily close=2021-03-30 idx=2801
[CHRONO] 5m day=2021-03-31 rows=367106:367297
[CHRONO] daily close=2021-03-31 idx=2802
[CHRONO] 5m day=2021-04-01 rows=367297:367488
[CHRONO] daily close=2021-04-01 idx=2803
[CHRONO] 5m day=2021-04-05 rows=367488:367680
[TRAIN][5M] asof=2021-04-05 feats=114 buy=YES sell=YES rows=75996
[CHRONO] daily close=2021-04-05 idx=2804
[CHRONO] 5m day=2021-04-06 rows=367680:367871
[CHRONO] daily close=2021-04-06 idx=2805
[CHRONO] 5m day=2021-04-07 rows=367871:368057
[CHRONO] daily close=2021-04-07 idx=2806
[CHRONO] 5m day=2021-04-08 rows=368057:368249
[CHRONO] daily close=2021-04-08 idx=2807
[CHRONO] 5m day=2021-04-09 rows=368249:368436
[CHRONO] daily close=2021-04-09 idx=2808
[CHRONO] 5m day=2021-04-12 rows=368436:368628
[TRAIN][5M] asof=2021-04-12 feats=114 buy=YES sell=YES rows=76200
[CHRONO] daily close=2021-04-12 idx=2809
[CHRONO] 5m day=2021-04-13 rows=368628:368820
[CHRONO] daily close=2021-04-13 idx=2810
[CHRONO] 5m day=2021-04-14 rows=368820:369011
[CHRONO] daily close=2021-04-14 idx=2811
[CHRONO] 5m day=2021-04-15 rows=369011:369201
[CHRONO] daily close=2021-04-15 idx=2812
[CHRONO] 5m day=2021-04-16 rows=369201:369386
[CHRONO] daily close=2021-04-16 idx=2813
[CHRONO] 5m day=2021-04-19 rows=369386:369578
[TRAIN][5M] asof=2021-04-19 feats=114 buy=YES sell=YES rows=76380
[CHRONO] daily close=2021-04-19 idx=2814
[CHRONO] 5m day=2021-04-20 rows=369578:369770
[CHRONO] daily close=2021-04-20 idx=2815
[CHRONO] 5m day=2021-04-21 rows=369770:369962
[CHRONO] daily close=2021-04-21 idx=2816
[TRAIN][DAILY-PROB] n=2643 pos=543 (20.54%)
[CHRONO] 5m day=2021-04-22 rows=369962:370154
[CHRONO] daily close=2021-04-22 idx=2817
[CHRONO] 5m day=2021-04-23 rows=370154:370343
[CHRONO] daily close=2021-04-23 idx=2818
[CHRONO] 5m day=2021-04-26 rows=370343:370534
[TRAIN][5M] asof=2021-04-26 feats=114 buy=YES sell=YES rows=76594
[CHRONO] daily close=2021-04-26 idx=2819
[CHRONO] 5m day=2021-04-27 rows=370534:370721
[CHRONO] daily close=2021-04-27 idx=2820
[CHRONO] 5m day=2021-04-28 rows=370721:370909
[CHRONO] daily close=2021-04-28 idx=2821
[CHRONO] 5m day=2021-04-29 rows=370909:371100
[CHRONO] daily close=2021-04-29 idx=2822
[CHRONO] 5m day=2021-04-30 rows=371100:371287
[CHRONO] daily close=2021-04-30 idx=2823
[CHRONO] 5m day=2021-05-03 rows=371287:371475
[TRAIN][5M] asof=2021-05-03 feats=114 buy=YES sell=YES rows=76789
[CHRONO] daily close=2021-05-03 idx=2824
[CHRONO] 5m day=2021-05-04 rows=371475:371663
[CHRONO] daily close=2021-05-04 idx=2825
[CHRONO] 5m day=2021-05-05 rows=371663:371854
[CHRONO] daily close=2021-05-05 idx=2826
[CHRONO] 5m day=2021-05-06 rows=371854:372046
[CHRONO] daily close=2021-05-06 idx=2827
[CHRONO] 5m day=2021-05-07 rows=372046:372225
[CHRONO] daily close=2021-05-07 idx=2828
[CHRONO] 5m day=2021-05-10 rows=372225:372416
[TRAIN][5M] asof=2021-05-10 feats=114 buy=YES sell=YES rows=76980
[CHRONO] daily close=2021-05-10 idx=2829
[CHRONO] 5m day=2021-05-11 rows=372416:372608
[CHRONO] daily close=2021-05-11 idx=2830
[CHRONO] 5m day=2021-05-12 rows=372608:372800
[CHRONO] daily close=2021-05-12 idx=2831
[CHRONO] 5m day=2021-05-13 rows=372800:372992
[CHRONO] daily close=2021-05-13 idx=2832
[CHRONO] 5m day=2021-05-14 rows=372992:373177
[CHRONO] daily close=2021-05-14 idx=2833
[CHRONO] 5m day=2021-05-17 rows=373177:373368
[TRAIN][5M] asof=2021-05-17 feats=114 buy=YES sell=YES rows=77172
[CHRONO] daily close=2021-05-17 idx=2834
[CHRONO] 5m day=2021-05-18 rows=373368:373560
[CHRONO] daily close=2021-05-18 idx=2835
[CHRONO] 5m day=2021-05-19 rows=373560:373752
[CHRONO] daily close=2021-05-19 idx=2836
[CHRONO] 5m day=2021-05-20 rows=373752:373941
[CHRONO] daily close=2021-05-20 idx=2837
[CHRONO] 5m day=2021-05-21 rows=373941:374127
[CHRONO] daily close=2021-05-21 idx=2838
[CHRONO] 5m day=2021-05-24 rows=374127:374318
[TRAIN][5M] asof=2021-05-24 feats=114 buy=YES sell=YES rows=77361
[CHRONO] daily close=2021-05-24 idx=2839
[CHRONO] 5m day=2021-05-25 rows=374318:374509
[CHRONO] daily close=2021-05-25 idx=2840
[CHRONO] 5m day=2021-05-26 rows=374509:374700
[CHRONO] daily close=2021-05-26 idx=2841
[TRAIN][DAILY-PROB] n=2668 pos=549 (20.58%)
[CHRONO] 5m day=2021-05-27 rows=374700:374887
[CHRONO] daily close=2021-05-27 idx=2842
[CHRONO] 5m day=2021-05-28 rows=374887:375069
[CHRONO] daily close=2021-05-28 idx=2843
[CHRONO] 5m day=2021-06-01 rows=375069:375258
[TRAIN][5M] asof=2021-06-01 feats=114 buy=YES sell=YES rows=77510
[CHRONO] daily close=2021-06-01 idx=2844
[CHRONO] 5m day=2021-06-02 rows=375258:375447
[CHRONO] daily close=2021-06-02 idx=2845
[CHRONO] 5m day=2021-06-03 rows=375447:375636
[CHRONO] daily close=2021-06-03 idx=2846
[CHRONO] 5m day=2021-06-04 rows=375636:375820
[CHRONO] daily close=2021-06-04 idx=2847
[CHRONO] 5m day=2021-06-07 rows=375820:376009
[TRAIN][5M] asof=2021-06-07 feats=114 buy=YES sell=YES rows=77676
[CHRONO] daily close=2021-06-07 idx=2848
[CHRONO] 5m day=2021-06-08 rows=376009:376198
[CHRONO] daily close=2021-06-08 idx=2849
[CHRONO] 5m day=2021-06-09 rows=376198:376386
[CHRONO] daily close=2021-06-09 idx=2850
[CHRONO] 5m day=2021-06-10 rows=376386:376576
[CHRONO] daily close=2021-06-10 idx=2851
[CHRONO] 5m day=2021-06-11 rows=376576:376751
[CHRONO] daily close=2021-06-11 idx=2852
[CHRONO] 5m day=2021-06-14 rows=376751:376937
[TRAIN][5M] asof=2021-06-14 feats=114 buy=YES sell=YES rows=77851
[CHRONO] daily close=2021-06-14 idx=2853
[CHRONO] 5m day=2021-06-15 rows=376937:377125
[CHRONO] daily close=2021-06-15 idx=2854
[CHRONO] 5m day=2021-06-16 rows=377125:377313
[CHRONO] daily close=2021-06-16 idx=2855
[CHRONO] 5m day=2021-06-17 rows=377313:377504
[CHRONO] daily close=2021-06-17 idx=2856
[CHRONO] 5m day=2021-06-18 rows=377504:377694
[CHRONO] daily close=2021-06-18 idx=2857
[CHRONO] 5m day=2021-06-21 rows=377694:377884
[TRAIN][5M] asof=2021-06-21 feats=114 buy=YES sell=YES rows=78048
[CHRONO] daily close=2021-06-21 idx=2858
[CHRONO] 5m day=2021-06-22 rows=377884:378075
[CHRONO] daily close=2021-06-22 idx=2859
[CHRONO] 5m day=2021-06-23 rows=378075:378265
[CHRONO] daily close=2021-06-23 idx=2860
[CHRONO] 5m day=2021-06-24 rows=378265:378454
[CHRONO] daily close=2021-06-24 idx=2861
[CHRONO] 5m day=2021-06-25 rows=378454:378640
[CHRONO] daily close=2021-06-25 idx=2862
[CHRONO] 5m day=2021-06-28 rows=378640:378828
[TRAIN][5M] asof=2021-06-28 feats=114 buy=YES sell=YES rows=78197
[CHRONO] daily close=2021-06-28 idx=2863
[CHRONO] 5m day=2021-06-29 rows=378828:379019
[CHRONO] daily close=2021-06-29 idx=2864
[CHRONO] 5m day=2021-06-30 rows=379019:379206
[CHRONO] daily close=2021-06-30 idx=2865
[CHRONO] 5m day=2021-07-01 rows=379206:379390
[CHRONO] daily close=2021-07-01 idx=2866
[TRAIN][DAILY-PROB] n=2693 pos=549 (20.39%)
[CHRONO] 5m day=2021-07-02 rows=379390:379570
[CHRONO] daily close=2021-07-02 idx=2867
[CHRONO] 5m day=2021-07-06 rows=379570:379759
[TRAIN][5M] asof=2021-07-06 feats=114 buy=YES sell=YES rows=78435
[CHRONO] daily close=2021-07-06 idx=2868
[CHRONO] 5m day=2021-07-07 rows=379759:379946
[CHRONO] daily close=2021-07-07 idx=2869
[CHRONO] 5m day=2021-07-08 rows=379946:380137
[CHRONO] daily close=2021-07-08 idx=2870
[CHRONO] 5m day=2021-07-09 rows=380137:380321
[CHRONO] daily close=2021-07-09 idx=2871
[CHRONO] 5m day=2021-07-12 rows=380321:380509
[TRAIN][5M] asof=2021-07-12 feats=114 buy=YES sell=YES rows=78576
[CHRONO] daily close=2021-07-12 idx=2872
[CHRONO] 5m day=2021-07-13 rows=380509:380698
[CHRONO] daily close=2021-07-13 idx=2873
[CHRONO] 5m day=2021-07-14 rows=380698:380884
[CHRONO] daily close=2021-07-14 idx=2874
[CHRONO] 5m day=2021-07-15 rows=380884:381073
[CHRONO] daily close=2021-07-15 idx=2875
[CHRONO] 5m day=2021-07-16 rows=381073:381265
[CHRONO] daily close=2021-07-16 idx=2876
[CHRONO] 5m day=2021-07-19 rows=381265:381457
[TRAIN][5M] asof=2021-07-19 feats=114 buy=YES sell=YES rows=78778
[CHRONO] daily close=2021-07-19 idx=2877
[CHRONO] 5m day=2021-07-20 rows=381457:381648
[CHRONO] daily close=2021-07-20 idx=2878
[CHRONO] 5m day=2021-07-21 rows=381648:381840
[CHRONO] daily close=2021-07-21 idx=2879
[CHRONO] 5m day=2021-07-22 rows=381840:382028
[CHRONO] daily close=2021-07-22 idx=2880
[CHRONO] 5m day=2021-07-23 rows=382028:382209
[CHRONO] daily close=2021-07-23 idx=2881
[CHRONO] 5m day=2021-07-26 rows=382209:382400
[TRAIN][5M] asof=2021-07-26 feats=114 buy=YES sell=YES rows=78978
[CHRONO] daily close=2021-07-26 idx=2882
[CHRONO] 5m day=2021-07-27 rows=382400:382590
[CHRONO] daily close=2021-07-27 idx=2883
[CHRONO] 5m day=2021-07-28 rows=382590:382781
[CHRONO] daily close=2021-07-28 idx=2884
[CHRONO] 5m day=2021-07-29 rows=382781:382970
[CHRONO] daily close=2021-07-29 idx=2885
[CHRONO] 5m day=2021-07-30 rows=382970:383154
[CHRONO] daily close=2021-07-30 idx=2886
[CHRONO] 5m day=2021-08-02 rows=383154:383346
[TRAIN][5M] asof=2021-08-02 feats=114 buy=YES sell=YES rows=79197
[CHRONO] daily close=2021-08-02 idx=2887
[CHRONO] 5m day=2021-08-03 rows=383346:383535
[CHRONO] daily close=2021-08-03 idx=2888
[CHRONO] 5m day=2021-08-04 rows=383535:383722
[CHRONO] daily close=2021-08-04 idx=2889
[CHRONO] 5m day=2021-08-05 rows=383722:383907
[CHRONO] daily close=2021-08-05 idx=2890
[CHRONO] 5m day=2021-08-06 rows=383907:384082
[CHRONO] daily close=2021-08-06 idx=2891
[TRAIN][DAILY-PROB] n=2718 pos=552 (20.31%)
[CHRONO] 5m day=2021-08-09 rows=384082:384268
[TRAIN][5M] asof=2021-08-09 feats=114 buy=YES sell=YES rows=79361
[CHRONO] daily close=2021-08-09 idx=2892
[CHRONO] 5m day=2021-08-10 rows=384268:384451
[CHRONO] daily close=2021-08-10 idx=2893
[CHRONO] 5m day=2021-08-11 rows=384451:384640
[CHRONO] daily close=2021-08-11 idx=2894
[CHRONO] 5m day=2021-08-12 rows=384640:384823
[CHRONO] daily close=2021-08-12 idx=2895
[CHRONO] 5m day=2021-08-13 rows=384823:384994
[CHRONO] daily close=2021-08-13 idx=2896
[CHRONO] 5m day=2021-08-16 rows=384994:385183
[TRAIN][5M] asof=2021-08-16 feats=114 buy=YES sell=YES rows=79540
[CHRONO] daily close=2021-08-16 idx=2897
[CHRONO] 5m day=2021-08-17 rows=385183:385370
[CHRONO] daily close=2021-08-17 idx=2898
[CHRONO] 5m day=2021-08-18 rows=385370:385556
[CHRONO] daily close=2021-08-18 idx=2899
[CHRONO] 5m day=2021-08-19 rows=385556:385748
[CHRONO] daily close=2021-08-19 idx=2900
[CHRONO] 5m day=2021-08-20 rows=385748:385930
[CHRONO] daily close=2021-08-20 idx=2901
[CHRONO] 5m day=2021-08-23 rows=385930:386121
[TRAIN][5M] asof=2021-08-23 feats=114 buy=YES sell=YES rows=79764
[CHRONO] daily close=2021-08-23 idx=2902
[CHRONO] 5m day=2021-08-24 rows=386121:386310
[CHRONO] daily close=2021-08-24 idx=2903
[CHRONO] 5m day=2021-08-25 rows=386310:386494
[CHRONO] daily close=2021-08-25 idx=2904
[CHRONO] 5m day=2021-08-26 rows=386494:386676
[CHRONO] daily close=2021-08-26 idx=2905
[CHRONO] 5m day=2021-08-27 rows=386676:386859
[CHRONO] daily close=2021-08-27 idx=2906
[CHRONO] 5m day=2021-08-30 rows=386859:387048
[TRAIN][5M] asof=2021-08-30 feats=114 buy=YES sell=YES rows=79957
[CHRONO] daily close=2021-08-30 idx=2907
[CHRONO] 5m day=2021-08-31 rows=387048:387238
[CHRONO] daily close=2021-08-31 idx=2908
[CHRONO] 5m day=2021-09-01 rows=387238:387426
[CHRONO] daily close=2021-09-01 idx=2909
[CHRONO] 5m day=2021-09-02 rows=387426:387607
[CHRONO] daily close=2021-09-02 idx=2910
[CHRONO] 5m day=2021-09-03 rows=387607:387785
[CHRONO] daily close=2021-09-03 idx=2911
[CHRONO] 5m day=2021-09-07 rows=387785:387974
[TRAIN][5M] asof=2021-09-07 feats=114 buy=YES sell=YES rows=80142
[CHRONO] daily close=2021-09-07 idx=2912
[CHRONO] 5m day=2021-09-08 rows=387974:388161
[CHRONO] daily close=2021-09-08 idx=2913
[CHRONO] 5m day=2021-09-09 rows=388161:388349
[CHRONO] daily close=2021-09-09 idx=2914
[CHRONO] 5m day=2021-09-10 rows=388349:388538
[CHRONO] daily close=2021-09-10 idx=2915
[CHRONO] 5m day=2021-09-13 rows=388538:388725
[TRAIN][5M] asof=2021-09-13 feats=114 buy=YES sell=YES rows=80277
[CHRONO] daily close=2021-09-13 idx=2916
[TRAIN][DAILY-PROB] n=2743 pos=555 (20.23%)
[CHRONO] 5m day=2021-09-14 rows=388725:388914
[CHRONO] daily close=2021-09-14 idx=2917
[CHRONO] 5m day=2021-09-15 rows=388914:389098
[CHRONO] daily close=2021-09-15 idx=2918
[CHRONO] 5m day=2021-09-16 rows=389098:389283
[CHRONO] daily close=2021-09-16 idx=2919
[CHRONO] 5m day=2021-09-17 rows=389283:389473
[CHRONO] daily close=2021-09-17 idx=2920
[CHRONO] 5m day=2021-09-20 rows=389473:389665
[TRAIN][5M] asof=2021-09-20 feats=114 buy=YES sell=YES rows=80488
[CHRONO] daily close=2021-09-20 idx=2921
[CHRONO] 5m day=2021-09-21 rows=389665:389855
[CHRONO] daily close=2021-09-21 idx=2922
[CHRONO] 5m day=2021-09-22 rows=389855:390047
[CHRONO] daily close=2021-09-22 idx=2923
[CHRONO] 5m day=2021-09-23 rows=390047:390237
[CHRONO] daily close=2021-09-23 idx=2924
[CHRONO] 5m day=2021-09-24 rows=390237:390415
[CHRONO] daily close=2021-09-24 idx=2925

c:\Users\TonyTang\Documents\chan.py\adaptive_reward_checkpoint_fresh.py:3132: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  daily_log_df = pd.concat(daily_log_frames, ignore_index=True, sort=False) if daily_log_frames else pd.DataFrame()

[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2021\trades.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2021\signal_decisions.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2021\daily_log.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2021\daily_reward_log.csv
[CHECKPOINT] saved chronological snapshot -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2021\continued_checkpoint__through_2021.joblib
[DONE] 2021 checkpoint: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2021\continued_checkpoint__through_2021.joblib
[RUN] 2022: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2021\continued_checkpoint__through_2021.joblib -> 2022-12-31 16:00:00
[CHRONO] 5m day=2021-12-31 rows=403211:403247
[TRAIN][5M] asof=2021-12-31 feats=114 buy=YES sell=YES rows=83047
[CHECKPOINT] autosaved chronological year-start snapshot for 2022 before 2022-01-03 -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2022\year_start_checkpoints\continued_checkpoint__through_2022__start_2022.joblib
[CHRONO] 5m day=2022-01-03 rows=403247:403436
[CHRONO] daily close=2022-01-03 idx=2994
[CHRONO] 5m day=2022-01-04 rows=403436:403627
[CHRONO] daily close=2022-01-04 idx=2995
[CHRONO] 5m day=2022-01-05 rows=403627:403818
[TRAIN][5M] asof=2022-01-05 feats=114 buy=YES sell=YES rows=83172
[CHRONO] daily close=2022-01-05 idx=2996
[CHRONO] 5m day=2022-01-06 rows=403818:404010
[CHRONO] daily close=2022-01-06 idx=2997
[CHRONO] 5m day=2022-01-07 rows=404010:404200
[CHRONO] daily close=2022-01-07 idx=2998
[CHRONO] 5m day=2022-01-10 rows=404200:404391
[TRAIN][5M] asof=2022-01-10 feats=114 buy=YES sell=YES rows=83270
[CHRONO] daily close=2022-01-10 idx=2999
[CHRONO] 5m day=2022-01-11 rows=404391:404583
[CHRONO] daily close=2022-01-11 idx=3000
[CHRONO] 5m day=2022-01-12 rows=404583:404775
[CHRONO] daily close=2022-01-12 idx=3001
[CHRONO] 5m day=2022-01-13 rows=404775:404966
[CHRONO] daily close=2022-01-13 idx=3002
[CHRONO] 5m day=2022-01-14 rows=404966:405154
[CHRONO] daily close=2022-01-14 idx=3003
[CHRONO] 5m day=2022-01-18 rows=405154:405345
[TRAIN][5M] asof=2022-01-18 feats=114 buy=YES sell=YES rows=83490
[CHRONO] daily close=2022-01-18 idx=3004
[CHRONO] 5m day=2022-01-19 rows=405345:405537
[CHRONO] daily close=2022-01-19 idx=3005
[CHRONO] 5m day=2022-01-20 rows=405537:405729
[CHRONO] daily close=2022-01-20 idx=3006
[CHRONO] 5m day=2022-01-21 rows=405729:405921
[CHRONO] daily close=2022-01-21 idx=3007
[CHRONO] 5m day=2022-01-24 rows=405921:406113
[TRAIN][5M] asof=2022-01-24 feats=114 buy=YES sell=YES rows=83652
[CHRONO] daily close=2022-01-24 idx=3008
[CHRONO] 5m day=2022-01-25 rows=406113:406305
[CHRONO] daily close=2022-01-25 idx=3009
[CHRONO] 5m day=2022-01-26 rows=406305:406497
[CHRONO] daily close=2022-01-26 idx=3010
[CHRONO] 5m day=2022-01-27 rows=406497:406689
[CHRONO] daily close=2022-01-27 idx=3011
[CHRONO] 5m day=2022-01-28 rows=406689:406881
[CHRONO] daily close=2022-01-28 idx=3012
[CHRONO] 5m day=2022-01-31 rows=406881:407073
[TRAIN][5M] asof=2022-01-31 feats=114 buy=YES sell=YES rows=83798
[CHRONO] daily close=2022-01-31 idx=3013
[CHRONO] 5m day=2022-02-01 rows=407073:407265
[CHRONO] daily close=2022-02-01 idx=3014
[CHRONO] 5m day=2022-02-02 rows=407265:407457
[CHRONO] daily close=2022-02-02 idx=3015
[CHRONO] 5m day=2022-02-03 rows=407457:407649
[CHRONO] daily close=2022-02-03 idx=3016
[CHRONO] 5m day=2022-02-04 rows=407649:407840
[CHRONO] daily close=2022-02-04 idx=3017
[CHRONO] 5m day=2022-02-07 rows=407840:408031
[TRAIN][5M] asof=2022-02-07 feats=114 buy=YES sell=YES rows=83981
[CHRONO] daily close=2022-02-07 idx=3018
[TRAIN][DAILY-PROB] n=2845 pos=582 (20.46%)
[CHRONO] 5m day=2022-02-08 rows=408031:408220
[CHRONO] daily close=2022-02-08 idx=3019
[CHRONO] 5m day=2022-02-09 rows=408220:408412
[CHRONO] daily close=2022-02-09 idx=3020
[CHRONO] 5m day=2022-02-10 rows=408412:408602
[CHRONO] daily close=2022-02-10 idx=3021
[CHRONO] 5m day=2022-02-11 rows=408602:408794
[CHRONO] daily close=2022-02-11 idx=3022
[CHRONO] 5m day=2022-02-14 rows=408794:408985
[TRAIN][5M] asof=2022-02-14 feats=114 buy=YES sell=YES rows=84150
[CHRONO] daily close=2022-02-14 idx=3023
[CHRONO] 5m day=2022-02-15 rows=408985:409177
[CHRONO] daily close=2022-02-15 idx=3024
[CHRONO] 5m day=2022-02-16 rows=409177:409369
[CHRONO] daily close=2022-02-16 idx=3025
[CHRONO] 5m day=2022-02-17 rows=409369:409560
[CHRONO] daily close=2022-02-17 idx=3026
[CHRONO] 5m day=2022-02-18 rows=409560:409752
[CHRONO] daily close=2022-02-18 idx=3027
[CHRONO] 5m day=2022-02-22 rows=409752:409944
[TRAIN][5M] asof=2022-02-22 feats=114 buy=YES sell=YES rows=84326
[CHRONO] daily close=2022-02-22 idx=3028
[CHRONO] 5m day=2022-02-23 rows=409944:410136
[CHRONO] daily close=2022-02-23 idx=3029
[CHRONO] 5m day=2022-02-24 rows=410136:410328
[CHRONO] daily close=2022-02-24 idx=3030
[CHRONO] 5m day=2022-02-25 rows=410328:410520
[CHRONO] daily close=2022-02-25 idx=3031
[CHRONO] 5m day=2022-02-28 rows=410520:410712
[TRAIN][5M] asof=2022-02-28 feats=114 buy=YES sell=YES rows=84502
[CHRONO] daily close=2022-02-28 idx=3032
[CHRONO] 5m day=2022-03-01 rows=410712:410904
[CHRONO] daily close=2022-03-01 idx=3033
[CHRONO] 5m day=2022-03-02 rows=410904:411096
[CHRONO] daily close=2022-03-02 idx=3034
[CHRONO] 5m day=2022-03-03 rows=411096:411287
[CHRONO] daily close=2022-03-03 idx=3035
[CHRONO] 5m day=2022-03-04 rows=411287:411478
[CHRONO] daily close=2022-03-04 idx=3036
[CHRONO] 5m day=2022-03-07 rows=411478:411670
[TRAIN][5M] asof=2022-03-07 feats=114 buy=YES sell=YES rows=84720
[CHRONO] daily close=2022-03-07 idx=3037
[CHRONO] 5m day=2022-03-08 rows=411670:411862
[CHRONO] daily close=2022-03-08 idx=3038
[CHRONO] 5m day=2022-03-09 rows=411862:412054
[CHRONO] daily close=2022-03-09 idx=3039
[CHRONO] 5m day=2022-03-10 rows=412054:412245
[CHRONO] daily close=2022-03-10 idx=3040
[CHRONO] 5m day=2022-03-11 rows=412245:412436
[CHRONO] daily close=2022-03-11 idx=3041
[CHRONO] 5m day=2022-03-14 rows=412436:412628
[TRAIN][5M] asof=2022-03-14 feats=114 buy=YES sell=YES rows=84875
[CHRONO] daily close=2022-03-14 idx=3042
[CHRONO] 5m day=2022-03-15 rows=412628:412820
[CHRONO] daily close=2022-03-15 idx=3043
[TRAIN][DAILY-PROB] n=2870 pos=583 (20.31%)
[CHRONO] 5m day=2022-03-16 rows=412820:413012
[CHRONO] daily close=2022-03-16 idx=3044
[CHRONO] 5m day=2022-03-17 rows=413012:413203
[CHRONO] daily close=2022-03-17 idx=3045
[CHRONO] 5m day=2022-03-18 rows=413203:413395
[CHRONO] daily close=2022-03-18 idx=3046
[CHRONO] 5m day=2022-03-21 rows=413395:413587
[TRAIN][5M] asof=2022-03-21 feats=114 buy=YES sell=YES rows=85081
[CHRONO] daily close=2022-03-21 idx=3047
[CHRONO] 5m day=2022-03-22 rows=413587:413779
[CHRONO] daily close=2022-03-22 idx=3048
[CHRONO] 5m day=2022-03-23 rows=413779:413970
[CHRONO] daily close=2022-03-23 idx=3049
[CHRONO] 5m day=2022-03-24 rows=413970:414161
[CHRONO] daily close=2022-03-24 idx=3050
[CHRONO] 5m day=2022-03-25 rows=414161:414350
[CHRONO] daily close=2022-03-25 idx=3051
[CHRONO] 5m day=2022-03-28 rows=414350:414542
[TRAIN][5M] asof=2022-03-28 feats=114 buy=YES sell=YES rows=85291
[CHRONO] daily close=2022-03-28 idx=3052
[CHRONO] 5m day=2022-03-29 rows=414542:414733
[CHRONO] daily close=2022-03-29 idx=3053
[CHRONO] 5m day=2022-03-30 rows=414733:414924
[CHRONO] daily close=2022-03-30 idx=3054
[CHRONO] 5m day=2022-03-31 rows=414924:415115
[CHRONO] daily close=2022-03-31 idx=3055
[CHRONO] 5m day=2022-04-01 rows=415115:415297
[CHRONO] daily close=2022-04-01 idx=3056
[CHRONO] 5m day=2022-04-04 rows=415297:415489
[TRAIN][5M] asof=2022-04-04 feats=114 buy=YES sell=YES rows=85502
[CHRONO] daily close=2022-04-04 idx=3057
[CHRONO] 5m day=2022-04-05 rows=415489:415681
[CHRONO] daily close=2022-04-05 idx=3058
[CHRONO] 5m day=2022-04-06 rows=415681:415873
[CHRONO] daily close=2022-04-06 idx=3059
[CHRONO] 5m day=2022-04-07 rows=415873:416065
[CHRONO] daily close=2022-04-07 idx=3060
[CHRONO] 5m day=2022-04-08 rows=416065:416256
[CHRONO] daily close=2022-04-08 idx=3061
[CHRONO] 5m day=2022-04-11 rows=416256:416446
[TRAIN][5M] asof=2022-04-11 feats=114 buy=YES sell=YES rows=85724
[CHRONO] daily close=2022-04-11 idx=3062
[CHRONO] 5m day=2022-04-12 rows=416446:416637
[CHRONO] daily close=2022-04-12 idx=3063
[CHRONO] 5m day=2022-04-13 rows=416637:416829
[CHRONO] daily close=2022-04-13 idx=3064
[CHRONO] 5m day=2022-04-14 rows=416829:417017
[CHRONO] daily close=2022-04-14 idx=3065
[CHRONO] 5m day=2022-04-18 rows=417017:417209
[TRAIN][5M] asof=2022-04-18 feats=114 buy=YES sell=YES rows=85889
[CHRONO] daily close=2022-04-18 idx=3066
[CHRONO] 5m day=2022-04-19 rows=417209:417401
[CHRONO] daily close=2022-04-19 idx=3067
[CHRONO] 5m day=2022-04-20 rows=417401:417593
[CHRONO] daily close=2022-04-20 idx=3068
[TRAIN][DAILY-PROB] n=2895 pos=593 (20.48%)
[CHRONO] 5m day=2022-04-21 rows=417593:417782
[CHRONO] daily close=2022-04-21 idx=3069
[CHRONO] 5m day=2022-04-22 rows=417782:417974
[CHRONO] daily close=2022-04-22 idx=3070
[CHRONO] 5m day=2022-04-25 rows=417974:418166
[TRAIN][5M] asof=2022-04-25 feats=114 buy=YES sell=YES rows=86068
[CHRONO] daily close=2022-04-25 idx=3071
[CHRONO] 5m day=2022-04-26 rows=418166:418358
[CHRONO] daily close=2022-04-26 idx=3072
[CHRONO] 5m day=2022-04-27 rows=418358:418550
[CHRONO] daily close=2022-04-27 idx=3073
[CHRONO] 5m day=2022-04-28 rows=418550:418742
[CHRONO] daily close=2022-04-28 idx=3074
[CHRONO] 5m day=2022-04-29 rows=418742:418934
[CHRONO] daily close=2022-04-29 idx=3075
[CHRONO] 5m day=2022-05-02 rows=418934:419126
[TRAIN][5M] asof=2022-05-02 feats=114 buy=YES sell=YES rows=86232
[CHRONO] daily close=2022-05-02 idx=3076
[CHRONO] 5m day=2022-05-03 rows=419126:419318
[CHRONO] daily close=2022-05-03 idx=3077
[CHRONO] 5m day=2022-05-04 rows=419318:419509
[CHRONO] daily close=2022-05-04 idx=3078
[CHRONO] 5m day=2022-05-05 rows=419509:419701
[CHRONO] daily close=2022-05-05 idx=3079
[CHRONO] 5m day=2022-05-06 rows=419701:419889
[CHRONO] daily close=2022-05-06 idx=3080
[CHRONO] 5m day=2022-05-09 rows=419889:420081
[TRAIN][5M] asof=2022-05-09 feats=114 buy=YES sell=YES rows=86421
[CHRONO] daily close=2022-05-09 idx=3081
[CHRONO] 5m day=2022-05-10 rows=420081:420273
[CHRONO] daily close=2022-05-10 idx=3082
[CHRONO] 5m day=2022-05-11 rows=420273:420465
[CHRONO] daily close=2022-05-11 idx=3083
[CHRONO] 5m day=2022-05-12 rows=420465:420657
[CHRONO] daily close=2022-05-12 idx=3084
[CHRONO] 5m day=2022-05-13 rows=420657:420849
[CHRONO] daily close=2022-05-13 idx=3085
[CHRONO] 5m day=2022-05-16 rows=420849:421041
[TRAIN][5M] asof=2022-05-16 feats=114 buy=YES sell=YES rows=86612
[CHRONO] daily close=2022-05-16 idx=3086
[CHRONO] 5m day=2022-05-17 rows=421041:421233
[CHRONO] daily close=2022-05-17 idx=3087
[CHRONO] 5m day=2022-05-18 rows=421233:421425
[CHRONO] daily close=2022-05-18 idx=3088
[CHRONO] 5m day=2022-05-19 rows=421425:421617
[CHRONO] daily close=2022-05-19 idx=3089
[CHRONO] 5m day=2022-05-20 rows=421617:421809
[CHRONO] daily close=2022-05-20 idx=3090
[CHRONO] 5m day=2022-05-23 rows=421809:422001
[TRAIN][5M] asof=2022-05-23 feats=114 buy=YES sell=YES rows=86839
[CHRONO] daily close=2022-05-23 idx=3091
[CHRONO] 5m day=2022-05-24 rows=422001:422193
[CHRONO] daily close=2022-05-24 idx=3092
[CHRONO] 5m day=2022-05-25 rows=422193:422385
[CHRONO] daily close=2022-05-25 idx=3093
[TRAIN][DAILY-PROB] n=2920 pos=594 (20.34%)
[CHRONO] 5m day=2022-05-26 rows=422385:422577
[CHRONO] daily close=2022-05-26 idx=3094
[CHRONO] 5m day=2022-05-27 rows=422577:422768
[CHRONO] daily close=2022-05-27 idx=3095
[CHRONO] 5m day=2022-05-31 rows=422768:422960
[TRAIN][5M] asof=2022-05-31 feats=114 buy=YES sell=YES rows=87065
[CHRONO] daily close=2022-05-31 idx=3096
[CHRONO] 5m day=2022-06-01 rows=422960:423152
[CHRONO] daily close=2022-06-01 idx=3097
[CHRONO] 5m day=2022-06-02 rows=423152:423344
[CHRONO] daily close=2022-06-02 idx=3098
[CHRONO] 5m day=2022-06-03 rows=423344:423536
[CHRONO] daily close=2022-06-03 idx=3099
[CHRONO] 5m day=2022-06-06 rows=423536:423727
[TRAIN][5M] asof=2022-06-06 feats=114 buy=YES sell=YES rows=87233
[CHRONO] daily close=2022-06-06 idx=3100
[CHRONO] 5m day=2022-06-07 rows=423727:423919
[CHRONO] daily close=2022-06-07 idx=3101
[CHRONO] 5m day=2022-06-08 rows=423919:424109
[CHRONO] daily close=2022-06-08 idx=3102
[CHRONO] 5m day=2022-06-09 rows=424109:424301
[CHRONO] daily close=2022-06-09 idx=3103
[CHRONO] 5m day=2022-06-10 rows=424301:424492
[CHRONO] daily close=2022-06-10 idx=3104
[CHRONO] 5m day=2022-06-13 rows=424492:424684
[TRAIN][5M] asof=2022-06-13 feats=114 buy=YES sell=YES rows=87458
[CHRONO] daily close=2022-06-13 idx=3105
[CHRONO] 5m day=2022-06-14 rows=424684:424875
[CHRONO] daily close=2022-06-14 idx=3106
[CHRONO] 5m day=2022-06-15 rows=424875:425067
[CHRONO] daily close=2022-06-15 idx=3107
[CHRONO] 5m day=2022-06-16 rows=425067:425259
[CHRONO] daily close=2022-06-16 idx=3108
[CHRONO] 5m day=2022-06-17 rows=425259:425450
[CHRONO] daily close=2022-06-17 idx=3109
[CHRONO] 5m day=2022-06-21 rows=425450:425640
[TRAIN][5M] asof=2022-06-21 feats=114 buy=YES sell=YES rows=87650
[CHRONO] daily close=2022-06-21 idx=3110
[CHRONO] 5m day=2022-06-22 rows=425640:425832
[CHRONO] daily close=2022-06-22 idx=3111
[CHRONO] 5m day=2022-06-23 rows=425832:426024
[CHRONO] daily close=2022-06-23 idx=3112
[CHRONO] 5m day=2022-06-24 rows=426024:426216
[CHRONO] daily close=2022-06-24 idx=3113
[CHRONO] 5m day=2022-06-27 rows=426216:426408
[TRAIN][5M] asof=2022-06-27 feats=114 buy=YES sell=YES rows=87781
[CHRONO] daily close=2022-06-27 idx=3114
[CHRONO] 5m day=2022-06-28 rows=426408:426597
[CHRONO] daily close=2022-06-28 idx=3115
[CHRONO] 5m day=2022-06-29 rows=426597:426785
[CHRONO] daily close=2022-06-29 idx=3116
[CHRONO] 5m day=2022-06-30 rows=426785:426977
[CHRONO] daily close=2022-06-30 idx=3117
[CHRONO] 5m day=2022-07-01 rows=426977:427164
[CHRONO] daily close=2022-07-01 idx=3118
[TRAIN][DAILY-PROB] n=2945 pos=604 (20.51%)
[CHRONO] 5m day=2022-07-05 rows=427164:427356
[TRAIN][5M] asof=2022-07-05 feats=114 buy=YES sell=YES rows=87979
[CHRONO] daily close=2022-07-05 idx=3119
[CHRONO] 5m day=2022-07-06 rows=427356:427547
[CHRONO] daily close=2022-07-06 idx=3120
[CHRONO] 5m day=2022-07-07 rows=427547:427739
[CHRONO] daily close=2022-07-07 idx=3121
[CHRONO] 5m day=2022-07-08 rows=427739:427930
[CHRONO] daily close=2022-07-08 idx=3122
[CHRONO] 5m day=2022-07-11 rows=427930:428122
[TRAIN][5M] asof=2022-07-11 feats=114 buy=YES sell=YES rows=88109
[CHRONO] daily close=2022-07-11 idx=3123
[CHRONO] 5m day=2022-07-12 rows=428122:428314
[CHRONO] daily close=2022-07-12 idx=3124
[CHRONO] 5m day=2022-07-13 rows=428314:428503
[CHRONO] daily close=2022-07-13 idx=3125
[CHRONO] 5m day=2022-07-14 rows=428503:428695
[CHRONO] daily close=2022-07-14 idx=3126
[CHRONO] 5m day=2022-07-15 rows=428695:428885
[CHRONO] daily close=2022-07-15 idx=3127
[CHRONO] 5m day=2022-07-18 rows=428885:429077
[TRAIN][5M] asof=2022-07-18 feats=114 buy=YES sell=YES rows=88211
[CHRONO] daily close=2022-07-18 idx=3128
[CHRONO] 5m day=2022-07-19 rows=429077:429269
[CHRONO] daily close=2022-07-19 idx=3129
[CHRONO] 5m day=2022-07-20 rows=429269:429461
[CHRONO] daily close=2022-07-20 idx=3130
[CHRONO] 5m day=2022-07-21 rows=429461:429653
[CHRONO] daily close=2022-07-21 idx=3131
[CHRONO] 5m day=2022-07-22 rows=429653:429844
[CHRONO] daily close=2022-07-22 idx=3132
[CHRONO] 5m day=2022-07-25 rows=429844:430036
[TRAIN][5M] asof=2022-07-25 feats=114 buy=YES sell=YES rows=88415
[CHRONO] daily close=2022-07-25 idx=3133
[CHRONO] 5m day=2022-07-26 rows=430036:430226
[CHRONO] daily close=2022-07-26 idx=3134
[CHRONO] 5m day=2022-07-27 rows=430226:430418
[CHRONO] daily close=2022-07-27 idx=3135
[CHRONO] 5m day=2022-07-28 rows=430418:430610
[CHRONO] daily close=2022-07-28 idx=3136
[CHRONO] 5m day=2022-07-29 rows=430610:430800
[CHRONO] daily close=2022-07-29 idx=3137
[CHRONO] 5m day=2022-08-01 rows=430800:430989
[TRAIN][5M] asof=2022-08-01 feats=114 buy=YES sell=YES rows=88569
[CHRONO] daily close=2022-08-01 idx=3138
[CHRONO] 5m day=2022-08-02 rows=430989:431181
[CHRONO] daily close=2022-08-02 idx=3139
[CHRONO] 5m day=2022-08-03 rows=431181:431373
[CHRONO] daily close=2022-08-03 idx=3140
[CHRONO] 5m day=2022-08-04 rows=431373:431564
[CHRONO] daily close=2022-08-04 idx=3141
[CHRONO] 5m day=2022-08-05 rows=431564:431748
[CHRONO] daily close=2022-08-05 idx=3142
[CHRONO] 5m day=2022-08-08 rows=431748:431940
[TRAIN][5M] asof=2022-08-08 feats=114 buy=YES sell=YES rows=88756
[CHRONO] daily close=2022-08-08 idx=3143
[TRAIN][DAILY-PROB] n=2970 pos=610 (20.54%)
[CHRONO] 5m day=2022-08-09 rows=431940:432129
[CHRONO] daily close=2022-08-09 idx=3144
[CHRONO] 5m day=2022-08-10 rows=432129:432320
[CHRONO] daily close=2022-08-10 idx=3145
[CHRONO] 5m day=2022-08-11 rows=432320:432512
[CHRONO] daily close=2022-08-11 idx=3146
[CHRONO] 5m day=2022-08-12 rows=432512:432703
[CHRONO] daily close=2022-08-12 idx=3147
[CHRONO] 5m day=2022-08-15 rows=432703:432893
[TRAIN][5M] asof=2022-08-15 feats=114 buy=YES sell=YES rows=88947
[CHRONO] daily close=2022-08-15 idx=3148
[CHRONO] 5m day=2022-08-16 rows=432893:433082
[CHRONO] daily close=2022-08-16 idx=3149
[CHRONO] 5m day=2022-08-17 rows=433082:433272
[CHRONO] daily close=2022-08-17 idx=3150
[CHRONO] 5m day=2022-08-18 rows=433272:433462
[CHRONO] daily close=2022-08-18 idx=3151
[CHRONO] 5m day=2022-08-19 rows=433462:433654
[CHRONO] daily close=2022-08-19 idx=3152
[CHRONO] 5m day=2022-08-22 rows=433654:433846
[TRAIN][5M] asof=2022-08-22 feats=114 buy=YES sell=YES rows=89216
[CHRONO] daily close=2022-08-22 idx=3153
[CHRONO] 5m day=2022-08-23 rows=433846:434038
[CHRONO] daily close=2022-08-23 idx=3154
[CHRONO] 5m day=2022-08-24 rows=434038:434229
[CHRONO] daily close=2022-08-24 idx=3155
[CHRONO] 5m day=2022-08-25 rows=434229:434420
[CHRONO] daily close=2022-08-25 idx=3156
[CHRONO] 5m day=2022-08-26 rows=434420:434612
[CHRONO] daily close=2022-08-26 idx=3157
[CHRONO] 5m day=2022-08-29 rows=434612:434804
[TRAIN][5M] asof=2022-08-29 feats=114 buy=YES sell=YES rows=89416
[CHRONO] daily close=2022-08-29 idx=3158
[CHRONO] 5m day=2022-08-30 rows=434804:434995
[CHRONO] daily close=2022-08-30 idx=3159
[CHRONO] 5m day=2022-08-31 rows=434995:435187
[CHRONO] daily close=2022-08-31 idx=3160
[CHRONO] 5m day=2022-09-01 rows=435187:435379
[CHRONO] daily close=2022-09-01 idx=3161
[CHRONO] 5m day=2022-09-02 rows=435379:435571
[CHRONO] daily close=2022-09-02 idx=3162
[CHRONO] 5m day=2022-09-06 rows=435571:435762
[TRAIN][5M] asof=2022-09-06 feats=114 buy=YES sell=YES rows=89619
[CHRONO] daily close=2022-09-06 idx=3163
[CHRONO] 5m day=2022-09-07 rows=435762:435954
[CHRONO] daily close=2022-09-07 idx=3164
[CHRONO] 5m day=2022-09-08 rows=435954:436143
[CHRONO] daily close=2022-09-08 idx=3165
[CHRONO] 5m day=2022-09-09 rows=436143:436334
[CHRONO] daily close=2022-09-09 idx=3166
[CHRONO] 5m day=2022-09-12 rows=436334:436526
[TRAIN][5M] asof=2022-09-12 feats=114 buy=YES sell=YES rows=89790
[CHRONO] daily close=2022-09-12 idx=3167
[CHRONO] 5m day=2022-09-13 rows=436526:436716
[CHRONO] daily close=2022-09-13 idx=3168
[TRAIN][DAILY-PROB] n=2995 pos=619 (20.67%)
[CHRONO] 5m day=2022-09-14 rows=436716:436908
[CHRONO] daily close=2022-09-14 idx=3169
[CHRONO] 5m day=2022-09-15 rows=436908:437098
[CHRONO] daily close=2022-09-15 idx=3170
[CHRONO] 5m day=2022-09-16 rows=437098:437290
[CHRONO] daily close=2022-09-16 idx=3171
[CHRONO] 5m day=2022-09-19 rows=437290:437482
[TRAIN][5M] asof=2022-09-19 feats=114 buy=YES sell=YES rows=89977
[CHRONO] daily close=2022-09-19 idx=3172
[CHRONO] 5m day=2022-09-20 rows=437482:437674
[CHRONO] daily close=2022-09-20 idx=3173
[CHRONO] 5m day=2022-09-21 rows=437674:437865
[CHRONO] daily close=2022-09-21 idx=3174
[CHRONO] 5m day=2022-09-22 rows=437865:438057
[CHRONO] daily close=2022-09-22 idx=3175
[CHRONO] 5m day=2022-09-23 rows=438057:438246
[CHRONO] daily close=2022-09-23 idx=3176
[CHRONO] 5m day=2022-09-26 rows=438246:438438
[TRAIN][5M] asof=2022-09-26 feats=114 buy=YES sell=YES rows=90181

c:\Users\TonyTang\Documents\chan.py\adaptive_reward_checkpoint_fresh.py:3132: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  daily_log_df = pd.concat(daily_log_frames, ignore_index=True, sort=False) if daily_log_frames else pd.DataFrame()

[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2022\trades.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2022\signal_decisions.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2022\daily_log.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2022\daily_reward_log.csv
[CHECKPOINT] saved chronological snapshot -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2022\continued_checkpoint__through_2022.joblib
[DONE] 2022 checkpoint: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2022\continued_checkpoint__through_2022.joblib
[RUN] 2023: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2022\continued_checkpoint__through_2022.joblib -> 2023-12-31 16:00:00
[CHECKPOINT] autosaved chronological year-start snapshot for 2023 before 2023-01-03 -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2023\year_start_checkpoints\continued_checkpoint__through_2023__start_2023.joblib
[CHRONO] 5m day=2023-01-03 rows=451208:451399
[TRAIN][5M] asof=2023-01-03 feats=114 buy=YES sell=YES rows=92646
[CHRONO] daily close=2023-01-03 idx=3245
[CHRONO] 5m day=2023-01-04 rows=451399:451591
[CHRONO] daily close=2023-01-04 idx=3246
[CHRONO] 5m day=2023-01-05 rows=451591:451783
[CHRONO] daily close=2023-01-05 idx=3247
[CHRONO] 5m day=2023-01-06 rows=451783:451973
[CHRONO] daily close=2023-01-06 idx=3248
[CHRONO] 5m day=2023-01-09 rows=451973:452165
[TRAIN][5M] asof=2023-01-09 feats=114 buy=YES sell=YES rows=92758
[CHRONO] daily close=2023-01-09 idx=3249
[CHRONO] 5m day=2023-01-10 rows=452165:452353
[CHRONO] daily close=2023-01-10 idx=3250
[CHRONO] 5m day=2023-01-11 rows=452353:452545
[CHRONO] daily close=2023-01-11 idx=3251
[CHRONO] 5m day=2023-01-12 rows=452545:452737
[CHRONO] daily close=2023-01-12 idx=3252
[CHRONO] 5m day=2023-01-13 rows=452737:452925
[CHRONO] daily close=2023-01-13 idx=3253
[CHRONO] 5m day=2023-01-17 rows=452925:453116
[TRAIN][5M] asof=2023-01-17 feats=114 buy=YES sell=YES rows=92934
[CHRONO] daily close=2023-01-17 idx=3254
[CHRONO] 5m day=2023-01-18 rows=453116:453308
[CHRONO] daily close=2023-01-18 idx=3255
[CHRONO] 5m day=2023-01-19 rows=453308:453500
[CHRONO] daily close=2023-01-19 idx=3256
[CHRONO] 5m day=2023-01-20 rows=453500:453686
[CHRONO] daily close=2023-01-20 idx=3257
[CHRONO] 5m day=2023-01-23 rows=453686:453877
[TRAIN][5M] asof=2023-01-23 feats=114 buy=YES sell=YES rows=93094
[CHRONO] daily close=2023-01-23 idx=3258
[CHRONO] 5m day=2023-01-24 rows=453877:454069
[CHRONO] daily close=2023-01-24 idx=3259
[CHRONO] 5m day=2023-01-25 rows=454069:454261
[CHRONO] daily close=2023-01-25 idx=3260
[CHRONO] 5m day=2023-01-26 rows=454261:454453
[CHRONO] daily close=2023-01-26 idx=3261
[CHRONO] 5m day=2023-01-27 rows=454453:454643
[CHRONO] daily close=2023-01-27 idx=3262
[CHRONO] 5m day=2023-01-30 rows=454643:454835
[TRAIN][5M] asof=2023-01-30 feats=114 buy=YES sell=YES rows=93278
[CHRONO] daily close=2023-01-30 idx=3263
[CHRONO] 5m day=2023-01-31 rows=454835:455027
[CHRONO] daily close=2023-01-31 idx=3264
[CHRONO] 5m day=2023-02-01 rows=455027:455218
[CHRONO] daily close=2023-02-01 idx=3265
[CHRONO] 5m day=2023-02-02 rows=455218:455410
[CHRONO] daily close=2023-02-02 idx=3266
[CHRONO] 5m day=2023-02-03 rows=455410:455596
[CHRONO] daily close=2023-02-03 idx=3267
[CHRONO] 5m day=2023-02-06 rows=455596:455788
[TRAIN][5M] asof=2023-02-06 feats=114 buy=YES sell=YES rows=93499
[CHRONO] daily close=2023-02-06 idx=3268
[CHRONO] 5m day=2023-02-07 rows=455788:455980
[CHRONO] daily close=2023-02-07 idx=3269
[TRAIN][DAILY-PROB] n=3096 pos=640 (20.67%)
[CHRONO] 5m day=2023-02-08 rows=455980:456171
[CHRONO] daily close=2023-02-08 idx=3270
[CHRONO] 5m day=2023-02-09 rows=456171:456363
[CHRONO] daily close=2023-02-09 idx=3271
[CHRONO] 5m day=2023-02-10 rows=456363:456548
[CHRONO] daily close=2023-02-10 idx=3272
[CHRONO] 5m day=2023-02-13 rows=456548:456740
[TRAIN][5M] asof=2023-02-13 feats=114 buy=YES sell=YES rows=93715
[CHRONO] daily close=2023-02-13 idx=3273
[CHRONO] 5m day=2023-02-14 rows=456740:456932
[CHRONO] daily close=2023-02-14 idx=3274
[CHRONO] 5m day=2023-02-15 rows=456932:457124
[CHRONO] daily close=2023-02-15 idx=3275
[CHRONO] 5m day=2023-02-16 rows=457124:457315
[CHRONO] daily close=2023-02-16 idx=3276
[CHRONO] 5m day=2023-02-17 rows=457315:457507
[CHRONO] daily close=2023-02-17 idx=3277
[CHRONO] 5m day=2023-02-21 rows=457507:457698
[TRAIN][5M] asof=2023-02-21 feats=114 buy=YES sell=YES rows=93862
[CHRONO] daily close=2023-02-21 idx=3278
[CHRONO] 5m day=2023-02-22 rows=457698:457890
[CHRONO] daily close=2023-02-22 idx=3279
[CHRONO] 5m day=2023-02-23 rows=457890:458080
[CHRONO] daily close=2023-02-23 idx=3280
[CHRONO] 5m day=2023-02-24 rows=458080:458269
[CHRONO] daily close=2023-02-24 idx=3281
[CHRONO] 5m day=2023-02-27 rows=458269:458459
[TRAIN][5M] asof=2023-02-27 feats=114 buy=YES sell=YES rows=93995
[CHRONO] daily close=2023-02-27 idx=3282
[CHRONO] 5m day=2023-02-28 rows=458459:458651
[CHRONO] daily close=2023-02-28 idx=3283
[CHRONO] 5m day=2023-03-01 rows=458651:458843
[CHRONO] daily close=2023-03-01 idx=3284
[CHRONO] 5m day=2023-03-02 rows=458843:459035
[CHRONO] daily close=2023-03-02 idx=3285
[CHRONO] 5m day=2023-03-03 rows=459035:459226
[CHRONO] daily close=2023-03-03 idx=3286
[CHRONO] 5m day=2023-03-06 rows=459226:459416
[TRAIN][5M] asof=2023-03-06 feats=114 buy=YES sell=YES rows=94228
[CHRONO] daily close=2023-03-06 idx=3287
[CHRONO] 5m day=2023-03-07 rows=459416:459607
[CHRONO] daily close=2023-03-07 idx=3288
[CHRONO] 5m day=2023-03-08 rows=459607:459798
[CHRONO] daily close=2023-03-08 idx=3289
[CHRONO] 5m day=2023-03-09 rows=459798:459990
[CHRONO] daily close=2023-03-09 idx=3290
[CHRONO] 5m day=2023-03-10 rows=459990:460181
[CHRONO] daily close=2023-03-10 idx=3291
[CHRONO] 5m day=2023-03-13 rows=460181:460373
[TRAIN][5M] asof=2023-03-13 feats=114 buy=YES sell=YES rows=94401
[CHRONO] daily close=2023-03-13 idx=3292
[CHRONO] 5m day=2023-03-14 rows=460373:460565
[CHRONO] daily close=2023-03-14 idx=3293
[CHRONO] 5m day=2023-03-15 rows=460565:460757
[CHRONO] daily close=2023-03-15 idx=3294
[TRAIN][DAILY-PROB] n=3121 pos=650 (20.83%)
[CHRONO] 5m day=2023-03-16 rows=460757:460948
[CHRONO] daily close=2023-03-16 idx=3295
[CHRONO] 5m day=2023-03-17 rows=460948:461140
[CHRONO] daily close=2023-03-17 idx=3296
[CHRONO] 5m day=2023-03-20 rows=461140:461330
[TRAIN][5M] asof=2023-03-20 feats=114 buy=YES sell=YES rows=94588
[CHRONO] daily close=2023-03-20 idx=3297
[CHRONO] 5m day=2023-03-21 rows=461330:461522
[CHRONO] daily close=2023-03-21 idx=3298
[CHRONO] 5m day=2023-03-22 rows=461522:461713
[CHRONO] daily close=2023-03-22 idx=3299
[CHRONO] 5m day=2023-03-23 rows=461713:461905
[CHRONO] daily close=2023-03-23 idx=3300
[CHRONO] 5m day=2023-03-24 rows=461905:462092
[CHRONO] daily close=2023-03-24 idx=3301
[CHRONO] 5m day=2023-03-27 rows=462092:462281
[TRAIN][5M] asof=2023-03-27 feats=114 buy=YES sell=YES rows=94778
[CHRONO] daily close=2023-03-27 idx=3302
[CHRONO] 5m day=2023-03-28 rows=462281:462468
[CHRONO] daily close=2023-03-28 idx=3303
[CHRONO] 5m day=2023-03-29 rows=462468:462660
[CHRONO] daily close=2023-03-29 idx=3304
[CHRONO] 5m day=2023-03-30 rows=462660:462851
[CHRONO] daily close=2023-03-30 idx=3305
[CHRONO] 5m day=2023-03-31 rows=462851:463040
[CHRONO] daily close=2023-03-31 idx=3306
[CHRONO] 5m day=2023-04-03 rows=463040:463230
[TRAIN][5M] asof=2023-04-03 feats=114 buy=YES sell=YES rows=94989
[CHRONO] daily close=2023-04-03 idx=3307
[CHRONO] 5m day=2023-04-04 rows=463230:463422
[CHRONO] daily close=2023-04-04 idx=3308
[CHRONO] 5m day=2023-04-05 rows=463422:463610
[CHRONO] daily close=2023-04-05 idx=3309
[CHRONO] 5m day=2023-04-06 rows=463610:463801
[CHRONO] daily close=2023-04-06 idx=3310
[CHRONO] 5m day=2023-04-10 rows=463801:463993
[TRAIN][5M] asof=2023-04-10 feats=114 buy=YES sell=YES rows=95139
[CHRONO] daily close=2023-04-10 idx=3311
[CHRONO] 5m day=2023-04-11 rows=463993:464185
[CHRONO] daily close=2023-04-11 idx=3312
[CHRONO] 5m day=2023-04-12 rows=464185:464375
[CHRONO] daily close=2023-04-12 idx=3313
[CHRONO] 5m day=2023-04-13 rows=464375:464566
[CHRONO] daily close=2023-04-13 idx=3314
[CHRONO] 5m day=2023-04-14 rows=464566:464754
[CHRONO] daily close=2023-04-14 idx=3315
[CHRONO] 5m day=2023-04-17 rows=464754:464944
[TRAIN][5M] asof=2023-04-17 feats=114 buy=YES sell=YES rows=95344
[CHRONO] daily close=2023-04-17 idx=3316
[CHRONO] 5m day=2023-04-18 rows=464944:465134
[CHRONO] daily close=2023-04-18 idx=3317
[CHRONO] 5m day=2023-04-19 rows=465134:465325
[CHRONO] daily close=2023-04-19 idx=3318
[CHRONO] 5m day=2023-04-20 rows=465325:465517
[CHRONO] daily close=2023-04-20 idx=3319
[TRAIN][DAILY-PROB] n=3146 pos=656 (20.85%)
[CHRONO] 5m day=2023-04-21 rows=465517:465706
[CHRONO] daily close=2023-04-21 idx=3320
[CHRONO] 5m day=2023-04-24 rows=465706:465897
[TRAIN][5M] asof=2023-04-24 feats=114 buy=YES sell=YES rows=95528
[CHRONO] daily close=2023-04-24 idx=3321
[CHRONO] 5m day=2023-04-25 rows=465897:466089
[CHRONO] daily close=2023-04-25 idx=3322
[CHRONO] 5m day=2023-04-26 rows=466089:466281
[CHRONO] daily close=2023-04-26 idx=3323
[CHRONO] 5m day=2023-04-27 rows=466281:466473
[CHRONO] daily close=2023-04-27 idx=3324
[CHRONO] 5m day=2023-04-28 rows=466473:466663
[CHRONO] daily close=2023-04-28 idx=3325
[CHRONO] 5m day=2023-05-01 rows=466663:466853
[TRAIN][5M] asof=2023-05-01 feats=114 buy=YES sell=YES rows=95721
[CHRONO] daily close=2023-05-01 idx=3326
[CHRONO] 5m day=2023-05-02 rows=466853:467041
[CHRONO] daily close=2023-05-02 idx=3327
[CHRONO] 5m day=2023-05-03 rows=467041:467233
[CHRONO] daily close=2023-05-03 idx=3328
[CHRONO] 5m day=2023-05-04 rows=467233:467424
[CHRONO] daily close=2023-05-04 idx=3329
[CHRONO] 5m day=2023-05-05 rows=467424:467611
[CHRONO] daily close=2023-05-05 idx=3330
[CHRONO] 5m day=2023-05-08 rows=467611:467797
[TRAIN][5M] asof=2023-05-08 feats=114 buy=YES sell=YES rows=95924
[CHRONO] daily close=2023-05-08 idx=3331
[CHRONO] 5m day=2023-05-09 rows=467797:467984
[CHRONO] daily close=2023-05-09 idx=3332
[CHRONO] 5m day=2023-05-10 rows=467984:468171
[CHRONO] daily close=2023-05-10 idx=3333
[CHRONO] 5m day=2023-05-11 rows=468171:468362
[CHRONO] daily close=2023-05-11 idx=3334
[CHRONO] 5m day=2023-05-12 rows=468362:468546
[CHRONO] daily close=2023-05-12 idx=3335
[CHRONO] 5m day=2023-05-15 rows=468546:468738
[TRAIN][5M] asof=2023-05-15 feats=114 buy=YES sell=YES rows=96092
[CHRONO] daily close=2023-05-15 idx=3336
[CHRONO] 5m day=2023-05-16 rows=468738:468921
[CHRONO] daily close=2023-05-16 idx=3337
[CHRONO] 5m day=2023-05-17 rows=468921:469109
[CHRONO] daily close=2023-05-17 idx=3338
[CHRONO] 5m day=2023-05-18 rows=469109:469301
[CHRONO] daily close=2023-05-18 idx=3339
[CHRONO] 5m day=2023-05-19 rows=469301:469491
[CHRONO] daily close=2023-05-19 idx=3340
[CHRONO] 5m day=2023-05-22 rows=469491:469680
[TRAIN][5M] asof=2023-05-22 feats=114 buy=YES sell=YES rows=96227
[CHRONO] daily close=2023-05-22 idx=3341
[CHRONO] 5m day=2023-05-23 rows=469680:469868
[CHRONO] daily close=2023-05-23 idx=3342
[CHRONO] 5m day=2023-05-24 rows=469868:470058
[CHRONO] daily close=2023-05-24 idx=3343
[CHRONO] 5m day=2023-05-25 rows=470058:470250
[CHRONO] daily close=2023-05-25 idx=3344
[TRAIN][DAILY-PROB] n=3171 pos=658 (20.75%)
[CHRONO] 5m day=2023-05-26 rows=470250:470440
[CHRONO] daily close=2023-05-26 idx=3345
[CHRONO] 5m day=2023-05-30 rows=470440:470632
[TRAIN][5M] asof=2023-05-30 feats=114 buy=YES sell=YES rows=96471
[CHRONO] daily close=2023-05-30 idx=3346
[CHRONO] 5m day=2023-05-31 rows=470632:470823
[CHRONO] daily close=2023-05-31 idx=3347
[CHRONO] 5m day=2023-06-01 rows=470823:471012
[CHRONO] daily close=2023-06-01 idx=3348
[CHRONO] 5m day=2023-06-02 rows=471012:471202
[CHRONO] daily close=2023-06-02 idx=3349
[CHRONO] 5m day=2023-06-05 rows=471202:471393
[TRAIN][5M] asof=2023-06-05 feats=114 buy=YES sell=YES rows=96613
[CHRONO] daily close=2023-06-05 idx=3350
[CHRONO] 5m day=2023-06-06 rows=471393:471580
[CHRONO] daily close=2023-06-06 idx=3351
[CHRONO] 5m day=2023-06-07 rows=471580:471771
[CHRONO] daily close=2023-06-07 idx=3352
[CHRONO] 5m day=2023-06-08 rows=471771:471960
[CHRONO] daily close=2023-06-08 idx=3353
[CHRONO] 5m day=2023-06-09 rows=471960:472149
[CHRONO] daily close=2023-06-09 idx=3354
[CHRONO] 5m day=2023-06-12 rows=472149:472341
[TRAIN][5M] asof=2023-06-12 feats=114 buy=YES sell=YES rows=96818
[CHRONO] daily close=2023-06-12 idx=3355
[CHRONO] 5m day=2023-06-13 rows=472341:472531
[CHRONO] daily close=2023-06-13 idx=3356
[CHRONO] 5m day=2023-06-14 rows=472531:472723
[CHRONO] daily close=2023-06-14 idx=3357
[CHRONO] 5m day=2023-06-15 rows=472723:472914
[CHRONO] daily close=2023-06-15 idx=3358
[CHRONO] 5m day=2023-06-16 rows=472914:473104
[CHRONO] daily close=2023-06-16 idx=3359
[CHRONO] 5m day=2023-06-20 rows=473104:473295
[TRAIN][5M] asof=2023-06-20 feats=114 buy=YES sell=YES rows=96993
[CHRONO] daily close=2023-06-20 idx=3360
[CHRONO] 5m day=2023-06-21 rows=473295:473485
[CHRONO] daily close=2023-06-21 idx=3361
[CHRONO] 5m day=2023-06-22 rows=473485:473676
[CHRONO] daily close=2023-06-22 idx=3362
[CHRONO] 5m day=2023-06-23 rows=473676:473865
[CHRONO] daily close=2023-06-23 idx=3363
[CHRONO] 5m day=2023-06-26 rows=473865:474057
[TRAIN][5M] asof=2023-06-26 feats=114 buy=YES sell=YES rows=97195
[CHRONO] daily close=2023-06-26 idx=3364
[CHRONO] 5m day=2023-06-27 rows=474057:474247
[CHRONO] daily close=2023-06-27 idx=3365
[CHRONO] 5m day=2023-06-28 rows=474247:474437
[CHRONO] daily close=2023-06-28 idx=3366
[CHRONO] 5m day=2023-06-29 rows=474437:474628
[CHRONO] daily close=2023-06-29 idx=3367
[CHRONO] 5m day=2023-06-30 rows=474628:474818
[CHRONO] daily close=2023-06-30 idx=3368
[CHRONO] 5m day=2023-07-03 rows=474818:474963
[TRAIN][5M] asof=2023-07-03 feats=114 buy=YES sell=YES rows=97400
[CHRONO] daily close=2023-07-03 idx=3369
[TRAIN][DAILY-PROB] n=3196 pos=660 (20.65%)
[CHRONO] 5m day=2023-07-05 rows=474963:475155
[CHRONO] daily close=2023-07-05 idx=3370
[CHRONO] 5m day=2023-07-06 rows=475155:475346
[CHRONO] daily close=2023-07-06 idx=3371
[CHRONO] 5m day=2023-07-07 rows=475346:475533
[CHRONO] daily close=2023-07-07 idx=3372
[CHRONO] 5m day=2023-07-10 rows=475533:475722
[TRAIN][5M] asof=2023-07-10 feats=114 buy=YES sell=YES rows=97556
[CHRONO] daily close=2023-07-10 idx=3373
[CHRONO] 5m day=2023-07-11 rows=475722:475912
[CHRONO] daily close=2023-07-11 idx=3374
[CHRONO] 5m day=2023-07-12 rows=475912:476102
[CHRONO] daily close=2023-07-12 idx=3375
[CHRONO] 5m day=2023-07-13 rows=476102:476294
[CHRONO] daily close=2023-07-13 idx=3376
[CHRONO] 5m day=2023-07-14 rows=476294:476481
[CHRONO] daily close=2023-07-14 idx=3377
[CHRONO] 5m day=2023-07-17 rows=476481:476672
[TRAIN][5M] asof=2023-07-17 feats=114 buy=YES sell=YES rows=97759
[CHRONO] daily close=2023-07-17 idx=3378
[CHRONO] 5m day=2023-07-18 rows=476672:476863
[CHRONO] daily close=2023-07-18 idx=3379
[CHRONO] 5m day=2023-07-19 rows=476863:477055
[CHRONO] daily close=2023-07-19 idx=3380
[CHRONO] 5m day=2023-07-20 rows=477055:477246
[CHRONO] daily close=2023-07-20 idx=3381
[CHRONO] 5m day=2023-07-21 rows=477246:477435
[CHRONO] daily close=2023-07-21 idx=3382
[CHRONO] 5m day=2023-07-24 rows=477435:477626
[TRAIN][5M] asof=2023-07-24 feats=114 buy=YES sell=YES rows=97914
[CHRONO] daily close=2023-07-24 idx=3383
[CHRONO] 5m day=2023-07-25 rows=477626:477818
[CHRONO] daily close=2023-07-25 idx=3384
[CHRONO] 5m day=2023-07-26 rows=477818:478007
[CHRONO] daily close=2023-07-26 idx=3385
[CHRONO] 5m day=2023-07-27 rows=478007:478197
[CHRONO] daily close=2023-07-27 idx=3386
[CHRONO] 5m day=2023-07-28 rows=478197:478385
[CHRONO] daily close=2023-07-28 idx=3387
[CHRONO] 5m day=2023-07-31 rows=478385:478573
[TRAIN][5M] asof=2023-07-31 feats=114 buy=YES sell=YES rows=98130
[CHRONO] daily close=2023-07-31 idx=3388
[CHRONO] 5m day=2023-08-01 rows=478573:478764
[CHRONO] daily close=2023-08-01 idx=3389
[CHRONO] 5m day=2023-08-02 rows=478764:478956
[CHRONO] daily close=2023-08-02 idx=3390
[CHRONO] 5m day=2023-08-03 rows=478956:479148
[CHRONO] daily close=2023-08-03 idx=3391
[CHRONO] 5m day=2023-08-04 rows=479148:479337
[CHRONO] daily close=2023-08-04 idx=3392
[CHRONO] 5m day=2023-08-07 rows=479337:479529
[TRAIN][5M] asof=2023-08-07 feats=114 buy=YES sell=YES rows=98320
[CHRONO] daily close=2023-08-07 idx=3393
[CHRONO] 5m day=2023-08-08 rows=479529:479720
[CHRONO] daily close=2023-08-08 idx=3394
[TRAIN][DAILY-PROB] n=3221 pos=663 (20.58%)
[CHRONO] 5m day=2023-08-09 rows=479720:479911
[CHRONO] daily close=2023-08-09 idx=3395
[CHRONO] 5m day=2023-08-10 rows=479911:480103
[CHRONO] daily close=2023-08-10 idx=3396
[CHRONO] 5m day=2023-08-11 rows=480103:480288
[CHRONO] daily close=2023-08-11 idx=3397
[CHRONO] 5m day=2023-08-14 rows=480288:480479
[TRAIN][5M] asof=2023-08-14 feats=114 buy=YES sell=YES rows=98514
[CHRONO] daily close=2023-08-14 idx=3398
[CHRONO] 5m day=2023-08-15 rows=480479:480670
[CHRONO] daily close=2023-08-15 idx=3399
[CHRONO] 5m day=2023-08-16 rows=480670:480862
[CHRONO] daily close=2023-08-16 idx=3400
[CHRONO] 5m day=2023-08-17 rows=480862:481054
[CHRONO] daily close=2023-08-17 idx=3401
[CHRONO] 5m day=2023-08-18 rows=481054:481244
[CHRONO] daily close=2023-08-18 idx=3402
[CHRONO] 5m day=2023-08-21 rows=481244:481435
[TRAIN][5M] asof=2023-08-21 feats=114 buy=YES sell=YES rows=98730
[CHRONO] daily close=2023-08-21 idx=3403
[CHRONO] 5m day=2023-08-22 rows=481435:481625
[CHRONO] daily close=2023-08-22 idx=3404
[CHRONO] 5m day=2023-08-23 rows=481625:481816
[CHRONO] daily close=2023-08-23 idx=3405
[CHRONO] 5m day=2023-08-24 rows=481816:482008
[CHRONO] daily close=2023-08-24 idx=3406
[CHRONO] 5m day=2023-08-25 rows=482008:482199
[CHRONO] daily close=2023-08-25 idx=3407
[CHRONO] 5m day=2023-08-28 rows=482199:482390
[TRAIN][5M] asof=2023-08-28 feats=114 buy=YES sell=YES rows=98971
[CHRONO] daily close=2023-08-28 idx=3408
[CHRONO] 5m day=2023-08-29 rows=482390:482581
[CHRONO] daily close=2023-08-29 idx=3409
[CHRONO] 5m day=2023-08-30 rows=482581:482772
[CHRONO] daily close=2023-08-30 idx=3410
[CHRONO] 5m day=2023-08-31 rows=482772:482962
[CHRONO] daily close=2023-08-31 idx=3411
[CHRONO] 5m day=2023-09-01 rows=482962:483144
[CHRONO] daily close=2023-09-01 idx=3412
[CHRONO] 5m day=2023-09-05 rows=483144:483336
[TRAIN][5M] asof=2023-09-05 feats=114 buy=YES sell=YES rows=99147
[CHRONO] daily close=2023-09-05 idx=3413
[CHRONO] 5m day=2023-09-06 rows=483336:483524
[CHRONO] daily close=2023-09-06 idx=3414
[CHRONO] 5m day=2023-09-07 rows=483524:483713
[CHRONO] daily close=2023-09-07 idx=3415
[CHRONO] 5m day=2023-09-08 rows=483713:483905
[CHRONO] daily close=2023-09-08 idx=3416
[CHRONO] 5m day=2023-09-11 rows=483905:484095
[TRAIN][5M] asof=2023-09-11 feats=114 buy=YES sell=YES rows=99284
[CHRONO] daily close=2023-09-11 idx=3417
[CHRONO] 5m day=2023-09-12 rows=484095:484285
[CHRONO] daily close=2023-09-12 idx=3418
[CHRONO] 5m day=2023-09-13 rows=484285:484471
[CHRONO] daily close=2023-09-13 idx=3419
[TRAIN][DAILY-PROB] n=3246 pos=672 (20.70%)
[CHRONO] 5m day=2023-09-14 rows=484471:484658
[CHRONO] daily close=2023-09-14 idx=3420
[CHRONO] 5m day=2023-09-15 rows=484658:484848
[CHRONO] daily close=2023-09-15 idx=3421
[CHRONO] 5m day=2023-09-18 rows=484848:485037
[TRAIN][5M] asof=2023-09-18 feats=114 buy=YES sell=YES rows=99466
[CHRONO] daily close=2023-09-18 idx=3422
[CHRONO] 5m day=2023-09-19 rows=485037:485226
[CHRONO] daily close=2023-09-19 idx=3423
[CHRONO] 5m day=2023-09-20 rows=485226:485418
[CHRONO] daily close=2023-09-20 idx=3424
[CHRONO] 5m day=2023-09-21 rows=485418:485610
[CHRONO] daily close=2023-09-21 idx=3425
[CHRONO] 5m day=2023-09-22 rows=485610:485798
[CHRONO] daily close=2023-09-22 idx=3426
[CHRONO] 5m day=2023-09-25 rows=485798:485990
[TRAIN][5M] asof=2023-09-25 feats=114 buy=YES sell=YES rows=99671
[CHRONO] daily close=2023-09-25 idx=3427
[CHRONO] 5m day=2023-09-26 rows=485990:486181
[CHRONO] daily close=2023-09-26 idx=3428
[CHRONO] 5m day=2023-09-27 rows=486181:486373
[CHRONO] daily close=2023-09-27 idx=3429

c:\Users\TonyTang\Documents\chan.py\adaptive_reward_checkpoint_fresh.py:3132: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  daily_log_df = pd.concat(daily_log_frames, ignore_index=True, sort=False) if daily_log_frames else pd.DataFrame()

[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2023\trades.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2023\signal_decisions.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2023\daily_log.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2023\daily_reward_log.csv
[CHECKPOINT] saved chronological snapshot -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2023\continued_checkpoint__through_2023.joblib
[DONE] 2023 checkpoint: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2023\continued_checkpoint__through_2023.joblib
[RUN] 2024: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2023\continued_checkpoint__through_2023.joblib -> 2024-12-31 16:00:00
[CHECKPOINT] autosaved chronological year-start snapshot for 2024 before 2024-01-02 -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2024\year_start_checkpoints\continued_checkpoint__through_2024__start_2024.joblib
[CHRONO] 5m day=2024-01-02 rows=498654:498845
[TRAIN][5M] asof=2024-01-02 feats=114 buy=YES sell=YES rows=102337
[CHRONO] daily close=2024-01-02 idx=3495
[CHRONO] 5m day=2024-01-03 rows=498845:499035
[CHRONO] daily close=2024-01-03 idx=3496
[CHRONO] 5m day=2024-01-04 rows=499035:499223
[CHRONO] daily close=2024-01-04 idx=3497
[CHRONO] 5m day=2024-01-05 rows=499223:499410
[CHRONO] daily close=2024-01-05 idx=3498
[CHRONO] 5m day=2024-01-08 rows=499410:499602
[TRAIN][5M] asof=2024-01-08 feats=114 buy=YES sell=YES rows=102483
[CHRONO] daily close=2024-01-08 idx=3499
[CHRONO] 5m day=2024-01-09 rows=499602:499793
[CHRONO] daily close=2024-01-09 idx=3500
[CHRONO] 5m day=2024-01-10 rows=499793:499985
[CHRONO] daily close=2024-01-10 idx=3501
[CHRONO] 5m day=2024-01-11 rows=499985:500176
[CHRONO] daily close=2024-01-11 idx=3502
[CHRONO] 5m day=2024-01-12 rows=500176:500353
[CHRONO] daily close=2024-01-12 idx=3503
[CHRONO] 5m day=2024-01-16 rows=500353:500545
[TRAIN][5M] asof=2024-01-16 feats=114 buy=YES sell=YES rows=102767
[CHRONO] daily close=2024-01-16 idx=3504
[CHRONO] 5m day=2024-01-17 rows=500545:500737
[CHRONO] daily close=2024-01-17 idx=3505
[CHRONO] 5m day=2024-01-18 rows=500737:500929
[CHRONO] daily close=2024-01-18 idx=3506
[CHRONO] 5m day=2024-01-19 rows=500929:501119
[CHRONO] daily close=2024-01-19 idx=3507
[CHRONO] 5m day=2024-01-22 rows=501119:501311
[TRAIN][5M] asof=2024-01-22 feats=114 buy=YES sell=YES rows=102955
[CHRONO] daily close=2024-01-22 idx=3508
[CHRONO] 5m day=2024-01-23 rows=501311:501502
[CHRONO] daily close=2024-01-23 idx=3509
[CHRONO] 5m day=2024-01-24 rows=501502:501694
[CHRONO] daily close=2024-01-24 idx=3510
[CHRONO] 5m day=2024-01-25 rows=501694:501884
[CHRONO] daily close=2024-01-25 idx=3511
[CHRONO] 5m day=2024-01-26 rows=501884:502074
[CHRONO] daily close=2024-01-26 idx=3512
[CHRONO] 5m day=2024-01-29 rows=502074:502265
[TRAIN][5M] asof=2024-01-29 feats=114 buy=YES sell=YES rows=103110
[CHRONO] daily close=2024-01-29 idx=3513
[CHRONO] 5m day=2024-01-30 rows=502265:502457
[CHRONO] daily close=2024-01-30 idx=3514
[CHRONO] 5m day=2024-01-31 rows=502457:502649
[CHRONO] daily close=2024-01-31 idx=3515
[CHRONO] 5m day=2024-02-01 rows=502649:502841
[CHRONO] daily close=2024-02-01 idx=3516
[CHRONO] 5m day=2024-02-02 rows=502841:503030
[CHRONO] daily close=2024-02-02 idx=3517
[CHRONO] 5m day=2024-02-05 rows=503030:503222
[TRAIN][5M] asof=2024-02-05 feats=114 buy=YES sell=YES rows=103279
[CHRONO] daily close=2024-02-05 idx=3518
[CHRONO] 5m day=2024-02-06 rows=503222:503413
[CHRONO] daily close=2024-02-06 idx=3519
[TRAIN][DAILY-PROB] n=3346 pos=698 (20.86%)
[CHRONO] 5m day=2024-02-07 rows=503413:503605
[CHRONO] daily close=2024-02-07 idx=3520
[CHRONO] 5m day=2024-02-08 rows=503605:503796
[CHRONO] daily close=2024-02-08 idx=3521
[CHRONO] 5m day=2024-02-09 rows=503796:503976
[CHRONO] daily close=2024-02-09 idx=3522
[CHRONO] 5m day=2024-02-12 rows=503976:504167
[TRAIN][5M] asof=2024-02-12 feats=114 buy=YES sell=YES rows=103434
[CHRONO] daily close=2024-02-12 idx=3523
[CHRONO] 5m day=2024-02-13 rows=504167:504359
[CHRONO] daily close=2024-02-13 idx=3524
[CHRONO] 5m day=2024-02-14 rows=504359:504550
[CHRONO] daily close=2024-02-14 idx=3525
[CHRONO] 5m day=2024-02-15 rows=504550:504741
[CHRONO] daily close=2024-02-15 idx=3526
[CHRONO] 5m day=2024-02-16 rows=504741:504927
[CHRONO] daily close=2024-02-16 idx=3527
[CHRONO] 5m day=2024-02-20 rows=504927:505119
[TRAIN][5M] asof=2024-02-20 feats=114 buy=YES sell=YES rows=103610
[CHRONO] daily close=2024-02-20 idx=3528
[CHRONO] 5m day=2024-02-21 rows=505119:505310
[CHRONO] daily close=2024-02-21 idx=3529
[CHRONO] 5m day=2024-02-22 rows=505310:505502
[CHRONO] daily close=2024-02-22 idx=3530
[CHRONO] 5m day=2024-02-23 rows=505502:505690
[CHRONO] daily close=2024-02-23 idx=3531
[CHRONO] 5m day=2024-02-26 rows=505690:505881
[TRAIN][5M] asof=2024-02-26 feats=114 buy=YES sell=YES rows=103768
[CHRONO] daily close=2024-02-26 idx=3532
[CHRONO] 5m day=2024-02-27 rows=505881:506073
[CHRONO] daily close=2024-02-27 idx=3533
[CHRONO] 5m day=2024-02-28 rows=506073:506265
[CHRONO] daily close=2024-02-28 idx=3534
[CHRONO] 5m day=2024-02-29 rows=506265:506456
[CHRONO] daily close=2024-02-29 idx=3535
[CHRONO] 5m day=2024-03-01 rows=506456:506645
[CHRONO] daily close=2024-03-01 idx=3536
[CHRONO] 5m day=2024-03-04 rows=506645:506836
[TRAIN][5M] asof=2024-03-04 feats=114 buy=YES sell=YES rows=103977
[CHRONO] daily close=2024-03-04 idx=3537
[CHRONO] 5m day=2024-03-05 rows=506836:507028
[CHRONO] daily close=2024-03-05 idx=3538
[CHRONO] 5m day=2024-03-06 rows=507028:507219
[CHRONO] daily close=2024-03-06 idx=3539
[CHRONO] 5m day=2024-03-07 rows=507219:507411
[CHRONO] daily close=2024-03-07 idx=3540
[CHRONO] 5m day=2024-03-08 rows=507411:507603
[CHRONO] daily close=2024-03-08 idx=3541
[CHRONO] 5m day=2024-03-11 rows=507603:507794
[TRAIN][5M] asof=2024-03-11 feats=114 buy=YES sell=YES rows=104198
[CHRONO] daily close=2024-03-11 idx=3542
[CHRONO] 5m day=2024-03-12 rows=507794:507984
[CHRONO] daily close=2024-03-12 idx=3543
[CHRONO] 5m day=2024-03-13 rows=507984:508176
[CHRONO] daily close=2024-03-13 idx=3544
[TRAIN][DAILY-PROB] n=3371 pos=699 (20.74%)
[CHRONO] 5m day=2024-03-14 rows=508176:508368
[CHRONO] daily close=2024-03-14 idx=3545
[CHRONO] 5m day=2024-03-15 rows=508368:508558
[CHRONO] daily close=2024-03-15 idx=3546
[CHRONO] 5m day=2024-03-18 rows=508558:508750
[TRAIN][5M] asof=2024-03-18 feats=114 buy=YES sell=YES rows=104359
[CHRONO] daily close=2024-03-18 idx=3547
[CHRONO] 5m day=2024-03-19 rows=508750:508942
[CHRONO] daily close=2024-03-19 idx=3548
[CHRONO] 5m day=2024-03-20 rows=508942:509134
[CHRONO] daily close=2024-03-20 idx=3549
[CHRONO] 5m day=2024-03-21 rows=509134:509326
[CHRONO] daily close=2024-03-21 idx=3550
[CHRONO] 5m day=2024-03-22 rows=509326:509511
[CHRONO] daily close=2024-03-22 idx=3551
[CHRONO] 5m day=2024-03-25 rows=509511:509703
[TRAIN][5M] asof=2024-03-25 feats=114 buy=YES sell=YES rows=104552
[CHRONO] daily close=2024-03-25 idx=3552
[CHRONO] 5m day=2024-03-26 rows=509703:509894
[CHRONO] daily close=2024-03-26 idx=3553
[CHRONO] 5m day=2024-03-27 rows=509894:510084
[CHRONO] daily close=2024-03-27 idx=3554
[CHRONO] 5m day=2024-03-28 rows=510084:510267
[CHRONO] daily close=2024-03-28 idx=3555
[CHRONO] 5m day=2024-04-01 rows=510267:510455
[TRAIN][5M] asof=2024-04-01 feats=114 buy=YES sell=YES rows=104673
[CHRONO] daily close=2024-04-01 idx=3556
[CHRONO] 5m day=2024-04-02 rows=510455:510644
[CHRONO] daily close=2024-04-02 idx=3557
[CHRONO] 5m day=2024-04-03 rows=510644:510832
[CHRONO] daily close=2024-04-03 idx=3558
[CHRONO] 5m day=2024-04-04 rows=510832:511022
[CHRONO] daily close=2024-04-04 idx=3559
[CHRONO] 5m day=2024-04-05 rows=511022:511210
[CHRONO] daily close=2024-04-05 idx=3560
[CHRONO] 5m day=2024-04-08 rows=511210:511398
[TRAIN][5M] asof=2024-04-08 feats=114 buy=YES sell=YES rows=104799
[CHRONO] daily close=2024-04-08 idx=3561
[CHRONO] 5m day=2024-04-09 rows=511398:511589
[CHRONO] daily close=2024-04-09 idx=3562
[CHRONO] 5m day=2024-04-10 rows=511589:511780
[CHRONO] daily close=2024-04-10 idx=3563
[CHRONO] 5m day=2024-04-11 rows=511780:511972
[CHRONO] daily close=2024-04-11 idx=3564
[CHRONO] 5m day=2024-04-12 rows=511972:512163
[CHRONO] daily close=2024-04-12 idx=3565
[CHRONO] 5m day=2024-04-15 rows=512163:512355
[TRAIN][5M] asof=2024-04-15 feats=114 buy=YES sell=YES rows=104990
[CHRONO] daily close=2024-04-15 idx=3566
[CHRONO] 5m day=2024-04-16 rows=512355:512547
[CHRONO] daily close=2024-04-16 idx=3567
[CHRONO] 5m day=2024-04-17 rows=512547:512738
[CHRONO] daily close=2024-04-17 idx=3568
[CHRONO] 5m day=2024-04-18 rows=512738:512930
[CHRONO] daily close=2024-04-18 idx=3569
[TRAIN][DAILY-PROB] n=3396 pos=705 (20.76%)
[CHRONO] 5m day=2024-04-19 rows=512930:513122
[CHRONO] daily close=2024-04-19 idx=3570
[CHRONO] 5m day=2024-04-22 rows=513122:513314
[TRAIN][5M] asof=2024-04-22 feats=114 buy=YES sell=YES rows=105125
[CHRONO] daily close=2024-04-22 idx=3571
[CHRONO] 5m day=2024-04-23 rows=513314:513506
[CHRONO] daily close=2024-04-23 idx=3572
[CHRONO] 5m day=2024-04-24 rows=513506:513698
[CHRONO] daily close=2024-04-24 idx=3573
[CHRONO] 5m day=2024-04-25 rows=513698:513890
[CHRONO] daily close=2024-04-25 idx=3574
[CHRONO] 5m day=2024-04-26 rows=513890:514081
[CHRONO] daily close=2024-04-26 idx=3575
[CHRONO] 5m day=2024-04-29 rows=514081:514272
[TRAIN][5M] asof=2024-04-29 feats=114 buy=YES sell=YES rows=105346
[CHRONO] daily close=2024-04-29 idx=3576
[CHRONO] 5m day=2024-04-30 rows=514272:514464
[CHRONO] daily close=2024-04-30 idx=3577
[CHRONO] 5m day=2024-05-01 rows=514464:514656
[CHRONO] daily close=2024-05-01 idx=3578
[CHRONO] 5m day=2024-05-02 rows=514656:514847
[CHRONO] daily close=2024-05-02 idx=3579
[CHRONO] 5m day=2024-05-03 rows=514847:515034
[CHRONO] daily close=2024-05-03 idx=3580
[CHRONO] 5m day=2024-05-06 rows=515034:515225
[TRAIN][5M] asof=2024-05-06 feats=114 buy=YES sell=YES rows=105508
[CHRONO] daily close=2024-05-06 idx=3581
[CHRONO] 5m day=2024-05-07 rows=515225:515415
[CHRONO] daily close=2024-05-07 idx=3582
[CHRONO] 5m day=2024-05-08 rows=515415:515603
[CHRONO] daily close=2024-05-08 idx=3583
[CHRONO] 5m day=2024-05-09 rows=515603:515788
[CHRONO] daily close=2024-05-09 idx=3584
[CHRONO] 5m day=2024-05-10 rows=515788:515977
[CHRONO] daily close=2024-05-10 idx=3585
[CHRONO] 5m day=2024-05-13 rows=515977:516161
[TRAIN][5M] asof=2024-05-13 feats=114 buy=YES sell=YES rows=105646
[CHRONO] daily close=2024-05-13 idx=3586
[CHRONO] 5m day=2024-05-14 rows=516161:516350
[CHRONO] daily close=2024-05-14 idx=3587
[CHRONO] 5m day=2024-05-15 rows=516350:516542
[CHRONO] daily close=2024-05-15 idx=3588
[CHRONO] 5m day=2024-05-16 rows=516542:516734
[CHRONO] daily close=2024-05-16 idx=3589
[CHRONO] 5m day=2024-05-17 rows=516734:516917
[CHRONO] daily close=2024-05-17 idx=3590
[CHRONO] 5m day=2024-05-20 rows=516917:517100
[TRAIN][5M] asof=2024-05-20 feats=114 buy=YES sell=YES rows=105790
[CHRONO] daily close=2024-05-20 idx=3591
[CHRONO] 5m day=2024-05-21 rows=517100:517284
[CHRONO] daily close=2024-05-21 idx=3592
[CHRONO] 5m day=2024-05-22 rows=517284:517473
[CHRONO] daily close=2024-05-22 idx=3593
[CHRONO] 5m day=2024-05-23 rows=517473:517662
[CHRONO] daily close=2024-05-23 idx=3594
[TRAIN][DAILY-PROB] n=3421 pos=709 (20.72%)
[CHRONO] 5m day=2024-05-24 rows=517662:517844
[CHRONO] daily close=2024-05-24 idx=3595
[CHRONO] 5m day=2024-05-28 rows=517844:518035
[TRAIN][5M] asof=2024-05-28 feats=114 buy=YES sell=YES rows=105984
[CHRONO] daily close=2024-05-28 idx=3596
[CHRONO] 5m day=2024-05-29 rows=518035:518227
[CHRONO] daily close=2024-05-29 idx=3597
[CHRONO] 5m day=2024-05-30 rows=518227:518419
[CHRONO] daily close=2024-05-30 idx=3598
[CHRONO] 5m day=2024-05-31 rows=518419:518610
[CHRONO] daily close=2024-05-31 idx=3599
[CHRONO] 5m day=2024-06-03 rows=518610:518798
[TRAIN][5M] asof=2024-06-03 feats=114 buy=YES sell=YES rows=106158
[CHRONO] daily close=2024-06-03 idx=3600
[CHRONO] 5m day=2024-06-04 rows=518798:518989
[CHRONO] daily close=2024-06-04 idx=3601
[CHRONO] 5m day=2024-06-05 rows=518989:519180
[CHRONO] daily close=2024-06-05 idx=3602
[CHRONO] 5m day=2024-06-06 rows=519180:519371
[CHRONO] daily close=2024-06-06 idx=3603
[CHRONO] 5m day=2024-06-07 rows=519371:519556
[CHRONO] daily close=2024-06-07 idx=3604
[CHRONO] 5m day=2024-06-10 rows=519556:519746
[TRAIN][5M] asof=2024-06-10 feats=114 buy=YES sell=YES rows=106333
[CHRONO] daily close=2024-06-10 idx=3605
[CHRONO] 5m day=2024-06-11 rows=519746:519935
[CHRONO] daily close=2024-06-11 idx=3606
[CHRONO] 5m day=2024-06-12 rows=519935:520125
[CHRONO] daily close=2024-06-12 idx=3607
[CHRONO] 5m day=2024-06-13 rows=520125:520314
[CHRONO] daily close=2024-06-13 idx=3608
[CHRONO] 5m day=2024-06-14 rows=520314:520505
[CHRONO] daily close=2024-06-14 idx=3609
[CHRONO] 5m day=2024-06-17 rows=520505:520694
[TRAIN][5M] asof=2024-06-17 feats=114 buy=YES sell=YES rows=106511
[CHRONO] daily close=2024-06-17 idx=3610
[CHRONO] 5m day=2024-06-18 rows=520694:520883
[CHRONO] daily close=2024-06-18 idx=3611
[CHRONO] 5m day=2024-06-20 rows=520883:521075
[CHRONO] daily close=2024-06-20 idx=3612
[CHRONO] 5m day=2024-06-21 rows=521075:521266
[CHRONO] daily close=2024-06-21 idx=3613
[CHRONO] 5m day=2024-06-24 rows=521266:521458
[TRAIN][5M] asof=2024-06-24 feats=114 buy=YES sell=YES rows=106645
[CHRONO] daily close=2024-06-24 idx=3614
[CHRONO] 5m day=2024-06-25 rows=521458:521650
[CHRONO] daily close=2024-06-25 idx=3615
[CHRONO] 5m day=2024-06-26 rows=521650:521840
[CHRONO] daily close=2024-06-26 idx=3616
[CHRONO] 5m day=2024-06-27 rows=521840:522030
[CHRONO] daily close=2024-06-27 idx=3617
[CHRONO] 5m day=2024-06-28 rows=522030:522215
[CHRONO] daily close=2024-06-28 idx=3618
[CHRONO] 5m day=2024-07-01 rows=522215:522403
[TRAIN][5M] asof=2024-07-01 feats=114 buy=YES sell=YES rows=106793
[CHRONO] daily close=2024-07-01 idx=3619
[TRAIN][DAILY-PROB] n=3446 pos=713 (20.69%)
[CHRONO] 5m day=2024-07-02 rows=522403:522591
[CHRONO] daily close=2024-07-02 idx=3620
[CHRONO] 5m day=2024-07-03 rows=522591:522745
[CHRONO] daily close=2024-07-03 idx=3621
[CHRONO] 5m day=2024-07-05 rows=522745:522932
[CHRONO] daily close=2024-07-05 idx=3622
[CHRONO] 5m day=2024-07-08 rows=522932:523124
[TRAIN][5M] asof=2024-07-08 feats=114 buy=YES sell=YES rows=106912
[CHRONO] daily close=2024-07-08 idx=3623
[CHRONO] 5m day=2024-07-09 rows=523124:523311
[CHRONO] daily close=2024-07-09 idx=3624
[CHRONO] 5m day=2024-07-10 rows=523311:523500
[CHRONO] daily close=2024-07-10 idx=3625
[CHRONO] 5m day=2024-07-11 rows=523500:523691
[CHRONO] daily close=2024-07-11 idx=3626
[CHRONO] 5m day=2024-07-12 rows=523691:523882
[CHRONO] daily close=2024-07-12 idx=3627
[CHRONO] 5m day=2024-07-15 rows=523882:524068
[TRAIN][5M] asof=2024-07-15 feats=114 buy=YES sell=YES rows=107093
[CHRONO] daily close=2024-07-15 idx=3628
[CHRONO] 5m day=2024-07-16 rows=524068:524257
[CHRONO] daily close=2024-07-16 idx=3629
[CHRONO] 5m day=2024-07-17 rows=524257:524449
[CHRONO] daily close=2024-07-17 idx=3630
[CHRONO] 5m day=2024-07-18 rows=524449:524641
[CHRONO] daily close=2024-07-18 idx=3631
[CHRONO] 5m day=2024-07-19 rows=524641:524829
[CHRONO] daily close=2024-07-19 idx=3632
[CHRONO] 5m day=2024-07-22 rows=524829:525021
[TRAIN][5M] asof=2024-07-22 feats=114 buy=YES sell=YES rows=107326
[CHRONO] daily close=2024-07-22 idx=3633
[CHRONO] 5m day=2024-07-23 rows=525021:525213
[CHRONO] daily close=2024-07-23 idx=3634
[CHRONO] 5m day=2024-07-24 rows=525213:525405
[CHRONO] daily close=2024-07-24 idx=3635
[CHRONO] 5m day=2024-07-25 rows=525405:525597
[CHRONO] daily close=2024-07-25 idx=3636
[CHRONO] 5m day=2024-07-26 rows=525597:525786
[CHRONO] daily close=2024-07-26 idx=3637
[CHRONO] 5m day=2024-07-29 rows=525786:525978
[TRAIN][5M] asof=2024-07-29 feats=114 buy=YES sell=YES rows=107583
[CHRONO] daily close=2024-07-29 idx=3638
[CHRONO] 5m day=2024-07-30 rows=525978:526170
[CHRONO] daily close=2024-07-30 idx=3639
[CHRONO] 5m day=2024-07-31 rows=526170:526362
[CHRONO] daily close=2024-07-31 idx=3640
[CHRONO] 5m day=2024-08-01 rows=526362:526554
[CHRONO] daily close=2024-08-01 idx=3641
[CHRONO] 5m day=2024-08-02 rows=526554:526746
[CHRONO] daily close=2024-08-02 idx=3642
[CHRONO] 5m day=2024-08-05 rows=526746:526938
[TRAIN][5M] asof=2024-08-05 feats=114 buy=YES sell=YES rows=107824
[CHRONO] daily close=2024-08-05 idx=3643
[CHRONO] 5m day=2024-08-06 rows=526938:527130
[CHRONO] daily close=2024-08-06 idx=3644
[TRAIN][DAILY-PROB] n=3471 pos=717 (20.66%)
[CHRONO] 5m day=2024-08-07 rows=527130:527322
[CHRONO] daily close=2024-08-07 idx=3645
[CHRONO] 5m day=2024-08-08 rows=527322:527514
[CHRONO] daily close=2024-08-08 idx=3646
[CHRONO] 5m day=2024-08-09 rows=527514:527702
[CHRONO] daily close=2024-08-09 idx=3647
[CHRONO] 5m day=2024-08-12 rows=527702:527891
[TRAIN][5M] asof=2024-08-12 feats=114 buy=YES sell=YES rows=107977
[CHRONO] daily close=2024-08-12 idx=3648
[CHRONO] 5m day=2024-08-13 rows=527891:528082
[CHRONO] daily close=2024-08-13 idx=3649
[CHRONO] 5m day=2024-08-14 rows=528082:528274
[CHRONO] daily close=2024-08-14 idx=3650
[CHRONO] 5m day=2024-08-15 rows=528274:528464
[CHRONO] daily close=2024-08-15 idx=3651
[CHRONO] 5m day=2024-08-16 rows=528464:528654
[CHRONO] daily close=2024-08-16 idx=3652
[CHRONO] 5m day=2024-08-19 rows=528654:528846
[TRAIN][5M] asof=2024-08-19 feats=114 buy=YES sell=YES rows=108166
[CHRONO] daily close=2024-08-19 idx=3653
[CHRONO] 5m day=2024-08-20 rows=528846:529038
[CHRONO] daily close=2024-08-20 idx=3654
[CHRONO] 5m day=2024-08-21 rows=529038:529227
[CHRONO] daily close=2024-08-21 idx=3655
[CHRONO] 5m day=2024-08-22 rows=529227:529415
[CHRONO] daily close=2024-08-22 idx=3656
[CHRONO] 5m day=2024-08-23 rows=529415:529604
[CHRONO] daily close=2024-08-23 idx=3657
[CHRONO] 5m day=2024-08-26 rows=529604:529795
[TRAIN][5M] asof=2024-08-26 feats=114 buy=YES sell=YES rows=108368
[CHRONO] daily close=2024-08-26 idx=3658
[CHRONO] 5m day=2024-08-27 rows=529795:529985
[CHRONO] daily close=2024-08-27 idx=3659
[CHRONO] 5m day=2024-08-28 rows=529985:530176
[CHRONO] daily close=2024-08-28 idx=3660
[CHRONO] 5m day=2024-08-29 rows=530176:530367
[CHRONO] daily close=2024-08-29 idx=3661
[CHRONO] 5m day=2024-08-30 rows=530367:530557
[CHRONO] daily close=2024-08-30 idx=3662
[CHRONO] 5m day=2024-09-03 rows=530557:530749
[TRAIN][5M] asof=2024-09-03 feats=114 buy=YES sell=YES rows=108531
[CHRONO] daily close=2024-09-03 idx=3663
[CHRONO] 5m day=2024-09-04 rows=530749:530941
[CHRONO] daily close=2024-09-04 idx=3664
[CHRONO] 5m day=2024-09-05 rows=530941:531132
[CHRONO] daily close=2024-09-05 idx=3665
[CHRONO] 5m day=2024-09-06 rows=531132:531324
[CHRONO] daily close=2024-09-06 idx=3666
[CHRONO] 5m day=2024-09-09 rows=531324:531516
[TRAIN][5M] asof=2024-09-09 feats=114 buy=YES sell=YES rows=108694
[CHRONO] daily close=2024-09-09 idx=3667
[CHRONO] 5m day=2024-09-10 rows=531516:531707
[CHRONO] daily close=2024-09-10 idx=3668
[CHRONO] 5m day=2024-09-11 rows=531707:531898
[CHRONO] daily close=2024-09-11 idx=3669
[TRAIN][DAILY-PROB] n=3496 pos=728 (20.82%)
[CHRONO] 5m day=2024-09-12 rows=531898:532090
[CHRONO] daily close=2024-09-12 idx=3670
[CHRONO] 5m day=2024-09-13 rows=532090:532277
[CHRONO] daily close=2024-09-13 idx=3671
[CHRONO] 5m day=2024-09-16 rows=532277:532466
[TRAIN][5M] asof=2024-09-16 feats=114 buy=YES sell=YES rows=108905
[CHRONO] daily close=2024-09-16 idx=3672
[CHRONO] 5m day=2024-09-17 rows=532466:532657
[CHRONO] daily close=2024-09-17 idx=3673
[CHRONO] 5m day=2024-09-18 rows=532657:532848
[CHRONO] daily close=2024-09-18 idx=3674
[CHRONO] 5m day=2024-09-19 rows=532848:533039
[CHRONO] daily close=2024-09-19 idx=3675
[CHRONO] 5m day=2024-09-20 rows=533039:533228
[CHRONO] daily close=2024-09-20 idx=3676
[CHRONO] 5m day=2024-09-23 rows=533228:533417
[TRAIN][5M] asof=2024-09-23 feats=114 buy=YES sell=YES rows=109107
[CHRONO] daily close=2024-09-23 idx=3677
[CHRONO] 5m day=2024-09-24 rows=533417:533607
[CHRONO] daily close=2024-09-24 idx=3678
[CHRONO] 5m day=2024-09-25 rows=533607:533796

c:\Users\TonyTang\Documents\chan.py\adaptive_reward_checkpoint_fresh.py:3132: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  daily_log_df = pd.concat(daily_log_frames, ignore_index=True, sort=False) if daily_log_frames else pd.DataFrame()

[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2024\trades.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2024\signal_decisions.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2024\daily_log.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2024\daily_reward_log.csv
[CHECKPOINT] saved chronological snapshot -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2024\continued_checkpoint__through_2024.joblib
[DONE] 2024 checkpoint: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2024\continued_checkpoint__through_2024.joblib
[RUN] 2025: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2024\continued_checkpoint__through_2024.joblib -> 2025-12-31 16:00:00
[CHRONO] 5m day=2024-12-31 rows=546413:546454
[TRAIN][5M] asof=2024-12-31 feats=114 buy=YES sell=YES rows=111599
[CHECKPOINT] autosaved chronological year-start snapshot for 2025 before 2025-01-02 -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2025\year_start_checkpoints\continued_checkpoint__through_2025__start_2025.joblib
[CHRONO] 5m day=2025-01-02 rows=546454:546646
[CHRONO] daily close=2025-01-02 idx=3747
[CHRONO] 5m day=2025-01-03 rows=546646:546834
[CHRONO] daily close=2025-01-03 idx=3748
[CHRONO] 5m day=2025-01-06 rows=546834:547026
[TRAIN][5M] asof=2025-01-06 feats=114 buy=YES sell=YES rows=111705
[CHRONO] daily close=2025-01-06 idx=3749
[CHRONO] 5m day=2025-01-07 rows=547026:547218
[CHRONO] daily close=2025-01-07 idx=3750
[CHRONO] 5m day=2025-01-08 rows=547218:547407
[CHRONO] daily close=2025-01-08 idx=3751
[CHRONO] 5m day=2025-01-10 rows=547407:547597
[CHRONO] daily close=2025-01-10 idx=3752
[CHRONO] 5m day=2025-01-13 rows=547597:547789
[TRAIN][5M] asof=2025-01-13 feats=114 buy=YES sell=YES rows=111886
[CHRONO] daily close=2025-01-13 idx=3753
[CHRONO] 5m day=2025-01-14 rows=547789:547981
[CHRONO] daily close=2025-01-14 idx=3754
[CHRONO] 5m day=2025-01-15 rows=547981:548171
[CHRONO] daily close=2025-01-15 idx=3755
[CHRONO] 5m day=2025-01-16 rows=548171:548363
[CHRONO] daily close=2025-01-16 idx=3756
[CHRONO] 5m day=2025-01-17 rows=548363:548555
[CHRONO] daily close=2025-01-17 idx=3757
[CHRONO] 5m day=2025-01-21 rows=548555:548747
[TRAIN][5M] asof=2025-01-21 feats=114 buy=YES sell=YES rows=112097
[CHRONO] daily close=2025-01-21 idx=3758
[CHRONO] 5m day=2025-01-22 rows=548747:548939
[CHRONO] daily close=2025-01-22 idx=3759
[CHRONO] 5m day=2025-01-23 rows=548939:549131
[CHRONO] daily close=2025-01-23 idx=3760
[CHRONO] 5m day=2025-01-24 rows=549131:549318
[CHRONO] daily close=2025-01-24 idx=3761
[CHRONO] 5m day=2025-01-27 rows=549318:549510
[TRAIN][5M] asof=2025-01-27 feats=114 buy=YES sell=YES rows=112244
[CHRONO] daily close=2025-01-27 idx=3762
[CHRONO] 5m day=2025-01-28 rows=549510:549702
[CHRONO] daily close=2025-01-28 idx=3763
[CHRONO] 5m day=2025-01-29 rows=549702:549894
[CHRONO] daily close=2025-01-29 idx=3764
[CHRONO] 5m day=2025-01-30 rows=549894:550086
[CHRONO] daily close=2025-01-30 idx=3765
[CHRONO] 5m day=2025-01-31 rows=550086:550277
[CHRONO] daily close=2025-01-31 idx=3766
[CHRONO] 5m day=2025-02-03 rows=550277:550469
[TRAIN][5M] asof=2025-02-03 feats=114 buy=YES sell=YES rows=112453
[CHRONO] daily close=2025-02-03 idx=3767
[CHRONO] 5m day=2025-02-04 rows=550469:550661
[CHRONO] daily close=2025-02-04 idx=3768
[CHRONO] 5m day=2025-02-05 rows=550661:550853
[CHRONO] daily close=2025-02-05 idx=3769
[CHRONO] 5m day=2025-02-06 rows=550853:551045
[CHRONO] daily close=2025-02-06 idx=3770
[CHRONO] 5m day=2025-02-07 rows=551045:551236
[CHRONO] daily close=2025-02-07 idx=3771
[TRAIN][DAILY-PROB] n=3598 pos=745 (20.71%)
[CHRONO] 5m day=2025-02-10 rows=551236:551425
[TRAIN][5M] asof=2025-02-10 feats=114 buy=YES sell=YES rows=112633
[CHRONO] daily close=2025-02-10 idx=3772
[CHRONO] 5m day=2025-02-11 rows=551425:551616
[CHRONO] daily close=2025-02-11 idx=3773
[CHRONO] 5m day=2025-02-12 rows=551616:551807
[CHRONO] daily close=2025-02-12 idx=3774
[CHRONO] 5m day=2025-02-13 rows=551807:551999
[CHRONO] daily close=2025-02-13 idx=3775
[CHRONO] 5m day=2025-02-14 rows=551999:552185
[CHRONO] daily close=2025-02-14 idx=3776
[CHRONO] 5m day=2025-02-18 rows=552185:552375
[TRAIN][5M] asof=2025-02-18 feats=114 buy=YES sell=YES rows=112760
[CHRONO] daily close=2025-02-18 idx=3777
[CHRONO] 5m day=2025-02-19 rows=552375:552567
[CHRONO] daily close=2025-02-19 idx=3778
[CHRONO] 5m day=2025-02-20 rows=552567:552755
[CHRONO] daily close=2025-02-20 idx=3779
[CHRONO] 5m day=2025-02-21 rows=552755:552946
[CHRONO] daily close=2025-02-21 idx=3780
[CHRONO] 5m day=2025-02-24 rows=552946:553137
[TRAIN][5M] asof=2025-02-24 feats=114 buy=YES sell=YES rows=112930
[CHRONO] daily close=2025-02-24 idx=3781
[CHRONO] 5m day=2025-02-25 rows=553137:553329
[CHRONO] daily close=2025-02-25 idx=3782
[CHRONO] 5m day=2025-02-26 rows=553329:553521
[CHRONO] daily close=2025-02-26 idx=3783
[CHRONO] 5m day=2025-02-27 rows=553521:553712
[CHRONO] daily close=2025-02-27 idx=3784
[CHRONO] 5m day=2025-02-28 rows=553712:553903
[CHRONO] daily close=2025-02-28 idx=3785
[CHRONO] 5m day=2025-03-03 rows=553903:554095
[TRAIN][5M] asof=2025-03-03 feats=114 buy=YES sell=YES rows=113106
[CHRONO] daily close=2025-03-03 idx=3786
[CHRONO] 5m day=2025-03-04 rows=554095:554287
[CHRONO] daily close=2025-03-04 idx=3787
[CHRONO] 5m day=2025-03-05 rows=554287:554479
[CHRONO] daily close=2025-03-05 idx=3788
[CHRONO] 5m day=2025-03-06 rows=554479:554671
[CHRONO] daily close=2025-03-06 idx=3789
[CHRONO] 5m day=2025-03-07 rows=554671:554863
[CHRONO] daily close=2025-03-07 idx=3790
[CHRONO] 5m day=2025-03-10 rows=554863:555055
[TRAIN][5M] asof=2025-03-10 feats=114 buy=YES sell=YES rows=113315
[CHRONO] daily close=2025-03-10 idx=3791
[CHRONO] 5m day=2025-03-11 rows=555055:555247
[CHRONO] daily close=2025-03-11 idx=3792
[CHRONO] 5m day=2025-03-12 rows=555247:555439
[CHRONO] daily close=2025-03-12 idx=3793
[CHRONO] 5m day=2025-03-13 rows=555439:555631
[CHRONO] daily close=2025-03-13 idx=3794
[CHRONO] 5m day=2025-03-14 rows=555631:555823
[CHRONO] daily close=2025-03-14 idx=3795
[CHRONO] 5m day=2025-03-17 rows=555823:556015
[TRAIN][5M] asof=2025-03-17 feats=114 buy=YES sell=YES rows=113499
[CHRONO] daily close=2025-03-17 idx=3796
[TRAIN][DAILY-PROB] n=3623 pos=756 (20.87%)
[CHRONO] 5m day=2025-03-18 rows=556015:556207
[CHRONO] daily close=2025-03-18 idx=3797
[CHRONO] 5m day=2025-03-19 rows=556207:556398
[CHRONO] daily close=2025-03-19 idx=3798
[CHRONO] 5m day=2025-03-20 rows=556398:556590
[CHRONO] daily close=2025-03-20 idx=3799
[CHRONO] 5m day=2025-03-21 rows=556590:556781
[CHRONO] daily close=2025-03-21 idx=3800
[CHRONO] 5m day=2025-03-24 rows=556781:556972
[TRAIN][5M] asof=2025-03-24 feats=114 buy=YES sell=YES rows=113697
[CHRONO] daily close=2025-03-24 idx=3801
[CHRONO] 5m day=2025-03-25 rows=556972:557163
[CHRONO] daily close=2025-03-25 idx=3802
[CHRONO] 5m day=2025-03-26 rows=557163:557355
[CHRONO] daily close=2025-03-26 idx=3803
[CHRONO] 5m day=2025-03-27 rows=557355:557545
[CHRONO] daily close=2025-03-27 idx=3804
[CHRONO] 5m day=2025-03-28 rows=557545:557736
[CHRONO] daily close=2025-03-28 idx=3805
[CHRONO] 5m day=2025-03-31 rows=557736:557928
[TRAIN][5M] asof=2025-03-31 feats=114 buy=YES sell=YES rows=113914
[CHRONO] daily close=2025-03-31 idx=3806
[CHRONO] 5m day=2025-04-01 rows=557928:558120
[CHRONO] daily close=2025-04-01 idx=3807
[CHRONO] 5m day=2025-04-02 rows=558120:558311
[CHRONO] daily close=2025-04-02 idx=3808
[CHRONO] 5m day=2025-04-03 rows=558311:558503
[CHRONO] daily close=2025-04-03 idx=3809
[CHRONO] 5m day=2025-04-04 rows=558503:558695
[CHRONO] daily close=2025-04-04 idx=3810
[CHRONO] 5m day=2025-04-07 rows=558695:558887
[TRAIN][5M] asof=2025-04-07 feats=114 buy=YES sell=YES rows=114112
[CHRONO] daily close=2025-04-07 idx=3811
[CHRONO] 5m day=2025-04-08 rows=558887:559079
[CHRONO] daily close=2025-04-08 idx=3812
[CHRONO] 5m day=2025-04-09 rows=559079:559271
[CHRONO] daily close=2025-04-09 idx=3813
[CHRONO] 5m day=2025-04-10 rows=559271:559463
[CHRONO] daily close=2025-04-10 idx=3814
[CHRONO] 5m day=2025-04-11 rows=559463:559655
[CHRONO] daily close=2025-04-11 idx=3815
[CHRONO] 5m day=2025-04-14 rows=559655:559847
[TRAIN][5M] asof=2025-04-14 feats=114 buy=YES sell=YES rows=114307
[CHRONO] daily close=2025-04-14 idx=3816
[CHRONO] 5m day=2025-04-15 rows=559847:560038
[CHRONO] daily close=2025-04-15 idx=3817
[CHRONO] 5m day=2025-04-16 rows=560038:560229
[CHRONO] daily close=2025-04-16 idx=3818
[CHRONO] 5m day=2025-04-17 rows=560229:560420
[CHRONO] daily close=2025-04-17 idx=3819
[CHRONO] 5m day=2025-04-21 rows=560420:560612
[TRAIN][5M] asof=2025-04-21 feats=114 buy=YES sell=YES rows=114439
[CHRONO] daily close=2025-04-21 idx=3820
[CHRONO] 5m day=2025-04-22 rows=560612:560804
[CHRONO] daily close=2025-04-22 idx=3821
[TRAIN][DAILY-PROB] n=3648 pos=764 (20.94%)
[CHRONO] 5m day=2025-04-23 rows=560804:560996
[CHRONO] daily close=2025-04-23 idx=3822
[CHRONO] 5m day=2025-04-24 rows=560996:561188
[CHRONO] daily close=2025-04-24 idx=3823
[CHRONO] 5m day=2025-04-25 rows=561188:561379
[CHRONO] daily close=2025-04-25 idx=3824
[CHRONO] 5m day=2025-04-28 rows=561379:561571
[TRAIN][5M] asof=2025-04-28 feats=114 buy=YES sell=YES rows=114690
[CHRONO] daily close=2025-04-28 idx=3825
[CHRONO] 5m day=2025-04-29 rows=561571:561761
[CHRONO] daily close=2025-04-29 idx=3826
[CHRONO] 5m day=2025-04-30 rows=561761:561953
[CHRONO] daily close=2025-04-30 idx=3827
[CHRONO] 5m day=2025-05-01 rows=561953:562145
[CHRONO] daily close=2025-05-01 idx=3828
[CHRONO] 5m day=2025-05-02 rows=562145:562335
[CHRONO] daily close=2025-05-02 idx=3829
[CHRONO] 5m day=2025-05-05 rows=562335:562527
[TRAIN][5M] asof=2025-05-05 feats=114 buy=YES sell=YES rows=114926
[CHRONO] daily close=2025-05-05 idx=3830
[CHRONO] 5m day=2025-05-06 rows=562527:562719
[CHRONO] daily close=2025-05-06 idx=3831
[CHRONO] 5m day=2025-05-07 rows=562719:562911
[CHRONO] daily close=2025-05-07 idx=3832
[CHRONO] 5m day=2025-05-08 rows=562911:563103
[CHRONO] daily close=2025-05-08 idx=3833
[CHRONO] 5m day=2025-05-09 rows=563103:563290
[CHRONO] daily close=2025-05-09 idx=3834
[CHRONO] 5m day=2025-05-12 rows=563290:563482
[TRAIN][5M] asof=2025-05-12 feats=114 buy=YES sell=YES rows=115080
[CHRONO] daily close=2025-05-12 idx=3835
[CHRONO] 5m day=2025-05-13 rows=563482:563673
[CHRONO] daily close=2025-05-13 idx=3836
[CHRONO] 5m day=2025-05-14 rows=563673:563864
[CHRONO] daily close=2025-05-14 idx=3837
[CHRONO] 5m day=2025-05-15 rows=563864:564056
[CHRONO] daily close=2025-05-15 idx=3838
[CHRONO] 5m day=2025-05-16 rows=564056:564248
[CHRONO] daily close=2025-05-16 idx=3839
[CHRONO] 5m day=2025-05-19 rows=564248:564438
[TRAIN][5M] asof=2025-05-19 feats=114 buy=YES sell=YES rows=115261
[CHRONO] daily close=2025-05-19 idx=3840
[CHRONO] 5m day=2025-05-20 rows=564438:564630
[CHRONO] daily close=2025-05-20 idx=3841
[CHRONO] 5m day=2025-05-21 rows=564630:564822
[CHRONO] daily close=2025-05-21 idx=3842
[CHRONO] 5m day=2025-05-22 rows=564822:565014
[CHRONO] daily close=2025-05-22 idx=3843
[CHRONO] 5m day=2025-05-23 rows=565014:565205
[CHRONO] daily close=2025-05-23 idx=3844
[CHRONO] 5m day=2025-05-27 rows=565205:565397
[TRAIN][5M] asof=2025-05-27 feats=114 buy=YES sell=YES rows=115452
[CHRONO] daily close=2025-05-27 idx=3845
[CHRONO] 5m day=2025-05-28 rows=565397:565589
[CHRONO] daily close=2025-05-28 idx=3846
[TRAIN][DAILY-PROB] n=3673 pos=768 (20.91%)
[CHRONO] 5m day=2025-05-29 rows=565589:565781
[CHRONO] daily close=2025-05-29 idx=3847
[CHRONO] 5m day=2025-05-30 rows=565781:565970
[CHRONO] daily close=2025-05-30 idx=3848
[CHRONO] 5m day=2025-06-02 rows=565970:566161
[TRAIN][5M] asof=2025-06-02 feats=114 buy=YES sell=YES rows=115575
[CHRONO] daily close=2025-06-02 idx=3849
[CHRONO] 5m day=2025-06-03 rows=566161:566353
[CHRONO] daily close=2025-06-03 idx=3850
[CHRONO] 5m day=2025-06-04 rows=566353:566545
[CHRONO] daily close=2025-06-04 idx=3851
[CHRONO] 5m day=2025-06-05 rows=566545:566737
[CHRONO] daily close=2025-06-05 idx=3852
[CHRONO] 5m day=2025-06-06 rows=566737:566929
[CHRONO] daily close=2025-06-06 idx=3853
[CHRONO] 5m day=2025-06-09 rows=566929:567121
[TRAIN][5M] asof=2025-06-09 feats=114 buy=YES sell=YES rows=115736
[CHRONO] daily close=2025-06-09 idx=3854
[CHRONO] 5m day=2025-06-10 rows=567121:567312
[CHRONO] daily close=2025-06-10 idx=3855
[CHRONO] 5m day=2025-06-11 rows=567312:567502
[CHRONO] daily close=2025-06-11 idx=3856
[CHRONO] 5m day=2025-06-12 rows=567502:567693
[CHRONO] daily close=2025-06-12 idx=3857
[CHRONO] 5m day=2025-06-13 rows=567693:567882
[CHRONO] daily close=2025-06-13 idx=3858
[CHRONO] 5m day=2025-06-16 rows=567882:568074
[TRAIN][5M] asof=2025-06-16 feats=114 buy=YES sell=YES rows=115855
[CHRONO] daily close=2025-06-16 idx=3859
[CHRONO] 5m day=2025-06-17 rows=568074:568266
[CHRONO] daily close=2025-06-17 idx=3860
[CHRONO] 5m day=2025-06-18 rows=568266:568458
[CHRONO] daily close=2025-06-18 idx=3861
[CHRONO] 5m day=2025-06-20 rows=568458:568650
[CHRONO] daily close=2025-06-20 idx=3862
[CHRONO] 5m day=2025-06-23 rows=568650:568842
[TRAIN][5M] asof=2025-06-23 feats=114 buy=YES sell=YES rows=115997
[CHRONO] daily close=2025-06-23 idx=3863
[CHRONO] 5m day=2025-06-24 rows=568842:569034
[CHRONO] daily close=2025-06-24 idx=3864
[CHRONO] 5m day=2025-06-25 rows=569034:569226
[CHRONO] daily close=2025-06-25 idx=3865
[CHRONO] 5m day=2025-06-26 rows=569226:569418
[CHRONO] daily close=2025-06-26 idx=3866
[CHRONO] 5m day=2025-06-27 rows=569418:569610
[CHRONO] daily close=2025-06-27 idx=3867
[CHRONO] 5m day=2025-06-30 rows=569610:569801
[TRAIN][5M] asof=2025-06-30 feats=114 buy=YES sell=YES rows=116144
[CHRONO] daily close=2025-06-30 idx=3868
[CHRONO] 5m day=2025-07-01 rows=569801:569991
[CHRONO] daily close=2025-07-01 idx=3869
[CHRONO] 5m day=2025-07-02 rows=569991:570182
[CHRONO] daily close=2025-07-02 idx=3870
[CHRONO] 5m day=2025-07-03 rows=570182:570337
[CHRONO] daily close=2025-07-03 idx=3871
[TRAIN][DAILY-PROB] n=3698 pos=770 (20.82%)
[CHRONO] 5m day=2025-07-07 rows=570337:570529
[TRAIN][5M] asof=2025-07-07 feats=114 buy=YES sell=YES rows=116302
[CHRONO] daily close=2025-07-07 idx=3872
[CHRONO] 5m day=2025-07-08 rows=570529:570720
[CHRONO] daily close=2025-07-08 idx=3873
[CHRONO] 5m day=2025-07-09 rows=570720:570911
[CHRONO] daily close=2025-07-09 idx=3874
[CHRONO] 5m day=2025-07-10 rows=570911:571102
[CHRONO] daily close=2025-07-10 idx=3875
[CHRONO] 5m day=2025-07-11 rows=571102:571290
[CHRONO] daily close=2025-07-11 idx=3876
[CHRONO] 5m day=2025-07-14 rows=571290:571482
[TRAIN][5M] asof=2025-07-14 feats=114 buy=YES sell=YES rows=116468
[CHRONO] daily close=2025-07-14 idx=3877
[CHRONO] 5m day=2025-07-15 rows=571482:571674
[CHRONO] daily close=2025-07-15 idx=3878
[CHRONO] 5m day=2025-07-16 rows=571674:571866
[CHRONO] daily close=2025-07-16 idx=3879
[CHRONO] 5m day=2025-07-17 rows=571866:572057
[CHRONO] daily close=2025-07-17 idx=3880
[CHRONO] 5m day=2025-07-18 rows=572057:572244
[CHRONO] daily close=2025-07-18 idx=3881
[CHRONO] 5m day=2025-07-21 rows=572244:572436
[TRAIN][5M] asof=2025-07-21 feats=114 buy=YES sell=YES rows=116680
[CHRONO] daily close=2025-07-21 idx=3882
[CHRONO] 5m day=2025-07-22 rows=572436:572628
[CHRONO] daily close=2025-07-22 idx=3883
[CHRONO] 5m day=2025-07-23 rows=572628:572820
[CHRONO] daily close=2025-07-23 idx=3884
[CHRONO] 5m day=2025-07-24 rows=572820:573011
[CHRONO] daily close=2025-07-24 idx=3885
[CHRONO] 5m day=2025-07-25 rows=573011:573198
[CHRONO] daily close=2025-07-25 idx=3886
[CHRONO] 5m day=2025-07-28 rows=573198:573389
[TRAIN][5M] asof=2025-07-28 feats=114 buy=YES sell=YES rows=116890
[CHRONO] daily close=2025-07-28 idx=3887
[CHRONO] 5m day=2025-07-29 rows=573389:573580
[CHRONO] daily close=2025-07-29 idx=3888
[CHRONO] 5m day=2025-07-30 rows=573580:573772
[CHRONO] daily close=2025-07-30 idx=3889
[CHRONO] 5m day=2025-07-31 rows=573772:573964
[CHRONO] daily close=2025-07-31 idx=3890
[CHRONO] 5m day=2025-08-01 rows=573964:574155
[CHRONO] daily close=2025-08-01 idx=3891
[CHRONO] 5m day=2025-08-04 rows=574155:574347
[TRAIN][5M] asof=2025-08-04 feats=114 buy=YES sell=YES rows=117078
[CHRONO] daily close=2025-08-04 idx=3892
[CHRONO] 5m day=2025-08-05 rows=574347:574539
[CHRONO] daily close=2025-08-05 idx=3893
[CHRONO] 5m day=2025-08-06 rows=574539:574731
[CHRONO] daily close=2025-08-06 idx=3894
[CHRONO] 5m day=2025-08-07 rows=574731:574923
[CHRONO] daily close=2025-08-07 idx=3895
[CHRONO] 5m day=2025-08-08 rows=574923:575112
[CHRONO] daily close=2025-08-08 idx=3896
[TRAIN][DAILY-PROB] n=3723 pos=771 (20.71%)
[CHRONO] 5m day=2025-08-11 rows=575112:575304
[TRAIN][5M] asof=2025-08-11 feats=114 buy=YES sell=YES rows=117252
[CHRONO] daily close=2025-08-11 idx=3897
[CHRONO] 5m day=2025-08-12 rows=575304:575496
[CHRONO] daily close=2025-08-12 idx=3898
[CHRONO] 5m day=2025-08-13 rows=575496:575688
[CHRONO] daily close=2025-08-13 idx=3899
[CHRONO] 5m day=2025-08-14 rows=575688:575879
[CHRONO] daily close=2025-08-14 idx=3900
[CHRONO] 5m day=2025-08-15 rows=575879:576068
[CHRONO] daily close=2025-08-15 idx=3901
[CHRONO] 5m day=2025-08-18 rows=576068:576260
[TRAIN][5M] asof=2025-08-18 feats=114 buy=YES sell=YES rows=117406
[CHRONO] daily close=2025-08-18 idx=3902
[CHRONO] 5m day=2025-08-19 rows=576260:576451
[CHRONO] daily close=2025-08-19 idx=3903
[CHRONO] 5m day=2025-08-20 rows=576451:576643
[CHRONO] daily close=2025-08-20 idx=3904
[CHRONO] 5m day=2025-08-21 rows=576643:576835
[CHRONO] daily close=2025-08-21 idx=3905
[CHRONO] 5m day=2025-08-22 rows=576835:577026
[CHRONO] daily close=2025-08-22 idx=3906
[CHRONO] 5m day=2025-08-25 rows=577026:577217
[TRAIN][5M] asof=2025-08-25 feats=114 buy=YES sell=YES rows=117591
[CHRONO] daily close=2025-08-25 idx=3907
[CHRONO] 5m day=2025-08-26 rows=577217:577409
[CHRONO] daily close=2025-08-26 idx=3908
[CHRONO] 5m day=2025-08-27 rows=577409:577601
[CHRONO] daily close=2025-08-27 idx=3909
[CHRONO] 5m day=2025-08-28 rows=577601:577792
[CHRONO] daily close=2025-08-28 idx=3910
[CHRONO] 5m day=2025-08-29 rows=577792:577983
[CHRONO] daily close=2025-08-29 idx=3911
[CHRONO] 5m day=2025-09-02 rows=577983:578175
[TRAIN][5M] asof=2025-09-02 feats=114 buy=YES sell=YES rows=117748
[CHRONO] daily close=2025-09-02 idx=3912
[CHRONO] 5m day=2025-09-03 rows=578175:578367
[CHRONO] daily close=2025-09-03 idx=3913
[CHRONO] 5m day=2025-09-04 rows=578367:578559
[CHRONO] daily close=2025-09-04 idx=3914
[CHRONO] 5m day=2025-09-05 rows=578559:578749
[CHRONO] daily close=2025-09-05 idx=3915
[CHRONO] 5m day=2025-09-08 rows=578749:578941
[TRAIN][5M] asof=2025-09-08 feats=114 buy=YES sell=YES rows=117886
[CHRONO] daily close=2025-09-08 idx=3916
[CHRONO] 5m day=2025-09-09 rows=578941:579133
[CHRONO] daily close=2025-09-09 idx=3917
[CHRONO] 5m day=2025-09-10 rows=579133:579325
[CHRONO] daily close=2025-09-10 idx=3918
[CHRONO] 5m day=2025-09-11 rows=579325:579517
[CHRONO] daily close=2025-09-11 idx=3919
[CHRONO] 5m day=2025-09-12 rows=579517:579708
[CHRONO] daily close=2025-09-12 idx=3920
[CHRONO] 5m day=2025-09-15 rows=579708:579899
[TRAIN][5M] asof=2025-09-15 feats=114 buy=YES sell=YES rows=118038
[CHRONO] daily close=2025-09-15 idx=3921
[TRAIN][DAILY-PROB] n=3748 pos=782 (20.86%)
[CHRONO] 5m day=2025-09-16 rows=579899:580089
[CHRONO] daily close=2025-09-16 idx=3922
[CHRONO] 5m day=2025-09-17 rows=580089:580280
[CHRONO] daily close=2025-09-17 idx=3923
[CHRONO] 5m day=2025-09-18 rows=580280:580471
[CHRONO] daily close=2025-09-18 idx=3924
[CHRONO] 5m day=2025-09-19 rows=580471:580660
[CHRONO] daily close=2025-09-19 idx=3925
[CHRONO] 5m day=2025-09-22 rows=580660:580851
[TRAIN][5M] asof=2025-09-22 feats=114 buy=YES sell=YES rows=118265
[CHRONO] daily close=2025-09-22 idx=3926
[CHRONO] 5m day=2025-09-23 rows=580851:581043
[CHRONO] daily close=2025-09-23 idx=3927
[CHRONO] 5m day=2025-09-24 rows=581043:581234
[CHRONO] daily close=2025-09-24 idx=3928
[CHRONO] 5m day=2025-09-25 rows=581234:581426
[CHRONO] daily close=2025-09-25 idx=3929
[CHRONO] 5m day=2025-09-26 rows=581426:581610
[CHRONO] daily close=2025-09-26 idx=3930

c:\Users\TonyTang\Documents\chan.py\adaptive_reward_checkpoint_fresh.py:3132: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  daily_log_df = pd.concat(daily_log_frames, ignore_index=True, sort=False) if daily_log_frames else pd.DataFrame()

[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2025\trades.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2025\signal_decisions.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2025\daily_log.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2025\daily_reward_log.csv
[CHECKPOINT] saved chronological snapshot -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2025\continued_checkpoint__through_2025.joblib
[DONE] 2025 checkpoint: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2025\continued_checkpoint__through_2025.joblib
[RUN] 2026: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2025\continued_checkpoint__through_2025.joblib -> 2026-06-12 16:00:00
[CHRONO] 5m day=2025-12-31 rows=594146:594193
[TRAIN][5M] asof=2025-12-31 feats=114 buy=YES sell=YES rows=121111
[CHECKPOINT] autosaved chronological year-start snapshot for 2026 before 2026-01-02 -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2026\year_start_checkpoints\continued_checkpoint__through_2026__start_2026.joblib
[CHRONO] 5m day=2026-01-02 rows=594193:594385
[CHRONO] daily close=2026-01-02 idx=3997
[CHRONO] 5m day=2026-01-05 rows=594385:594577
[TRAIN][5M] asof=2026-01-05 feats=114 buy=YES sell=YES rows=121153
[CHRONO] daily close=2026-01-05 idx=3998
[CHRONO] 5m day=2026-01-06 rows=594577:594769
[CHRONO] daily close=2026-01-06 idx=3999
[CHRONO] 5m day=2026-01-07 rows=594769:594961
[CHRONO] daily close=2026-01-07 idx=4000
[CHRONO] 5m day=2026-01-08 rows=594961:595153
[CHRONO] daily close=2026-01-08 idx=4001
[CHRONO] 5m day=2026-01-09 rows=595153:595344
[CHRONO] daily close=2026-01-09 idx=4002
[CHRONO] 5m day=2026-01-12 rows=595344:595536
[TRAIN][5M] asof=2026-01-12 feats=114 buy=YES sell=YES rows=121375
[CHRONO] daily close=2026-01-12 idx=4003
[CHRONO] 5m day=2026-01-13 rows=595536:595728
[CHRONO] daily close=2026-01-13 idx=4004
[CHRONO] 5m day=2026-01-14 rows=595728:595920
[CHRONO] daily close=2026-01-14 idx=4005
[CHRONO] 5m day=2026-01-15 rows=595920:596112
[CHRONO] daily close=2026-01-15 idx=4006
[CHRONO] 5m day=2026-01-16 rows=596112:596304
[CHRONO] daily close=2026-01-16 idx=4007
[CHRONO] 5m day=2026-01-20 rows=596304:596496
[TRAIN][5M] asof=2026-01-20 feats=114 buy=YES sell=YES rows=121539
[CHRONO] daily close=2026-01-20 idx=4008
[CHRONO] 5m day=2026-01-21 rows=596496:596688
[CHRONO] daily close=2026-01-21 idx=4009
[CHRONO] 5m day=2026-01-22 rows=596688:596880
[CHRONO] daily close=2026-01-22 idx=4010
[CHRONO] 5m day=2026-01-23 rows=596880:597071
[CHRONO] daily close=2026-01-23 idx=4011
[CHRONO] 5m day=2026-01-26 rows=597071:597263
[TRAIN][5M] asof=2026-01-26 feats=114 buy=YES sell=YES rows=121725
[CHRONO] daily close=2026-01-26 idx=4012
[CHRONO] 5m day=2026-01-27 rows=597263:597455
[CHRONO] daily close=2026-01-27 idx=4013
[CHRONO] 5m day=2026-01-28 rows=597455:597647
[CHRONO] daily close=2026-01-28 idx=4014
[CHRONO] 5m day=2026-01-29 rows=597647:597839
[CHRONO] daily close=2026-01-29 idx=4015
[CHRONO] 5m day=2026-01-30 rows=597839:598031
[CHRONO] daily close=2026-01-30 idx=4016
[CHRONO] 5m day=2026-02-02 rows=598031:598223
[TRAIN][5M] asof=2026-02-02 feats=114 buy=YES sell=YES rows=121952
[CHRONO] daily close=2026-02-02 idx=4017
[CHRONO] 5m day=2026-02-03 rows=598223:598415
[CHRONO] daily close=2026-02-03 idx=4018
[CHRONO] 5m day=2026-02-04 rows=598415:598607
[CHRONO] daily close=2026-02-04 idx=4019
[CHRONO] 5m day=2026-02-05 rows=598607:598799
[CHRONO] daily close=2026-02-05 idx=4020
[CHRONO] 5m day=2026-02-06 rows=598799:598991
[CHRONO] daily close=2026-02-06 idx=4021
[TRAIN][DAILY-PROB] n=3848 pos=803 (20.87%)
[CHRONO] 5m day=2026-02-09 rows=598991:599183
[TRAIN][5M] asof=2026-02-09 feats=114 buy=YES sell=YES rows=122183
[CHRONO] daily close=2026-02-09 idx=4022
[CHRONO] 5m day=2026-02-10 rows=599183:599375
[CHRONO] daily close=2026-02-10 idx=4023
[CHRONO] 5m day=2026-02-11 rows=599375:599567
[CHRONO] daily close=2026-02-11 idx=4024
[CHRONO] 5m day=2026-02-12 rows=599567:599759
[CHRONO] daily close=2026-02-12 idx=4025
[CHRONO] 5m day=2026-02-13 rows=599759:599951
[CHRONO] daily close=2026-02-13 idx=4026
[CHRONO] 5m day=2026-02-17 rows=599951:600143
[TRAIN][5M] asof=2026-02-17 feats=114 buy=YES sell=YES rows=122387
[CHRONO] daily close=2026-02-17 idx=4027
[CHRONO] 5m day=2026-02-18 rows=600143:600335
[CHRONO] daily close=2026-02-18 idx=4028
[CHRONO] 5m day=2026-02-19 rows=600335:600527
[CHRONO] daily close=2026-02-19 idx=4029
[CHRONO] 5m day=2026-02-20 rows=600527:600719
[CHRONO] daily close=2026-02-20 idx=4030
[CHRONO] 5m day=2026-02-23 rows=600719:600911
[TRAIN][5M] asof=2026-02-23 feats=114 buy=YES sell=YES rows=122527
[CHRONO] daily close=2026-02-23 idx=4031
[CHRONO] 5m day=2026-02-24 rows=600911:601103
[CHRONO] daily close=2026-02-24 idx=4032
[CHRONO] 5m day=2026-02-25 rows=601103:601295
[CHRONO] daily close=2026-02-25 idx=4033
[CHRONO] 5m day=2026-02-26 rows=601295:601487
[CHRONO] daily close=2026-02-26 idx=4034
[CHRONO] 5m day=2026-02-27 rows=601487:601679
[CHRONO] daily close=2026-02-27 idx=4035
[CHRONO] 5m day=2026-03-02 rows=601679:601871
[TRAIN][5M] asof=2026-03-02 feats=114 buy=YES sell=YES rows=122734
[CHRONO] daily close=2026-03-02 idx=4036
[CHRONO] 5m day=2026-03-03 rows=601871:602063
[CHRONO] daily close=2026-03-03 idx=4037
[CHRONO] 5m day=2026-03-04 rows=602063:602255
[CHRONO] daily close=2026-03-04 idx=4038
[CHRONO] 5m day=2026-03-05 rows=602255:602447
[CHRONO] daily close=2026-03-05 idx=4039
[CHRONO] 5m day=2026-03-06 rows=602447:602639
[CHRONO] daily close=2026-03-06 idx=4040
[CHRONO] 5m day=2026-03-09 rows=602639:602831
[TRAIN][5M] asof=2026-03-09 feats=114 buy=YES sell=YES rows=122927
[CHRONO] daily close=2026-03-09 idx=4041
[CHRONO] 5m day=2026-03-10 rows=602831:603023
[CHRONO] daily close=2026-03-10 idx=4042
[CHRONO] 5m day=2026-03-11 rows=603023:603215
[CHRONO] daily close=2026-03-11 idx=4043
[CHRONO] 5m day=2026-03-12 rows=603215:603407
[CHRONO] daily close=2026-03-12 idx=4044
[CHRONO] 5m day=2026-03-13 rows=603407:603599
[CHRONO] daily close=2026-03-13 idx=4045
[CHRONO] 5m day=2026-03-16 rows=603599:603791
[TRAIN][5M] asof=2026-03-16 feats=114 buy=YES sell=YES rows=123147
[CHRONO] daily close=2026-03-16 idx=4046
[TRAIN][DAILY-PROB] n=3873 pos=809 (20.89%)
[CHRONO] 5m day=2026-03-17 rows=603791:603982
[CHRONO] daily close=2026-03-17 idx=4047
[CHRONO] 5m day=2026-03-18 rows=603982:604174
[CHRONO] daily close=2026-03-18 idx=4048
[CHRONO] 5m day=2026-03-19 rows=604174:604366
[CHRONO] daily close=2026-03-19 idx=4049
[CHRONO] 5m day=2026-03-20 rows=604366:604558
[CHRONO] daily close=2026-03-20 idx=4050
[CHRONO] 5m day=2026-03-23 rows=604558:604750
[TRAIN][5M] asof=2026-03-23 feats=114 buy=YES sell=YES rows=123361
[CHRONO] daily close=2026-03-23 idx=4051
[CHRONO] 5m day=2026-03-24 rows=604750:604942
[CHRONO] daily close=2026-03-24 idx=4052
[CHRONO] 5m day=2026-03-25 rows=604942:605134
[CHRONO] daily close=2026-03-25 idx=4053
[CHRONO] 5m day=2026-03-26 rows=605134:605326
[CHRONO] daily close=2026-03-26 idx=4054
[CHRONO] 5m day=2026-03-27 rows=605326:605518
[CHRONO] daily close=2026-03-27 idx=4055
[CHRONO] 5m day=2026-03-30 rows=605518:605710
[TRAIN][5M] asof=2026-03-30 feats=114 buy=YES sell=YES rows=123556
[CHRONO] daily close=2026-03-30 idx=4056
[CHRONO] 5m day=2026-03-31 rows=605710:605901
[CHRONO] daily close=2026-03-31 idx=4057
[CHRONO] 5m day=2026-04-01 rows=605901:606093
[CHRONO] daily close=2026-04-01 idx=4058
[CHRONO] 5m day=2026-04-02 rows=606093:606286
[CHRONO] daily close=2026-04-02 idx=4059
[CHRONO] 5m day=2026-04-06 rows=606286:606478
[TRAIN][5M] asof=2026-04-06 feats=114 buy=YES sell=YES rows=123664
[CHRONO] daily close=2026-04-06 idx=4060
[CHRONO] 5m day=2026-04-07 rows=606478:606671
[CHRONO] daily close=2026-04-07 idx=4061
[CHRONO] 5m day=2026-04-08 rows=606671:606864
[CHRONO] daily close=2026-04-08 idx=4062
[CHRONO] 5m day=2026-04-09 rows=606864:607057
[CHRONO] daily close=2026-04-09 idx=4063
[CHRONO] 5m day=2026-04-10 rows=607057:607250
[CHRONO] daily close=2026-04-10 idx=4064
[CHRONO] 5m day=2026-04-13 rows=607250:607443
[TRAIN][5M] asof=2026-04-13 feats=114 buy=YES sell=YES rows=123860
[CHRONO] daily close=2026-04-13 idx=4065
[CHRONO] 5m day=2026-04-14 rows=607443:607636
[CHRONO] daily close=2026-04-14 idx=4066
[CHRONO] 5m day=2026-04-15 rows=607636:607829
[CHRONO] daily close=2026-04-15 idx=4067
[CHRONO] 5m day=2026-04-16 rows=607829:608021
[CHRONO] daily close=2026-04-16 idx=4068
[CHRONO] 5m day=2026-04-17 rows=608021:608213
[CHRONO] daily close=2026-04-17 idx=4069
[CHRONO] 5m day=2026-04-20 rows=608213:608405
[TRAIN][5M] asof=2026-04-20 feats=114 buy=YES sell=YES rows=124037
[CHRONO] daily close=2026-04-20 idx=4070
[CHRONO] 5m day=2026-04-21 rows=608405:608597
[CHRONO] daily close=2026-04-21 idx=4071
[TRAIN][DAILY-PROB] n=3898 pos=812 (20.83%)
[CHRONO] 5m day=2026-04-22 rows=608597:608789
[CHRONO] daily close=2026-04-22 idx=4072
[CHRONO] 5m day=2026-04-23 rows=608789:608981
[CHRONO] daily close=2026-04-23 idx=4073
[CHRONO] 5m day=2026-04-24 rows=608981:609173
[CHRONO] daily close=2026-04-24 idx=4074
[CHRONO] 5m day=2026-04-27 rows=609173:609365
[TRAIN][5M] asof=2026-04-27 feats=114 buy=YES sell=YES rows=124210
[CHRONO] daily close=2026-04-27 idx=4075
[CHRONO] 5m day=2026-04-28 rows=609365:609557
[CHRONO] daily close=2026-04-28 idx=4076
[CHRONO] 5m day=2026-04-29 rows=609557:609749
[CHRONO] daily close=2026-04-29 idx=4077
[CHRONO] 5m day=2026-04-30 rows=609749:609941
[CHRONO] daily close=2026-04-30 idx=4078
[CHRONO] 5m day=2026-05-01 rows=609941:610133
[CHRONO] daily close=2026-05-01 idx=4079
[CHRONO] 5m day=2026-05-04 rows=610133:610325
[TRAIN][5M] asof=2026-05-04 feats=114 buy=YES sell=YES rows=124366
[CHRONO] daily close=2026-05-04 idx=4080
[CHRONO] 5m day=2026-05-05 rows=610325:610517
[CHRONO] daily close=2026-05-05 idx=4081
[CHRONO] 5m day=2026-05-06 rows=610517:610709
[CHRONO] daily close=2026-05-06 idx=4082
[CHRONO] 5m day=2026-05-07 rows=610709:610901
[CHRONO] daily close=2026-05-07 idx=4083
[CHRONO] 5m day=2026-05-08 rows=610901:611093
[CHRONO] daily close=2026-05-08 idx=4084
[CHRONO] 5m day=2026-05-11 rows=611093:611285
[TRAIN][5M] asof=2026-05-11 feats=114 buy=YES sell=YES rows=124576
[CHRONO] daily close=2026-05-11 idx=4085
[CHRONO] 5m day=2026-05-12 rows=611285:611477
[CHRONO] daily close=2026-05-12 idx=4086
[CHRONO] 5m day=2026-05-13 rows=611477:611669
[CHRONO] daily close=2026-05-13 idx=4087
[CHRONO] 5m day=2026-05-14 rows=611669:611861
[CHRONO] daily close=2026-05-14 idx=4088
[CHRONO] 5m day=2026-05-15 rows=611861:612053
[CHRONO] daily close=2026-05-15 idx=4089
[CHRONO] 5m day=2026-05-18 rows=612053:612245
[TRAIN][5M] asof=2026-05-18 feats=114 buy=YES sell=YES rows=124722
[CHRONO] daily close=2026-05-18 idx=4090
[CHRONO] 5m day=2026-05-19 rows=612245:612437
[CHRONO] daily close=2026-05-19 idx=4091
[CHRONO] 5m day=2026-05-20 rows=612437:612629
[CHRONO] daily close=2026-05-20 idx=4092
[CHRONO] 5m day=2026-05-21 rows=612629:612821
[CHRONO] daily close=2026-05-21 idx=4093
[CHRONO] 5m day=2026-05-22 rows=612821:613013
[CHRONO] daily close=2026-05-22 idx=4094
[CHRONO] 5m day=2026-05-26 rows=613013:613205
[TRAIN][5M] asof=2026-05-26 feats=114 buy=YES sell=YES rows=124927
[CHRONO] daily close=2026-05-26 idx=4095
[CHRONO] 5m day=2026-05-27 rows=613205:613397
[CHRONO] daily close=2026-05-27 idx=4096
[TRAIN][DAILY-PROB] n=3923 pos=813 (20.72%)
[CHRONO] 5m day=2026-05-28 rows=613397:613589
[CHRONO] daily close=2026-05-28 idx=4097
[CHRONO] 5m day=2026-05-29 rows=613589:613781
[CHRONO] daily close=2026-05-29 idx=4098
[CHRONO] 5m day=2026-06-01 rows=613781:613973
[TRAIN][5M] asof=2026-06-01 feats=114 buy=YES sell=YES rows=125060
[CHRONO] daily close=2026-06-01 idx=4099
[CHRONO] 5m day=2026-06-02 rows=613973:614165
[CHRONO] daily close=2026-06-02 idx=4100
[CHRONO] 5m day=2026-06-03 rows=614165:614357
[CHRONO] daily close=2026-06-03 idx=4101
[CHRONO] 5m day=2026-06-04 rows=614357:614549
[CHRONO] daily close=2026-06-04 idx=4102
[CHRONO] 5m day=2026-06-05 rows=614549:614741
[CHRONO] daily close=2026-06-05 idx=4103
[CHRONO] 5m day=2026-06-08 rows=614741:614933
[TRAIN][5M] asof=2026-06-08 feats=114 buy=YES sell=YES rows=125326
[CHRONO] daily close=2026-06-08 idx=4104
[CHRONO] 5m day=2026-06-09 rows=614933:615125
[CHRONO] daily close=2026-06-09 idx=4105
[CHRONO] 5m day=2026-06-10 rows=615125:615317
[CHRONO] daily close=2026-06-10 idx=4106
[CHRONO] 5m day=2026-06-11 rows=615317:615509
[CHRONO] daily close=2026-06-11 idx=4107
[CHRONO] 5m day=2026-06-12 rows=615509:615654
[CHRONO] daily close=2026-06-12 idx=4108

c:\Users\TonyTang\Documents\chan.py\adaptive_reward_checkpoint_fresh.py:3132: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  daily_log_df = pd.concat(daily_log_frames, ignore_index=True, sort=False) if daily_log_frames else pd.DataFrame()

[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2026\trades.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2026\signal_decisions.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2026\daily_log.csv
[SAVED] output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2026\daily_reward_log.csv
[CHECKPOINT] saved chronological snapshot -> output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2026\continued_checkpoint__through_2026.joblib
[DONE] 2026 checkpoint: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2026\continued_checkpoint__through_2026.joblib
Final checkpoint: output_QQQ_chrono_prev_daily_context_wide_5m_resumable\chunk_2026\continued_checkpoint__through_2026.joblib