In [ ]:
from dataclasses import replace
from pathlib import Path

from realistic_chan_simulation import (
    RealisticSimulationConfig,
    run_realistic_simulation,
    print_simulation_summary,
)

config = RealisticSimulationConfig()

config = replace(
    config,
    data_path=Path("DataAPI/data/TQQQ_5M.csv"),
    bsp_workbook_path=Path(
        "outputs/bspoints_TQQQ_5m_2020-2026.xlsx"
    ),
    replay_mode="regenerate",

    chan=replace(
        config.chan,
        code="TQQQ",
        start="2020-01-01",
        end="2026-05-30",
        warmup_bars=500,
        max_klines=500,
    ),

    risk=replace(
        config.risk,
        stop_loss_pct=0.10,
        take_profit_pct=0.15,
        trailing_stop_pct=0.15,
        max_holding_bars=78 * 10,
    ),

    backtest=replace(
        config.backtest,
        initial_capital=100_000,
        fee_pct=0.0,
        slippage_pct=0.0,
    ),
)

output = run_realistic_simulation(config)

print_simulation_summary(output)

In [ ]:
# strategy_config = replace(
#     config.strategy,

#     buy_lookback_bars_by_segment={
#         "up": 10,
#         "down": 20,
#     },

#     required_buy_signals_by_segment={
#         "up": {
#             "1": 1,
#             "1p": 1,
#             "2": 1,
#             "2s": 1,
#             "3a": 2,
#             "3b": 2,
#         },
#         "down": {
#             "1": 7,
#             "1p": 7,
#             "2": 5,
#             "2s": 5,
#             "3a": 12,
#             "3b": 12,
#         },
#     },

#     sell_lookback_bars_by_entry_segment={
#         "up": 20,
#         "down": 10,
#     },

#     required_sell_signals_by_entry_segment={
#         "up": {
#             "1": 15,
#             "1p": 15,
#             "2": 15,
#             "2s": 15,
#             "3a": 15,
#             "3b": 15,
#         },
#         "down": {
#             "1": 1,
#             "1p": 1,
#             "2": 1,
#             "2s": 1,
#             "3a": 1,
#             "3b": 1,
#         },
#     },
# )

In [3]:
from realistic_chan_simulation import (
    RealisticSimulationConfig,
    run_realistic_simulation,
    print_simulation_summary,
)
import pandas as pd
import matplotlib.pyplot as plt

result = output.result

# Summary printed as text
print_simulation_summary(output)

# Metrics table
metrics_df = pd.DataFrame(
    result.metrics.items(),
    columns=["metric", "value"],
)

display(metrics_df)

# All buy and sell fills
display(result.trades)

# Most recent equity rows
display(result.equity.tail(20))

Price rows: 305,893
Chan feed rows (including warmup): 306,393
Point-in-time BSP events: 39,232
Simulation period: 2020-01-02 04:00:00 to 2026-05-29 19:55:00

Strategy metrics:
final_equity: 161933.05442371723
total_return: 0.6193305442371724
max_drawdown: -0.15214801060064442
sharpe: 0.4004638232655409
closed_trades: 757
win_rate: 0.5363276089828269
profit_factor: 1.1726068166803503

          metric          value
0   final_equity  161933.054424
1   total_return       0.619331
2   max_drawdown      -0.152148
3         sharpe       0.400464
4  closed_trades     757.000000
5       win_rate       0.536328
6  profit_factor       1.172607

,side,seen_idx,exec_idx,exec_px,reason,position_fraction,idx,px,raw_px,qty,fee,pnl,return_pct
0,buy,625,626,215.1400,5/5 type-1 buy-signal bars in 15-bar window; B...,1.0,626,215.1400,215.1400,464.813610,0.0,NaN,NaN
1,sell,835,836,216.3700,1/1 type-1 sell-signal bars in 10-bar window i...,1.0,836,216.3700,216.3700,464.813610,0.0,571.720740,0.005717
2,buy,2522,2523,224.2630,1/1 type-3a buy-signal bars in 10-bar window; ...,1.0,2523,224.2630,224.2630,448.454363,0.0,NaN,NaN
3,sell,2523,2524,224.3050,entry segment up; exit segment down,1.0,2524,224.3050,224.3050,448.454363,0.0,18.835083,0.000187
4,buy,2526,2527,223.6600,5/5 type-1 buy-signal bars in 15-bar window; B...,1.0,2527,223.6600,223.6600,449.747634,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1509,sell,303637,303638,712.5435,1/1 type-1 sell-signal bars in 10-bar window i...,1.0,303638,712.5435,712.5435,223.977865,0.0,2041.222273,0.012956
1510,buy,304030,304031,707.1900,5/5 type-1p buy-signal bars in 15-bar window; ...,1.0,304031,707.1900,707.1900,225.673400,0.0,NaN,NaN
1511,sell,304199,304200,706.5400,1/1 type-1 sell-signal bars in 10-bar window i...,1.0,304200,706.5400,706.5400,225.673400,0.0,-146.687710,-0.000919
1512,buy,304766,304767,712.6400,1/1 type-2 buy-signal bars in 10-bar window; B...,1.0,304767,712.6400,712.6400,223.741699,0.0,NaN,NaN
1513,sell,305136,305137,723.7500,entry segment up; exit segment down,1.0,305137,723.7500,723.7500,223.741699,0.0,2485.770272,0.015590

                 timestamp  bar_index         equity  position
305873 2026-05-29 18:20:00     305873  161933.054424         0
305874 2026-05-29 18:25:00     305874  161933.054424         0
305875 2026-05-29 18:30:00     305875  161933.054424         0
305876 2026-05-29 18:35:00     305876  161933.054424         0
305877 2026-05-29 18:40:00     305877  161933.054424         0
305878 2026-05-29 18:45:00     305878  161933.054424         0
305879 2026-05-29 18:50:00     305879  161933.054424         0
305880 2026-05-29 18:55:00     305880  161933.054424         0
305881 2026-05-29 19:00:00     305881  161933.054424         0
305882 2026-05-29 19:05:00     305882  161933.054424         0
305883 2026-05-29 19:10:00     305883  161933.054424         0
305884 2026-05-29 19:15:00     305884  161933.054424         0
305885 2026-05-29 19:20:00     305885  161933.054424         0
305886 2026-05-29 19:25:00     305886  161933.054424         0
305887 2026-05-29 19:30:00     305887  161933.054424         0
305888 2026-05-29 19:35:00     305888  161933.054424         0
305889 2026-05-29 19:40:00     305889  161933.054424         0
305890 2026-05-29 19:45:00     305890  161933.054424         0
305891 2026-05-29 19:50:00     305891  161933.054424         0
305892 2026-05-29 19:55:00     305892  161933.054424         0

In [7]:
from pathlib import Path
import pandas as pd

excel_path = Path(
    "outputs/strategy_backtest/TQQQ_realistic_strategy_result.xlsx"
)

excel_path.parent.mkdir(
    parents=True,
    exist_ok=True,
)

metrics_df = pd.DataFrame(
    output.result.metrics.items(),
    columns=["metric", "value"],
)

with pd.ExcelWriter(
    excel_path,
    engine="openpyxl",
) as writer:
    metrics_df.to_excel(
        writer,
        sheet_name="Metrics",
        index=False,
    )

    output.result.trades.to_excel(
        writer,
        sheet_name="Fills",
        index=False,
    )

    output.result.equity.to_excel(
        writer,
        sheet_name="Equity",
        index=False,
    )

    output.bsp_df.to_excel(
        writer,
        sheet_name="BSP Points",
        index=False,
    )

    output.price_df.to_excel(
        writer,
        sheet_name="Price Data",
        index=False,
    )

print(f"Saved Excel workbook to:\n{excel_path.resolve()}")

Saved Excel workbook to:
C:\Users\TonyTang\Documents\chan.py\outputs\strategy_backtest\TQQQ_realistic_strategy_result.xlsx