# Adaptive Reward Checkpoint With Fresh Trade Restart

This notebook builds an `adaptive_reward` snapshot using long-history data, then resumes trading from that snapshot without carrying over prior positions, cash, or trade logs.

What is preserved:
- Daily probability model
- 5-minute buy/sell models
- Adaptive-reward threshold history
- Chan warmup bars and feature state needed to continue training

What is reset on resume:
- Execution engine state
- Open position
- Trade log
- Equity path

In [ ]:
from pathlib import Path
import pandas as pd

from adaptive_reward_checkpoint_fresh import (
    build_adaptive_reward_snapshot,
    run_adaptive_reward_from_snapshot,
)
from adaptive_trade_extensions import RollingThresholdConfig, make_threshold_grid

snapshot_path = Path("checkpoints") / "SPY_adaptive_reward_fresh_start.joblib"

common_kwargs = dict(
    daily_csv_path="DataAPI/data/SPY_DAY.csv",
    k5m_csv_path="DataAPI/data/SPY_5M.csv",
    code="SPY",
    daily_chan_start="2008-01-01",
    accumulation_start="2010-01-01",
    N_confirm=5,
    min_labeled_days_to_train=200,
    retrain_every_new_labels=25,
    dp_lookback=5,
    lookahead_days_5m=2.0,
    retrain_every_days_5m=5,
    min_samples_total_5m=300,
    threshold_window_days=2.0,
    threshold_ret_grid=None,
    threshold_min_open_signals=10,
    initial_capital=100000.0,
    fee_pct=0.0,
    daily_chan_max_klines=500,
    five_chan_max_klines=500,
    macro_files={
        "vix_": "VIX.csv",
    },
    static_buy_level=0.20,
    static_sell_level=0.30,
    daily_threshold_config=RollingThresholdConfig(
        lookback_days=15,
        buy_grid=make_threshold_grid(0.05, 0.35, 0.005),
        sell_grid=make_threshold_grid(0.15, 0.60, 0.005),
        min_gap=0.02,
        min_obs=60,
        switch_penalty=0.0,
    ),
    verbose=True,
)

## 1. Build And Save The Snapshot

This step trains using daily history starting in 2008 and 5-minute history starting in 2010, then saves a reusable snapshot.

In [8]:
snapshot_res = build_adaptive_reward_snapshot(
    snapshot_path=str(snapshot_path),
    snapshot_end_time="2023-12-31",
    output_dir="output_adaptive_reward_snapshot_build_SPY",
    **common_kwargs,
)

print(snapshot_res["snapshot_path"])
display(snapshot_res["daily_reward_df"].tail())
display(snapshot_res["daily_log_df"].tail())

[TRAIN][DAILY-PROB] n=200 pos=43 (21.50%)
[TRAIN][DAILY-PROB] n=225 pos=49 (21.78%)
[TRAIN][DAILY-PROB] n=250 pos=57 (22.80%)
[TRAIN][DAILY-PROB] n=275 pos=66 (24.00%)
[TRAIN][DAILY-PROB] n=300 pos=74 (24.67%)
[TRAIN][DAILY-PROB] n=325 pos=78 (24.00%)
[TRAIN][DAILY-PROB] n=350 pos=85 (24.29%)
[TRAIN][DAILY-PROB] n=375 pos=94 (25.07%)
[TRAIN][DAILY-PROB] n=400 pos=101 (25.25%)
[TRAIN][DAILY-PROB] n=425 pos=104 (24.47%)
[TRAIN][DAILY-PROB] n=450 pos=112 (24.89%)
[TRAIN][DAILY-PROB] n=475 pos=112 (23.58%)
[TRAIN][DAILY-PROB] n=500 pos=113 (22.60%)
[TRAIN][DAILY-PROB] n=525 pos=124 (23.62%)
[TRAIN][DAILY-PROB] n=550 pos=131 (23.82%)
[TRAIN][DAILY-PROB] n=575 pos=143 (24.87%)
[TRAIN][DAILY-PROB] n=600 pos=150 (25.00%)
[TRAIN][DAILY-PROB] n=625 pos=150 (24.00%)
[TRAIN][DAILY-PROB] n=650 pos=158 (24.31%)
[TRAIN][DAILY-PROB] n=675 pos=160 (23.70%)
[TRAIN][DAILY-PROB] n=700 pos=161 (23.00%)
[TRAIN][DAILY-PROB] n=725 pos=168 (23.17%)
[TRAIN][DAILY-PROB] n=750 pos=173 (23.07%)
[TRAIN][DAILY-PROB] n=775 pos=180 (23.23%)
[TRAIN][DAILY-PROB] n=800 pos=188 (23.50%)
[TRAIN][DAILY-PROB] n=825 pos=198 (24.00%)
[TRAIN][DAILY-PROB] n=850 pos=204 (24.00%)
[TRAIN][DAILY-PROB] n=875 pos=214 (24.46%)
[TRAIN][DAILY-PROB] n=900 pos=220 (24.44%)
[TRAIN][DAILY-PROB] n=925 pos=227 (24.54%)
[TRAIN][DAILY-PROB] n=950 pos=232 (24.42%)
[TRAIN][DAILY-PROB] n=975 pos=234 (24.00%)
[TRAIN][DAILY-PROB] n=1000 pos=240 (24.00%)
[TRAIN][DAILY-PROB] n=1025 pos=248 (24.20%)
[TRAIN][DAILY-PROB] n=1050 pos=257 (24.48%)
[TRAIN][DAILY-PROB] n=1075 pos=265 (24.65%)
[TRAIN][DAILY-PROB] n=1100 pos=267 (24.27%)
[TRAIN][DAILY-PROB] n=1125 pos=275 (24.44%)
[TRAIN][DAILY-PROB] n=1150 pos=278 (24.17%)
[TRAIN][DAILY-PROB] n=1175 pos=287 (24.43%)
[TRAIN][DAILY-PROB] n=1200 pos=289 (24.08%)
[TRAIN][DAILY-PROB] n=1225 pos=295 (24.08%)
[TRAIN][DAILY-PROB] n=1250 pos=298 (23.84%)
[TRAIN][DAILY-PROB] n=1275 pos=300 (23.53%)
[TRAIN][DAILY-PROB] n=1300 pos=308 (23.69%)
[TRAIN][DAILY-PROB] n=1325 pos=313 (23.62%)
[TRAIN][DAILY-PROB] n=1350 pos=321 (23.78%)
[TRAIN][DAILY-PROB] n=1375 pos=325 (23.64%)
[TRAIN][DAILY-PROB] n=1400 pos=330 (23.57%)
[TRAIN][DAILY-PROB] n=1425 pos=334 (23.44%)
[TRAIN][DAILY-PROB] n=1450 pos=342 (23.59%)
[TRAIN][DAILY-PROB] n=1475 pos=343 (23.25%)
[TRAIN][DAILY-PROB] n=1500 pos=348 (23.20%)
[TRAIN][DAILY-PROB] n=1525 pos=353 (23.15%)
[TRAIN][DAILY-PROB] n=1550 pos=356 (22.97%)
[TRAIN][DAILY-PROB] n=1575 pos=359 (22.79%)
[TRAIN][DAILY-PROB] n=1600 pos=362 (22.62%)
[TRAIN][DAILY-PROB] n=1625 pos=371 (22.83%)
[TRAIN][DAILY-PROB] n=1650 pos=375 (22.73%)
[TRAIN][DAILY-PROB] n=1675 pos=378 (22.57%)
[TRAIN][DAILY-PROB] n=1700 pos=387 (22.76%)
[TRAIN][DAILY-PROB] n=1725 pos=390 (22.61%)
[TRAIN][DAILY-PROB] n=1750 pos=398 (22.74%)
[TRAIN][DAILY-PROB] n=1775 pos=401 (22.59%)
[TRAIN][DAILY-PROB] n=1800 pos=406 (22.56%)
[TRAIN][DAILY-PROB] n=1825 pos=421 (23.07%)
[TRAIN][DAILY-PROB] n=1850 pos=427 (23.08%)
[TRAIN][DAILY-PROB] n=1875 pos=433 (23.09%)
[TRAIN][DAILY-PROB] n=1900 pos=444 (23.37%)
[TRAIN][DAILY-PROB] n=1925 pos=454 (23.58%)
[TRAIN][DAILY-PROB] n=1950 pos=459 (23.54%)
[TRAIN][DAILY-PROB] n=1975 pos=465 (23.54%)
[TRAIN][DAILY-PROB] n=2000 pos=467 (23.35%)
[TRAIN][DAILY-PROB] n=2025 pos=472 (23.31%)
[TRAIN][DAILY-PROB] n=2050 pos=479 (23.37%)
[TRAIN][DAILY-PROB] n=2075 pos=482 (23.23%)
[TRAIN][DAILY-PROB] n=2100 pos=484 (23.05%)
[TRAIN][DAILY-PROB] n=2125 pos=492 (23.15%)
[TRAIN][DAILY-PROB] n=2150 pos=500 (23.26%)
[TRAIN][DAILY-PROB] n=2175 pos=508 (23.36%)
[TRAIN][DAILY-PROB] n=2200 pos=514 (23.36%)
[TRAIN][DAILY-PROB] n=2225 pos=518 (23.28%)
[TRAIN][DAILY-PROB] n=2250 pos=526 (23.38%)
[TRAIN][DAILY-PROB] n=2275 pos=530 (23.30%)
[TRAIN][DAILY-PROB] n=2300 pos=532 (23.13%)
[TRAIN][DAILY-PROB] n=2325 pos=538 (23.14%)
[TRAIN][DAILY-PROB] n=2350 pos=543 (23.11%)
[TRAIN][DAILY-PROB] n=2375 pos=544 (22.91%)
[TRAIN][DAILY-PROB] n=2400 pos=544 (22.67%)
[TRAIN][DAILY-PROB] n=2425 pos=547 (22.56%)
[TRAIN][DAILY-PROB] n=2450 pos=549 (22.41%)
[TRAIN][DAILY-PROB] n=2475 pos=557 (22.51%)
[TRAIN][DAILY-PROB] n=2500 pos=567 (22.68%)
[TRAIN][DAILY-PROB] n=2525 pos=571 (22.61%)
[TRAIN][DAILY-PROB] n=2550 pos=574 (22.51%)
[TRAIN][DAILY-PROB] n=2575 pos=581 (22.56%)
[TRAIN][DAILY-PROB] n=2600 pos=586 (22.54%)
[TRAIN][DAILY-PROB] n=2625 pos=592 (22.55%)
[TRAIN][DAILY-PROB] n=2650 pos=603 (22.75%)
[TRAIN][DAILY-PROB] n=2675 pos=611 (22.84%)
[TRAIN][DAILY-PROB] n=2700 pos=615 (22.78%)
[TRAIN][DAILY-PROB] n=2725 pos=616 (22.61%)
[TRAIN][DAILY-PROB] n=2750 pos=623 (22.65%)
[TRAIN][DAILY-PROB] n=2775 pos=624 (22.49%)
[TRAIN][DAILY-PROB] n=2800 pos=634 (22.64%)
[TRAIN][DAILY-PROB] n=2825 pos=637 (22.55%)
[TRAIN][DAILY-PROB] n=2850 pos=646 (22.67%)
[TRAIN][DAILY-PROB] n=2875 pos=650 (22.61%)
[TRAIN][DAILY-PROB] n=2900 pos=655 (22.59%)
[TRAIN][DAILY-PROB] n=2925 pos=656 (22.43%)
[TRAIN][DAILY-PROB] n=2950 pos=656 (22.24%)
[TRAIN][DAILY-PROB] n=2975 pos=658 (22.12%)
[TRAIN][DAILY-PROB] n=3000 pos=675 (22.50%)
[TRAIN][DAILY-PROB] n=3025 pos=686 (22.68%)
[TRAIN][DAILY-PROB] n=3050 pos=691 (22.66%)
[TRAIN][DAILY-PROB] n=3075 pos=696 (22.63%)
[TRAIN][DAILY-PROB] n=3100 pos=697 (22.48%)
[TRAIN][DAILY-PROB] n=3125 pos=704 (22.53%)
[TRAIN][DAILY-PROB] n=3150 pos=712 (22.60%)
[TRAIN][DAILY-PROB] n=3175 pos=715 (22.52%)
[TRAIN][DAILY-PROB] n=3200 pos=716 (22.38%)
[TRAIN][DAILY-PROB] n=3225 pos=718 (22.26%)
[TRAIN][DAILY-PROB] n=3250 pos=727 (22.37%)
[TRAIN][DAILY-PROB] n=3275 pos=727 (22.20%)
[TRAIN][DAILY-PROB] n=3300 pos=730 (22.12%)
[TRAIN][DAILY-PROB] n=3325 pos=732 (22.02%)
[TRAIN][DAILY-PROB] n=3350 pos=733 (21.88%)
[TRAIN][DAILY-PROB] n=3375 pos=742 (21.99%)
[TRAIN][DAILY-PROB] n=3400 pos=747 (21.97%)
[TRAIN][DAILY-PROB] n=3425 pos=752 (21.96%)
[TRAIN][DAILY-PROB] n=3450 pos=754 (21.86%)
[TRAIN][DAILY-PROB] n=3475 pos=764 (21.99%)
[TRAIN][DAILY-PROB] n=3500 pos=773 (22.09%)
[TRAIN][DAILY-PROB] n=3525 pos=777 (22.04%)
[TRAIN][DAILY-PROB] n=3550 pos=781 (22.00%)
[TRAIN][DAILY-PROB] n=3575 pos=791 (22.13%)
[TRAIN][DAILY-PROB] n=3600 pos=795 (22.08%)
[TRAIN][DAILY-PROB] n=3625 pos=808 (22.29%)
[TRAIN][DAILY-PROB] n=3650 pos=812 (22.25%)
[TRAIN][DAILY-PROB] n=3675 pos=818 (22.26%)
[TRAIN][DAILY-PROB] n=3700 pos=827 (22.35%)
[TRAIN][DAILY-PROB] n=3725 pos=831 (22.31%)
[TRAIN][DAILY-PROB] n=3750 pos=838 (22.35%)
[TRAIN][DAILY-PROB] n=3775 pos=843 (22.33%)
[TRAIN][DAILY-PROB] n=3800 pos=850 (22.37%)
[TRAIN][DAILY-PROB] n=3825 pos=859 (22.46%)
[TRAIN][DAILY-PROB] n=3850 pos=864 (22.44%)
[TRAIN][DAILY-PROB] n=3875 pos=871 (22.48%)
[TRAIN][DAILY-PROB] n=3900 pos=881 (22.59%)
[TRAIN][DAILY-PROB] n=3925 pos=886 (22.57%)
[TRAIN][5M] asof=2010-02-03 feats=69 buy=NO sell=YES rows=587
[TRAIN][5M] asof=2010-02-08 feats=69 buy=NO sell=YES rows=677
[TRAIN][5M] asof=2010-02-16 feats=69 buy=YES sell=YES rows=804
[TRAIN][5M] asof=2010-02-22 feats=69 buy=YES sell=YES rows=923
[TRAIN][5M] asof=2010-03-01 feats=69 buy=YES sell=YES rows=1091
[TRAIN][5M] asof=2010-03-08 feats=69 buy=YES sell=YES rows=1223
[TRAIN][5M] asof=2010-03-15 feats=69 buy=YES sell=YES rows=1368
[TRAIN][5M] asof=2010-03-22 feats=69 buy=YES sell=YES rows=1487
[TRAIN][5M] asof=2010-03-29 feats=69 buy=YES sell=YES rows=1573
[TRAIN][5M] asof=2010-04-05 feats=69 buy=YES sell=YES rows=1709
[TRAIN][5M] asof=2010-04-12 feats=69 buy=YES sell=YES rows=1845
[TRAIN][5M] asof=2010-04-19 feats=69 buy=YES sell=YES rows=1983
[TRAIN][5M] asof=2010-04-26 feats=69 buy=YES sell=YES rows=2105
[TRAIN][5M] asof=2010-05-03 feats=69 buy=YES sell=YES rows=2250
[TRAIN][5M] asof=2010-05-10 feats=69 buy=YES sell=YES rows=2348
[TRAIN][5M] asof=2010-05-17 feats=69 buy=YES sell=YES rows=2506
[TRAIN][5M] asof=2010-05-24 feats=69 buy=YES sell=YES rows=2723
[TRAIN][5M] asof=2010-06-01 feats=69 buy=YES sell=YES rows=2888
[TRAIN][5M] asof=2010-06-07 feats=69 buy=YES sell=YES rows=3027
[TRAIN][5M] asof=2010-06-14 feats=69 buy=YES sell=YES rows=3162
[TRAIN][5M] asof=2010-06-21 feats=69 buy=YES sell=YES rows=3227
[TRAIN][5M] asof=2010-06-28 feats=69 buy=YES sell=YES rows=3382
[TRAIN][5M] asof=2010-07-06 feats=69 buy=YES sell=YES rows=3547
[TRAIN][5M] asof=2010-07-12 feats=69 buy=YES sell=YES rows=3680
[TRAIN][5M] asof=2010-07-19 feats=69 buy=YES sell=YES rows=3845
[TRAIN][5M] asof=2010-07-26 feats=69 buy=YES sell=YES rows=4037
[TRAIN][5M] asof=2010-08-02 feats=69 buy=YES sell=YES rows=4139
[TRAIN][5M] asof=2010-08-09 feats=69 buy=YES sell=YES rows=4281
[TRAIN][5M] asof=2010-08-16 feats=69 buy=YES sell=YES rows=4446
[TRAIN][5M] asof=2010-08-23 feats=69 buy=YES sell=YES rows=4558
[TRAIN][5M] asof=2010-08-30 feats=69 buy=YES sell=YES rows=4713
[TRAIN][5M] asof=2010-09-07 feats=69 buy=YES sell=YES rows=4816
[TRAIN][5M] asof=2010-09-13 feats=69 buy=YES sell=YES rows=5014
[TRAIN][5M] asof=2010-09-20 feats=69 buy=YES sell=YES rows=5202
[TRAIN][5M] asof=2010-09-27 feats=69 buy=YES sell=YES rows=5324
[TRAIN][5M] asof=2010-10-04 feats=69 buy=YES sell=YES rows=5563
[TRAIN][5M] asof=2010-10-11 feats=69 buy=YES sell=YES rows=5693
[TRAIN][5M] asof=2010-10-18 feats=69 buy=YES sell=YES rows=5853
[TRAIN][5M] asof=2010-10-25 feats=69 buy=YES sell=YES rows=5992
[TRAIN][5M] asof=2010-11-01 feats=69 buy=YES sell=YES rows=6165
[TRAIN][5M] asof=2010-11-08 feats=69 buy=YES sell=YES rows=6288
[TRAIN][5M] asof=2010-11-15 feats=69 buy=YES sell=YES rows=6473
[TRAIN][5M] asof=2010-11-22 feats=69 buy=YES sell=YES rows=6586
[TRAIN][5M] asof=2010-11-29 feats=69 buy=YES sell=YES rows=6730
[TRAIN][5M] asof=2010-12-06 feats=69 buy=YES sell=YES rows=6915
[TRAIN][5M] asof=2010-12-13 feats=69 buy=YES sell=YES rows=7069
[TRAIN][5M] asof=2010-12-20 feats=69 buy=YES sell=YES rows=7250
[TRAIN][5M] asof=2010-12-27 feats=69 buy=YES sell=YES rows=7367
[TRAIN][5M] asof=2011-01-03 feats=69 buy=YES sell=YES rows=7473
[TRAIN][5M] asof=2011-01-10 feats=69 buy=YES sell=YES rows=7584
[TRAIN][5M] asof=2011-01-18 feats=69 buy=YES sell=YES rows=7743
[TRAIN][5M] asof=2011-01-24 feats=69 buy=YES sell=YES rows=7867
[TRAIN][5M] asof=2011-01-31 feats=69 buy=YES sell=YES rows=8067
[TRAIN][5M] asof=2011-02-07 feats=69 buy=YES sell=YES rows=8176
[TRAIN][5M] asof=2011-02-14 feats=69 buy=YES sell=YES rows=8329
[TRAIN][5M] asof=2011-02-22 feats=69 buy=YES sell=YES rows=8484
[TRAIN][5M] asof=2011-02-28 feats=69 buy=YES sell=YES rows=8650
[TRAIN][5M] asof=2011-03-07 feats=69 buy=YES sell=YES rows=8802
[TRAIN][5M] asof=2011-03-14 feats=69 buy=YES sell=YES rows=8948
[TRAIN][5M] asof=2011-03-21 feats=69 buy=YES sell=YES rows=9048
[TRAIN][5M] asof=2011-03-28 feats=69 buy=YES sell=YES rows=9222
[TRAIN][5M] asof=2011-04-04 feats=69 buy=YES sell=YES rows=9346
[TRAIN][5M] asof=2011-04-11 feats=69 buy=YES sell=YES rows=9488
[TRAIN][5M] asof=2011-04-18 feats=69 buy=YES sell=YES rows=9681
[TRAIN][5M] asof=2011-04-25 feats=69 buy=YES sell=YES rows=9828
[TRAIN][5M] asof=2011-05-02 feats=69 buy=YES sell=YES rows=10015
[TRAIN][5M] asof=2011-05-09 feats=69 buy=YES sell=YES rows=10197
[TRAIN][5M] asof=2011-05-16 feats=69 buy=YES sell=YES rows=10400
[TRAIN][5M] asof=2011-05-23 feats=69 buy=YES sell=YES rows=10568
[TRAIN][5M] asof=2011-05-31 feats=69 buy=YES sell=YES rows=10737
[TRAIN][5M] asof=2011-06-06 feats=69 buy=YES sell=YES rows=10844
[TRAIN][5M] asof=2011-06-13 feats=69 buy=YES sell=YES rows=11012
[TRAIN][5M] asof=2011-06-20 feats=69 buy=YES sell=YES rows=11194
[TRAIN][5M] asof=2011-06-27 feats=69 buy=YES sell=YES rows=11349
[TRAIN][5M] asof=2011-07-05 feats=69 buy=YES sell=YES rows=11515
[TRAIN][5M] asof=2011-07-11 feats=69 buy=YES sell=YES rows=11657
[TRAIN][5M] asof=2011-07-18 feats=69 buy=YES sell=YES rows=11849
[TRAIN][5M] asof=2011-07-25 feats=69 buy=YES sell=YES rows=11985
[TRAIN][5M] asof=2011-08-01 feats=69 buy=YES sell=YES rows=12157
[TRAIN][5M] asof=2011-08-08 feats=69 buy=YES sell=YES rows=12381
[TRAIN][5M] asof=2011-08-15 feats=69 buy=YES sell=YES rows=12573
[TRAIN][5M] asof=2011-08-22 feats=69 buy=YES sell=YES rows=12739
[TRAIN][5M] asof=2011-08-29 feats=69 buy=YES sell=YES rows=12909
[TRAIN][5M] asof=2011-09-06 feats=69 buy=YES sell=YES rows=13075
[TRAIN][5M] asof=2011-09-12 feats=69 buy=YES sell=YES rows=13208
[TRAIN][5M] asof=2011-09-19 feats=69 buy=YES sell=YES rows=13373
[TRAIN][5M] asof=2011-09-26 feats=69 buy=YES sell=YES rows=13551
[TRAIN][5M] asof=2011-10-03 feats=69 buy=YES sell=YES rows=13714
[TRAIN][5M] asof=2011-10-10 feats=69 buy=YES sell=YES rows=13825
[TRAIN][5M] asof=2011-10-17 feats=69 buy=YES sell=YES rows=14011
[TRAIN][5M] asof=2011-10-24 feats=69 buy=YES sell=YES rows=14173
[TRAIN][5M] asof=2011-10-31 feats=69 buy=YES sell=YES rows=14332
[TRAIN][5M] asof=2011-11-07 feats=69 buy=YES sell=YES rows=14422
[TRAIN][5M] asof=2011-11-14 feats=69 buy=YES sell=YES rows=14583
[TRAIN][5M] asof=2011-11-21 feats=69 buy=YES sell=YES rows=14743
[TRAIN][5M] asof=2011-11-28 feats=69 buy=YES sell=YES rows=14889
[TRAIN][5M] asof=2011-12-05 feats=69 buy=YES sell=YES rows=15070
[TRAIN][5M] asof=2011-12-12 feats=69 buy=YES sell=YES rows=15237
[TRAIN][5M] asof=2011-12-19 feats=69 buy=YES sell=YES rows=15369
[TRAIN][5M] asof=2011-12-27 feats=69 buy=YES sell=YES rows=15494
[TRAIN][5M] asof=2012-01-03 feats=69 buy=YES sell=YES rows=15563
[TRAIN][5M] asof=2012-01-09 feats=69 buy=YES sell=YES rows=15619
[TRAIN][5M] asof=2012-01-17 feats=69 buy=YES sell=YES rows=15794
[TRAIN][5M] asof=2012-01-23 feats=69 buy=YES sell=YES rows=15961
[TRAIN][5M] asof=2012-01-30 feats=69 buy=YES sell=YES rows=16144
[TRAIN][5M] asof=2012-02-06 feats=69 buy=YES sell=YES rows=16247
[TRAIN][5M] asof=2012-02-13 feats=69 buy=YES sell=YES rows=16349
[TRAIN][5M] asof=2012-02-21 feats=69 buy=YES sell=YES rows=16540
[TRAIN][5M] asof=2012-02-27 feats=69 buy=YES sell=YES rows=16670
[TRAIN][5M] asof=2012-03-05 feats=69 buy=YES sell=YES rows=16775
[TRAIN][5M] asof=2012-03-12 feats=69 buy=YES sell=YES rows=16869
[TRAIN][5M] asof=2012-03-19 feats=69 buy=YES sell=YES rows=17054
[TRAIN][5M] asof=2012-03-26 feats=69 buy=YES sell=YES rows=17260
[TRAIN][5M] asof=2012-04-02 feats=69 buy=YES sell=YES rows=17426
[TRAIN][5M] asof=2012-04-09 feats=69 buy=YES sell=YES rows=17521
[TRAIN][5M] asof=2012-04-16 feats=69 buy=YES sell=YES rows=17625
[TRAIN][5M] asof=2012-04-23 feats=69 buy=YES sell=YES rows=17737
[TRAIN][5M] asof=2012-04-30 feats=69 buy=YES sell=YES rows=17868
[TRAIN][5M] asof=2012-05-07 feats=69 buy=YES sell=YES rows=18047
[TRAIN][5M] asof=2012-05-14 feats=69 buy=YES sell=YES rows=18264
[TRAIN][5M] asof=2012-05-21 feats=69 buy=YES sell=YES rows=18442
[TRAIN][5M] asof=2012-05-29 feats=69 buy=YES sell=YES rows=18559
[TRAIN][5M] asof=2012-06-04 feats=69 buy=YES sell=YES rows=18674
[TRAIN][5M] asof=2012-06-11 feats=69 buy=YES sell=YES rows=18830
[TRAIN][5M] asof=2012-06-18 feats=69 buy=YES sell=YES rows=18989
[TRAIN][5M] asof=2012-06-25 feats=69 buy=YES sell=YES rows=19153
[TRAIN][5M] asof=2012-07-02 feats=69 buy=YES sell=YES rows=19268
[TRAIN][5M] asof=2012-07-09 feats=69 buy=YES sell=YES rows=19395
[TRAIN][5M] asof=2012-07-16 feats=69 buy=YES sell=YES rows=19508
[TRAIN][5M] asof=2012-07-23 feats=69 buy=YES sell=YES rows=19652
[TRAIN][5M] asof=2012-07-30 feats=69 buy=YES sell=YES rows=19752
[TRAIN][5M] asof=2012-08-06 feats=69 buy=YES sell=YES rows=19891
[TRAIN][5M] asof=2012-08-13 feats=69 buy=YES sell=YES rows=20074
[TRAIN][5M] asof=2012-08-20 feats=69 buy=YES sell=YES rows=20211
[TRAIN][5M] asof=2012-08-27 feats=69 buy=YES sell=YES rows=20367
[TRAIN][5M] asof=2012-09-04 feats=69 buy=YES sell=YES rows=20487
[TRAIN][5M] asof=2012-09-10 feats=69 buy=YES sell=YES rows=20636
[TRAIN][5M] asof=2012-09-17 feats=69 buy=YES sell=YES rows=20807
[TRAIN][5M] asof=2012-09-24 feats=69 buy=YES sell=YES rows=20919
[TRAIN][5M] asof=2012-10-01 feats=69 buy=YES sell=YES rows=21030
[TRAIN][5M] asof=2012-10-08 feats=69 buy=YES sell=YES rows=21163
[TRAIN][5M] asof=2012-10-15 feats=69 buy=YES sell=YES rows=21282
[TRAIN][5M] asof=2012-10-22 feats=69 buy=YES sell=YES rows=21399
[TRAIN][5M] asof=2012-10-31 feats=69 buy=YES sell=YES rows=21552
[TRAIN][5M] asof=2012-11-05 feats=69 buy=YES sell=YES rows=21673
[TRAIN][5M] asof=2012-11-12 feats=69 buy=YES sell=YES rows=21880
[TRAIN][5M] asof=2012-11-19 feats=69 buy=YES sell=YES rows=22049
[TRAIN][5M] asof=2012-11-26 feats=69 buy=YES sell=YES rows=22156
[TRAIN][5M] asof=2012-12-03 feats=69 buy=YES sell=YES rows=22306
[TRAIN][5M] asof=2012-12-10 feats=69 buy=YES sell=YES rows=22416
[TRAIN][5M] asof=2012-12-17 feats=69 buy=YES sell=YES rows=22546
[TRAIN][5M] asof=2012-12-24 feats=69 buy=YES sell=YES rows=22656
[TRAIN][5M] asof=2012-12-31 feats=69 buy=YES sell=YES rows=22773
[TRAIN][5M] asof=2013-01-07 feats=69 buy=YES sell=YES rows=22871
[TRAIN][5M] asof=2013-01-14 feats=69 buy=YES sell=YES rows=23094
[TRAIN][5M] asof=2013-01-22 feats=69 buy=YES sell=YES rows=23225
[TRAIN][5M] asof=2013-01-28 feats=69 buy=YES sell=YES rows=23353
[TRAIN][5M] asof=2013-02-04 feats=69 buy=YES sell=YES rows=23555
[TRAIN][5M] asof=2013-02-11 feats=69 buy=YES sell=YES rows=23696
[TRAIN][5M] asof=2013-02-19 feats=69 buy=YES sell=YES rows=23856
[TRAIN][5M] asof=2013-02-25 feats=69 buy=YES sell=YES rows=23976
[TRAIN][5M] asof=2013-03-04 feats=69 buy=YES sell=YES rows=24065
[TRAIN][5M] asof=2013-03-11 feats=69 buy=YES sell=YES rows=24249
[TRAIN][5M] asof=2013-03-18 feats=69 buy=YES sell=YES rows=24446
[TRAIN][5M] asof=2013-03-25 feats=69 buy=YES sell=YES rows=24604
[TRAIN][5M] asof=2013-04-01 feats=69 buy=YES sell=YES rows=24774
[TRAIN][5M] asof=2013-04-08 feats=69 buy=YES sell=YES rows=24958
[TRAIN][5M] asof=2013-04-15 feats=69 buy=YES sell=YES rows=25124
[TRAIN][5M] asof=2013-04-22 feats=69 buy=YES sell=YES rows=25274
[TRAIN][5M] asof=2013-04-29 feats=69 buy=YES sell=YES rows=25454
[TRAIN][5M] asof=2013-05-06 feats=69 buy=YES sell=YES rows=25575
[TRAIN][5M] asof=2013-05-13 feats=69 buy=YES sell=YES rows=25735
[TRAIN][5M] asof=2013-05-20 feats=69 buy=YES sell=YES rows=25838
[TRAIN][5M] asof=2013-05-28 feats=69 buy=YES sell=YES rows=26012
[TRAIN][5M] asof=2013-06-03 feats=69 buy=YES sell=YES rows=26173
[TRAIN][5M] asof=2013-06-10 feats=69 buy=YES sell=YES rows=26342
[TRAIN][5M] asof=2013-06-17 feats=69 buy=YES sell=YES rows=26518
[TRAIN][5M] asof=2013-06-24 feats=69 buy=YES sell=YES rows=26721
[TRAIN][5M] asof=2013-07-01 feats=69 buy=YES sell=YES rows=26921
[TRAIN][5M] asof=2013-07-08 feats=69 buy=YES sell=YES rows=27027
[TRAIN][5M] asof=2013-07-15 feats=69 buy=YES sell=YES rows=27170
[TRAIN][5M] asof=2013-07-22 feats=69 buy=YES sell=YES rows=27305
[TRAIN][5M] asof=2013-07-29 feats=69 buy=YES sell=YES rows=27509
[TRAIN][5M] asof=2013-08-05 feats=69 buy=YES sell=YES rows=27675
[TRAIN][5M] asof=2013-08-12 feats=69 buy=YES sell=YES rows=27877
[TRAIN][5M] asof=2013-08-19 feats=69 buy=YES sell=YES rows=28091
[TRAIN][5M] asof=2013-08-26 feats=69 buy=YES sell=YES rows=28220
[TRAIN][5M] asof=2013-09-03 feats=69 buy=YES sell=YES rows=28372
[TRAIN][5M] asof=2013-09-09 feats=69 buy=YES sell=YES rows=28468
[TRAIN][5M] asof=2013-09-16 feats=69 buy=YES sell=YES rows=28604
[TRAIN][5M] asof=2013-09-23 feats=69 buy=YES sell=YES rows=28767
[TRAIN][5M] asof=2013-09-30 feats=69 buy=YES sell=YES rows=28933
[TRAIN][5M] asof=2013-10-07 feats=69 buy=YES sell=YES rows=29089
[TRAIN][5M] asof=2013-10-14 feats=69 buy=YES sell=YES rows=29228
[TRAIN][5M] asof=2013-10-21 feats=69 buy=YES sell=YES rows=29377
[TRAIN][5M] asof=2013-10-28 feats=69 buy=YES sell=YES rows=29506
[TRAIN][5M] asof=2013-11-04 feats=69 buy=YES sell=YES rows=29679
[TRAIN][5M] asof=2013-11-11 feats=69 buy=YES sell=YES rows=29779
[TRAIN][5M] asof=2013-11-18 feats=69 buy=YES sell=YES rows=29945
[TRAIN][5M] asof=2013-11-25 feats=69 buy=YES sell=YES rows=30112
[TRAIN][5M] asof=2013-12-02 feats=69 buy=YES sell=YES rows=30204
[TRAIN][5M] asof=2013-12-09 feats=69 buy=YES sell=YES rows=30363
[TRAIN][5M] asof=2013-12-16 feats=69 buy=YES sell=YES rows=30545
[TRAIN][5M] asof=2013-12-23 feats=69 buy=YES sell=YES rows=30626
[TRAIN][5M] asof=2013-12-30 feats=69 buy=YES sell=YES rows=30760
[TRAIN][5M] asof=2014-01-06 feats=69 buy=YES sell=YES rows=30918
[TRAIN][5M] asof=2014-01-13 feats=69 buy=YES sell=YES rows=31119

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
3517,2023-12-22,0.150978,0.2,0.3,FORCE_BUY,-0.003475,-0.002643,0.000000,-0.003475,FORCE_SELL,2.536816e+09,473.18,1.95,0.75
3518,2023-12-26,0.136758,0.2,0.3,FORCE_BUY,0.002487,0.002162,0.000190,0.002487,FORCE_BUY,2.543126e+09,475.59,1.55,-0.50
3519,2023-12-27,0.114461,0.2,0.3,FORCE_BUY,0.002649,0.004244,0.000105,0.002649,FREE,2.553920e+09,476.90,1.55,-0.50
3520,2023-12-28,0.139579,0.2,0.3,FORCE_BUY,0.000000,0.000189,-0.000210,0.000000,FREE,2.554402e+09,477.05,-0.50,1.40
3521,2023-12-29,0.154243,0.2,0.3,FORCE_BUY,-0.004881,-0.005516,0.000126,-0.004881,FORCE_SELL,2.554723e+09,475.07,1.80,1.40

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
3517,2023-12-22,795220.002406,0.0,1,1.55,-0.5,0.150978,FORCE_BUY,0.2,0.3
3518,2023-12-26,799270.216290,0.0,1,1.55,-0.5,0.136758,FORCE_BUY,0.2,0.3
3519,2023-12-27,801471.784833,0.0,1,-0.50,1.4,0.114461,FORCE_BUY,0.2,0.3
3520,2023-12-28,801723.872834,0.0,1,1.80,1.4,0.139579,FORCE_BUY,0.2,0.3
3521,2023-12-29,798396.311220,0.0,1,1.80,1.4,0.154243,FORCE_BUY,0.2,0.3

## 2. Resume With Fresh Trading State

This step loads the saved models and adaptive-reward history, but it starts trading fresh from the next period using a brand-new execution engine.

In [9]:
resume_res = run_adaptive_reward_from_snapshot(
    snapshot_path=str(snapshot_path),
    end_time="2026-12-31",
    sim_start="2024-01-01",
    initial_capital=100000.0,
    fee_pct=0.0,
    output_dir="output_adaptive_reward_resumed_fresh_SPY_15day",
    # Optional. If omitted, the code saves next to the source snapshot as
    # checkpoints/SPY_adaptive_reward_fresh_start__continued.joblib
    save_snapshot_path=None,
    verbose=True,
)

print("continued snapshot:", resume_res["continued_snapshot_path"])

display(resume_res["daily_reward_df"].tail())
display(resume_res["daily_log_df"].tail())
display(resume_res["trades_df"].head())

[TRAIN][DAILY-PROB] n=3969 pos=890 (22.42%)
[TRAIN][DAILY-PROB] n=3994 pos=891 (22.31%)
[TRAIN][DAILY-PROB] n=4019 pos=898 (22.34%)
[TRAIN][DAILY-PROB] n=4044 pos=901 (22.28%)
[TRAIN][DAILY-PROB] n=4069 pos=909 (22.34%)
[TRAIN][DAILY-PROB] n=4094 pos=913 (22.30%)
[TRAIN][DAILY-PROB] n=4119 pos=917 (22.26%)
[TRAIN][DAILY-PROB] n=4144 pos=920 (22.20%)
[TRAIN][DAILY-PROB] n=4169 pos=928 (22.26%)
[TRAIN][DAILY-PROB] n=4194 pos=933 (22.25%)
[TRAIN][DAILY-PROB] n=4219 pos=937 (22.21%)
[TRAIN][DAILY-PROB] n=4244 pos=947 (22.31%)
[TRAIN][DAILY-PROB] n=4269 pos=955 (22.37%)
[TRAIN][DAILY-PROB] n=4294 pos=959 (22.33%)
[TRAIN][DAILY-PROB] n=4319 pos=963 (22.30%)
[TRAIN][DAILY-PROB] n=4344 pos=963 (22.17%)
[TRAIN][DAILY-PROB] n=4369 pos=970 (22.20%)
[TRAIN][DAILY-PROB] n=4394 pos=980 (22.30%)
[TRAIN][DAILY-PROB] n=4419 pos=988 (22.36%)
[TRAIN][DAILY-PROB] n=4444 pos=998 (22.46%)
[TRAIN][DAILY-PROB] n=4469 pos=1006 (22.51%)
[TRAIN][DAILY-PROB] n=4494 pos=1015 (22.59%)
[TRAIN][DAILY-PROB] n=4519 pos=1022 (22.62%)
[TRAIN][5M] asof=2024-01-02 feats=69 buy=YES sell=YES rows=120691
[TRAIN][5M] asof=2024-01-08 feats=69 buy=YES sell=YES rows=120841
[TRAIN][5M] asof=2024-01-16 feats=69 buy=YES sell=YES rows=121012
[TRAIN][5M] asof=2024-01-22 feats=69 buy=YES sell=YES rows=121112
[TRAIN][5M] asof=2024-01-29 feats=69 buy=YES sell=YES rows=121401
[TRAIN][5M] asof=2024-02-05 feats=69 buy=YES sell=YES rows=121554
[TRAIN][5M] asof=2024-02-12 feats=69 buy=YES sell=YES rows=121700
[TRAIN][5M] asof=2024-02-20 feats=69 buy=YES sell=YES rows=121907
[TRAIN][5M] asof=2024-02-26 feats=69 buy=YES sell=YES rows=122029
[TRAIN][5M] asof=2024-03-04 feats=69 buy=YES sell=YES rows=122233
[TRAIN][5M] asof=2024-03-11 feats=69 buy=YES sell=YES rows=122446
[TRAIN][5M] asof=2024-03-18 feats=69 buy=YES sell=YES rows=122626
[TRAIN][5M] asof=2024-03-25 feats=69 buy=YES sell=YES rows=122774
[TRAIN][5M] asof=2024-04-01 feats=69 buy=YES sell=YES rows=122860
[TRAIN][5M] asof=2024-04-08 feats=69 buy=YES sell=YES rows=123007
[TRAIN][5M] asof=2024-04-15 feats=69 buy=YES sell=YES rows=123175
[TRAIN][5M] asof=2024-04-22 feats=69 buy=YES sell=YES rows=123303
[TRAIN][5M] asof=2024-04-29 feats=69 buy=YES sell=YES rows=123487
[TRAIN][5M] asof=2024-05-06 feats=69 buy=YES sell=YES rows=123670
[TRAIN][5M] asof=2024-05-13 feats=69 buy=YES sell=YES rows=123879
[TRAIN][5M] asof=2024-05-20 feats=69 buy=YES sell=YES rows=124030
[TRAIN][5M] asof=2024-05-28 feats=69 buy=YES sell=YES rows=124229
[TRAIN][5M] asof=2024-06-03 feats=69 buy=YES sell=YES rows=124373
[TRAIN][5M] asof=2024-06-10 feats=69 buy=YES sell=YES rows=124609
[TRAIN][5M] asof=2024-06-17 feats=69 buy=YES sell=YES rows=124819
[TRAIN][5M] asof=2024-06-24 feats=69 buy=YES sell=YES rows=124940
[TRAIN][5M] asof=2024-07-01 feats=69 buy=YES sell=YES rows=125142
[TRAIN][5M] asof=2024-07-08 feats=69 buy=YES sell=YES rows=125271
[TRAIN][5M] asof=2024-07-15 feats=69 buy=YES sell=YES rows=125449
[TRAIN][5M] asof=2024-07-22 feats=69 buy=YES sell=YES rows=125674
[TRAIN][5M] asof=2024-07-29 feats=69 buy=YES sell=YES rows=125894
[TRAIN][5M] asof=2024-08-05 feats=69 buy=YES sell=YES rows=126110
[TRAIN][5M] asof=2024-08-12 feats=69 buy=YES sell=YES rows=126322
[TRAIN][5M] asof=2024-08-19 feats=69 buy=YES sell=YES rows=126527
[TRAIN][5M] asof=2024-08-26 feats=69 buy=YES sell=YES rows=126711
[TRAIN][5M] asof=2024-09-03 feats=69 buy=YES sell=YES rows=126901
[TRAIN][5M] asof=2024-09-09 feats=69 buy=YES sell=YES rows=127034
[TRAIN][5M] asof=2024-09-16 feats=69 buy=YES sell=YES rows=127191
[TRAIN][5M] asof=2024-09-23 feats=69 buy=YES sell=YES rows=127384
[TRAIN][5M] asof=2024-09-30 feats=69 buy=YES sell=YES rows=127562
[TRAIN][5M] asof=2024-10-07 feats=69 buy=YES sell=YES rows=127730
[TRAIN][5M] asof=2024-10-14 feats=69 buy=YES sell=YES rows=127918
[TRAIN][5M] asof=2024-10-21 feats=69 buy=YES sell=YES rows=128112
[TRAIN][5M] asof=2024-10-28 feats=69 buy=YES sell=YES rows=128339
[TRAIN][5M] asof=2024-11-04 feats=69 buy=YES sell=YES rows=128491
[TRAIN][5M] asof=2024-11-11 feats=69 buy=YES sell=YES rows=128681
[TRAIN][5M] asof=2024-11-18 feats=69 buy=YES sell=YES rows=128868
[TRAIN][5M] asof=2024-11-25 feats=69 buy=YES sell=YES rows=129076
[TRAIN][5M] asof=2024-12-02 feats=69 buy=YES sell=YES rows=129186
[TRAIN][5M] asof=2024-12-09 feats=69 buy=YES sell=YES rows=129361
[TRAIN][5M] asof=2024-12-16 feats=69 buy=YES sell=YES rows=129499
[TRAIN][5M] asof=2024-12-23 feats=69 buy=YES sell=YES rows=129717
[TRAIN][5M] asof=2024-12-30 feats=69 buy=YES sell=YES rows=129827
[TRAIN][5M] asof=2025-01-06 feats=69 buy=YES sell=YES rows=129936
[TRAIN][5M] asof=2025-01-13 feats=69 buy=YES sell=YES rows=130098
[TRAIN][5M] asof=2025-01-21 feats=69 buy=YES sell=YES rows=130324
[TRAIN][5M] asof=2025-01-27 feats=69 buy=YES sell=YES rows=130475
[TRAIN][5M] asof=2025-02-03 feats=69 buy=YES sell=YES rows=130682
[TRAIN][5M] asof=2025-02-10 feats=69 buy=YES sell=YES rows=130876
[TRAIN][5M] asof=2025-02-18 feats=69 buy=YES sell=YES rows=131042
[TRAIN][5M] asof=2025-02-24 feats=69 buy=YES sell=YES rows=131155
[TRAIN][5M] asof=2025-03-03 feats=69 buy=YES sell=YES rows=131313
[TRAIN][5M] asof=2025-03-10 feats=69 buy=YES sell=YES rows=131520
[TRAIN][5M] asof=2025-03-17 feats=69 buy=YES sell=YES rows=131720
[TRAIN][5M] asof=2025-03-24 feats=69 buy=YES sell=YES rows=131905
[TRAIN][5M] asof=2025-03-31 feats=69 buy=YES sell=YES rows=132139
[TRAIN][5M] asof=2025-04-07 feats=69 buy=YES sell=YES rows=132333
[TRAIN][5M] asof=2025-04-14 feats=69 buy=YES sell=YES rows=132491
[TRAIN][5M] asof=2025-04-21 feats=69 buy=YES sell=YES rows=132608
[TRAIN][5M] asof=2025-04-28 feats=69 buy=YES sell=YES rows=132856
[TRAIN][5M] asof=2025-05-05 feats=69 buy=YES sell=YES rows=133061
[TRAIN][5M] asof=2025-05-12 feats=69 buy=YES sell=YES rows=133177
[TRAIN][5M] asof=2025-05-19 feats=69 buy=YES sell=YES rows=133348
[TRAIN][5M] asof=2025-05-27 feats=69 buy=YES sell=YES rows=133550
[TRAIN][5M] asof=2025-06-02 feats=69 buy=YES sell=YES rows=133707
[TRAIN][5M] asof=2025-06-09 feats=69 buy=YES sell=YES rows=133893
[TRAIN][5M] asof=2025-06-16 feats=69 buy=YES sell=YES rows=134055
[TRAIN][5M] asof=2025-06-23 feats=69 buy=YES sell=YES rows=134164
[TRAIN][5M] asof=2025-06-30 feats=69 buy=YES sell=YES rows=134302
[TRAIN][5M] asof=2025-07-07 feats=69 buy=YES sell=YES rows=134419
[TRAIN][5M] asof=2025-07-14 feats=69 buy=YES sell=YES rows=134615
[TRAIN][5M] asof=2025-07-21 feats=69 buy=YES sell=YES rows=134837
[TRAIN][5M] asof=2025-07-28 feats=69 buy=YES sell=YES rows=134988
[TRAIN][5M] asof=2025-08-04 feats=69 buy=YES sell=YES rows=135175
[TRAIN][5M] asof=2025-08-11 feats=69 buy=YES sell=YES rows=135358
[TRAIN][5M] asof=2025-08-18 feats=69 buy=YES sell=YES rows=135530
[TRAIN][5M] asof=2025-08-25 feats=69 buy=YES sell=YES rows=135768
[TRAIN][5M] asof=2025-09-02 feats=69 buy=YES sell=YES rows=135919
[TRAIN][5M] asof=2025-09-08 feats=69 buy=YES sell=YES rows=136086
[TRAIN][5M] asof=2025-09-15 feats=69 buy=YES sell=YES rows=136272
[TRAIN][5M] asof=2025-09-22 feats=69 buy=YES sell=YES rows=136450
[TRAIN][5M] asof=2025-09-29 feats=69 buy=YES sell=YES rows=136621
[TRAIN][5M] asof=2025-10-06 feats=69 buy=YES sell=YES rows=136813
[TRAIN][5M] asof=2025-10-13 feats=69 buy=YES sell=YES rows=136990
[TRAIN][5M] asof=2025-10-20 feats=69 buy=YES sell=YES rows=137160
[TRAIN][5M] asof=2025-10-27 feats=69 buy=YES sell=YES rows=137342
[TRAIN][5M] asof=2025-11-03 feats=69 buy=YES sell=YES rows=137487
[TRAIN][5M] asof=2025-11-10 feats=69 buy=YES sell=YES rows=137719
[TRAIN][5M] asof=2025-11-17 feats=69 buy=YES sell=YES rows=137929
[TRAIN][5M] asof=2025-11-24 feats=69 buy=YES sell=YES rows=138145
[TRAIN][5M] asof=2025-12-01 feats=69 buy=YES sell=YES rows=138259
[TRAIN][5M] asof=2025-12-08 feats=69 buy=YES sell=YES rows=138412
[TRAIN][5M] asof=2025-12-15 feats=69 buy=YES sell=YES rows=138611
[TRAIN][5M] asof=2025-12-22 feats=69 buy=YES sell=YES rows=138796
[TRAIN][5M] asof=2025-12-29 feats=69 buy=YES sell=YES rows=138947
[TRAIN][5M] asof=2026-01-05 feats=69 buy=YES sell=YES rows=139111
[TRAIN][5M] asof=2026-01-12 feats=69 buy=YES sell=YES rows=139349
[TRAIN][5M] asof=2026-01-20 feats=69 buy=YES sell=YES rows=139508
[TRAIN][5M] asof=2026-01-26 feats=69 buy=YES sell=YES rows=139679
[TRAIN][5M] asof=2026-02-02 feats=69 buy=YES sell=YES rows=139935
[TRAIN][5M] asof=2026-02-09 feats=69 buy=YES sell=YES rows=140177
[TRAIN][5M] asof=2026-02-17 feats=69 buy=YES sell=YES rows=140364
[TRAIN][5M] asof=2026-02-23 feats=69 buy=YES sell=YES rows=140486
[TRAIN][5M] asof=2026-03-02 feats=69 buy=YES sell=YES rows=140693
[TRAIN][5M] asof=2026-03-09 feats=69 buy=YES sell=YES rows=140907
[TRAIN][5M] asof=2026-03-16 feats=69 buy=YES sell=YES rows=141114
[TRAIN][5M] asof=2026-03-23 feats=69 buy=YES sell=YES rows=141320
[TRAIN][5M] asof=2026-03-30 feats=69 buy=YES sell=YES rows=141507
[TRAIN][5M] asof=2026-04-06 feats=69 buy=YES sell=YES rows=141585
[TRAIN][5M] asof=2026-04-13 feats=69 buy=YES sell=YES rows=141791
[TRAIN][5M] asof=2026-04-20 feats=69 buy=YES sell=YES rows=141987
[SAVED] output_adaptive_reward_resumed_fresh_SPY_15day\trades.csv
[SAVED] output_adaptive_reward_resumed_fresh_SPY_15day\daily_log.csv
[SAVED] output_adaptive_reward_resumed_fresh_SPY_15day\daily_reward_log.csv
[SAVED] output_adaptive_reward_resumed_fresh_SPY_15day\equity_vs_buyhold.png
[SAVED] output_adaptive_reward_resumed_fresh_SPY_15day\price_with_trades.png
[SAVED] output_adaptive_reward_resumed_fresh_SPY_15day\p_day.png
[CHECKPOINT] saved continued snapshot -> checkpoints\SPY_adaptive_reward_fresh_start__continued.joblib
continued snapshot: checkpoints\SPY_adaptive_reward_fresh_start__continued.joblib

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
4094,2026-04-15,0.125536,0.2,0.3,FORCE_BUY,0.008710,-0.000604,-0.000604,0.008710,FORCE_BUY,592023.898955,700.65,-0.50,2.00
4095,2026-04-16,0.119575,0.2,0.3,FORCE_BUY,0.001812,0.001528,-0.000257,0.001812,FORCE_BUY,593096.543725,702.22,-0.50,2.00
4096,2026-04-17,0.138861,0.2,0.3,FORCE_BUY,0.011427,0.001167,0.001167,0.011427,FORCE_BUY,599873.873595,710.75,0.85,2.45
4097,2026-04-20,0.138060,0.2,0.3,FORCE_BUY,0.004147,0.004147,0.004147,0.004147,FORCE_BUY,602361.461980,709.49,0.80,2.35
4098,2026-04-21,0.187429,0.2,0.3,FORCE_BUY,-0.003720,-0.003720,-0.003720,-0.003720,FORCE_BUY,600120.559185,707.00,0.80,2.35

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
572,2026-04-15,210746.488312,0.0,1,-0.50,2.00,0.125536,FORCE_BUY,0.2,0.3
573,2026-04-16,211218.724074,0.0,1,0.85,2.45,0.119575,FORCE_BUY,0.2,0.3
574,2026-04-17,213784.438118,0.0,1,0.80,2.35,0.138861,FORCE_BUY,0.2,0.3
575,2026-04-20,213405.446360,0.0,1,0.80,2.35,0.138060,FORCE_BUY,0.2,0.3
576,2026-04-21,212656.486457,0.0,1,0.80,2.35,0.187429,FORCE_BUY,0.2,0.3

,side,seen_idx,exec_px,qty,fee,reason,ts,pred,th,gate,pnl,entry_px,entry_idx
0,buy,643541,469.280,213.092397,0.0,5m BUY signal,2024-01-04 05:45:00,0.576991,0.45,FREE,NaN,NaN,NaN
1,sell,643961,469.080,213.092397,0.0,5m SELL signal,2024-01-08 09:30:00,7.518479,-0.50,FREE,-42.618479,469.280,643541.0
2,buy,643981,470.275,212.550915,0.0,5m BUY signal,2024-01-08 11:10:00,0.467693,0.35,FREE,NaN,NaN,NaN
3,sell,643991,471.080,212.550915,0.0,5m SELL signal,2024-01-08 12:00:00,8.529417,-0.50,FREE,171.103487,470.275,643981.0
4,buy,644317,473.810,211.326238,0.0,5m BUY signal,2024-01-10 08:00:00,1.297413,-0.50,FREE,NaN,NaN,NaN

In [10]:
from pathlib import Path
import pandas as pd

from adaptive_reward_checkpoint_fresh import (
    build_adaptive_reward_snapshot,
    run_adaptive_reward_from_snapshot,
)
from adaptive_trade_extensions import RollingThresholdConfig, make_threshold_grid

snapshot_path = Path("checkpoints") / "QQQ_adaptive_reward_fresh_start_15days.joblib"

common_kwargs = dict(
    daily_csv_path="DataAPI/data/QQQ_DAY.csv",
    k5m_csv_path="DataAPI/data/QQQ_5M.csv",
    code="QQQ",
    daily_chan_start="2008-01-01",
    accumulation_start="2010-01-01",
    N_confirm=5,
    min_labeled_days_to_train=200,
    retrain_every_new_labels=25,
    dp_lookback=5,
    lookahead_days_5m=2.0,
    retrain_every_days_5m=5,
    min_samples_total_5m=300,
    threshold_window_days=2.0,
    threshold_ret_grid=None,
    threshold_min_open_signals=10,
    initial_capital=100000.0,
    fee_pct=0.0,
    daily_chan_max_klines=500,
    five_chan_max_klines=500,
    macro_files={
        "vix_": "VIX.csv",
    },
    static_buy_level=0.20,
    static_sell_level=0.30,
    daily_threshold_config=RollingThresholdConfig(
        lookback_days=15,
        buy_grid=make_threshold_grid(0.05, 0.35, 0.005),
        sell_grid=make_threshold_grid(0.15, 0.60, 0.005),
        min_gap=0.02,
        min_obs=60,
        switch_penalty=0.0,
    ),
    verbose=True,
)

In [11]:
snapshot_res = build_adaptive_reward_snapshot(
    snapshot_path=str(snapshot_path),
    snapshot_end_time="2023-12-31",
    output_dir="output_adaptive_reward_snapshot_build_QQQ_15days",
    **common_kwargs,
)

print(snapshot_res["snapshot_path"])
display(snapshot_res["daily_reward_df"].tail())
display(snapshot_res["daily_log_df"].tail())

[TRAIN][DAILY-PROB] n=200 pos=33 (16.50%)
[TRAIN][DAILY-PROB] n=225 pos=40 (17.78%)
[TRAIN][DAILY-PROB] n=250 pos=46 (18.40%)
[TRAIN][DAILY-PROB] n=275 pos=50 (18.18%)
[TRAIN][DAILY-PROB] n=300 pos=56 (18.67%)
[TRAIN][DAILY-PROB] n=325 pos=59 (18.15%)
[TRAIN][DAILY-PROB] n=350 pos=73 (20.86%)
[TRAIN][DAILY-PROB] n=375 pos=78 (20.80%)
[TRAIN][DAILY-PROB] n=400 pos=89 (22.25%)
[TRAIN][DAILY-PROB] n=425 pos=101 (23.76%)
[TRAIN][DAILY-PROB] n=450 pos=108 (24.00%)
[TRAIN][DAILY-PROB] n=475 pos=114 (24.00%)
[TRAIN][DAILY-PROB] n=500 pos=119 (23.80%)
[TRAIN][DAILY-PROB] n=525 pos=119 (22.67%)
[TRAIN][DAILY-PROB] n=550 pos=125 (22.73%)
[TRAIN][DAILY-PROB] n=575 pos=130 (22.61%)
[TRAIN][DAILY-PROB] n=600 pos=138 (23.00%)
[TRAIN][DAILY-PROB] n=625 pos=144 (23.04%)
[TRAIN][DAILY-PROB] n=650 pos=145 (22.31%)
[TRAIN][DAILY-PROB] n=675 pos=145 (21.48%)
[TRAIN][DAILY-PROB] n=700 pos=149 (21.29%)
[TRAIN][DAILY-PROB] n=725 pos=151 (20.83%)
[TRAIN][DAILY-PROB] n=750 pos=155 (20.67%)
[TRAIN][DAILY-PROB] n=775 pos=163 (21.03%)
[TRAIN][DAILY-PROB] n=800 pos=168 (21.00%)
[TRAIN][DAILY-PROB] n=825 pos=181 (21.94%)
[TRAIN][DAILY-PROB] n=850 pos=184 (21.65%)
[TRAIN][DAILY-PROB] n=875 pos=193 (22.06%)
[TRAIN][DAILY-PROB] n=900 pos=200 (22.22%)
[TRAIN][DAILY-PROB] n=925 pos=203 (21.95%)
[TRAIN][DAILY-PROB] n=950 pos=212 (22.32%)
[TRAIN][DAILY-PROB] n=975 pos=214 (21.95%)
[TRAIN][DAILY-PROB] n=1000 pos=214 (21.40%)
[TRAIN][DAILY-PROB] n=1025 pos=214 (20.88%)
[TRAIN][DAILY-PROB] n=1050 pos=224 (21.33%)
[TRAIN][DAILY-PROB] n=1075 pos=233 (21.67%)
[TRAIN][DAILY-PROB] n=1100 pos=243 (22.09%)
[TRAIN][DAILY-PROB] n=1125 pos=246 (21.87%)
[TRAIN][DAILY-PROB] n=1150 pos=251 (21.83%)
[TRAIN][DAILY-PROB] n=1175 pos=259 (22.04%)
[TRAIN][DAILY-PROB] n=1200 pos=265 (22.08%)
[TRAIN][DAILY-PROB] n=1225 pos=269 (21.96%)
[TRAIN][DAILY-PROB] n=1250 pos=272 (21.76%)
[TRAIN][DAILY-PROB] n=1275 pos=281 (22.04%)
[TRAIN][DAILY-PROB] n=1300 pos=292 (22.46%)
[TRAIN][DAILY-PROB] n=1325 pos=297 (22.42%)
[TRAIN][DAILY-PROB] n=1350 pos=301 (22.30%)
[TRAIN][DAILY-PROB] n=1375 pos=305 (22.18%)
[TRAIN][DAILY-PROB] n=1400 pos=309 (22.07%)
[TRAIN][DAILY-PROB] n=1425 pos=313 (21.96%)
[TRAIN][DAILY-PROB] n=1450 pos=313 (21.59%)
[TRAIN][DAILY-PROB] n=1475 pos=317 (21.49%)
[TRAIN][DAILY-PROB] n=1500 pos=322 (21.47%)
[TRAIN][DAILY-PROB] n=1525 pos=328 (21.51%)
[TRAIN][DAILY-PROB] n=1550 pos=334 (21.55%)
[TRAIN][DAILY-PROB] n=1575 pos=335 (21.27%)
[TRAIN][DAILY-PROB] n=1600 pos=335 (20.94%)
[TRAIN][DAILY-PROB] n=1625 pos=338 (20.80%)
[TRAIN][DAILY-PROB] n=1650 pos=342 (20.73%)
[TRAIN][DAILY-PROB] n=1675 pos=348 (20.78%)
[TRAIN][DAILY-PROB] n=1700 pos=351 (20.65%)
[TRAIN][DAILY-PROB] n=1725 pos=360 (20.87%)
[TRAIN][DAILY-PROB] n=1750 pos=363 (20.74%)
[TRAIN][DAILY-PROB] n=1775 pos=371 (20.90%)
[TRAIN][DAILY-PROB] n=1800 pos=376 (20.89%)
[TRAIN][DAILY-PROB] n=1825 pos=382 (20.93%)
[TRAIN][DAILY-PROB] n=1850 pos=390 (21.08%)
[TRAIN][DAILY-PROB] n=1875 pos=397 (21.17%)
[TRAIN][DAILY-PROB] n=1900 pos=408 (21.47%)
[TRAIN][DAILY-PROB] n=1925 pos=415 (21.56%)
[TRAIN][DAILY-PROB] n=1950 pos=421 (21.59%)
[TRAIN][DAILY-PROB] n=1975 pos=430 (21.77%)
[TRAIN][DAILY-PROB] n=2000 pos=437 (21.85%)
[TRAIN][DAILY-PROB] n=2025 pos=445 (21.98%)
[TRAIN][DAILY-PROB] n=2050 pos=449 (21.90%)
[TRAIN][DAILY-PROB] n=2075 pos=456 (21.98%)
[TRAIN][DAILY-PROB] n=2100 pos=463 (22.05%)
[TRAIN][DAILY-PROB] n=2125 pos=463 (21.79%)
[TRAIN][DAILY-PROB] n=2150 pos=471 (21.91%)
[TRAIN][DAILY-PROB] n=2175 pos=476 (21.89%)
[TRAIN][DAILY-PROB] n=2200 pos=483 (21.95%)
[TRAIN][DAILY-PROB] n=2225 pos=487 (21.89%)
[TRAIN][DAILY-PROB] n=2250 pos=488 (21.69%)
[TRAIN][DAILY-PROB] n=2275 pos=490 (21.54%)
[TRAIN][DAILY-PROB] n=2300 pos=493 (21.43%)
[TRAIN][DAILY-PROB] n=2325 pos=494 (21.25%)
[TRAIN][DAILY-PROB] n=2350 pos=500 (21.28%)
[TRAIN][DAILY-PROB] n=2375 pos=502 (21.14%)
[TRAIN][DAILY-PROB] n=2400 pos=507 (21.12%)
[TRAIN][DAILY-PROB] n=2425 pos=512 (21.11%)
[TRAIN][DAILY-PROB] n=2450 pos=513 (20.94%)
[TRAIN][DAILY-PROB] n=2475 pos=519 (20.97%)
[TRAIN][DAILY-PROB] n=2500 pos=526 (21.04%)
[TRAIN][DAILY-PROB] n=2525 pos=532 (21.07%)
[TRAIN][DAILY-PROB] n=2550 pos=540 (21.18%)
[TRAIN][DAILY-PROB] n=2575 pos=541 (21.01%)
[TRAIN][DAILY-PROB] n=2600 pos=546 (21.00%)
[TRAIN][DAILY-PROB] n=2625 pos=548 (20.88%)
[TRAIN][DAILY-PROB] n=2650 pos=555 (20.94%)
[TRAIN][DAILY-PROB] n=2675 pos=564 (21.08%)
[TRAIN][DAILY-PROB] n=2700 pos=579 (21.44%)
[TRAIN][DAILY-PROB] n=2725 pos=589 (21.61%)
[TRAIN][DAILY-PROB] n=2750 pos=591 (21.49%)
[TRAIN][DAILY-PROB] n=2775 pos=592 (21.33%)
[TRAIN][DAILY-PROB] n=2800 pos=599 (21.39%)
[TRAIN][DAILY-PROB] n=2825 pos=607 (21.49%)
[TRAIN][DAILY-PROB] n=2850 pos=612 (21.47%)
[TRAIN][DAILY-PROB] n=2875 pos=619 (21.53%)
[TRAIN][DAILY-PROB] n=2900 pos=622 (21.45%)
[TRAIN][DAILY-PROB] n=2925 pos=631 (21.57%)
[TRAIN][DAILY-PROB] n=2950 pos=631 (21.39%)
[TRAIN][DAILY-PROB] n=2975 pos=633 (21.28%)
[TRAIN][DAILY-PROB] n=3000 pos=634 (21.13%)
[TRAIN][DAILY-PROB] n=3025 pos=639 (21.12%)
[TRAIN][DAILY-PROB] n=3050 pos=643 (21.08%)
[TRAIN][DAILY-PROB] n=3075 pos=643 (20.91%)
[TRAIN][DAILY-PROB] n=3100 pos=646 (20.84%)
[TRAIN][DAILY-PROB] n=3125 pos=653 (20.90%)
[TRAIN][DAILY-PROB] n=3150 pos=658 (20.89%)
[TRAIN][DAILY-PROB] n=3175 pos=666 (20.98%)
[TRAIN][DAILY-PROB] n=3200 pos=674 (21.06%)
[TRAIN][DAILY-PROB] n=3225 pos=675 (20.93%)
[TRAIN][DAILY-PROB] n=3250 pos=678 (20.86%)
[TRAIN][DAILY-PROB] n=3275 pos=685 (20.92%)
[TRAIN][DAILY-PROB] n=3300 pos=688 (20.85%)
[TRAIN][DAILY-PROB] n=3325 pos=694 (20.87%)
[TRAIN][DAILY-PROB] n=3350 pos=694 (20.72%)
[TRAIN][DAILY-PROB] n=3375 pos=697 (20.65%)
[TRAIN][DAILY-PROB] n=3400 pos=701 (20.62%)
[TRAIN][DAILY-PROB] n=3425 pos=711 (20.76%)
[TRAIN][DAILY-PROB] n=3450 pos=714 (20.70%)
[TRAIN][DAILY-PROB] n=3475 pos=719 (20.69%)
[TRAIN][DAILY-PROB] n=3500 pos=726 (20.74%)
[TRAIN][DAILY-PROB] n=3525 pos=728 (20.65%)
[TRAIN][DAILY-PROB] n=3550 pos=738 (20.79%)
[TRAIN][DAILY-PROB] n=3575 pos=739 (20.67%)
[TRAIN][DAILY-PROB] n=3600 pos=749 (20.81%)
[TRAIN][DAILY-PROB] n=3625 pos=755 (20.83%)
[TRAIN][DAILY-PROB] n=3650 pos=763 (20.90%)
[TRAIN][DAILY-PROB] n=3675 pos=770 (20.95%)
[TRAIN][DAILY-PROB] n=3700 pos=778 (21.03%)
[TRAIN][DAILY-PROB] n=3725 pos=782 (20.99%)
[TRAIN][DAILY-PROB] n=3750 pos=785 (20.93%)
[TRAIN][DAILY-PROB] n=3775 pos=795 (21.06%)
[TRAIN][DAILY-PROB] n=3800 pos=801 (21.08%)
[TRAIN][DAILY-PROB] n=3825 pos=803 (20.99%)
[TRAIN][DAILY-PROB] n=3850 pos=805 (20.91%)
[TRAIN][DAILY-PROB] n=3875 pos=806 (20.80%)
[TRAIN][DAILY-PROB] n=3900 pos=815 (20.90%)
[TRAIN][DAILY-PROB] n=3925 pos=824 (20.99%)
[TRAIN][DAILY-PROB] n=3950 pos=834 (21.11%)
[TRAIN][DAILY-PROB] n=3975 pos=835 (21.01%)
[TRAIN][5M] asof=2010-02-05 feats=69 buy=NO sell=YES rows=592
[TRAIN][5M] asof=2010-02-10 feats=69 buy=NO sell=YES rows=667
[TRAIN][5M] asof=2010-02-16 feats=69 buy=NO sell=YES rows=729
[TRAIN][5M] asof=2010-02-22 feats=69 buy=NO sell=YES rows=847
[TRAIN][5M] asof=2010-03-01 feats=69 buy=YES sell=YES rows=969
[TRAIN][5M] asof=2010-03-08 feats=69 buy=YES sell=YES rows=1122
[TRAIN][5M] asof=2010-03-15 feats=69 buy=YES sell=YES rows=1242
[TRAIN][5M] asof=2010-03-22 feats=69 buy=YES sell=YES rows=1405
[TRAIN][5M] asof=2010-03-29 feats=69 buy=YES sell=YES rows=1538
[TRAIN][5M] asof=2010-04-05 feats=69 buy=YES sell=YES rows=1649
[TRAIN][5M] asof=2010-04-12 feats=69 buy=YES sell=YES rows=1755
[TRAIN][5M] asof=2010-04-19 feats=69 buy=YES sell=YES rows=1875
[TRAIN][5M] asof=2010-04-26 feats=69 buy=YES sell=YES rows=1973
[TRAIN][5M] asof=2010-05-03 feats=69 buy=YES sell=YES rows=2086
[TRAIN][5M] asof=2010-05-10 feats=69 buy=YES sell=YES rows=2232
[TRAIN][5M] asof=2010-05-17 feats=69 buy=YES sell=YES rows=2380
[TRAIN][5M] asof=2010-05-24 feats=69 buy=YES sell=YES rows=2548
[TRAIN][5M] asof=2010-06-01 feats=69 buy=YES sell=YES rows=2722
[TRAIN][5M] asof=2010-06-07 feats=69 buy=YES sell=YES rows=2852
[TRAIN][5M] asof=2010-06-14 feats=69 buy=YES sell=YES rows=2964
[TRAIN][5M] asof=2010-06-21 feats=69 buy=YES sell=YES rows=3124
[TRAIN][5M] asof=2010-06-28 feats=69 buy=YES sell=YES rows=3328
[TRAIN][5M] asof=2010-07-06 feats=69 buy=YES sell=YES rows=3468
[TRAIN][5M] asof=2010-07-12 feats=69 buy=YES sell=YES rows=3554
[TRAIN][5M] asof=2010-07-19 feats=69 buy=YES sell=YES rows=3637
[TRAIN][5M] asof=2010-07-26 feats=69 buy=YES sell=YES rows=3813
[TRAIN][5M] asof=2010-08-02 feats=69 buy=YES sell=YES rows=3991
[TRAIN][5M] asof=2010-08-09 feats=69 buy=YES sell=YES rows=4096
[TRAIN][5M] asof=2010-08-16 feats=69 buy=YES sell=YES rows=4282
[TRAIN][5M] asof=2010-08-23 feats=69 buy=YES sell=YES rows=4395
[TRAIN][5M] asof=2010-08-30 feats=69 buy=YES sell=YES rows=4568
[TRAIN][5M] asof=2010-09-07 feats=69 buy=YES sell=YES rows=4684
[TRAIN][5M] asof=2010-09-13 feats=69 buy=YES sell=YES rows=4784
[TRAIN][5M] asof=2010-09-20 feats=69 buy=YES sell=YES rows=4979
[TRAIN][5M] asof=2010-09-27 feats=69 buy=YES sell=YES rows=5113
[TRAIN][5M] asof=2010-10-04 feats=69 buy=YES sell=YES rows=5274
[TRAIN][5M] asof=2010-10-11 feats=69 buy=YES sell=YES rows=5383
[TRAIN][5M] asof=2010-10-18 feats=69 buy=YES sell=YES rows=5522
[TRAIN][5M] asof=2010-10-25 feats=69 buy=YES sell=YES rows=5684
[TRAIN][5M] asof=2010-11-01 feats=69 buy=YES sell=YES rows=5864
[TRAIN][5M] asof=2010-11-08 feats=69 buy=YES sell=YES rows=6010
[TRAIN][5M] asof=2010-11-15 feats=69 buy=YES sell=YES rows=6197
[TRAIN][5M] asof=2010-11-22 feats=69 buy=YES sell=YES rows=6388
[TRAIN][5M] asof=2010-11-29 feats=69 buy=YES sell=YES rows=6495
[TRAIN][5M] asof=2010-12-06 feats=69 buy=YES sell=YES rows=6662
[TRAIN][5M] asof=2010-12-13 feats=69 buy=YES sell=YES rows=6806
[TRAIN][5M] asof=2010-12-20 feats=69 buy=YES sell=YES rows=6945
[TRAIN][5M] asof=2010-12-27 feats=69 buy=YES sell=YES rows=6987
[TRAIN][5M] asof=2011-01-03 feats=69 buy=YES sell=YES rows=7109
[TRAIN][5M] asof=2011-01-10 feats=69 buy=YES sell=YES rows=7283
[TRAIN][5M] asof=2011-01-18 feats=69 buy=YES sell=YES rows=7395
[TRAIN][5M] asof=2011-01-24 feats=69 buy=YES sell=YES rows=7503
[TRAIN][5M] asof=2011-01-31 feats=69 buy=YES sell=YES rows=7672
[TRAIN][5M] asof=2011-02-07 feats=69 buy=YES sell=YES rows=7788
[TRAIN][5M] asof=2011-02-14 feats=69 buy=YES sell=YES rows=7915
[TRAIN][5M] asof=2011-02-22 feats=69 buy=YES sell=YES rows=8087
[TRAIN][5M] asof=2011-02-28 feats=69 buy=YES sell=YES rows=8225
[TRAIN][5M] asof=2011-03-07 feats=69 buy=YES sell=YES rows=8404
[TRAIN][5M] asof=2011-03-14 feats=69 buy=YES sell=YES rows=8581
[TRAIN][5M] asof=2011-03-21 feats=69 buy=YES sell=YES rows=8813
[TRAIN][5M] asof=2011-03-28 feats=69 buy=YES sell=YES rows=8906
[TRAIN][5M] asof=2011-04-04 feats=69 buy=YES sell=YES rows=9022
[TRAIN][5M] asof=2011-04-11 feats=69 buy=YES sell=YES rows=9179
[TRAIN][5M] asof=2011-04-18 feats=69 buy=YES sell=YES rows=9363
[TRAIN][5M] asof=2011-04-25 feats=69 buy=YES sell=YES rows=9481
[TRAIN][5M] asof=2011-05-02 feats=69 buy=YES sell=YES rows=9589
[TRAIN][5M] asof=2011-05-09 feats=69 buy=YES sell=YES rows=9764
[TRAIN][5M] asof=2011-05-16 feats=69 buy=YES sell=YES rows=9911
[TRAIN][5M] asof=2011-05-23 feats=69 buy=YES sell=YES rows=10062
[TRAIN][5M] asof=2011-05-31 feats=69 buy=YES sell=YES rows=10211
[TRAIN][5M] asof=2011-06-06 feats=69 buy=YES sell=YES rows=10324
[TRAIN][5M] asof=2011-06-13 feats=69 buy=YES sell=YES rows=10460
[TRAIN][5M] asof=2011-06-20 feats=69 buy=YES sell=YES rows=10579
[TRAIN][5M] asof=2011-06-27 feats=69 buy=YES sell=YES rows=10695
[TRAIN][5M] asof=2011-07-05 feats=69 buy=YES sell=YES rows=10836
[TRAIN][5M] asof=2011-07-11 feats=69 buy=YES sell=YES rows=10957
[TRAIN][5M] asof=2011-07-18 feats=69 buy=YES sell=YES rows=11088
[TRAIN][5M] asof=2011-07-25 feats=69 buy=YES sell=YES rows=11260
[TRAIN][5M] asof=2011-08-01 feats=69 buy=YES sell=YES rows=11415
[TRAIN][5M] asof=2011-08-08 feats=69 buy=YES sell=YES rows=11598
[TRAIN][5M] asof=2011-08-15 feats=69 buy=YES sell=YES rows=11782
[TRAIN][5M] asof=2011-08-22 feats=69 buy=YES sell=YES rows=12033
[TRAIN][5M] asof=2011-08-29 feats=69 buy=YES sell=YES rows=12199
[TRAIN][5M] asof=2011-09-06 feats=69 buy=YES sell=YES rows=12402
[TRAIN][5M] asof=2011-09-12 feats=69 buy=YES sell=YES rows=12547
[TRAIN][5M] asof=2011-09-19 feats=69 buy=YES sell=YES rows=12739
[TRAIN][5M] asof=2011-09-26 feats=69 buy=YES sell=YES rows=12948
[TRAIN][5M] asof=2011-10-03 feats=69 buy=YES sell=YES rows=13139
[TRAIN][5M] asof=2011-10-10 feats=69 buy=YES sell=YES rows=13265
[TRAIN][5M] asof=2011-10-17 feats=69 buy=YES sell=YES rows=13415
[TRAIN][5M] asof=2011-10-24 feats=69 buy=YES sell=YES rows=13569
[TRAIN][5M] asof=2011-10-31 feats=69 buy=YES sell=YES rows=13735
[TRAIN][5M] asof=2011-11-07 feats=69 buy=YES sell=YES rows=13974
[TRAIN][5M] asof=2011-11-14 feats=69 buy=YES sell=YES rows=14156
[TRAIN][5M] asof=2011-11-21 feats=69 buy=YES sell=YES rows=14376
[TRAIN][5M] asof=2011-11-28 feats=69 buy=YES sell=YES rows=14516
[TRAIN][5M] asof=2011-12-05 feats=69 buy=YES sell=YES rows=14668
[TRAIN][5M] asof=2011-12-12 feats=69 buy=YES sell=YES rows=14847
[TRAIN][5M] asof=2011-12-19 feats=69 buy=YES sell=YES rows=15060
[TRAIN][5M] asof=2011-12-27 feats=69 buy=YES sell=YES rows=15214
[TRAIN][5M] asof=2012-01-03 feats=69 buy=YES sell=YES rows=15317
[TRAIN][5M] asof=2012-01-09 feats=69 buy=YES sell=YES rows=15431
[TRAIN][5M] asof=2012-01-17 feats=69 buy=YES sell=YES rows=15570
[TRAIN][5M] asof=2012-01-23 feats=69 buy=YES sell=YES rows=15681
[TRAIN][5M] asof=2012-01-30 feats=69 buy=YES sell=YES rows=15866
[TRAIN][5M] asof=2012-02-06 feats=69 buy=YES sell=YES rows=16009
[TRAIN][5M] asof=2012-02-13 feats=69 buy=YES sell=YES rows=16175
[TRAIN][5M] asof=2012-02-21 feats=69 buy=YES sell=YES rows=16363
[TRAIN][5M] asof=2012-02-27 feats=69 buy=YES sell=YES rows=16499
[TRAIN][5M] asof=2012-03-05 feats=69 buy=YES sell=YES rows=16647
[TRAIN][5M] asof=2012-03-12 feats=69 buy=YES sell=YES rows=16795
[TRAIN][5M] asof=2012-03-19 feats=69 buy=YES sell=YES rows=16905
[TRAIN][5M] asof=2012-03-26 feats=69 buy=YES sell=YES rows=17093
[TRAIN][5M] asof=2012-04-02 feats=69 buy=YES sell=YES rows=17210
[TRAIN][5M] asof=2012-04-09 feats=69 buy=YES sell=YES rows=17310
[TRAIN][5M] asof=2012-04-16 feats=69 buy=YES sell=YES rows=17453
[TRAIN][5M] asof=2012-04-23 feats=69 buy=YES sell=YES rows=17594
[TRAIN][5M] asof=2012-04-30 feats=69 buy=YES sell=YES rows=17762
[TRAIN][5M] asof=2012-05-07 feats=69 buy=YES sell=YES rows=17932
[TRAIN][5M] asof=2012-05-14 feats=69 buy=YES sell=YES rows=18132
[TRAIN][5M] asof=2012-05-21 feats=69 buy=YES sell=YES rows=18279
[TRAIN][5M] asof=2012-05-29 feats=69 buy=YES sell=YES rows=18449
[TRAIN][5M] asof=2012-06-04 feats=69 buy=YES sell=YES rows=18533
[TRAIN][5M] asof=2012-06-11 feats=69 buy=YES sell=YES rows=18705
[TRAIN][5M] asof=2012-06-18 feats=69 buy=YES sell=YES rows=18835
[TRAIN][5M] asof=2012-06-25 feats=69 buy=YES sell=YES rows=18954
[TRAIN][5M] asof=2012-07-02 feats=69 buy=YES sell=YES rows=19070
[TRAIN][5M] asof=2012-07-09 feats=69 buy=YES sell=YES rows=19167
[TRAIN][5M] asof=2012-07-16 feats=69 buy=YES sell=YES rows=19277
[TRAIN][5M] asof=2012-07-23 feats=69 buy=YES sell=YES rows=19415
[TRAIN][5M] asof=2012-07-30 feats=69 buy=YES sell=YES rows=19534
[TRAIN][5M] asof=2012-08-06 feats=69 buy=YES sell=YES rows=19696
[TRAIN][5M] asof=2012-08-13 feats=69 buy=YES sell=YES rows=19815
[TRAIN][5M] asof=2012-08-20 feats=69 buy=YES sell=YES rows=19962
[TRAIN][5M] asof=2012-08-27 feats=69 buy=YES sell=YES rows=20145
[TRAIN][5M] asof=2012-09-04 feats=69 buy=YES sell=YES rows=20285
[TRAIN][5M] asof=2012-09-10 feats=69 buy=YES sell=YES rows=20408
[TRAIN][5M] asof=2012-09-17 feats=69 buy=YES sell=YES rows=20564
[TRAIN][5M] asof=2012-09-24 feats=69 buy=YES sell=YES rows=20679
[TRAIN][5M] asof=2012-10-01 feats=69 buy=YES sell=YES rows=20821
[TRAIN][5M] asof=2012-10-08 feats=69 buy=YES sell=YES rows=20992
[TRAIN][5M] asof=2012-10-15 feats=69 buy=YES sell=YES rows=21165
[TRAIN][5M] asof=2012-10-22 feats=69 buy=YES sell=YES rows=21266
[TRAIN][5M] asof=2012-10-31 feats=69 buy=YES sell=YES rows=21413
[TRAIN][5M] asof=2012-11-05 feats=69 buy=YES sell=YES rows=21502
[TRAIN][5M] asof=2012-11-12 feats=69 buy=YES sell=YES rows=21667
[TRAIN][5M] asof=2012-11-19 feats=69 buy=YES sell=YES rows=21793
[TRAIN][5M] asof=2012-11-26 feats=69 buy=YES sell=YES rows=21908
[TRAIN][5M] asof=2012-12-03 feats=69 buy=YES sell=YES rows=22041
[TRAIN][5M] asof=2012-12-10 feats=69 buy=YES sell=YES rows=22184
[TRAIN][5M] asof=2012-12-17 feats=69 buy=YES sell=YES rows=22306
[TRAIN][5M] asof=2012-12-24 feats=69 buy=YES sell=YES rows=22410
[TRAIN][5M] asof=2012-12-31 feats=69 buy=YES sell=YES rows=22485
[TRAIN][5M] asof=2013-01-07 feats=69 buy=YES sell=YES rows=22568
[TRAIN][5M] asof=2013-01-14 feats=69 buy=YES sell=YES rows=22680
[TRAIN][5M] asof=2013-01-22 feats=69 buy=YES sell=YES rows=22787
[TRAIN][5M] asof=2013-01-28 feats=69 buy=YES sell=YES rows=22937
[TRAIN][5M] asof=2013-02-04 feats=69 buy=YES sell=YES rows=23101
[TRAIN][5M] asof=2013-02-11 feats=69 buy=YES sell=YES rows=23253
[TRAIN][5M] asof=2013-02-19 feats=69 buy=YES sell=YES rows=23410
[TRAIN][5M] asof=2013-02-25 feats=69 buy=YES sell=YES rows=23548
[TRAIN][5M] asof=2013-03-04 feats=69 buy=YES sell=YES rows=23691
[TRAIN][5M] asof=2013-03-11 feats=69 buy=YES sell=YES rows=23848
[TRAIN][5M] asof=2013-03-18 feats=69 buy=YES sell=YES rows=23972
[TRAIN][5M] asof=2013-03-25 feats=69 buy=YES sell=YES rows=24088
[TRAIN][5M] asof=2013-04-01 feats=69 buy=YES sell=YES rows=24222
[TRAIN][5M] asof=2013-04-08 feats=69 buy=YES sell=YES rows=24299
[TRAIN][5M] asof=2013-04-15 feats=69 buy=YES sell=YES rows=24416
[TRAIN][5M] asof=2013-04-22 feats=69 buy=YES sell=YES rows=24540
[TRAIN][5M] asof=2013-04-29 feats=69 buy=YES sell=YES rows=24620
[TRAIN][5M] asof=2013-05-06 feats=69 buy=YES sell=YES rows=24756
[TRAIN][5M] asof=2013-05-13 feats=69 buy=YES sell=YES rows=24892
[TRAIN][5M] asof=2013-05-20 feats=69 buy=YES sell=YES rows=25020
[TRAIN][5M] asof=2013-05-28 feats=69 buy=YES sell=YES rows=25175
[TRAIN][5M] asof=2013-06-03 feats=69 buy=YES sell=YES rows=25336
[TRAIN][5M] asof=2013-06-10 feats=69 buy=YES sell=YES rows=25455
[TRAIN][5M] asof=2013-06-17 feats=69 buy=YES sell=YES rows=25592
[TRAIN][5M] asof=2013-06-24 feats=69 buy=YES sell=YES rows=25772
[TRAIN][5M] asof=2013-07-01 feats=69 buy=YES sell=YES rows=25946
[TRAIN][5M] asof=2013-07-08 feats=69 buy=YES sell=YES rows=26030
[TRAIN][5M] asof=2013-07-15 feats=69 buy=YES sell=YES rows=26170
[TRAIN][5M] asof=2013-07-22 feats=69 buy=YES sell=YES rows=26289
[TRAIN][5M] asof=2013-07-29 feats=69 buy=YES sell=YES rows=26458
[TRAIN][5M] asof=2013-08-05 feats=69 buy=YES sell=YES rows=26595
[TRAIN][5M] asof=2013-08-12 feats=69 buy=YES sell=YES rows=26740
[TRAIN][5M] asof=2013-08-19 feats=69 buy=YES sell=YES rows=26965
[TRAIN][5M] asof=2013-08-26 feats=69 buy=YES sell=YES rows=27091
[TRAIN][5M] asof=2013-09-03 feats=69 buy=YES sell=YES rows=27267
[TRAIN][5M] asof=2013-09-09 feats=69 buy=YES sell=YES rows=27401
[TRAIN][5M] asof=2013-09-16 feats=69 buy=YES sell=YES rows=27588
[TRAIN][5M] asof=2013-09-23 feats=69 buy=YES sell=YES rows=27703
[TRAIN][5M] asof=2013-09-30 feats=69 buy=YES sell=YES rows=27904
[TRAIN][5M] asof=2013-10-07 feats=69 buy=YES sell=YES rows=28040
[TRAIN][5M] asof=2013-10-14 feats=69 buy=YES sell=YES rows=28230
[TRAIN][5M] asof=2013-10-21 feats=69 buy=YES sell=YES rows=28392
[TRAIN][5M] asof=2013-10-28 feats=69 buy=YES sell=YES rows=28528
[TRAIN][5M] asof=2013-11-04 feats=69 buy=YES sell=YES rows=28730
[TRAIN][5M] asof=2013-11-11 feats=69 buy=YES sell=YES rows=28907
[TRAIN][5M] asof=2013-11-18 feats=69 buy=YES sell=YES rows=29043
[TRAIN][5M] asof=2013-11-25 feats=69 buy=YES sell=YES rows=29202
[TRAIN][5M] asof=2013-12-02 feats=69 buy=YES sell=YES rows=29301
[TRAIN][5M] asof=2013-12-09 feats=69 buy=YES sell=YES rows=29477
[TRAIN][5M] asof=2013-12-16 feats=69 buy=YES sell=YES rows=29657
[TRAIN][5M] asof=2013-12-23 feats=69 buy=YES sell=YES rows=29862
[TRAIN][5M] asof=2013-12-30 feats=69 buy=YES sell=YES rows=29988
[TRAIN][5M] asof=2014-01-06 feats=69 buy=YES sell=YES rows=30079

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
3517,2023-12-22,0.164723,0.2,0.3,FORCE_BUY,0.003787,0.003836,0.003049,0.003787,FREE,2.003848e+11,408.20,1.8,1.9
3518,2023-12-26,0.160003,0.2,0.3,FORCE_BUY,0.003149,-0.000098,-0.000098,0.003149,FORCE_BUY,2.010158e+11,410.89,1.9,-0.5
3519,2023-12-27,0.139857,0.2,0.3,FORCE_BUY,0.002019,0.000827,0.000827,0.002019,FORCE_BUY,2.014217e+11,411.90,1.9,-0.5
3520,2023-12-28,0.197356,0.2,0.3,FORCE_BUY,-0.002109,0.001019,0.000412,-0.002109,FREE,2.016269e+11,411.68,1.9,-0.5
3521,2023-12-29,0.204446,0.2,0.3,FREE,-0.006967,-0.004135,0.000170,-0.004135,FORCE_SELL,2.016611e+11,409.06,1.9,-0.5

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
3517,2023-12-22,1.797983e+07,0.000000e+00,1,1.9,-0.5,0.164723,FORCE_BUY,0.2,0.3
3518,2023-12-26,1.809831e+07,0.000000e+00,1,1.9,-0.5,0.160003,FORCE_BUY,0.2,0.3
3519,2023-12-27,1.814280e+07,0.000000e+00,1,1.9,-0.5,0.139857,FORCE_BUY,0.2,0.3
3520,2023-12-28,1.813311e+07,0.000000e+00,1,1.9,-0.5,0.197356,FORCE_BUY,0.2,0.3
3521,2023-12-29,1.806910e+07,1.806910e+07,0,1.9,-0.5,0.204446,FREE,0.2,0.3

In [12]:
snapshot_path = Path("checkpoints") / "QQQ_adaptive_reward_fresh_start_15days.joblib"
resume_res = run_adaptive_reward_from_snapshot(
    snapshot_path=str(snapshot_path),
    end_time="2026-12-31",
    sim_start="2024-01-01",
    initial_capital=100000.0,
    fee_pct=0.0,
    output_dir="output_adaptive_reward_resumed_fresh_QQQ_15days",
    # Optional. If omitted, the code saves next to the source snapshot as
    # checkpoints/SPY_adaptive_reward_fresh_start__continued.joblib
    save_snapshot_path=None,
    verbose=True,
)

print("continued snapshot:", resume_res["continued_snapshot_path"])

display(resume_res["daily_reward_df"].tail())
display(resume_res["daily_log_df"].tail())
display(resume_res["trades_df"].head())

[TRAIN][DAILY-PROB] n=4002 pos=843 (21.06%)
[TRAIN][DAILY-PROB] n=4027 pos=844 (20.96%)
[TRAIN][DAILY-PROB] n=4052 pos=850 (20.98%)
[TRAIN][DAILY-PROB] n=4077 pos=854 (20.95%)
[TRAIN][DAILY-PROB] n=4102 pos=858 (20.92%)
[TRAIN][DAILY-PROB] n=4127 pos=862 (20.89%)
[TRAIN][DAILY-PROB] n=4152 pos=873 (21.03%)
[TRAIN][DAILY-PROB] n=4177 pos=876 (20.97%)
[TRAIN][DAILY-PROB] n=4202 pos=881 (20.97%)
[TRAIN][DAILY-PROB] n=4227 pos=885 (20.94%)
[TRAIN][DAILY-PROB] n=4252 pos=890 (20.93%)
[TRAIN][DAILY-PROB] n=4277 pos=900 (21.04%)
[TRAIN][DAILY-PROB] n=4302 pos=909 (21.13%)
[TRAIN][DAILY-PROB] n=4327 pos=913 (21.10%)
[TRAIN][DAILY-PROB] n=4352 pos=915 (21.02%)
[TRAIN][DAILY-PROB] n=4377 pos=915 (20.90%)
[TRAIN][DAILY-PROB] n=4402 pos=926 (21.04%)
[TRAIN][DAILY-PROB] n=4427 pos=930 (21.01%)
[TRAIN][DAILY-PROB] n=4452 pos=937 (21.05%)
[TRAIN][DAILY-PROB] n=4477 pos=944 (21.09%)
[TRAIN][DAILY-PROB] n=4502 pos=947 (21.04%)
[TRAIN][DAILY-PROB] n=4527 pos=953 (21.05%)
[TRAIN][DAILY-PROB] n=4552 pos=957 (21.02%)
[TRAIN][5M] asof=2024-01-02 feats=69 buy=YES sell=YES rows=118486
[TRAIN][5M] asof=2024-01-08 feats=69 buy=YES sell=YES rows=118632
[TRAIN][5M] asof=2024-01-16 feats=69 buy=YES sell=YES rows=118916
[TRAIN][5M] asof=2024-01-22 feats=69 buy=YES sell=YES rows=119104
[TRAIN][5M] asof=2024-01-29 feats=69 buy=YES sell=YES rows=119259
[TRAIN][5M] asof=2024-02-05 feats=69 buy=YES sell=YES rows=119428
[TRAIN][5M] asof=2024-02-12 feats=69 buy=YES sell=YES rows=119583
[TRAIN][5M] asof=2024-02-20 feats=69 buy=YES sell=YES rows=119759
[TRAIN][5M] asof=2024-02-26 feats=69 buy=YES sell=YES rows=119917
[TRAIN][5M] asof=2024-03-04 feats=69 buy=YES sell=YES rows=120126
[TRAIN][5M] asof=2024-03-11 feats=69 buy=YES sell=YES rows=120347
[TRAIN][5M] asof=2024-03-18 feats=69 buy=YES sell=YES rows=120508
[TRAIN][5M] asof=2024-03-25 feats=69 buy=YES sell=YES rows=120701
[TRAIN][5M] asof=2024-04-01 feats=69 buy=YES sell=YES rows=120822
[TRAIN][5M] asof=2024-04-08 feats=69 buy=YES sell=YES rows=120948
[TRAIN][5M] asof=2024-04-15 feats=69 buy=YES sell=YES rows=121139
[TRAIN][5M] asof=2024-04-22 feats=69 buy=YES sell=YES rows=121274
[TRAIN][5M] asof=2024-04-29 feats=69 buy=YES sell=YES rows=121495
[TRAIN][5M] asof=2024-05-06 feats=69 buy=YES sell=YES rows=121657
[TRAIN][5M] asof=2024-05-13 feats=69 buy=YES sell=YES rows=121795
[TRAIN][5M] asof=2024-05-20 feats=69 buy=YES sell=YES rows=121939
[TRAIN][5M] asof=2024-05-28 feats=69 buy=YES sell=YES rows=122133
[TRAIN][5M] asof=2024-06-03 feats=69 buy=YES sell=YES rows=122307
[TRAIN][5M] asof=2024-06-10 feats=69 buy=YES sell=YES rows=122482
[TRAIN][5M] asof=2024-06-17 feats=69 buy=YES sell=YES rows=122660
[TRAIN][5M] asof=2024-06-24 feats=69 buy=YES sell=YES rows=122794
[TRAIN][5M] asof=2024-07-01 feats=69 buy=YES sell=YES rows=122942
[TRAIN][5M] asof=2024-07-08 feats=69 buy=YES sell=YES rows=123061
[TRAIN][5M] asof=2024-07-15 feats=69 buy=YES sell=YES rows=123242
[TRAIN][5M] asof=2024-07-22 feats=69 buy=YES sell=YES rows=123475
[TRAIN][5M] asof=2024-07-29 feats=69 buy=YES sell=YES rows=123732
[TRAIN][5M] asof=2024-08-05 feats=69 buy=YES sell=YES rows=123973
[TRAIN][5M] asof=2024-08-12 feats=69 buy=YES sell=YES rows=124126
[TRAIN][5M] asof=2024-08-19 feats=69 buy=YES sell=YES rows=124315
[TRAIN][5M] asof=2024-08-26 feats=69 buy=YES sell=YES rows=124517
[TRAIN][5M] asof=2024-09-03 feats=69 buy=YES sell=YES rows=124680
[TRAIN][5M] asof=2024-09-09 feats=69 buy=YES sell=YES rows=124843
[TRAIN][5M] asof=2024-09-16 feats=69 buy=YES sell=YES rows=125054
[TRAIN][5M] asof=2024-09-23 feats=69 buy=YES sell=YES rows=125256
[TRAIN][5M] asof=2024-09-30 feats=69 buy=YES sell=YES rows=125412
[TRAIN][5M] asof=2024-10-07 feats=69 buy=YES sell=YES rows=125555
[TRAIN][5M] asof=2024-10-14 feats=69 buy=YES sell=YES rows=125725
[TRAIN][5M] asof=2024-10-21 feats=69 buy=YES sell=YES rows=125933
[TRAIN][5M] asof=2024-10-28 feats=69 buy=YES sell=YES rows=126148
[TRAIN][5M] asof=2024-11-04 feats=69 buy=YES sell=YES rows=126341
[TRAIN][5M] asof=2024-11-11 feats=69 buy=YES sell=YES rows=126509
[TRAIN][5M] asof=2024-11-18 feats=69 buy=YES sell=YES rows=126689
[TRAIN][5M] asof=2024-11-25 feats=69 buy=YES sell=YES rows=126880
[TRAIN][5M] asof=2024-12-02 feats=69 buy=YES sell=YES rows=126997
[TRAIN][5M] asof=2024-12-09 feats=69 buy=YES sell=YES rows=127174
[TRAIN][5M] asof=2024-12-16 feats=69 buy=YES sell=YES rows=127367
[TRAIN][5M] asof=2024-12-23 feats=69 buy=YES sell=YES rows=127550
[TRAIN][5M] asof=2024-12-30 feats=69 buy=YES sell=YES rows=127719
[TRAIN][5M] asof=2025-01-06 feats=69 buy=YES sell=YES rows=127854
[TRAIN][5M] asof=2025-01-13 feats=69 buy=YES sell=YES rows=128035
[TRAIN][5M] asof=2025-01-21 feats=69 buy=YES sell=YES rows=128246
[TRAIN][5M] asof=2025-01-27 feats=69 buy=YES sell=YES rows=128393
[TRAIN][5M] asof=2025-02-03 feats=69 buy=YES sell=YES rows=128602
[TRAIN][5M] asof=2025-02-10 feats=69 buy=YES sell=YES rows=128782
[TRAIN][5M] asof=2025-02-18 feats=69 buy=YES sell=YES rows=128909
[TRAIN][5M] asof=2025-02-24 feats=69 buy=YES sell=YES rows=129079
[TRAIN][5M] asof=2025-03-03 feats=69 buy=YES sell=YES rows=129255
[TRAIN][5M] asof=2025-03-10 feats=69 buy=YES sell=YES rows=129464
[TRAIN][5M] asof=2025-03-17 feats=69 buy=YES sell=YES rows=129648
[TRAIN][5M] asof=2025-03-24 feats=69 buy=YES sell=YES rows=129846
[TRAIN][5M] asof=2025-03-31 feats=69 buy=YES sell=YES rows=130063
[TRAIN][5M] asof=2025-04-07 feats=69 buy=YES sell=YES rows=130261
[TRAIN][5M] asof=2025-04-14 feats=69 buy=YES sell=YES rows=130456
[TRAIN][5M] asof=2025-04-21 feats=69 buy=YES sell=YES rows=130588
[TRAIN][5M] asof=2025-04-28 feats=69 buy=YES sell=YES rows=130839
[TRAIN][5M] asof=2025-05-05 feats=69 buy=YES sell=YES rows=131075
[TRAIN][5M] asof=2025-05-12 feats=69 buy=YES sell=YES rows=131229
[TRAIN][5M] asof=2025-05-19 feats=69 buy=YES sell=YES rows=131410
[TRAIN][5M] asof=2025-05-27 feats=69 buy=YES sell=YES rows=131601
[TRAIN][5M] asof=2025-06-02 feats=69 buy=YES sell=YES rows=131724
[TRAIN][5M] asof=2025-06-09 feats=69 buy=YES sell=YES rows=131885
[TRAIN][5M] asof=2025-06-16 feats=69 buy=YES sell=YES rows=132004
[TRAIN][5M] asof=2025-06-23 feats=69 buy=YES sell=YES rows=132146
[TRAIN][5M] asof=2025-06-30 feats=69 buy=YES sell=YES rows=132293
[TRAIN][5M] asof=2025-07-07 feats=69 buy=YES sell=YES rows=132451
[TRAIN][5M] asof=2025-07-14 feats=69 buy=YES sell=YES rows=132617
[TRAIN][5M] asof=2025-07-21 feats=69 buy=YES sell=YES rows=132829
[TRAIN][5M] asof=2025-07-28 feats=69 buy=YES sell=YES rows=133039
[TRAIN][5M] asof=2025-08-04 feats=69 buy=YES sell=YES rows=133227
[TRAIN][5M] asof=2025-08-11 feats=69 buy=YES sell=YES rows=133401
[TRAIN][5M] asof=2025-08-18 feats=69 buy=YES sell=YES rows=133555
[TRAIN][5M] asof=2025-08-25 feats=69 buy=YES sell=YES rows=133740
[TRAIN][5M] asof=2025-09-02 feats=69 buy=YES sell=YES rows=133897
[TRAIN][5M] asof=2025-09-08 feats=69 buy=YES sell=YES rows=134035
[TRAIN][5M] asof=2025-09-15 feats=69 buy=YES sell=YES rows=134187
[TRAIN][5M] asof=2025-09-22 feats=69 buy=YES sell=YES rows=134414
[TRAIN][5M] asof=2025-09-29 feats=69 buy=YES sell=YES rows=134604
[TRAIN][5M] asof=2025-10-06 feats=69 buy=YES sell=YES rows=134830
[TRAIN][5M] asof=2025-10-13 feats=69 buy=YES sell=YES rows=135026
[TRAIN][5M] asof=2025-10-20 feats=69 buy=YES sell=YES rows=135242
[TRAIN][5M] asof=2025-10-27 feats=69 buy=YES sell=YES rows=135444
[TRAIN][5M] asof=2025-11-03 feats=69 buy=YES sell=YES rows=135659
[TRAIN][5M] asof=2025-11-10 feats=69 buy=YES sell=YES rows=135906
[TRAIN][5M] asof=2025-11-17 feats=69 buy=YES sell=YES rows=136114
[TRAIN][5M] asof=2025-11-24 feats=69 buy=YES sell=YES rows=136347
[TRAIN][5M] asof=2025-12-01 feats=69 buy=YES sell=YES rows=136464
[TRAIN][5M] asof=2025-12-08 feats=69 buy=YES sell=YES rows=136656
[TRAIN][5M] asof=2025-12-15 feats=69 buy=YES sell=YES rows=136865
[TRAIN][5M] asof=2025-12-22 feats=69 buy=YES sell=YES rows=137055
[TRAIN][5M] asof=2025-12-29 feats=69 buy=YES sell=YES rows=137169
[TRAIN][5M] asof=2026-01-05 feats=69 buy=YES sell=YES rows=137284
[TRAIN][5M] asof=2026-01-12 feats=69 buy=YES sell=YES rows=137506
[TRAIN][5M] asof=2026-01-20 feats=69 buy=YES sell=YES rows=137670
[TRAIN][5M] asof=2026-01-26 feats=69 buy=YES sell=YES rows=137856
[TRAIN][5M] asof=2026-02-02 feats=69 buy=YES sell=YES rows=138083
[TRAIN][5M] asof=2026-02-09 feats=69 buy=YES sell=YES rows=138314
[TRAIN][5M] asof=2026-02-17 feats=69 buy=YES sell=YES rows=138518
[TRAIN][5M] asof=2026-02-23 feats=69 buy=YES sell=YES rows=138658
[TRAIN][5M] asof=2026-03-02 feats=69 buy=YES sell=YES rows=138865
[TRAIN][5M] asof=2026-03-09 feats=69 buy=YES sell=YES rows=139058
[TRAIN][5M] asof=2026-03-16 feats=69 buy=YES sell=YES rows=139278
[TRAIN][5M] asof=2026-03-23 feats=69 buy=YES sell=YES rows=139492
[TRAIN][5M] asof=2026-03-30 feats=69 buy=YES sell=YES rows=139687
[TRAIN][5M] asof=2026-04-06 feats=69 buy=YES sell=YES rows=139795
[TRAIN][5M] asof=2026-04-13 feats=69 buy=YES sell=YES rows=139991
[TRAIN][5M] asof=2026-04-20 feats=69 buy=YES sell=YES rows=140168
[SAVED] output_adaptive_reward_resumed_fresh_QQQ_15days\trades.csv
[SAVED] output_adaptive_reward_resumed_fresh_QQQ_15days\daily_log.csv
[SAVED] output_adaptive_reward_resumed_fresh_QQQ_15days\daily_reward_log.csv
[SAVED] output_adaptive_reward_resumed_fresh_QQQ_15days\equity_vs_buyhold.png
[SAVED] output_adaptive_reward_resumed_fresh_QQQ_15days\price_with_trades.png
[SAVED] output_adaptive_reward_resumed_fresh_QQQ_15days\p_day.png
[CHECKPOINT] saved continued snapshot -> checkpoints\QQQ_adaptive_reward_fresh_start_15days__continued.joblib
continued snapshot: checkpoints\QQQ_adaptive_reward_fresh_start_15days__continued.joblib

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
4094,2026-04-15,0.195553,0.2,0.3,FORCE_BUY,0.010239,0.001994,0.000000,0.010239,FORCE_BUY,1.422341e+06,638.3600,0.85,2.50
4095,2026-04-16,0.180557,0.2,0.3,FORCE_BUY,0.001439,0.004868,0.000094,0.001439,FREE,1.429265e+06,640.2400,0.85,2.50
4096,2026-04-17,0.189899,0.2,0.3,FORCE_BUY,0.013857,0.005735,0.002843,0.013857,FORCE_BUY,1.449070e+06,648.9700,0.85,2.50
4097,2026-04-20,0.150277,0.2,0.3,FORCE_BUY,0.005571,0.004654,0.002343,0.005571,FORCE_BUY,1.457143e+06,647.9701,0.85,2.50
4098,2026-04-21,0.181344,0.2,0.3,FORCE_BUY,-0.001865,0.002293,-0.000231,-0.001865,FREE,1.460485e+06,647.4900,-0.50,2.25

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
572,2026-04-15,295368.607460,0.0,1,0.85,2.50,0.195553,FORCE_BUY,0.2,0.3
573,2026-04-16,296238.481797,0.0,1,0.85,2.50,0.180557,FORCE_BUY,0.2,0.3
574,2026-04-17,300277.845077,0.0,1,0.85,2.50,0.189899,FORCE_BUY,0.2,0.3
575,2026-04-20,299815.192231,0.0,1,-0.50,2.25,0.150277,FORCE_BUY,0.2,0.3
576,2026-04-21,299593.050386,0.0,1,-0.50,2.25,0.181344,FORCE_BUY,0.2,0.3

,side,seen_idx,exec_px,qty,fee,reason,ts,pred,th,gate,pnl,entry_px,entry_idx
0,buy,581988,421.2401,237.394303,0.0,5m BUY signal,2024-01-22 13:25:00,1.132745,0.2,FREE,NaN,NaN,NaN
1,sell,581995,422.2700,237.394303,0.0,5m SELL signal,2024-01-22 14:00:00,1.855192,-0.5,FREE,244.492393,421.2401,581988.0
2,buy,581999,421.5700,237.788487,0.0,5m BUY signal,2024-01-22 14:20:00,1.110677,0.2,FREE,NaN,NaN,NaN
3,sell,582009,422.0600,237.788487,0.0,5m SELL signal,2024-01-22 15:10:00,1.354036,-0.5,FREE,116.516359,421.5700,581999.0
4,buy,582018,421.7200,237.980197,0.0,5m BUY signal,2024-01-22 15:55:00,0.827127,0.2,FREE,NaN,NaN,NaN

In [13]:
from pathlib import Path
import pandas as pd

from adaptive_reward_checkpoint_fresh import (
    build_adaptive_reward_snapshot,
    run_adaptive_reward_from_snapshot,
)
from adaptive_trade_extensions import RollingThresholdConfig, make_threshold_grid

snapshot_path = Path("checkpoints") / "SPY_adaptive_reward_fresh_start_90days.joblib"

common_kwargs = dict(
    daily_csv_path="DataAPI/data/SPY_DAY.csv",
    k5m_csv_path="DataAPI/data/SPY_5M.csv",
    code="SPY",
    daily_chan_start="2008-01-01",
    accumulation_start="2010-01-01",
    N_confirm=5,
    min_labeled_days_to_train=200,
    retrain_every_new_labels=25,
    dp_lookback=5,
    lookahead_days_5m=2.0,
    retrain_every_days_5m=5,
    min_samples_total_5m=300,
    threshold_window_days=2.0,
    threshold_ret_grid=None,
    threshold_min_open_signals=10,
    initial_capital=100000.0,
    fee_pct=0.0,
    daily_chan_max_klines=500,
    five_chan_max_klines=500,
    macro_files={
        "vix_": "VIX.csv",
    },
    static_buy_level=0.20,
    static_sell_level=0.30,
    daily_threshold_config=RollingThresholdConfig(
        lookback_days=90,
        buy_grid=make_threshold_grid(0.05, 0.35, 0.005),
        sell_grid=make_threshold_grid(0.15, 0.60, 0.005),
        min_gap=0.02,
        min_obs=60,
        switch_penalty=0.0,
    ),
    verbose=True,
)

In [14]:
snapshot_res = build_adaptive_reward_snapshot(
    snapshot_path=str(snapshot_path),
    snapshot_end_time="2023-12-31",
    output_dir="output_adaptive_reward_snapshot_build_SPY_90days",
    **common_kwargs,
)

print(snapshot_res["snapshot_path"])
display(snapshot_res["daily_reward_df"].tail())
display(snapshot_res["daily_log_df"].tail())

[TRAIN][DAILY-PROB] n=200 pos=43 (21.50%)
[TRAIN][DAILY-PROB] n=225 pos=49 (21.78%)
[TRAIN][DAILY-PROB] n=250 pos=57 (22.80%)
[TRAIN][DAILY-PROB] n=275 pos=66 (24.00%)
[TRAIN][DAILY-PROB] n=300 pos=74 (24.67%)
[TRAIN][DAILY-PROB] n=325 pos=78 (24.00%)
[TRAIN][DAILY-PROB] n=350 pos=85 (24.29%)
[TRAIN][DAILY-PROB] n=375 pos=94 (25.07%)
[TRAIN][DAILY-PROB] n=400 pos=101 (25.25%)
[TRAIN][DAILY-PROB] n=425 pos=104 (24.47%)
[TRAIN][DAILY-PROB] n=450 pos=112 (24.89%)
[TRAIN][DAILY-PROB] n=475 pos=112 (23.58%)
[TRAIN][DAILY-PROB] n=500 pos=113 (22.60%)
[TRAIN][DAILY-PROB] n=525 pos=124 (23.62%)
[TRAIN][DAILY-PROB] n=550 pos=131 (23.82%)
[TRAIN][DAILY-PROB] n=575 pos=143 (24.87%)
[TRAIN][DAILY-PROB] n=600 pos=150 (25.00%)
[TRAIN][DAILY-PROB] n=625 pos=150 (24.00%)
[TRAIN][DAILY-PROB] n=650 pos=158 (24.31%)
[TRAIN][DAILY-PROB] n=675 pos=160 (23.70%)
[TRAIN][DAILY-PROB] n=700 pos=161 (23.00%)
[TRAIN][DAILY-PROB] n=725 pos=168 (23.17%)
[TRAIN][DAILY-PROB] n=750 pos=173 (23.07%)
[TRAIN][DAILY-PROB] n=775 pos=180 (23.23%)
[TRAIN][DAILY-PROB] n=800 pos=188 (23.50%)
[TRAIN][DAILY-PROB] n=825 pos=198 (24.00%)
[TRAIN][DAILY-PROB] n=850 pos=204 (24.00%)
[TRAIN][DAILY-PROB] n=875 pos=214 (24.46%)
[TRAIN][DAILY-PROB] n=900 pos=220 (24.44%)
[TRAIN][DAILY-PROB] n=925 pos=227 (24.54%)
[TRAIN][DAILY-PROB] n=950 pos=232 (24.42%)
[TRAIN][DAILY-PROB] n=975 pos=234 (24.00%)
[TRAIN][DAILY-PROB] n=1000 pos=240 (24.00%)
[TRAIN][DAILY-PROB] n=1025 pos=248 (24.20%)
[TRAIN][DAILY-PROB] n=1050 pos=257 (24.48%)
[TRAIN][DAILY-PROB] n=1075 pos=265 (24.65%)
[TRAIN][DAILY-PROB] n=1100 pos=267 (24.27%)
[TRAIN][DAILY-PROB] n=1125 pos=275 (24.44%)
[TRAIN][DAILY-PROB] n=1150 pos=278 (24.17%)
[TRAIN][DAILY-PROB] n=1175 pos=287 (24.43%)
[TRAIN][DAILY-PROB] n=1200 pos=289 (24.08%)
[TRAIN][DAILY-PROB] n=1225 pos=295 (24.08%)
[TRAIN][DAILY-PROB] n=1250 pos=298 (23.84%)
[TRAIN][DAILY-PROB] n=1275 pos=300 (23.53%)
[TRAIN][DAILY-PROB] n=1300 pos=308 (23.69%)
[TRAIN][DAILY-PROB] n=1325 pos=313 (23.62%)
[TRAIN][DAILY-PROB] n=1350 pos=321 (23.78%)
[TRAIN][DAILY-PROB] n=1375 pos=325 (23.64%)
[TRAIN][DAILY-PROB] n=1400 pos=330 (23.57%)
[TRAIN][DAILY-PROB] n=1425 pos=334 (23.44%)
[TRAIN][DAILY-PROB] n=1450 pos=342 (23.59%)
[TRAIN][DAILY-PROB] n=1475 pos=343 (23.25%)
[TRAIN][DAILY-PROB] n=1500 pos=348 (23.20%)
[TRAIN][DAILY-PROB] n=1525 pos=353 (23.15%)
[TRAIN][DAILY-PROB] n=1550 pos=356 (22.97%)
[TRAIN][DAILY-PROB] n=1575 pos=359 (22.79%)
[TRAIN][DAILY-PROB] n=1600 pos=362 (22.62%)
[TRAIN][DAILY-PROB] n=1625 pos=371 (22.83%)
[TRAIN][DAILY-PROB] n=1650 pos=375 (22.73%)
[TRAIN][DAILY-PROB] n=1675 pos=378 (22.57%)
[TRAIN][DAILY-PROB] n=1700 pos=387 (22.76%)
[TRAIN][DAILY-PROB] n=1725 pos=390 (22.61%)
[TRAIN][DAILY-PROB] n=1750 pos=398 (22.74%)
[TRAIN][DAILY-PROB] n=1775 pos=401 (22.59%)
[TRAIN][DAILY-PROB] n=1800 pos=406 (22.56%)
[TRAIN][DAILY-PROB] n=1825 pos=421 (23.07%)
[TRAIN][DAILY-PROB] n=1850 pos=427 (23.08%)
[TRAIN][DAILY-PROB] n=1875 pos=433 (23.09%)
[TRAIN][DAILY-PROB] n=1900 pos=444 (23.37%)
[TRAIN][DAILY-PROB] n=1925 pos=454 (23.58%)
[TRAIN][DAILY-PROB] n=1950 pos=459 (23.54%)
[TRAIN][DAILY-PROB] n=1975 pos=465 (23.54%)
[TRAIN][DAILY-PROB] n=2000 pos=467 (23.35%)
[TRAIN][DAILY-PROB] n=2025 pos=472 (23.31%)
[TRAIN][DAILY-PROB] n=2050 pos=479 (23.37%)
[TRAIN][DAILY-PROB] n=2075 pos=482 (23.23%)
[TRAIN][DAILY-PROB] n=2100 pos=484 (23.05%)
[TRAIN][DAILY-PROB] n=2125 pos=492 (23.15%)
[TRAIN][DAILY-PROB] n=2150 pos=500 (23.26%)
[TRAIN][DAILY-PROB] n=2175 pos=508 (23.36%)
[TRAIN][DAILY-PROB] n=2200 pos=514 (23.36%)
[TRAIN][DAILY-PROB] n=2225 pos=518 (23.28%)
[TRAIN][DAILY-PROB] n=2250 pos=526 (23.38%)
[TRAIN][DAILY-PROB] n=2275 pos=530 (23.30%)
[TRAIN][DAILY-PROB] n=2300 pos=532 (23.13%)
[TRAIN][DAILY-PROB] n=2325 pos=538 (23.14%)
[TRAIN][DAILY-PROB] n=2350 pos=543 (23.11%)
[TRAIN][DAILY-PROB] n=2375 pos=544 (22.91%)
[TRAIN][DAILY-PROB] n=2400 pos=544 (22.67%)
[TRAIN][DAILY-PROB] n=2425 pos=547 (22.56%)
[TRAIN][DAILY-PROB] n=2450 pos=549 (22.41%)
[TRAIN][DAILY-PROB] n=2475 pos=557 (22.51%)
[TRAIN][DAILY-PROB] n=2500 pos=567 (22.68%)
[TRAIN][DAILY-PROB] n=2525 pos=571 (22.61%)
[TRAIN][DAILY-PROB] n=2550 pos=574 (22.51%)
[TRAIN][DAILY-PROB] n=2575 pos=581 (22.56%)
[TRAIN][DAILY-PROB] n=2600 pos=586 (22.54%)
[TRAIN][DAILY-PROB] n=2625 pos=592 (22.55%)
[TRAIN][DAILY-PROB] n=2650 pos=603 (22.75%)
[TRAIN][DAILY-PROB] n=2675 pos=611 (22.84%)
[TRAIN][DAILY-PROB] n=2700 pos=615 (22.78%)
[TRAIN][DAILY-PROB] n=2725 pos=616 (22.61%)
[TRAIN][DAILY-PROB] n=2750 pos=623 (22.65%)
[TRAIN][DAILY-PROB] n=2775 pos=624 (22.49%)
[TRAIN][DAILY-PROB] n=2800 pos=634 (22.64%)
[TRAIN][DAILY-PROB] n=2825 pos=637 (22.55%)
[TRAIN][DAILY-PROB] n=2850 pos=646 (22.67%)
[TRAIN][DAILY-PROB] n=2875 pos=650 (22.61%)
[TRAIN][DAILY-PROB] n=2900 pos=655 (22.59%)
[TRAIN][DAILY-PROB] n=2925 pos=656 (22.43%)
[TRAIN][DAILY-PROB] n=2950 pos=656 (22.24%)
[TRAIN][DAILY-PROB] n=2975 pos=658 (22.12%)
[TRAIN][DAILY-PROB] n=3000 pos=675 (22.50%)
[TRAIN][DAILY-PROB] n=3025 pos=686 (22.68%)
[TRAIN][DAILY-PROB] n=3050 pos=691 (22.66%)
[TRAIN][DAILY-PROB] n=3075 pos=696 (22.63%)
[TRAIN][DAILY-PROB] n=3100 pos=697 (22.48%)
[TRAIN][DAILY-PROB] n=3125 pos=704 (22.53%)
[TRAIN][DAILY-PROB] n=3150 pos=712 (22.60%)
[TRAIN][DAILY-PROB] n=3175 pos=715 (22.52%)
[TRAIN][DAILY-PROB] n=3200 pos=716 (22.38%)
[TRAIN][DAILY-PROB] n=3225 pos=718 (22.26%)
[TRAIN][DAILY-PROB] n=3250 pos=727 (22.37%)
[TRAIN][DAILY-PROB] n=3275 pos=727 (22.20%)
[TRAIN][DAILY-PROB] n=3300 pos=730 (22.12%)
[TRAIN][DAILY-PROB] n=3325 pos=732 (22.02%)
[TRAIN][DAILY-PROB] n=3350 pos=733 (21.88%)
[TRAIN][DAILY-PROB] n=3375 pos=742 (21.99%)
[TRAIN][DAILY-PROB] n=3400 pos=747 (21.97%)
[TRAIN][DAILY-PROB] n=3425 pos=752 (21.96%)
[TRAIN][DAILY-PROB] n=3450 pos=754 (21.86%)
[TRAIN][DAILY-PROB] n=3475 pos=764 (21.99%)
[TRAIN][DAILY-PROB] n=3500 pos=773 (22.09%)
[TRAIN][DAILY-PROB] n=3525 pos=777 (22.04%)
[TRAIN][DAILY-PROB] n=3550 pos=781 (22.00%)
[TRAIN][DAILY-PROB] n=3575 pos=791 (22.13%)
[TRAIN][DAILY-PROB] n=3600 pos=795 (22.08%)
[TRAIN][DAILY-PROB] n=3625 pos=808 (22.29%)
[TRAIN][DAILY-PROB] n=3650 pos=812 (22.25%)
[TRAIN][DAILY-PROB] n=3675 pos=818 (22.26%)
[TRAIN][DAILY-PROB] n=3700 pos=827 (22.35%)
[TRAIN][DAILY-PROB] n=3725 pos=831 (22.31%)
[TRAIN][DAILY-PROB] n=3750 pos=838 (22.35%)
[TRAIN][DAILY-PROB] n=3775 pos=843 (22.33%)
[TRAIN][DAILY-PROB] n=3800 pos=850 (22.37%)
[TRAIN][DAILY-PROB] n=3825 pos=859 (22.46%)
[TRAIN][DAILY-PROB] n=3850 pos=864 (22.44%)
[TRAIN][DAILY-PROB] n=3875 pos=871 (22.48%)
[TRAIN][DAILY-PROB] n=3900 pos=881 (22.59%)
[TRAIN][DAILY-PROB] n=3925 pos=886 (22.57%)
[TRAIN][5M] asof=2010-02-03 feats=69 buy=NO sell=YES rows=587
[TRAIN][5M] asof=2010-02-08 feats=69 buy=NO sell=YES rows=677
[TRAIN][5M] asof=2010-02-16 feats=69 buy=YES sell=YES rows=804
[TRAIN][5M] asof=2010-02-22 feats=69 buy=YES sell=YES rows=923
[TRAIN][5M] asof=2010-03-01 feats=69 buy=YES sell=YES rows=1091
[TRAIN][5M] asof=2010-03-08 feats=69 buy=YES sell=YES rows=1223
[TRAIN][5M] asof=2010-03-15 feats=69 buy=YES sell=YES rows=1368
[TRAIN][5M] asof=2010-03-22 feats=69 buy=YES sell=YES rows=1487
[TRAIN][5M] asof=2010-03-29 feats=69 buy=YES sell=YES rows=1573
[TRAIN][5M] asof=2010-04-05 feats=69 buy=YES sell=YES rows=1709
[TRAIN][5M] asof=2010-04-12 feats=69 buy=YES sell=YES rows=1845
[TRAIN][5M] asof=2010-04-19 feats=69 buy=YES sell=YES rows=1983
[TRAIN][5M] asof=2010-04-26 feats=69 buy=YES sell=YES rows=2105
[TRAIN][5M] asof=2010-05-03 feats=69 buy=YES sell=YES rows=2250
[TRAIN][5M] asof=2010-05-10 feats=69 buy=YES sell=YES rows=2348
[TRAIN][5M] asof=2010-05-17 feats=69 buy=YES sell=YES rows=2506
[TRAIN][5M] asof=2010-05-24 feats=69 buy=YES sell=YES rows=2723
[TRAIN][5M] asof=2010-06-01 feats=69 buy=YES sell=YES rows=2888
[TRAIN][5M] asof=2010-06-07 feats=69 buy=YES sell=YES rows=3027
[TRAIN][5M] asof=2010-06-14 feats=69 buy=YES sell=YES rows=3162
[TRAIN][5M] asof=2010-06-21 feats=69 buy=YES sell=YES rows=3227
[TRAIN][5M] asof=2010-06-28 feats=69 buy=YES sell=YES rows=3382
[TRAIN][5M] asof=2010-07-06 feats=69 buy=YES sell=YES rows=3547
[TRAIN][5M] asof=2010-07-12 feats=69 buy=YES sell=YES rows=3680
[TRAIN][5M] asof=2010-07-19 feats=69 buy=YES sell=YES rows=3845
[TRAIN][5M] asof=2010-07-26 feats=69 buy=YES sell=YES rows=4037
[TRAIN][5M] asof=2010-08-02 feats=69 buy=YES sell=YES rows=4139
[TRAIN][5M] asof=2010-08-09 feats=69 buy=YES sell=YES rows=4281
[TRAIN][5M] asof=2010-08-16 feats=69 buy=YES sell=YES rows=4446
[TRAIN][5M] asof=2010-08-23 feats=69 buy=YES sell=YES rows=4558
[TRAIN][5M] asof=2010-08-30 feats=69 buy=YES sell=YES rows=4713
[TRAIN][5M] asof=2010-09-07 feats=69 buy=YES sell=YES rows=4816
[TRAIN][5M] asof=2010-09-13 feats=69 buy=YES sell=YES rows=5014
[TRAIN][5M] asof=2010-09-20 feats=69 buy=YES sell=YES rows=5202
[TRAIN][5M] asof=2010-09-27 feats=69 buy=YES sell=YES rows=5324
[TRAIN][5M] asof=2010-10-04 feats=69 buy=YES sell=YES rows=5563
[TRAIN][5M] asof=2010-10-11 feats=69 buy=YES sell=YES rows=5693
[TRAIN][5M] asof=2010-10-18 feats=69 buy=YES sell=YES rows=5853
[TRAIN][5M] asof=2010-10-25 feats=69 buy=YES sell=YES rows=5992
[TRAIN][5M] asof=2010-11-01 feats=69 buy=YES sell=YES rows=6165
[TRAIN][5M] asof=2010-11-08 feats=69 buy=YES sell=YES rows=6288
[TRAIN][5M] asof=2010-11-15 feats=69 buy=YES sell=YES rows=6473
[TRAIN][5M] asof=2010-11-22 feats=69 buy=YES sell=YES rows=6586
[TRAIN][5M] asof=2010-11-29 feats=69 buy=YES sell=YES rows=6730
[TRAIN][5M] asof=2010-12-06 feats=69 buy=YES sell=YES rows=6915
[TRAIN][5M] asof=2010-12-13 feats=69 buy=YES sell=YES rows=7069
[TRAIN][5M] asof=2010-12-20 feats=69 buy=YES sell=YES rows=7250
[TRAIN][5M] asof=2010-12-27 feats=69 buy=YES sell=YES rows=7367
[TRAIN][5M] asof=2011-01-03 feats=69 buy=YES sell=YES rows=7473
[TRAIN][5M] asof=2011-01-10 feats=69 buy=YES sell=YES rows=7584
[TRAIN][5M] asof=2011-01-18 feats=69 buy=YES sell=YES rows=7743
[TRAIN][5M] asof=2011-01-24 feats=69 buy=YES sell=YES rows=7867
[TRAIN][5M] asof=2011-01-31 feats=69 buy=YES sell=YES rows=8067
[TRAIN][5M] asof=2011-02-07 feats=69 buy=YES sell=YES rows=8176
[TRAIN][5M] asof=2011-02-14 feats=69 buy=YES sell=YES rows=8329
[TRAIN][5M] asof=2011-02-22 feats=69 buy=YES sell=YES rows=8484
[TRAIN][5M] asof=2011-02-28 feats=69 buy=YES sell=YES rows=8650
[TRAIN][5M] asof=2011-03-07 feats=69 buy=YES sell=YES rows=8802
[TRAIN][5M] asof=2011-03-14 feats=69 buy=YES sell=YES rows=8948
[TRAIN][5M] asof=2011-03-21 feats=69 buy=YES sell=YES rows=9048
[TRAIN][5M] asof=2011-03-28 feats=69 buy=YES sell=YES rows=9222
[TRAIN][5M] asof=2011-04-04 feats=69 buy=YES sell=YES rows=9346
[TRAIN][5M] asof=2011-04-11 feats=69 buy=YES sell=YES rows=9488
[TRAIN][5M] asof=2011-04-18 feats=69 buy=YES sell=YES rows=9681
[TRAIN][5M] asof=2011-04-25 feats=69 buy=YES sell=YES rows=9828
[TRAIN][5M] asof=2011-05-02 feats=69 buy=YES sell=YES rows=10015
[TRAIN][5M] asof=2011-05-09 feats=69 buy=YES sell=YES rows=10197
[TRAIN][5M] asof=2011-05-16 feats=69 buy=YES sell=YES rows=10400
[TRAIN][5M] asof=2011-05-23 feats=69 buy=YES sell=YES rows=10568
[TRAIN][5M] asof=2011-05-31 feats=69 buy=YES sell=YES rows=10737
[TRAIN][5M] asof=2011-06-06 feats=69 buy=YES sell=YES rows=10844
[TRAIN][5M] asof=2011-06-13 feats=69 buy=YES sell=YES rows=11012
[TRAIN][5M] asof=2011-06-20 feats=69 buy=YES sell=YES rows=11194
[TRAIN][5M] asof=2011-06-27 feats=69 buy=YES sell=YES rows=11349
[TRAIN][5M] asof=2011-07-05 feats=69 buy=YES sell=YES rows=11515
[TRAIN][5M] asof=2011-07-11 feats=69 buy=YES sell=YES rows=11657
[TRAIN][5M] asof=2011-07-18 feats=69 buy=YES sell=YES rows=11849
[TRAIN][5M] asof=2011-07-25 feats=69 buy=YES sell=YES rows=11985
[TRAIN][5M] asof=2011-08-01 feats=69 buy=YES sell=YES rows=12157
[TRAIN][5M] asof=2011-08-08 feats=69 buy=YES sell=YES rows=12381
[TRAIN][5M] asof=2011-08-15 feats=69 buy=YES sell=YES rows=12573
[TRAIN][5M] asof=2011-08-22 feats=69 buy=YES sell=YES rows=12739
[TRAIN][5M] asof=2011-08-29 feats=69 buy=YES sell=YES rows=12909
[TRAIN][5M] asof=2011-09-06 feats=69 buy=YES sell=YES rows=13075
[TRAIN][5M] asof=2011-09-12 feats=69 buy=YES sell=YES rows=13208
[TRAIN][5M] asof=2011-09-19 feats=69 buy=YES sell=YES rows=13373
[TRAIN][5M] asof=2011-09-26 feats=69 buy=YES sell=YES rows=13551
[TRAIN][5M] asof=2011-10-03 feats=69 buy=YES sell=YES rows=13714
[TRAIN][5M] asof=2011-10-10 feats=69 buy=YES sell=YES rows=13825
[TRAIN][5M] asof=2011-10-17 feats=69 buy=YES sell=YES rows=14011
[TRAIN][5M] asof=2011-10-24 feats=69 buy=YES sell=YES rows=14173
[TRAIN][5M] asof=2011-10-31 feats=69 buy=YES sell=YES rows=14332
[TRAIN][5M] asof=2011-11-07 feats=69 buy=YES sell=YES rows=14422
[TRAIN][5M] asof=2011-11-14 feats=69 buy=YES sell=YES rows=14583
[TRAIN][5M] asof=2011-11-21 feats=69 buy=YES sell=YES rows=14743
[TRAIN][5M] asof=2011-11-28 feats=69 buy=YES sell=YES rows=14889
[TRAIN][5M] asof=2011-12-05 feats=69 buy=YES sell=YES rows=15070
[TRAIN][5M] asof=2011-12-12 feats=69 buy=YES sell=YES rows=15237
[TRAIN][5M] asof=2011-12-19 feats=69 buy=YES sell=YES rows=15369
[TRAIN][5M] asof=2011-12-27 feats=69 buy=YES sell=YES rows=15494
[TRAIN][5M] asof=2012-01-03 feats=69 buy=YES sell=YES rows=15563
[TRAIN][5M] asof=2012-01-09 feats=69 buy=YES sell=YES rows=15619
[TRAIN][5M] asof=2012-01-17 feats=69 buy=YES sell=YES rows=15794
[TRAIN][5M] asof=2012-01-23 feats=69 buy=YES sell=YES rows=15961
[TRAIN][5M] asof=2012-01-30 feats=69 buy=YES sell=YES rows=16144
[TRAIN][5M] asof=2012-02-06 feats=69 buy=YES sell=YES rows=16247
[TRAIN][5M] asof=2012-02-13 feats=69 buy=YES sell=YES rows=16349
[TRAIN][5M] asof=2012-02-21 feats=69 buy=YES sell=YES rows=16540
[TRAIN][5M] asof=2012-02-27 feats=69 buy=YES sell=YES rows=16670
[TRAIN][5M] asof=2012-03-05 feats=69 buy=YES sell=YES rows=16775
[TRAIN][5M] asof=2012-03-12 feats=69 buy=YES sell=YES rows=16869
[TRAIN][5M] asof=2012-03-19 feats=69 buy=YES sell=YES rows=17054
[TRAIN][5M] asof=2012-03-26 feats=69 buy=YES sell=YES rows=17260
[TRAIN][5M] asof=2012-04-02 feats=69 buy=YES sell=YES rows=17426
[TRAIN][5M] asof=2012-04-09 feats=69 buy=YES sell=YES rows=17521
[TRAIN][5M] asof=2012-04-16 feats=69 buy=YES sell=YES rows=17625
[TRAIN][5M] asof=2012-04-23 feats=69 buy=YES sell=YES rows=17737
[TRAIN][5M] asof=2012-04-30 feats=69 buy=YES sell=YES rows=17868
[TRAIN][5M] asof=2012-05-07 feats=69 buy=YES sell=YES rows=18047
[TRAIN][5M] asof=2012-05-14 feats=69 buy=YES sell=YES rows=18264
[TRAIN][5M] asof=2012-05-21 feats=69 buy=YES sell=YES rows=18442
[TRAIN][5M] asof=2012-05-29 feats=69 buy=YES sell=YES rows=18559
[TRAIN][5M] asof=2012-06-04 feats=69 buy=YES sell=YES rows=18674
[TRAIN][5M] asof=2012-06-11 feats=69 buy=YES sell=YES rows=18830
[TRAIN][5M] asof=2012-06-18 feats=69 buy=YES sell=YES rows=18989
[TRAIN][5M] asof=2012-06-25 feats=69 buy=YES sell=YES rows=19153
[TRAIN][5M] asof=2012-07-02 feats=69 buy=YES sell=YES rows=19268
[TRAIN][5M] asof=2012-07-09 feats=69 buy=YES sell=YES rows=19395
[TRAIN][5M] asof=2012-07-16 feats=69 buy=YES sell=YES rows=19508
[TRAIN][5M] asof=2012-07-23 feats=69 buy=YES sell=YES rows=19652
[TRAIN][5M] asof=2012-07-30 feats=69 buy=YES sell=YES rows=19752
[TRAIN][5M] asof=2012-08-06 feats=69 buy=YES sell=YES rows=19891
[TRAIN][5M] asof=2012-08-13 feats=69 buy=YES sell=YES rows=20074
[TRAIN][5M] asof=2012-08-20 feats=69 buy=YES sell=YES rows=20211
[TRAIN][5M] asof=2012-08-27 feats=69 buy=YES sell=YES rows=20367
[TRAIN][5M] asof=2012-09-04 feats=69 buy=YES sell=YES rows=20487
[TRAIN][5M] asof=2012-09-10 feats=69 buy=YES sell=YES rows=20636
[TRAIN][5M] asof=2012-09-17 feats=69 buy=YES sell=YES rows=20807
[TRAIN][5M] asof=2012-09-24 feats=69 buy=YES sell=YES rows=20919
[TRAIN][5M] asof=2012-10-01 feats=69 buy=YES sell=YES rows=21030
[TRAIN][5M] asof=2012-10-08 feats=69 buy=YES sell=YES rows=21163
[TRAIN][5M] asof=2012-10-15 feats=69 buy=YES sell=YES rows=21282
[TRAIN][5M] asof=2012-10-22 feats=69 buy=YES sell=YES rows=21399
[TRAIN][5M] asof=2012-10-31 feats=69 buy=YES sell=YES rows=21552
[TRAIN][5M] asof=2012-11-05 feats=69 buy=YES sell=YES rows=21673
[TRAIN][5M] asof=2012-11-12 feats=69 buy=YES sell=YES rows=21880
[TRAIN][5M] asof=2012-11-19 feats=69 buy=YES sell=YES rows=22049
[TRAIN][5M] asof=2012-11-26 feats=69 buy=YES sell=YES rows=22156
[TRAIN][5M] asof=2012-12-03 feats=69 buy=YES sell=YES rows=22306
[TRAIN][5M] asof=2012-12-10 feats=69 buy=YES sell=YES rows=22416
[TRAIN][5M] asof=2012-12-17 feats=69 buy=YES sell=YES rows=22546
[TRAIN][5M] asof=2012-12-24 feats=69 buy=YES sell=YES rows=22656
[TRAIN][5M] asof=2012-12-31 feats=69 buy=YES sell=YES rows=22773
[TRAIN][5M] asof=2013-01-07 feats=69 buy=YES sell=YES rows=22871
[TRAIN][5M] asof=2013-01-14 feats=69 buy=YES sell=YES rows=23094
[TRAIN][5M] asof=2013-01-22 feats=69 buy=YES sell=YES rows=23225
[TRAIN][5M] asof=2013-01-28 feats=69 buy=YES sell=YES rows=23353
[TRAIN][5M] asof=2013-02-04 feats=69 buy=YES sell=YES rows=23555
[TRAIN][5M] asof=2013-02-11 feats=69 buy=YES sell=YES rows=23696
[TRAIN][5M] asof=2013-02-19 feats=69 buy=YES sell=YES rows=23856
[TRAIN][5M] asof=2013-02-25 feats=69 buy=YES sell=YES rows=23976
[TRAIN][5M] asof=2013-03-04 feats=69 buy=YES sell=YES rows=24065
[TRAIN][5M] asof=2013-03-11 feats=69 buy=YES sell=YES rows=24249
[TRAIN][5M] asof=2013-03-18 feats=69 buy=YES sell=YES rows=24446
[TRAIN][5M] asof=2013-03-25 feats=69 buy=YES sell=YES rows=24604
[TRAIN][5M] asof=2013-04-01 feats=69 buy=YES sell=YES rows=24774
[TRAIN][5M] asof=2013-04-08 feats=69 buy=YES sell=YES rows=24958
[TRAIN][5M] asof=2013-04-15 feats=69 buy=YES sell=YES rows=25124
[TRAIN][5M] asof=2013-04-22 feats=69 buy=YES sell=YES rows=25274
[TRAIN][5M] asof=2013-04-29 feats=69 buy=YES sell=YES rows=25454
[TRAIN][5M] asof=2013-05-06 feats=69 buy=YES sell=YES rows=25575
[TRAIN][5M] asof=2013-05-13 feats=69 buy=YES sell=YES rows=25735
[TRAIN][5M] asof=2013-05-20 feats=69 buy=YES sell=YES rows=25838
[TRAIN][5M] asof=2013-05-28 feats=69 buy=YES sell=YES rows=26012
[TRAIN][5M] asof=2013-06-03 feats=69 buy=YES sell=YES rows=26173
[TRAIN][5M] asof=2013-06-10 feats=69 buy=YES sell=YES rows=26342
[TRAIN][5M] asof=2013-06-17 feats=69 buy=YES sell=YES rows=26518
[TRAIN][5M] asof=2013-06-24 feats=69 buy=YES sell=YES rows=26721
[TRAIN][5M] asof=2013-07-01 feats=69 buy=YES sell=YES rows=26921
[TRAIN][5M] asof=2013-07-08 feats=69 buy=YES sell=YES rows=27027
[TRAIN][5M] asof=2013-07-15 feats=69 buy=YES sell=YES rows=27170
[TRAIN][5M] asof=2013-07-22 feats=69 buy=YES sell=YES rows=27305
[TRAIN][5M] asof=2013-07-29 feats=69 buy=YES sell=YES rows=27509
[TRAIN][5M] asof=2013-08-05 feats=69 buy=YES sell=YES rows=27675
[TRAIN][5M] asof=2013-08-12 feats=69 buy=YES sell=YES rows=27877
[TRAIN][5M] asof=2013-08-19 feats=69 buy=YES sell=YES rows=28091
[TRAIN][5M] asof=2013-08-26 feats=69 buy=YES sell=YES rows=28220
[TRAIN][5M] asof=2013-09-03 feats=69 buy=YES sell=YES rows=28372
[TRAIN][5M] asof=2013-09-09 feats=69 buy=YES sell=YES rows=28468
[TRAIN][5M] asof=2013-09-16 feats=69 buy=YES sell=YES rows=28604
[TRAIN][5M] asof=2013-09-23 feats=69 buy=YES sell=YES rows=28767
[TRAIN][5M] asof=2013-09-30 feats=69 buy=YES sell=YES rows=28933
[TRAIN][5M] asof=2013-10-07 feats=69 buy=YES sell=YES rows=29089
[TRAIN][5M] asof=2013-10-14 feats=69 buy=YES sell=YES rows=29228
[TRAIN][5M] asof=2013-10-21 feats=69 buy=YES sell=YES rows=29377
[TRAIN][5M] asof=2013-10-28 feats=69 buy=YES sell=YES rows=29506
[TRAIN][5M] asof=2013-11-04 feats=69 buy=YES sell=YES rows=29679
[TRAIN][5M] asof=2013-11-11 feats=69 buy=YES sell=YES rows=29779
[TRAIN][5M] asof=2013-11-18 feats=69 buy=YES sell=YES rows=29945
[TRAIN][5M] asof=2013-11-25 feats=69 buy=YES sell=YES rows=30112
[TRAIN][5M] asof=2013-12-02 feats=69 buy=YES sell=YES rows=30204
[TRAIN][5M] asof=2013-12-09 feats=69 buy=YES sell=YES rows=30363
[TRAIN][5M] asof=2013-12-16 feats=69 buy=YES sell=YES rows=30545
[TRAIN][5M] asof=2013-12-23 feats=69 buy=YES sell=YES rows=30626
[TRAIN][5M] asof=2013-12-30 feats=69 buy=YES sell=YES rows=30760
[TRAIN][5M] asof=2014-01-06 feats=69 buy=YES sell=YES rows=30918
[TRAIN][5M] asof=2014-01-13 feats=69 buy=YES sell=YES rows=31119

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
3517,2023-12-22,0.151024,0.165,0.190,FORCE_BUY,-0.003475,-0.002643,0.000000,-0.003475,FORCE_SELL,3.722095e+09,473.18,1.95,0.75
3518,2023-12-26,0.136806,0.165,0.225,FORCE_BUY,0.002487,0.002162,0.000190,0.002487,FORCE_BUY,3.731353e+09,475.59,1.55,-0.50
3519,2023-12-27,0.114499,0.165,0.225,FORCE_BUY,0.002649,0.004244,0.000105,0.002649,FREE,3.747190e+09,476.90,1.55,-0.50
3520,2023-12-28,0.139628,0.165,0.225,FORCE_BUY,0.000000,0.000189,-0.000210,0.000000,FREE,3.747897e+09,477.05,-0.50,1.40
3521,2023-12-29,0.154295,0.165,0.225,FORCE_BUY,-0.004881,-0.005516,0.000126,-0.004881,FORCE_SELL,3.748368e+09,475.07,1.80,1.40

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
3517,2023-12-22,1.459875e+06,0.0,1,1.55,-0.5,0.151024,FORCE_BUY,0.165,0.190
3518,2023-12-26,1.467310e+06,0.0,1,1.55,-0.5,0.136806,FORCE_BUY,0.165,0.225
3519,2023-12-27,1.471352e+06,0.0,1,-0.50,1.4,0.114499,FORCE_BUY,0.165,0.225
3520,2023-12-28,1.471814e+06,0.0,1,1.80,1.4,0.139628,FORCE_BUY,0.165,0.225
3521,2023-12-29,1.465706e+06,0.0,1,1.80,1.4,0.154295,FORCE_BUY,0.165,0.225

In [15]:
resume_res = run_adaptive_reward_from_snapshot(
    snapshot_path=str(snapshot_path),
    end_time="2026-12-31",
    sim_start="2024-01-01",
    initial_capital=100000.0,
    fee_pct=0.0,
    output_dir="output_adaptive_reward_resumed_fresh_SPY_90days",
    # Optional. If omitted, the code saves next to the source snapshot as
    # checkpoints/SPY_adaptive_reward_fresh_start__continued.joblib
    save_snapshot_path=None,
    verbose=True,
)

print("continued snapshot:", resume_res["continued_snapshot_path"])

display(resume_res["daily_reward_df"].tail())
display(resume_res["daily_log_df"].tail())
display(resume_res["trades_df"].head())

[TRAIN][DAILY-PROB] n=3969 pos=890 (22.42%)
[TRAIN][DAILY-PROB] n=3994 pos=891 (22.31%)
[TRAIN][DAILY-PROB] n=4019 pos=898 (22.34%)
[TRAIN][DAILY-PROB] n=4044 pos=901 (22.28%)
[TRAIN][DAILY-PROB] n=4069 pos=909 (22.34%)
[TRAIN][DAILY-PROB] n=4094 pos=913 (22.30%)
[TRAIN][DAILY-PROB] n=4119 pos=917 (22.26%)
[TRAIN][DAILY-PROB] n=4144 pos=920 (22.20%)
[TRAIN][DAILY-PROB] n=4169 pos=928 (22.26%)
[TRAIN][DAILY-PROB] n=4194 pos=933 (22.25%)
[TRAIN][DAILY-PROB] n=4219 pos=937 (22.21%)
[TRAIN][DAILY-PROB] n=4244 pos=947 (22.31%)
[TRAIN][DAILY-PROB] n=4269 pos=955 (22.37%)
[TRAIN][DAILY-PROB] n=4294 pos=959 (22.33%)
[TRAIN][DAILY-PROB] n=4319 pos=963 (22.30%)
[TRAIN][DAILY-PROB] n=4344 pos=963 (22.17%)
[TRAIN][DAILY-PROB] n=4369 pos=970 (22.20%)
[TRAIN][DAILY-PROB] n=4394 pos=980 (22.30%)
[TRAIN][DAILY-PROB] n=4419 pos=988 (22.36%)
[TRAIN][DAILY-PROB] n=4444 pos=998 (22.46%)
[TRAIN][DAILY-PROB] n=4469 pos=1006 (22.51%)
[TRAIN][DAILY-PROB] n=4494 pos=1015 (22.59%)
[TRAIN][DAILY-PROB] n=4519 pos=1022 (22.62%)
[TRAIN][5M] asof=2024-01-02 feats=69 buy=YES sell=YES rows=120691
[TRAIN][5M] asof=2024-01-08 feats=69 buy=YES sell=YES rows=120841
[TRAIN][5M] asof=2024-01-16 feats=69 buy=YES sell=YES rows=121012
[TRAIN][5M] asof=2024-01-22 feats=69 buy=YES sell=YES rows=121112
[TRAIN][5M] asof=2024-01-29 feats=69 buy=YES sell=YES rows=121401
[TRAIN][5M] asof=2024-02-05 feats=69 buy=YES sell=YES rows=121554
[TRAIN][5M] asof=2024-02-12 feats=69 buy=YES sell=YES rows=121700
[TRAIN][5M] asof=2024-02-20 feats=69 buy=YES sell=YES rows=121907
[TRAIN][5M] asof=2024-02-26 feats=69 buy=YES sell=YES rows=122029
[TRAIN][5M] asof=2024-03-04 feats=69 buy=YES sell=YES rows=122233
[TRAIN][5M] asof=2024-03-11 feats=69 buy=YES sell=YES rows=122446
[TRAIN][5M] asof=2024-03-18 feats=69 buy=YES sell=YES rows=122626
[TRAIN][5M] asof=2024-03-25 feats=69 buy=YES sell=YES rows=122774
[TRAIN][5M] asof=2024-04-01 feats=69 buy=YES sell=YES rows=122860
[TRAIN][5M] asof=2024-04-08 feats=69 buy=YES sell=YES rows=123007
[TRAIN][5M] asof=2024-04-15 feats=69 buy=YES sell=YES rows=123175
[TRAIN][5M] asof=2024-04-22 feats=69 buy=YES sell=YES rows=123303
[TRAIN][5M] asof=2024-04-29 feats=69 buy=YES sell=YES rows=123487
[TRAIN][5M] asof=2024-05-06 feats=69 buy=YES sell=YES rows=123670
[TRAIN][5M] asof=2024-05-13 feats=69 buy=YES sell=YES rows=123879
[TRAIN][5M] asof=2024-05-20 feats=69 buy=YES sell=YES rows=124030
[TRAIN][5M] asof=2024-05-28 feats=69 buy=YES sell=YES rows=124229
[TRAIN][5M] asof=2024-06-03 feats=69 buy=YES sell=YES rows=124373
[TRAIN][5M] asof=2024-06-10 feats=69 buy=YES sell=YES rows=124609
[TRAIN][5M] asof=2024-06-17 feats=69 buy=YES sell=YES rows=124819
[TRAIN][5M] asof=2024-06-24 feats=69 buy=YES sell=YES rows=124940
[TRAIN][5M] asof=2024-07-01 feats=69 buy=YES sell=YES rows=125142
[TRAIN][5M] asof=2024-07-08 feats=69 buy=YES sell=YES rows=125271
[TRAIN][5M] asof=2024-07-15 feats=69 buy=YES sell=YES rows=125449
[TRAIN][5M] asof=2024-07-22 feats=69 buy=YES sell=YES rows=125674
[TRAIN][5M] asof=2024-07-29 feats=69 buy=YES sell=YES rows=125894
[TRAIN][5M] asof=2024-08-05 feats=69 buy=YES sell=YES rows=126110
[TRAIN][5M] asof=2024-08-12 feats=69 buy=YES sell=YES rows=126322
[TRAIN][5M] asof=2024-08-19 feats=69 buy=YES sell=YES rows=126527
[TRAIN][5M] asof=2024-08-26 feats=69 buy=YES sell=YES rows=126711
[TRAIN][5M] asof=2024-09-03 feats=69 buy=YES sell=YES rows=126901
[TRAIN][5M] asof=2024-09-09 feats=69 buy=YES sell=YES rows=127034
[TRAIN][5M] asof=2024-09-16 feats=69 buy=YES sell=YES rows=127191
[TRAIN][5M] asof=2024-09-23 feats=69 buy=YES sell=YES rows=127384
[TRAIN][5M] asof=2024-09-30 feats=69 buy=YES sell=YES rows=127562
[TRAIN][5M] asof=2024-10-07 feats=69 buy=YES sell=YES rows=127730
[TRAIN][5M] asof=2024-10-14 feats=69 buy=YES sell=YES rows=127918
[TRAIN][5M] asof=2024-10-21 feats=69 buy=YES sell=YES rows=128112
[TRAIN][5M] asof=2024-10-28 feats=69 buy=YES sell=YES rows=128339
[TRAIN][5M] asof=2024-11-04 feats=69 buy=YES sell=YES rows=128491
[TRAIN][5M] asof=2024-11-11 feats=69 buy=YES sell=YES rows=128681
[TRAIN][5M] asof=2024-11-18 feats=69 buy=YES sell=YES rows=128868
[TRAIN][5M] asof=2024-11-25 feats=69 buy=YES sell=YES rows=129076
[TRAIN][5M] asof=2024-12-02 feats=69 buy=YES sell=YES rows=129186
[TRAIN][5M] asof=2024-12-09 feats=69 buy=YES sell=YES rows=129361
[TRAIN][5M] asof=2024-12-16 feats=69 buy=YES sell=YES rows=129499
[TRAIN][5M] asof=2024-12-23 feats=69 buy=YES sell=YES rows=129717
[TRAIN][5M] asof=2024-12-30 feats=69 buy=YES sell=YES rows=129827
[TRAIN][5M] asof=2025-01-06 feats=69 buy=YES sell=YES rows=129936
[TRAIN][5M] asof=2025-01-13 feats=69 buy=YES sell=YES rows=130098
[TRAIN][5M] asof=2025-01-21 feats=69 buy=YES sell=YES rows=130324
[TRAIN][5M] asof=2025-01-27 feats=69 buy=YES sell=YES rows=130475
[TRAIN][5M] asof=2025-02-03 feats=69 buy=YES sell=YES rows=130682
[TRAIN][5M] asof=2025-02-10 feats=69 buy=YES sell=YES rows=130876
[TRAIN][5M] asof=2025-02-18 feats=69 buy=YES sell=YES rows=131042
[TRAIN][5M] asof=2025-02-24 feats=69 buy=YES sell=YES rows=131155
[TRAIN][5M] asof=2025-03-03 feats=69 buy=YES sell=YES rows=131313
[TRAIN][5M] asof=2025-03-10 feats=69 buy=YES sell=YES rows=131520
[TRAIN][5M] asof=2025-03-17 feats=69 buy=YES sell=YES rows=131720
[TRAIN][5M] asof=2025-03-24 feats=69 buy=YES sell=YES rows=131905
[TRAIN][5M] asof=2025-03-31 feats=69 buy=YES sell=YES rows=132139
[TRAIN][5M] asof=2025-04-07 feats=69 buy=YES sell=YES rows=132333
[TRAIN][5M] asof=2025-04-14 feats=69 buy=YES sell=YES rows=132491
[TRAIN][5M] asof=2025-04-21 feats=69 buy=YES sell=YES rows=132608
[TRAIN][5M] asof=2025-04-28 feats=69 buy=YES sell=YES rows=132856
[TRAIN][5M] asof=2025-05-05 feats=69 buy=YES sell=YES rows=133061
[TRAIN][5M] asof=2025-05-12 feats=69 buy=YES sell=YES rows=133177
[TRAIN][5M] asof=2025-05-19 feats=69 buy=YES sell=YES rows=133348
[TRAIN][5M] asof=2025-05-27 feats=69 buy=YES sell=YES rows=133550
[TRAIN][5M] asof=2025-06-02 feats=69 buy=YES sell=YES rows=133707
[TRAIN][5M] asof=2025-06-09 feats=69 buy=YES sell=YES rows=133893
[TRAIN][5M] asof=2025-06-16 feats=69 buy=YES sell=YES rows=134055
[TRAIN][5M] asof=2025-06-23 feats=69 buy=YES sell=YES rows=134164
[TRAIN][5M] asof=2025-06-30 feats=69 buy=YES sell=YES rows=134302
[TRAIN][5M] asof=2025-07-07 feats=69 buy=YES sell=YES rows=134419
[TRAIN][5M] asof=2025-07-14 feats=69 buy=YES sell=YES rows=134615
[TRAIN][5M] asof=2025-07-21 feats=69 buy=YES sell=YES rows=134837
[TRAIN][5M] asof=2025-07-28 feats=69 buy=YES sell=YES rows=134988
[TRAIN][5M] asof=2025-08-04 feats=69 buy=YES sell=YES rows=135175
[TRAIN][5M] asof=2025-08-11 feats=69 buy=YES sell=YES rows=135358
[TRAIN][5M] asof=2025-08-18 feats=69 buy=YES sell=YES rows=135530
[TRAIN][5M] asof=2025-08-25 feats=69 buy=YES sell=YES rows=135768
[TRAIN][5M] asof=2025-09-02 feats=69 buy=YES sell=YES rows=135919
[TRAIN][5M] asof=2025-09-08 feats=69 buy=YES sell=YES rows=136086
[TRAIN][5M] asof=2025-09-15 feats=69 buy=YES sell=YES rows=136272
[TRAIN][5M] asof=2025-09-22 feats=69 buy=YES sell=YES rows=136450
[TRAIN][5M] asof=2025-09-29 feats=69 buy=YES sell=YES rows=136621
[TRAIN][5M] asof=2025-10-06 feats=69 buy=YES sell=YES rows=136813
[TRAIN][5M] asof=2025-10-13 feats=69 buy=YES sell=YES rows=136990
[TRAIN][5M] asof=2025-10-20 feats=69 buy=YES sell=YES rows=137160
[TRAIN][5M] asof=2025-10-27 feats=69 buy=YES sell=YES rows=137342
[TRAIN][5M] asof=2025-11-03 feats=69 buy=YES sell=YES rows=137487
[TRAIN][5M] asof=2025-11-10 feats=69 buy=YES sell=YES rows=137719
[TRAIN][5M] asof=2025-11-17 feats=69 buy=YES sell=YES rows=137929
[TRAIN][5M] asof=2025-11-24 feats=69 buy=YES sell=YES rows=138145
[TRAIN][5M] asof=2025-12-01 feats=69 buy=YES sell=YES rows=138259
[TRAIN][5M] asof=2025-12-08 feats=69 buy=YES sell=YES rows=138412
[TRAIN][5M] asof=2025-12-15 feats=69 buy=YES sell=YES rows=138611
[TRAIN][5M] asof=2025-12-22 feats=69 buy=YES sell=YES rows=138796
[TRAIN][5M] asof=2025-12-29 feats=69 buy=YES sell=YES rows=138947
[TRAIN][5M] asof=2026-01-05 feats=69 buy=YES sell=YES rows=139111
[TRAIN][5M] asof=2026-01-12 feats=69 buy=YES sell=YES rows=139349
[TRAIN][5M] asof=2026-01-20 feats=69 buy=YES sell=YES rows=139508
[TRAIN][5M] asof=2026-01-26 feats=69 buy=YES sell=YES rows=139679
[TRAIN][5M] asof=2026-02-02 feats=69 buy=YES sell=YES rows=139935
[TRAIN][5M] asof=2026-02-09 feats=69 buy=YES sell=YES rows=140177
[TRAIN][5M] asof=2026-02-17 feats=69 buy=YES sell=YES rows=140364
[TRAIN][5M] asof=2026-02-23 feats=69 buy=YES sell=YES rows=140486
[TRAIN][5M] asof=2026-03-02 feats=69 buy=YES sell=YES rows=140693
[TRAIN][5M] asof=2026-03-09 feats=69 buy=YES sell=YES rows=140907
[TRAIN][5M] asof=2026-03-16 feats=69 buy=YES sell=YES rows=141114
[TRAIN][5M] asof=2026-03-23 feats=69 buy=YES sell=YES rows=141320
[TRAIN][5M] asof=2026-03-30 feats=69 buy=YES sell=YES rows=141507
[TRAIN][5M] asof=2026-04-06 feats=69 buy=YES sell=YES rows=141585
[TRAIN][5M] asof=2026-04-13 feats=69 buy=YES sell=YES rows=141791
[TRAIN][5M] asof=2026-04-20 feats=69 buy=YES sell=YES rows=141987
[SAVED] output_adaptive_reward_resumed_fresh_SPY_90days\trades.csv
[SAVED] output_adaptive_reward_resumed_fresh_SPY_90days\daily_log.csv
[SAVED] output_adaptive_reward_resumed_fresh_SPY_90days\daily_reward_log.csv
[SAVED] output_adaptive_reward_resumed_fresh_SPY_90days\equity_vs_buyhold.png
[SAVED] output_adaptive_reward_resumed_fresh_SPY_90days\price_with_trades.png
[SAVED] output_adaptive_reward_resumed_fresh_SPY_90days\p_day.png
[CHECKPOINT] saved continued snapshot -> checkpoints\SPY_adaptive_reward_fresh_start_90days__continued.joblib
continued snapshot: checkpoints\SPY_adaptive_reward_fresh_start_90days__continued.joblib

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
4094,2026-04-15,0.125592,0.15,0.245,FORCE_BUY,0.008710,-0.000604,-0.000604,0.008710,FORCE_BUY,590909.363220,700.65,-0.50,2.00
4095,2026-04-16,0.119636,0.15,0.245,FORCE_BUY,0.001812,0.001528,-0.000257,0.001812,FORCE_BUY,591979.988644,702.22,-0.50,2.00
4096,2026-04-17,0.138922,0.15,0.245,FORCE_BUY,0.011427,0.001167,0.001167,0.011427,FORCE_BUY,598744.559610,710.75,0.85,2.45
4097,2026-04-20,0.138204,0.15,0.245,FORCE_BUY,0.004147,0.004147,0.004147,0.004147,FORCE_BUY,601227.464897,709.49,0.80,2.35
4098,2026-04-21,0.187617,0.15,0.245,FREE,-0.003720,-0.003720,-0.003720,-0.003720,FORCE_BUY,598990.780793,707.00,0.80,2.35

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
572,2026-04-15,220822.165281,0.0,1,-0.50,2.00,0.125592,FORCE_BUY,0.15,0.245
573,2026-04-16,221316.978382,0.0,1,0.85,2.45,0.119636,FORCE_BUY,0.15,0.245
574,2026-04-17,224005.357844,0.0,1,0.80,2.35,0.138922,FORCE_BUY,0.15,0.245
575,2026-04-20,223608.246692,0.0,1,0.80,2.35,0.138204,FORCE_BUY,0.15,0.245
576,2026-04-21,222823.479417,0.0,1,0.80,2.35,0.187617,FREE,0.15,0.245

,side,seen_idx,exec_px,qty,fee,reason,ts,pred,th,gate,pnl,entry_px,entry_idx
0,buy,644657,476.30,209.951711,0.0,5m BUY signal,2024-01-12 04:50:00,0.097202,0.05,FREE,NaN,NaN,NaN
1,sell,644700,476.36,209.951711,0.0,5m SELL signal,2024-01-12 08:30:00,3.818075,-0.50,FREE,12.597103,476.3,644657.0
2,buy,644721,476.00,210.110498,0.0,5m BUY signal,2024-01-12 10:15:00,0.079194,0.05,FREE,NaN,NaN,NaN
3,sell,644733,476.51,210.110498,0.0,5m SELL signal,2024-01-12 11:15:00,3.214192,-0.50,FREE,107.156354,476.0,644721.0
4,buy,644796,476.02,210.326779,0.0,5m BUY signal,2024-01-12 16:30:00,0.179593,0.05,FREE,NaN,NaN,NaN

In [1]:
from pathlib import Path
import pandas as pd

from adaptive_reward_checkpoint_fresh import (
    build_adaptive_reward_snapshot,
    run_adaptive_reward_from_snapshot,
)
from adaptive_trade_extensions import RollingThresholdConfig, make_threshold_grid

snapshot_path = Path("checkpoints") / "QQQ_adaptive_reward_fresh_start_90days.joblib"

common_kwargs = dict(
    daily_csv_path="DataAPI/data/QQQ_DAY.csv",
    k5m_csv_path="DataAPI/data/QQQ_5M.csv",
    code="QQQ",
    daily_chan_start="2008-01-01",
    accumulation_start="2010-01-01",
    N_confirm=5,
    min_labeled_days_to_train=200,
    retrain_every_new_labels=25,
    dp_lookback=5,
    lookahead_days_5m=2.0,
    retrain_every_days_5m=5,
    min_samples_total_5m=300,
    threshold_window_days=2.0,
    threshold_ret_grid=None,
    threshold_min_open_signals=10,
    initial_capital=100000.0,
    fee_pct=0.0,
    daily_chan_max_klines=500,
    five_chan_max_klines=500,
    macro_files={
        "vix_": "VIX.csv",
    },
    static_buy_level=0.20,
    static_sell_level=0.30,
    daily_threshold_config=RollingThresholdConfig(
        lookback_days=90,
        buy_grid=make_threshold_grid(0.05, 0.35, 0.005),
        sell_grid=make_threshold_grid(0.15, 0.60, 0.005),
        min_gap=0.02,
        min_obs=60,
        switch_penalty=0.0,
    ),
    verbose=True,
)

In [2]:
snapshot_res = build_adaptive_reward_snapshot(
    snapshot_path=str(snapshot_path),
    snapshot_end_time="2023-12-31",
    output_dir="output_adaptive_reward_snapshot_build_QQQ_90days",
    **common_kwargs,
)

print(snapshot_res["snapshot_path"])
display(snapshot_res["daily_reward_df"].tail())
display(snapshot_res["daily_log_df"].tail())

[TRAIN][DAILY-PROB] n=200 pos=33 (16.50%)
[TRAIN][DAILY-PROB] n=225 pos=40 (17.78%)
[TRAIN][DAILY-PROB] n=250 pos=46 (18.40%)
[TRAIN][DAILY-PROB] n=275 pos=50 (18.18%)
[TRAIN][DAILY-PROB] n=300 pos=56 (18.67%)
[TRAIN][DAILY-PROB] n=325 pos=59 (18.15%)
[TRAIN][DAILY-PROB] n=350 pos=73 (20.86%)
[TRAIN][DAILY-PROB] n=375 pos=78 (20.80%)
[TRAIN][DAILY-PROB] n=400 pos=89 (22.25%)
[TRAIN][DAILY-PROB] n=425 pos=101 (23.76%)
[TRAIN][DAILY-PROB] n=450 pos=108 (24.00%)
[TRAIN][DAILY-PROB] n=475 pos=114 (24.00%)
[TRAIN][DAILY-PROB] n=500 pos=119 (23.80%)
[TRAIN][DAILY-PROB] n=525 pos=119 (22.67%)
[TRAIN][DAILY-PROB] n=550 pos=125 (22.73%)
[TRAIN][DAILY-PROB] n=575 pos=130 (22.61%)
[TRAIN][DAILY-PROB] n=600 pos=138 (23.00%)
[TRAIN][DAILY-PROB] n=625 pos=144 (23.04%)
[TRAIN][DAILY-PROB] n=650 pos=145 (22.31%)
[TRAIN][DAILY-PROB] n=675 pos=145 (21.48%)
[TRAIN][DAILY-PROB] n=700 pos=149 (21.29%)
[TRAIN][DAILY-PROB] n=725 pos=151 (20.83%)
[TRAIN][DAILY-PROB] n=750 pos=155 (20.67%)
[TRAIN][DAILY-PROB] n=775 pos=163 (21.03%)
[TRAIN][DAILY-PROB] n=800 pos=168 (21.00%)
[TRAIN][DAILY-PROB] n=825 pos=181 (21.94%)
[TRAIN][DAILY-PROB] n=850 pos=184 (21.65%)
[TRAIN][DAILY-PROB] n=875 pos=193 (22.06%)
[TRAIN][DAILY-PROB] n=900 pos=200 (22.22%)
[TRAIN][DAILY-PROB] n=925 pos=203 (21.95%)
[TRAIN][DAILY-PROB] n=950 pos=212 (22.32%)
[TRAIN][DAILY-PROB] n=975 pos=214 (21.95%)
[TRAIN][DAILY-PROB] n=1000 pos=214 (21.40%)
[TRAIN][DAILY-PROB] n=1025 pos=214 (20.88%)
[TRAIN][DAILY-PROB] n=1050 pos=224 (21.33%)
[TRAIN][DAILY-PROB] n=1075 pos=233 (21.67%)
[TRAIN][DAILY-PROB] n=1100 pos=243 (22.09%)
[TRAIN][DAILY-PROB] n=1125 pos=246 (21.87%)
[TRAIN][DAILY-PROB] n=1150 pos=251 (21.83%)
[TRAIN][DAILY-PROB] n=1175 pos=259 (22.04%)
[TRAIN][DAILY-PROB] n=1200 pos=265 (22.08%)
[TRAIN][DAILY-PROB] n=1225 pos=269 (21.96%)
[TRAIN][DAILY-PROB] n=1250 pos=272 (21.76%)
[TRAIN][DAILY-PROB] n=1275 pos=281 (22.04%)
[TRAIN][DAILY-PROB] n=1300 pos=292 (22.46%)
[TRAIN][DAILY-PROB] n=1325 pos=297 (22.42%)
[TRAIN][DAILY-PROB] n=1350 pos=301 (22.30%)
[TRAIN][DAILY-PROB] n=1375 pos=305 (22.18%)
[TRAIN][DAILY-PROB] n=1400 pos=309 (22.07%)
[TRAIN][DAILY-PROB] n=1425 pos=313 (21.96%)
[TRAIN][DAILY-PROB] n=1450 pos=313 (21.59%)
[TRAIN][DAILY-PROB] n=1475 pos=317 (21.49%)
[TRAIN][DAILY-PROB] n=1500 pos=322 (21.47%)
[TRAIN][DAILY-PROB] n=1525 pos=328 (21.51%)
[TRAIN][DAILY-PROB] n=1550 pos=334 (21.55%)
[TRAIN][DAILY-PROB] n=1575 pos=335 (21.27%)
[TRAIN][DAILY-PROB] n=1600 pos=335 (20.94%)
[TRAIN][DAILY-PROB] n=1625 pos=338 (20.80%)
[TRAIN][DAILY-PROB] n=1650 pos=342 (20.73%)
[TRAIN][DAILY-PROB] n=1675 pos=348 (20.78%)
[TRAIN][DAILY-PROB] n=1700 pos=351 (20.65%)
[TRAIN][DAILY-PROB] n=1725 pos=360 (20.87%)
[TRAIN][DAILY-PROB] n=1750 pos=363 (20.74%)
[TRAIN][DAILY-PROB] n=1775 pos=371 (20.90%)
[TRAIN][DAILY-PROB] n=1800 pos=376 (20.89%)
[TRAIN][DAILY-PROB] n=1825 pos=382 (20.93%)
[TRAIN][DAILY-PROB] n=1850 pos=390 (21.08%)
[TRAIN][DAILY-PROB] n=1875 pos=397 (21.17%)
[TRAIN][DAILY-PROB] n=1900 pos=408 (21.47%)
[TRAIN][DAILY-PROB] n=1925 pos=415 (21.56%)
[TRAIN][DAILY-PROB] n=1950 pos=421 (21.59%)
[TRAIN][DAILY-PROB] n=1975 pos=430 (21.77%)
[TRAIN][DAILY-PROB] n=2000 pos=437 (21.85%)
[TRAIN][DAILY-PROB] n=2025 pos=445 (21.98%)
[TRAIN][DAILY-PROB] n=2050 pos=449 (21.90%)
[TRAIN][DAILY-PROB] n=2075 pos=456 (21.98%)
[TRAIN][DAILY-PROB] n=2100 pos=463 (22.05%)
[TRAIN][DAILY-PROB] n=2125 pos=463 (21.79%)
[TRAIN][DAILY-PROB] n=2150 pos=471 (21.91%)
[TRAIN][DAILY-PROB] n=2175 pos=476 (21.89%)
[TRAIN][DAILY-PROB] n=2200 pos=483 (21.95%)
[TRAIN][DAILY-PROB] n=2225 pos=487 (21.89%)
[TRAIN][DAILY-PROB] n=2250 pos=488 (21.69%)
[TRAIN][DAILY-PROB] n=2275 pos=490 (21.54%)
[TRAIN][DAILY-PROB] n=2300 pos=493 (21.43%)
[TRAIN][DAILY-PROB] n=2325 pos=494 (21.25%)
[TRAIN][DAILY-PROB] n=2350 pos=500 (21.28%)
[TRAIN][DAILY-PROB] n=2375 pos=502 (21.14%)
[TRAIN][DAILY-PROB] n=2400 pos=507 (21.12%)
[TRAIN][DAILY-PROB] n=2425 pos=512 (21.11%)
[TRAIN][DAILY-PROB] n=2450 pos=513 (20.94%)
[TRAIN][DAILY-PROB] n=2475 pos=519 (20.97%)
[TRAIN][DAILY-PROB] n=2500 pos=526 (21.04%)
[TRAIN][DAILY-PROB] n=2525 pos=532 (21.07%)
[TRAIN][DAILY-PROB] n=2550 pos=540 (21.18%)
[TRAIN][DAILY-PROB] n=2575 pos=541 (21.01%)
[TRAIN][DAILY-PROB] n=2600 pos=546 (21.00%)
[TRAIN][DAILY-PROB] n=2625 pos=548 (20.88%)
[TRAIN][DAILY-PROB] n=2650 pos=555 (20.94%)
[TRAIN][DAILY-PROB] n=2675 pos=564 (21.08%)
[TRAIN][DAILY-PROB] n=2700 pos=579 (21.44%)
[TRAIN][DAILY-PROB] n=2725 pos=589 (21.61%)
[TRAIN][DAILY-PROB] n=2750 pos=591 (21.49%)
[TRAIN][DAILY-PROB] n=2775 pos=592 (21.33%)
[TRAIN][DAILY-PROB] n=2800 pos=599 (21.39%)
[TRAIN][DAILY-PROB] n=2825 pos=607 (21.49%)
[TRAIN][DAILY-PROB] n=2850 pos=612 (21.47%)
[TRAIN][DAILY-PROB] n=2875 pos=619 (21.53%)
[TRAIN][DAILY-PROB] n=2900 pos=622 (21.45%)
[TRAIN][DAILY-PROB] n=2925 pos=631 (21.57%)
[TRAIN][DAILY-PROB] n=2950 pos=631 (21.39%)
[TRAIN][DAILY-PROB] n=2975 pos=633 (21.28%)
[TRAIN][DAILY-PROB] n=3000 pos=634 (21.13%)
[TRAIN][DAILY-PROB] n=3025 pos=639 (21.12%)
[TRAIN][DAILY-PROB] n=3050 pos=643 (21.08%)
[TRAIN][DAILY-PROB] n=3075 pos=643 (20.91%)
[TRAIN][DAILY-PROB] n=3100 pos=646 (20.84%)
[TRAIN][DAILY-PROB] n=3125 pos=653 (20.90%)
[TRAIN][DAILY-PROB] n=3150 pos=658 (20.89%)
[TRAIN][DAILY-PROB] n=3175 pos=666 (20.98%)
[TRAIN][DAILY-PROB] n=3200 pos=674 (21.06%)
[TRAIN][DAILY-PROB] n=3225 pos=675 (20.93%)
[TRAIN][DAILY-PROB] n=3250 pos=678 (20.86%)
[TRAIN][DAILY-PROB] n=3275 pos=685 (20.92%)
[TRAIN][DAILY-PROB] n=3300 pos=688 (20.85%)
[TRAIN][DAILY-PROB] n=3325 pos=694 (20.87%)
[TRAIN][DAILY-PROB] n=3350 pos=694 (20.72%)
[TRAIN][DAILY-PROB] n=3375 pos=697 (20.65%)
[TRAIN][DAILY-PROB] n=3400 pos=701 (20.62%)
[TRAIN][DAILY-PROB] n=3425 pos=711 (20.76%)
[TRAIN][DAILY-PROB] n=3450 pos=714 (20.70%)
[TRAIN][DAILY-PROB] n=3475 pos=719 (20.69%)
[TRAIN][DAILY-PROB] n=3500 pos=726 (20.74%)
[TRAIN][DAILY-PROB] n=3525 pos=728 (20.65%)
[TRAIN][DAILY-PROB] n=3550 pos=738 (20.79%)
[TRAIN][DAILY-PROB] n=3575 pos=739 (20.67%)
[TRAIN][DAILY-PROB] n=3600 pos=749 (20.81%)
[TRAIN][DAILY-PROB] n=3625 pos=755 (20.83%)
[TRAIN][DAILY-PROB] n=3650 pos=763 (20.90%)
[TRAIN][DAILY-PROB] n=3675 pos=770 (20.95%)
[TRAIN][DAILY-PROB] n=3700 pos=778 (21.03%)
[TRAIN][DAILY-PROB] n=3725 pos=782 (20.99%)
[TRAIN][DAILY-PROB] n=3750 pos=785 (20.93%)
[TRAIN][DAILY-PROB] n=3775 pos=795 (21.06%)
[TRAIN][DAILY-PROB] n=3800 pos=801 (21.08%)
[TRAIN][DAILY-PROB] n=3825 pos=803 (20.99%)
[TRAIN][DAILY-PROB] n=3850 pos=805 (20.91%)
[TRAIN][DAILY-PROB] n=3875 pos=806 (20.80%)
[TRAIN][DAILY-PROB] n=3900 pos=815 (20.90%)
[TRAIN][DAILY-PROB] n=3925 pos=824 (20.99%)
[TRAIN][DAILY-PROB] n=3950 pos=834 (21.11%)
[TRAIN][DAILY-PROB] n=3975 pos=835 (21.01%)
[TRAIN][5M] asof=2010-02-05 feats=69 buy=NO sell=YES rows=592
[TRAIN][5M] asof=2010-02-10 feats=69 buy=NO sell=YES rows=667
[TRAIN][5M] asof=2010-02-16 feats=69 buy=NO sell=YES rows=729
[TRAIN][5M] asof=2010-02-22 feats=69 buy=NO sell=YES rows=847
[TRAIN][5M] asof=2010-03-01 feats=69 buy=YES sell=YES rows=969
[TRAIN][5M] asof=2010-03-08 feats=69 buy=YES sell=YES rows=1122
[TRAIN][5M] asof=2010-03-15 feats=69 buy=YES sell=YES rows=1242
[TRAIN][5M] asof=2010-03-22 feats=69 buy=YES sell=YES rows=1405
[TRAIN][5M] asof=2010-03-29 feats=69 buy=YES sell=YES rows=1538
[TRAIN][5M] asof=2010-04-05 feats=69 buy=YES sell=YES rows=1649
[TRAIN][5M] asof=2010-04-12 feats=69 buy=YES sell=YES rows=1755
[TRAIN][5M] asof=2010-04-19 feats=69 buy=YES sell=YES rows=1875
[TRAIN][5M] asof=2010-04-26 feats=69 buy=YES sell=YES rows=1973
[TRAIN][5M] asof=2010-05-03 feats=69 buy=YES sell=YES rows=2086
[TRAIN][5M] asof=2010-05-10 feats=69 buy=YES sell=YES rows=2232
[TRAIN][5M] asof=2010-05-17 feats=69 buy=YES sell=YES rows=2380
[TRAIN][5M] asof=2010-05-24 feats=69 buy=YES sell=YES rows=2548
[TRAIN][5M] asof=2010-06-01 feats=69 buy=YES sell=YES rows=2722
[TRAIN][5M] asof=2010-06-07 feats=69 buy=YES sell=YES rows=2852
[TRAIN][5M] asof=2010-06-14 feats=69 buy=YES sell=YES rows=2964
[TRAIN][5M] asof=2010-06-21 feats=69 buy=YES sell=YES rows=3124
[TRAIN][5M] asof=2010-06-28 feats=69 buy=YES sell=YES rows=3328
[TRAIN][5M] asof=2010-07-06 feats=69 buy=YES sell=YES rows=3468
[TRAIN][5M] asof=2010-07-12 feats=69 buy=YES sell=YES rows=3554
[TRAIN][5M] asof=2010-07-19 feats=69 buy=YES sell=YES rows=3637
[TRAIN][5M] asof=2010-07-26 feats=69 buy=YES sell=YES rows=3813
[TRAIN][5M] asof=2010-08-02 feats=69 buy=YES sell=YES rows=3991
[TRAIN][5M] asof=2010-08-09 feats=69 buy=YES sell=YES rows=4096
[TRAIN][5M] asof=2010-08-16 feats=69 buy=YES sell=YES rows=4282
[TRAIN][5M] asof=2010-08-23 feats=69 buy=YES sell=YES rows=4395
[TRAIN][5M] asof=2010-08-30 feats=69 buy=YES sell=YES rows=4568
[TRAIN][5M] asof=2010-09-07 feats=69 buy=YES sell=YES rows=4684
[TRAIN][5M] asof=2010-09-13 feats=69 buy=YES sell=YES rows=4784
[TRAIN][5M] asof=2010-09-20 feats=69 buy=YES sell=YES rows=4979
[TRAIN][5M] asof=2010-09-27 feats=69 buy=YES sell=YES rows=5113
[TRAIN][5M] asof=2010-10-04 feats=69 buy=YES sell=YES rows=5274
[TRAIN][5M] asof=2010-10-11 feats=69 buy=YES sell=YES rows=5383
[TRAIN][5M] asof=2010-10-18 feats=69 buy=YES sell=YES rows=5522
[TRAIN][5M] asof=2010-10-25 feats=69 buy=YES sell=YES rows=5684
[TRAIN][5M] asof=2010-11-01 feats=69 buy=YES sell=YES rows=5864
[TRAIN][5M] asof=2010-11-08 feats=69 buy=YES sell=YES rows=6010
[TRAIN][5M] asof=2010-11-15 feats=69 buy=YES sell=YES rows=6197
[TRAIN][5M] asof=2010-11-22 feats=69 buy=YES sell=YES rows=6388
[TRAIN][5M] asof=2010-11-29 feats=69 buy=YES sell=YES rows=6495
[TRAIN][5M] asof=2010-12-06 feats=69 buy=YES sell=YES rows=6662
[TRAIN][5M] asof=2010-12-13 feats=69 buy=YES sell=YES rows=6806
[TRAIN][5M] asof=2010-12-20 feats=69 buy=YES sell=YES rows=6945
[TRAIN][5M] asof=2010-12-27 feats=69 buy=YES sell=YES rows=6987
[TRAIN][5M] asof=2011-01-03 feats=69 buy=YES sell=YES rows=7109
[TRAIN][5M] asof=2011-01-10 feats=69 buy=YES sell=YES rows=7283
[TRAIN][5M] asof=2011-01-18 feats=69 buy=YES sell=YES rows=7395
[TRAIN][5M] asof=2011-01-24 feats=69 buy=YES sell=YES rows=7503
[TRAIN][5M] asof=2011-01-31 feats=69 buy=YES sell=YES rows=7672
[TRAIN][5M] asof=2011-02-07 feats=69 buy=YES sell=YES rows=7788
[TRAIN][5M] asof=2011-02-14 feats=69 buy=YES sell=YES rows=7915
[TRAIN][5M] asof=2011-02-22 feats=69 buy=YES sell=YES rows=8087
[TRAIN][5M] asof=2011-02-28 feats=69 buy=YES sell=YES rows=8225
[TRAIN][5M] asof=2011-03-07 feats=69 buy=YES sell=YES rows=8404
[TRAIN][5M] asof=2011-03-14 feats=69 buy=YES sell=YES rows=8581
[TRAIN][5M] asof=2011-03-21 feats=69 buy=YES sell=YES rows=8813
[TRAIN][5M] asof=2011-03-28 feats=69 buy=YES sell=YES rows=8906
[TRAIN][5M] asof=2011-04-04 feats=69 buy=YES sell=YES rows=9022
[TRAIN][5M] asof=2011-04-11 feats=69 buy=YES sell=YES rows=9179
[TRAIN][5M] asof=2011-04-18 feats=69 buy=YES sell=YES rows=9363
[TRAIN][5M] asof=2011-04-25 feats=69 buy=YES sell=YES rows=9481
[TRAIN][5M] asof=2011-05-02 feats=69 buy=YES sell=YES rows=9589
[TRAIN][5M] asof=2011-05-09 feats=69 buy=YES sell=YES rows=9764
[TRAIN][5M] asof=2011-05-16 feats=69 buy=YES sell=YES rows=9911
[TRAIN][5M] asof=2011-05-23 feats=69 buy=YES sell=YES rows=10062
[TRAIN][5M] asof=2011-05-31 feats=69 buy=YES sell=YES rows=10211
[TRAIN][5M] asof=2011-06-06 feats=69 buy=YES sell=YES rows=10324
[TRAIN][5M] asof=2011-06-13 feats=69 buy=YES sell=YES rows=10460
[TRAIN][5M] asof=2011-06-20 feats=69 buy=YES sell=YES rows=10579
[TRAIN][5M] asof=2011-06-27 feats=69 buy=YES sell=YES rows=10695
[TRAIN][5M] asof=2011-07-05 feats=69 buy=YES sell=YES rows=10836
[TRAIN][5M] asof=2011-07-11 feats=69 buy=YES sell=YES rows=10957
[TRAIN][5M] asof=2011-07-18 feats=69 buy=YES sell=YES rows=11088
[TRAIN][5M] asof=2011-07-25 feats=69 buy=YES sell=YES rows=11260
[TRAIN][5M] asof=2011-08-01 feats=69 buy=YES sell=YES rows=11415
[TRAIN][5M] asof=2011-08-08 feats=69 buy=YES sell=YES rows=11598
[TRAIN][5M] asof=2011-08-15 feats=69 buy=YES sell=YES rows=11782
[TRAIN][5M] asof=2011-08-22 feats=69 buy=YES sell=YES rows=12033
[TRAIN][5M] asof=2011-08-29 feats=69 buy=YES sell=YES rows=12199
[TRAIN][5M] asof=2011-09-06 feats=69 buy=YES sell=YES rows=12402
[TRAIN][5M] asof=2011-09-12 feats=69 buy=YES sell=YES rows=12547
[TRAIN][5M] asof=2011-09-19 feats=69 buy=YES sell=YES rows=12739
[TRAIN][5M] asof=2011-09-26 feats=69 buy=YES sell=YES rows=12948
[TRAIN][5M] asof=2011-10-03 feats=69 buy=YES sell=YES rows=13139
[TRAIN][5M] asof=2011-10-10 feats=69 buy=YES sell=YES rows=13265
[TRAIN][5M] asof=2011-10-17 feats=69 buy=YES sell=YES rows=13415
[TRAIN][5M] asof=2011-10-24 feats=69 buy=YES sell=YES rows=13569
[TRAIN][5M] asof=2011-10-31 feats=69 buy=YES sell=YES rows=13735
[TRAIN][5M] asof=2011-11-07 feats=69 buy=YES sell=YES rows=13974
[TRAIN][5M] asof=2011-11-14 feats=69 buy=YES sell=YES rows=14156
[TRAIN][5M] asof=2011-11-21 feats=69 buy=YES sell=YES rows=14376
[TRAIN][5M] asof=2011-11-28 feats=69 buy=YES sell=YES rows=14516
[TRAIN][5M] asof=2011-12-05 feats=69 buy=YES sell=YES rows=14668
[TRAIN][5M] asof=2011-12-12 feats=69 buy=YES sell=YES rows=14847
[TRAIN][5M] asof=2011-12-19 feats=69 buy=YES sell=YES rows=15060
[TRAIN][5M] asof=2011-12-27 feats=69 buy=YES sell=YES rows=15214
[TRAIN][5M] asof=2012-01-03 feats=69 buy=YES sell=YES rows=15317
[TRAIN][5M] asof=2012-01-09 feats=69 buy=YES sell=YES rows=15431
[TRAIN][5M] asof=2012-01-17 feats=69 buy=YES sell=YES rows=15570
[TRAIN][5M] asof=2012-01-23 feats=69 buy=YES sell=YES rows=15681
[TRAIN][5M] asof=2012-01-30 feats=69 buy=YES sell=YES rows=15866
[TRAIN][5M] asof=2012-02-06 feats=69 buy=YES sell=YES rows=16009
[TRAIN][5M] asof=2012-02-13 feats=69 buy=YES sell=YES rows=16175
[TRAIN][5M] asof=2012-02-21 feats=69 buy=YES sell=YES rows=16363
[TRAIN][5M] asof=2012-02-27 feats=69 buy=YES sell=YES rows=16499
[TRAIN][5M] asof=2012-03-05 feats=69 buy=YES sell=YES rows=16647
[TRAIN][5M] asof=2012-03-12 feats=69 buy=YES sell=YES rows=16795
[TRAIN][5M] asof=2012-03-19 feats=69 buy=YES sell=YES rows=16905
[TRAIN][5M] asof=2012-03-26 feats=69 buy=YES sell=YES rows=17093
[TRAIN][5M] asof=2012-04-02 feats=69 buy=YES sell=YES rows=17210
[TRAIN][5M] asof=2012-04-09 feats=69 buy=YES sell=YES rows=17310
[TRAIN][5M] asof=2012-04-16 feats=69 buy=YES sell=YES rows=17453
[TRAIN][5M] asof=2012-04-23 feats=69 buy=YES sell=YES rows=17594
[TRAIN][5M] asof=2012-04-30 feats=69 buy=YES sell=YES rows=17762
[TRAIN][5M] asof=2012-05-07 feats=69 buy=YES sell=YES rows=17932
[TRAIN][5M] asof=2012-05-14 feats=69 buy=YES sell=YES rows=18132
[TRAIN][5M] asof=2012-05-21 feats=69 buy=YES sell=YES rows=18279
[TRAIN][5M] asof=2012-05-29 feats=69 buy=YES sell=YES rows=18449
[TRAIN][5M] asof=2012-06-04 feats=69 buy=YES sell=YES rows=18533
[TRAIN][5M] asof=2012-06-11 feats=69 buy=YES sell=YES rows=18705
[TRAIN][5M] asof=2012-06-18 feats=69 buy=YES sell=YES rows=18835
[TRAIN][5M] asof=2012-06-25 feats=69 buy=YES sell=YES rows=18954
[TRAIN][5M] asof=2012-07-02 feats=69 buy=YES sell=YES rows=19070
[TRAIN][5M] asof=2012-07-09 feats=69 buy=YES sell=YES rows=19167
[TRAIN][5M] asof=2012-07-16 feats=69 buy=YES sell=YES rows=19277
[TRAIN][5M] asof=2012-07-23 feats=69 buy=YES sell=YES rows=19415
[TRAIN][5M] asof=2012-07-30 feats=69 buy=YES sell=YES rows=19534
[TRAIN][5M] asof=2012-08-06 feats=69 buy=YES sell=YES rows=19696
[TRAIN][5M] asof=2012-08-13 feats=69 buy=YES sell=YES rows=19815
[TRAIN][5M] asof=2012-08-20 feats=69 buy=YES sell=YES rows=19962
[TRAIN][5M] asof=2012-08-27 feats=69 buy=YES sell=YES rows=20145
[TRAIN][5M] asof=2012-09-04 feats=69 buy=YES sell=YES rows=20285
[TRAIN][5M] asof=2012-09-10 feats=69 buy=YES sell=YES rows=20408
[TRAIN][5M] asof=2012-09-17 feats=69 buy=YES sell=YES rows=20564
[TRAIN][5M] asof=2012-09-24 feats=69 buy=YES sell=YES rows=20679
[TRAIN][5M] asof=2012-10-01 feats=69 buy=YES sell=YES rows=20821
[TRAIN][5M] asof=2012-10-08 feats=69 buy=YES sell=YES rows=20992
[TRAIN][5M] asof=2012-10-15 feats=69 buy=YES sell=YES rows=21165
[TRAIN][5M] asof=2012-10-22 feats=69 buy=YES sell=YES rows=21266
[TRAIN][5M] asof=2012-10-31 feats=69 buy=YES sell=YES rows=21413
[TRAIN][5M] asof=2012-11-05 feats=69 buy=YES sell=YES rows=21502
[TRAIN][5M] asof=2012-11-12 feats=69 buy=YES sell=YES rows=21667
[TRAIN][5M] asof=2012-11-19 feats=69 buy=YES sell=YES rows=21793
[TRAIN][5M] asof=2012-11-26 feats=69 buy=YES sell=YES rows=21908
[TRAIN][5M] asof=2012-12-03 feats=69 buy=YES sell=YES rows=22041
[TRAIN][5M] asof=2012-12-10 feats=69 buy=YES sell=YES rows=22184
[TRAIN][5M] asof=2012-12-17 feats=69 buy=YES sell=YES rows=22306
[TRAIN][5M] asof=2012-12-24 feats=69 buy=YES sell=YES rows=22410
[TRAIN][5M] asof=2012-12-31 feats=69 buy=YES sell=YES rows=22485
[TRAIN][5M] asof=2013-01-07 feats=69 buy=YES sell=YES rows=22568
[TRAIN][5M] asof=2013-01-14 feats=69 buy=YES sell=YES rows=22680
[TRAIN][5M] asof=2013-01-22 feats=69 buy=YES sell=YES rows=22787
[TRAIN][5M] asof=2013-01-28 feats=69 buy=YES sell=YES rows=22937
[TRAIN][5M] asof=2013-02-04 feats=69 buy=YES sell=YES rows=23101
[TRAIN][5M] asof=2013-02-11 feats=69 buy=YES sell=YES rows=23253
[TRAIN][5M] asof=2013-02-19 feats=69 buy=YES sell=YES rows=23410
[TRAIN][5M] asof=2013-02-25 feats=69 buy=YES sell=YES rows=23548
[TRAIN][5M] asof=2013-03-04 feats=69 buy=YES sell=YES rows=23691
[TRAIN][5M] asof=2013-03-11 feats=69 buy=YES sell=YES rows=23848
[TRAIN][5M] asof=2013-03-18 feats=69 buy=YES sell=YES rows=23972
[TRAIN][5M] asof=2013-03-25 feats=69 buy=YES sell=YES rows=24088
[TRAIN][5M] asof=2013-04-01 feats=69 buy=YES sell=YES rows=24222
[TRAIN][5M] asof=2013-04-08 feats=69 buy=YES sell=YES rows=24299
[TRAIN][5M] asof=2013-04-15 feats=69 buy=YES sell=YES rows=24416
[TRAIN][5M] asof=2013-04-22 feats=69 buy=YES sell=YES rows=24540
[TRAIN][5M] asof=2013-04-29 feats=69 buy=YES sell=YES rows=24620
[TRAIN][5M] asof=2013-05-06 feats=69 buy=YES sell=YES rows=24756
[TRAIN][5M] asof=2013-05-13 feats=69 buy=YES sell=YES rows=24892
[TRAIN][5M] asof=2013-05-20 feats=69 buy=YES sell=YES rows=25020
[TRAIN][5M] asof=2013-05-28 feats=69 buy=YES sell=YES rows=25175
[TRAIN][5M] asof=2013-06-03 feats=69 buy=YES sell=YES rows=25336
[TRAIN][5M] asof=2013-06-10 feats=69 buy=YES sell=YES rows=25455
[TRAIN][5M] asof=2013-06-17 feats=69 buy=YES sell=YES rows=25592
[TRAIN][5M] asof=2013-06-24 feats=69 buy=YES sell=YES rows=25772
[TRAIN][5M] asof=2013-07-01 feats=69 buy=YES sell=YES rows=25946
[TRAIN][5M] asof=2013-07-08 feats=69 buy=YES sell=YES rows=26030
[TRAIN][5M] asof=2013-07-15 feats=69 buy=YES sell=YES rows=26170
[TRAIN][5M] asof=2013-07-22 feats=69 buy=YES sell=YES rows=26289
[TRAIN][5M] asof=2013-07-29 feats=69 buy=YES sell=YES rows=26458
[TRAIN][5M] asof=2013-08-05 feats=69 buy=YES sell=YES rows=26595
[TRAIN][5M] asof=2013-08-12 feats=69 buy=YES sell=YES rows=26740
[TRAIN][5M] asof=2013-08-19 feats=69 buy=YES sell=YES rows=26965
[TRAIN][5M] asof=2013-08-26 feats=69 buy=YES sell=YES rows=27091
[TRAIN][5M] asof=2013-09-03 feats=69 buy=YES sell=YES rows=27267
[TRAIN][5M] asof=2013-09-09 feats=69 buy=YES sell=YES rows=27401
[TRAIN][5M] asof=2013-09-16 feats=69 buy=YES sell=YES rows=27588
[TRAIN][5M] asof=2013-09-23 feats=69 buy=YES sell=YES rows=27703
[TRAIN][5M] asof=2013-09-30 feats=69 buy=YES sell=YES rows=27904
[TRAIN][5M] asof=2013-10-07 feats=69 buy=YES sell=YES rows=28040
[TRAIN][5M] asof=2013-10-14 feats=69 buy=YES sell=YES rows=28230
[TRAIN][5M] asof=2013-10-21 feats=69 buy=YES sell=YES rows=28392
[TRAIN][5M] asof=2013-10-28 feats=69 buy=YES sell=YES rows=28528
[TRAIN][5M] asof=2013-11-04 feats=69 buy=YES sell=YES rows=28730
[TRAIN][5M] asof=2013-11-11 feats=69 buy=YES sell=YES rows=28907
[TRAIN][5M] asof=2013-11-18 feats=69 buy=YES sell=YES rows=29043
[TRAIN][5M] asof=2013-11-25 feats=69 buy=YES sell=YES rows=29202
[TRAIN][5M] asof=2013-12-02 feats=69 buy=YES sell=YES rows=29301
[TRAIN][5M] asof=2013-12-09 feats=69 buy=YES sell=YES rows=29477
[TRAIN][5M] asof=2013-12-16 feats=69 buy=YES sell=YES rows=29657
[TRAIN][5M] asof=2013-12-23 feats=69 buy=YES sell=YES rows=29862
[TRAIN][5M] asof=2013-12-30 feats=69 buy=YES sell=YES rows=29988
[TRAIN][5M] asof=2014-01-06 feats=69 buy=YES sell=YES rows=30079

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
3517,2023-12-22,0.164809,0.22,0.28,FORCE_BUY,0.003787,0.003836,0.003049,0.003787,FREE,2.453586e+11,408.20,1.8,1.9
3518,2023-12-26,0.160100,0.22,0.28,FORCE_BUY,0.003149,-0.000098,-0.000098,0.003149,FORCE_BUY,2.461314e+11,410.89,1.9,-0.5
3519,2023-12-27,0.139934,0.22,0.30,FORCE_BUY,0.002019,0.000827,0.000827,0.002019,FORCE_BUY,2.466283e+11,411.90,1.9,-0.5
3520,2023-12-28,0.197314,0.22,0.30,FORCE_BUY,-0.002109,0.001019,0.000412,-0.002109,FREE,2.468795e+11,411.68,1.9,-0.5
3521,2023-12-29,0.204419,0.22,0.30,FORCE_BUY,-0.006967,-0.004135,0.000170,-0.006967,FORCE_SELL,2.469215e+11,409.06,1.9,-0.5

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
3517,2023-12-22,1.751273e+07,0.0,1,1.9,-0.5,0.164809,FORCE_BUY,0.22,0.28
3518,2023-12-26,1.762813e+07,0.0,1,1.9,-0.5,0.160100,FORCE_BUY,0.22,0.28
3519,2023-12-27,1.767146e+07,0.0,1,1.9,-0.5,0.139934,FORCE_BUY,0.22,0.30
3520,2023-12-28,1.766203e+07,0.0,1,1.9,-0.5,0.197314,FORCE_BUY,0.22,0.30
3521,2023-12-29,1.754962e+07,0.0,1,1.9,-0.5,0.204419,FORCE_BUY,0.22,0.30

In [3]:
resume_res = run_adaptive_reward_from_snapshot(
    snapshot_path=str(snapshot_path),
    end_time="2026-12-31",
    sim_start="2024-01-01",
    initial_capital=100000.0,
    fee_pct=0.0,
    output_dir="output_adaptive_reward_resumed_fresh_QQQ_90days",
    # Optional. If omitted, the code saves next to the source snapshot as
    # checkpoints/QQQ_adaptive_reward_fresh_start__continued.joblib
    save_snapshot_path=None,
    verbose=True,
)

print("continued snapshot:", resume_res["continued_snapshot_path"])

display(resume_res["daily_reward_df"].tail())
display(resume_res["daily_log_df"].tail())
display(resume_res["trades_df"].head())

[TRAIN][DAILY-PROB] n=4002 pos=843 (21.06%)
[TRAIN][DAILY-PROB] n=4027 pos=844 (20.96%)
[TRAIN][DAILY-PROB] n=4052 pos=850 (20.98%)
[TRAIN][DAILY-PROB] n=4077 pos=854 (20.95%)
[TRAIN][DAILY-PROB] n=4102 pos=858 (20.92%)
[TRAIN][DAILY-PROB] n=4127 pos=862 (20.89%)
[TRAIN][DAILY-PROB] n=4152 pos=873 (21.03%)
[TRAIN][DAILY-PROB] n=4177 pos=876 (20.97%)
[TRAIN][DAILY-PROB] n=4202 pos=881 (20.97%)
[TRAIN][DAILY-PROB] n=4227 pos=885 (20.94%)
[TRAIN][DAILY-PROB] n=4252 pos=890 (20.93%)
[TRAIN][DAILY-PROB] n=4277 pos=900 (21.04%)
[TRAIN][DAILY-PROB] n=4302 pos=909 (21.13%)
[TRAIN][DAILY-PROB] n=4327 pos=913 (21.10%)
[TRAIN][DAILY-PROB] n=4352 pos=915 (21.02%)
[TRAIN][DAILY-PROB] n=4377 pos=915 (20.90%)
[TRAIN][DAILY-PROB] n=4402 pos=926 (21.04%)
[TRAIN][DAILY-PROB] n=4427 pos=930 (21.01%)
[TRAIN][DAILY-PROB] n=4452 pos=937 (21.05%)
[TRAIN][DAILY-PROB] n=4477 pos=944 (21.09%)
[TRAIN][DAILY-PROB] n=4502 pos=947 (21.04%)
[TRAIN][DAILY-PROB] n=4527 pos=953 (21.05%)
[TRAIN][DAILY-PROB] n=4552 pos=957 (21.02%)
[TRAIN][5M] asof=2024-01-02 feats=69 buy=YES sell=YES rows=118486
[TRAIN][5M] asof=2024-01-08 feats=69 buy=YES sell=YES rows=118632
[TRAIN][5M] asof=2024-01-16 feats=69 buy=YES sell=YES rows=118916
[TRAIN][5M] asof=2024-01-22 feats=69 buy=YES sell=YES rows=119104
[TRAIN][5M] asof=2024-01-29 feats=69 buy=YES sell=YES rows=119259
[TRAIN][5M] asof=2024-02-05 feats=69 buy=YES sell=YES rows=119428
[TRAIN][5M] asof=2024-02-12 feats=69 buy=YES sell=YES rows=119583
[TRAIN][5M] asof=2024-02-20 feats=69 buy=YES sell=YES rows=119759
[TRAIN][5M] asof=2024-02-26 feats=69 buy=YES sell=YES rows=119917
[TRAIN][5M] asof=2024-03-04 feats=69 buy=YES sell=YES rows=120126
[TRAIN][5M] asof=2024-03-11 feats=69 buy=YES sell=YES rows=120347
[TRAIN][5M] asof=2024-03-18 feats=69 buy=YES sell=YES rows=120508
[TRAIN][5M] asof=2024-03-25 feats=69 buy=YES sell=YES rows=120701
[TRAIN][5M] asof=2024-04-01 feats=69 buy=YES sell=YES rows=120822
[TRAIN][5M] asof=2024-04-08 feats=69 buy=YES sell=YES rows=120948
[TRAIN][5M] asof=2024-04-15 feats=69 buy=YES sell=YES rows=121139
[TRAIN][5M] asof=2024-04-22 feats=69 buy=YES sell=YES rows=121274
[TRAIN][5M] asof=2024-04-29 feats=69 buy=YES sell=YES rows=121495
[TRAIN][5M] asof=2024-05-06 feats=69 buy=YES sell=YES rows=121657
[TRAIN][5M] asof=2024-05-13 feats=69 buy=YES sell=YES rows=121795
[TRAIN][5M] asof=2024-05-20 feats=69 buy=YES sell=YES rows=121939
[TRAIN][5M] asof=2024-05-28 feats=69 buy=YES sell=YES rows=122133
[TRAIN][5M] asof=2024-06-03 feats=69 buy=YES sell=YES rows=122307
[TRAIN][5M] asof=2024-06-10 feats=69 buy=YES sell=YES rows=122482
[TRAIN][5M] asof=2024-06-17 feats=69 buy=YES sell=YES rows=122660
[TRAIN][5M] asof=2024-06-24 feats=69 buy=YES sell=YES rows=122794
[TRAIN][5M] asof=2024-07-01 feats=69 buy=YES sell=YES rows=122942
[TRAIN][5M] asof=2024-07-08 feats=69 buy=YES sell=YES rows=123061
[TRAIN][5M] asof=2024-07-15 feats=69 buy=YES sell=YES rows=123242
[TRAIN][5M] asof=2024-07-22 feats=69 buy=YES sell=YES rows=123475
[TRAIN][5M] asof=2024-07-29 feats=69 buy=YES sell=YES rows=123732
[TRAIN][5M] asof=2024-08-05 feats=69 buy=YES sell=YES rows=123973
[TRAIN][5M] asof=2024-08-12 feats=69 buy=YES sell=YES rows=124126
[TRAIN][5M] asof=2024-08-19 feats=69 buy=YES sell=YES rows=124315
[TRAIN][5M] asof=2024-08-26 feats=69 buy=YES sell=YES rows=124517
[TRAIN][5M] asof=2024-09-03 feats=69 buy=YES sell=YES rows=124680
[TRAIN][5M] asof=2024-09-09 feats=69 buy=YES sell=YES rows=124843
[TRAIN][5M] asof=2024-09-16 feats=69 buy=YES sell=YES rows=125054
[TRAIN][5M] asof=2024-09-23 feats=69 buy=YES sell=YES rows=125256
[TRAIN][5M] asof=2024-09-30 feats=69 buy=YES sell=YES rows=125412
[TRAIN][5M] asof=2024-10-07 feats=69 buy=YES sell=YES rows=125555
[TRAIN][5M] asof=2024-10-14 feats=69 buy=YES sell=YES rows=125725
[TRAIN][5M] asof=2024-10-21 feats=69 buy=YES sell=YES rows=125933
[TRAIN][5M] asof=2024-10-28 feats=69 buy=YES sell=YES rows=126148
[TRAIN][5M] asof=2024-11-04 feats=69 buy=YES sell=YES rows=126341
[TRAIN][5M] asof=2024-11-11 feats=69 buy=YES sell=YES rows=126509
[TRAIN][5M] asof=2024-11-18 feats=69 buy=YES sell=YES rows=126689
[TRAIN][5M] asof=2024-11-25 feats=69 buy=YES sell=YES rows=126880
[TRAIN][5M] asof=2024-12-02 feats=69 buy=YES sell=YES rows=126997
[TRAIN][5M] asof=2024-12-09 feats=69 buy=YES sell=YES rows=127174
[TRAIN][5M] asof=2024-12-16 feats=69 buy=YES sell=YES rows=127367
[TRAIN][5M] asof=2024-12-23 feats=69 buy=YES sell=YES rows=127550
[TRAIN][5M] asof=2024-12-30 feats=69 buy=YES sell=YES rows=127719
[TRAIN][5M] asof=2025-01-06 feats=69 buy=YES sell=YES rows=127854
[TRAIN][5M] asof=2025-01-13 feats=69 buy=YES sell=YES rows=128035
[TRAIN][5M] asof=2025-01-21 feats=69 buy=YES sell=YES rows=128246
[TRAIN][5M] asof=2025-01-27 feats=69 buy=YES sell=YES rows=128393
[TRAIN][5M] asof=2025-02-03 feats=69 buy=YES sell=YES rows=128602
[TRAIN][5M] asof=2025-02-10 feats=69 buy=YES sell=YES rows=128782
[TRAIN][5M] asof=2025-02-18 feats=69 buy=YES sell=YES rows=128909
[TRAIN][5M] asof=2025-02-24 feats=69 buy=YES sell=YES rows=129079
[TRAIN][5M] asof=2025-03-03 feats=69 buy=YES sell=YES rows=129255
[TRAIN][5M] asof=2025-03-10 feats=69 buy=YES sell=YES rows=129464
[TRAIN][5M] asof=2025-03-17 feats=69 buy=YES sell=YES rows=129648
[TRAIN][5M] asof=2025-03-24 feats=69 buy=YES sell=YES rows=129846
[TRAIN][5M] asof=2025-03-31 feats=69 buy=YES sell=YES rows=130063
[TRAIN][5M] asof=2025-04-07 feats=69 buy=YES sell=YES rows=130261
[TRAIN][5M] asof=2025-04-14 feats=69 buy=YES sell=YES rows=130456
[TRAIN][5M] asof=2025-04-21 feats=69 buy=YES sell=YES rows=130588
[TRAIN][5M] asof=2025-04-28 feats=69 buy=YES sell=YES rows=130839
[TRAIN][5M] asof=2025-05-05 feats=69 buy=YES sell=YES rows=131075
[TRAIN][5M] asof=2025-05-12 feats=69 buy=YES sell=YES rows=131229
[TRAIN][5M] asof=2025-05-19 feats=69 buy=YES sell=YES rows=131410
[TRAIN][5M] asof=2025-05-27 feats=69 buy=YES sell=YES rows=131601
[TRAIN][5M] asof=2025-06-02 feats=69 buy=YES sell=YES rows=131724
[TRAIN][5M] asof=2025-06-09 feats=69 buy=YES sell=YES rows=131885
[TRAIN][5M] asof=2025-06-16 feats=69 buy=YES sell=YES rows=132004
[TRAIN][5M] asof=2025-06-23 feats=69 buy=YES sell=YES rows=132146
[TRAIN][5M] asof=2025-06-30 feats=69 buy=YES sell=YES rows=132293
[TRAIN][5M] asof=2025-07-07 feats=69 buy=YES sell=YES rows=132451
[TRAIN][5M] asof=2025-07-14 feats=69 buy=YES sell=YES rows=132617
[TRAIN][5M] asof=2025-07-21 feats=69 buy=YES sell=YES rows=132829
[TRAIN][5M] asof=2025-07-28 feats=69 buy=YES sell=YES rows=133039
[TRAIN][5M] asof=2025-08-04 feats=69 buy=YES sell=YES rows=133227
[TRAIN][5M] asof=2025-08-11 feats=69 buy=YES sell=YES rows=133401
[TRAIN][5M] asof=2025-08-18 feats=69 buy=YES sell=YES rows=133555
[TRAIN][5M] asof=2025-08-25 feats=69 buy=YES sell=YES rows=133740
[TRAIN][5M] asof=2025-09-02 feats=69 buy=YES sell=YES rows=133897
[TRAIN][5M] asof=2025-09-08 feats=69 buy=YES sell=YES rows=134035
[TRAIN][5M] asof=2025-09-15 feats=69 buy=YES sell=YES rows=134187
[TRAIN][5M] asof=2025-09-22 feats=69 buy=YES sell=YES rows=134414
[TRAIN][5M] asof=2025-09-29 feats=69 buy=YES sell=YES rows=134604
[TRAIN][5M] asof=2025-10-06 feats=69 buy=YES sell=YES rows=134830
[TRAIN][5M] asof=2025-10-13 feats=69 buy=YES sell=YES rows=135026
[TRAIN][5M] asof=2025-10-20 feats=69 buy=YES sell=YES rows=135242
[TRAIN][5M] asof=2025-10-27 feats=69 buy=YES sell=YES rows=135444
[TRAIN][5M] asof=2025-11-03 feats=69 buy=YES sell=YES rows=135659
[TRAIN][5M] asof=2025-11-10 feats=69 buy=YES sell=YES rows=135906
[TRAIN][5M] asof=2025-11-17 feats=69 buy=YES sell=YES rows=136114
[TRAIN][5M] asof=2025-11-24 feats=69 buy=YES sell=YES rows=136347
[TRAIN][5M] asof=2025-12-01 feats=69 buy=YES sell=YES rows=136464
[TRAIN][5M] asof=2025-12-08 feats=69 buy=YES sell=YES rows=136656
[TRAIN][5M] asof=2025-12-15 feats=69 buy=YES sell=YES rows=136865
[TRAIN][5M] asof=2025-12-22 feats=69 buy=YES sell=YES rows=137055
[TRAIN][5M] asof=2025-12-29 feats=69 buy=YES sell=YES rows=137169
[TRAIN][5M] asof=2026-01-05 feats=69 buy=YES sell=YES rows=137284
[TRAIN][5M] asof=2026-01-12 feats=69 buy=YES sell=YES rows=137506
[TRAIN][5M] asof=2026-01-20 feats=69 buy=YES sell=YES rows=137670
[TRAIN][5M] asof=2026-01-26 feats=69 buy=YES sell=YES rows=137856
[TRAIN][5M] asof=2026-02-02 feats=69 buy=YES sell=YES rows=138083
[TRAIN][5M] asof=2026-02-09 feats=69 buy=YES sell=YES rows=138314
[TRAIN][5M] asof=2026-02-17 feats=69 buy=YES sell=YES rows=138518
[TRAIN][5M] asof=2026-02-23 feats=69 buy=YES sell=YES rows=138658
[TRAIN][5M] asof=2026-03-02 feats=69 buy=YES sell=YES rows=138865
[TRAIN][5M] asof=2026-03-09 feats=69 buy=YES sell=YES rows=139058
[TRAIN][5M] asof=2026-03-16 feats=69 buy=YES sell=YES rows=139278
[TRAIN][5M] asof=2026-03-23 feats=69 buy=YES sell=YES rows=139492
[TRAIN][5M] asof=2026-03-30 feats=69 buy=YES sell=YES rows=139687
[TRAIN][5M] asof=2026-04-06 feats=69 buy=YES sell=YES rows=139795
[TRAIN][5M] asof=2026-04-13 feats=69 buy=YES sell=YES rows=139991
[TRAIN][5M] asof=2026-04-20 feats=69 buy=YES sell=YES rows=140168
[SAVED] output_adaptive_reward_resumed_fresh_QQQ_90days\trades.csv
[SAVED] output_adaptive_reward_resumed_fresh_QQQ_90days\daily_log.csv
[SAVED] output_adaptive_reward_resumed_fresh_QQQ_90days\daily_reward_log.csv
[SAVED] output_adaptive_reward_resumed_fresh_QQQ_90days\equity_vs_buyhold.png
[SAVED] output_adaptive_reward_resumed_fresh_QQQ_90days\price_with_trades.png
[SAVED] output_adaptive_reward_resumed_fresh_QQQ_90days\p_day.png
[CHECKPOINT] saved continued snapshot -> checkpoints\QQQ_adaptive_reward_fresh_start_90days__continued.joblib
continued snapshot: checkpoints\QQQ_adaptive_reward_fresh_start_90days__continued.joblib

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
4094,2026-04-15,0.195582,0.24,0.445,FORCE_BUY,0.010239,0.001994,0.000000,0.010239,FORCE_BUY,1.504969e+06,638.3600,0.85,2.50
4095,2026-04-16,0.180534,0.24,0.445,FORCE_BUY,0.001439,0.004868,0.000094,0.001439,FREE,1.512295e+06,640.2400,0.85,2.50
4096,2026-04-17,0.189910,0.24,0.445,FORCE_BUY,0.013857,0.005735,0.002843,0.013857,FORCE_BUY,1.533251e+06,648.9700,0.85,2.50
4097,2026-04-20,0.150180,0.24,0.445,FORCE_BUY,0.005571,0.004654,0.002343,0.005571,FORCE_BUY,1.541794e+06,647.9701,0.85,2.50
4098,2026-04-21,0.181258,0.34,0.445,FORCE_BUY,-0.001865,0.002293,-0.000231,-0.001865,FREE,1.545329e+06,647.4900,-0.50,2.25

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
572,2026-04-15,268998.496978,0.0,1,0.85,2.50,0.195582,FORCE_BUY,0.24,0.445
573,2026-04-16,269790.710109,0.0,1,0.85,2.50,0.180534,FORCE_BUY,0.24,0.445
574,2026-04-17,273469.444488,0.0,1,0.85,2.50,0.189910,FORCE_BUY,0.24,0.445
575,2026-04-20,273048.096664,0.0,1,-0.50,2.25,0.150180,FORCE_BUY,0.24,0.445
576,2026-04-21,272845.787343,0.0,1,-0.50,2.25,0.181258,FORCE_BUY,0.34,0.445

,side,seen_idx,exec_px,qty,fee,reason,ts,pred,th,gate,pnl,entry_px,entry_idx
0,buy,581988,421.2401,237.394303,0.0,5m BUY signal,2024-01-22 13:25:00,1.132745,0.2,FREE,NaN,NaN,NaN
1,sell,581995,422.2700,237.394303,0.0,5m SELL signal,2024-01-22 14:00:00,1.855192,-0.5,FREE,244.492393,421.2401,581988.0
2,buy,581999,421.5700,237.788487,0.0,5m BUY signal,2024-01-22 14:20:00,1.110677,0.2,FREE,NaN,NaN,NaN
3,sell,582009,422.0600,237.788487,0.0,5m SELL signal,2024-01-22 15:10:00,1.354036,-0.5,FREE,116.516359,421.5700,581999.0
4,buy,582018,421.7200,237.980197,0.0,5m BUY signal,2024-01-22 15:55:00,0.827127,0.2,FREE,NaN,NaN,NaN

In [1]:
from pathlib import Path
import pandas as pd

from adaptive_reward_checkpoint_fresh import (
    build_adaptive_reward_snapshot,
    run_adaptive_reward_from_snapshot,
)
from adaptive_trade_extensions import RollingThresholdConfig, make_threshold_grid

snapshot_path = Path("checkpoints") / "SPY_adaptive_reward_fresh_start_90days_at_2020.joblib"

common_kwargs = dict(
    daily_csv_path="DataAPI/data/SPY_DAY.csv",
    k5m_csv_path="DataAPI/data/SPY_5M.csv",
    code="SPY",
    daily_chan_start="2008-01-01",
    accumulation_start="2010-01-01",
    N_confirm=5,
    min_labeled_days_to_train=200,
    retrain_every_new_labels=25,
    dp_lookback=5,
    lookahead_days_5m=2.0,
    retrain_every_days_5m=5,
    min_samples_total_5m=300,
    threshold_window_days=2.0,
    threshold_ret_grid=None,
    threshold_min_open_signals=10,
    initial_capital=100000.0,
    fee_pct=0.0,
    daily_chan_max_klines=500,
    five_chan_max_klines=500,
    macro_files={
        "vix_": "VIX.csv",
    },
    static_buy_level=0.20,
    static_sell_level=0.30,
    daily_threshold_config=RollingThresholdConfig(
        lookback_days=252,
        buy_grid=make_threshold_grid(0.05, 0.35, 0.005),
        sell_grid=make_threshold_grid(0.15, 0.60, 0.005),
        min_gap=0.02,
        min_obs=60,
        switch_penalty=0.0,
    ),
    verbose=True,
)

In [5]:
snapshot_res = build_adaptive_reward_snapshot(
    snapshot_path=str(snapshot_path),
    snapshot_end_time="2019-12-31",
    output_dir="output_adaptive_reward_snapshot_build_SPY_90days_at_2020",
    **common_kwargs,
)

print(snapshot_res["snapshot_path"])
display(snapshot_res["daily_reward_df"].tail())
display(snapshot_res["daily_log_df"].tail())

[TRAIN][DAILY-PROB] n=200 pos=43 (21.50%)
[TRAIN][DAILY-PROB] n=225 pos=49 (21.78%)
[TRAIN][DAILY-PROB] n=250 pos=57 (22.80%)
[TRAIN][DAILY-PROB] n=275 pos=66 (24.00%)
[TRAIN][DAILY-PROB] n=300 pos=74 (24.67%)
[TRAIN][DAILY-PROB] n=325 pos=78 (24.00%)
[TRAIN][DAILY-PROB] n=350 pos=85 (24.29%)
[TRAIN][DAILY-PROB] n=375 pos=94 (25.07%)
[TRAIN][DAILY-PROB] n=400 pos=101 (25.25%)
[TRAIN][DAILY-PROB] n=425 pos=104 (24.47%)
[TRAIN][DAILY-PROB] n=450 pos=112 (24.89%)
[TRAIN][DAILY-PROB] n=475 pos=112 (23.58%)
[TRAIN][DAILY-PROB] n=500 pos=113 (22.60%)
[TRAIN][DAILY-PROB] n=525 pos=124 (23.62%)
[TRAIN][DAILY-PROB] n=550 pos=131 (23.82%)
[TRAIN][DAILY-PROB] n=575 pos=143 (24.87%)
[TRAIN][DAILY-PROB] n=600 pos=150 (25.00%)
[TRAIN][DAILY-PROB] n=625 pos=150 (24.00%)
[TRAIN][DAILY-PROB] n=650 pos=158 (24.31%)
[TRAIN][DAILY-PROB] n=675 pos=160 (23.70%)
[TRAIN][DAILY-PROB] n=700 pos=161 (23.00%)
[TRAIN][DAILY-PROB] n=725 pos=168 (23.17%)
[TRAIN][DAILY-PROB] n=750 pos=173 (23.07%)
[TRAIN][DAILY-PROB] n=775 pos=180 (23.23%)
[TRAIN][DAILY-PROB] n=800 pos=188 (23.50%)
[TRAIN][DAILY-PROB] n=825 pos=198 (24.00%)
[TRAIN][DAILY-PROB] n=850 pos=204 (24.00%)
[TRAIN][DAILY-PROB] n=875 pos=214 (24.46%)
[TRAIN][DAILY-PROB] n=900 pos=220 (24.44%)
[TRAIN][DAILY-PROB] n=925 pos=227 (24.54%)
[TRAIN][DAILY-PROB] n=950 pos=232 (24.42%)
[TRAIN][DAILY-PROB] n=975 pos=234 (24.00%)
[TRAIN][DAILY-PROB] n=1000 pos=240 (24.00%)
[TRAIN][DAILY-PROB] n=1025 pos=248 (24.20%)
[TRAIN][DAILY-PROB] n=1050 pos=257 (24.48%)
[TRAIN][DAILY-PROB] n=1075 pos=265 (24.65%)
[TRAIN][DAILY-PROB] n=1100 pos=267 (24.27%)
[TRAIN][DAILY-PROB] n=1125 pos=275 (24.44%)
[TRAIN][DAILY-PROB] n=1150 pos=278 (24.17%)
[TRAIN][DAILY-PROB] n=1175 pos=287 (24.43%)
[TRAIN][DAILY-PROB] n=1200 pos=289 (24.08%)
[TRAIN][DAILY-PROB] n=1225 pos=295 (24.08%)
[TRAIN][DAILY-PROB] n=1250 pos=298 (23.84%)
[TRAIN][DAILY-PROB] n=1275 pos=300 (23.53%)
[TRAIN][DAILY-PROB] n=1300 pos=308 (23.69%)
[TRAIN][DAILY-PROB] n=1325 pos=313 (23.62%)
[TRAIN][DAILY-PROB] n=1350 pos=321 (23.78%)
[TRAIN][DAILY-PROB] n=1375 pos=325 (23.64%)
[TRAIN][DAILY-PROB] n=1400 pos=330 (23.57%)
[TRAIN][DAILY-PROB] n=1425 pos=334 (23.44%)
[TRAIN][DAILY-PROB] n=1450 pos=342 (23.59%)
[TRAIN][DAILY-PROB] n=1475 pos=343 (23.25%)
[TRAIN][DAILY-PROB] n=1500 pos=348 (23.20%)
[TRAIN][DAILY-PROB] n=1525 pos=353 (23.15%)
[TRAIN][DAILY-PROB] n=1550 pos=356 (22.97%)
[TRAIN][DAILY-PROB] n=1575 pos=359 (22.79%)
[TRAIN][DAILY-PROB] n=1600 pos=362 (22.62%)
[TRAIN][DAILY-PROB] n=1625 pos=371 (22.83%)
[TRAIN][DAILY-PROB] n=1650 pos=375 (22.73%)
[TRAIN][DAILY-PROB] n=1675 pos=378 (22.57%)
[TRAIN][DAILY-PROB] n=1700 pos=387 (22.76%)
[TRAIN][DAILY-PROB] n=1725 pos=390 (22.61%)
[TRAIN][DAILY-PROB] n=1750 pos=398 (22.74%)
[TRAIN][DAILY-PROB] n=1775 pos=401 (22.59%)
[TRAIN][DAILY-PROB] n=1800 pos=406 (22.56%)
[TRAIN][DAILY-PROB] n=1825 pos=421 (23.07%)
[TRAIN][DAILY-PROB] n=1850 pos=427 (23.08%)
[TRAIN][DAILY-PROB] n=1875 pos=433 (23.09%)
[TRAIN][DAILY-PROB] n=1900 pos=444 (23.37%)
[TRAIN][DAILY-PROB] n=1925 pos=454 (23.58%)
[TRAIN][DAILY-PROB] n=1950 pos=459 (23.54%)
[TRAIN][DAILY-PROB] n=1975 pos=465 (23.54%)
[TRAIN][DAILY-PROB] n=2000 pos=467 (23.35%)
[TRAIN][DAILY-PROB] n=2025 pos=472 (23.31%)
[TRAIN][DAILY-PROB] n=2050 pos=479 (23.37%)
[TRAIN][DAILY-PROB] n=2075 pos=482 (23.23%)
[TRAIN][DAILY-PROB] n=2100 pos=484 (23.05%)
[TRAIN][DAILY-PROB] n=2125 pos=492 (23.15%)
[TRAIN][DAILY-PROB] n=2150 pos=500 (23.26%)
[TRAIN][DAILY-PROB] n=2175 pos=508 (23.36%)
[TRAIN][DAILY-PROB] n=2200 pos=514 (23.36%)
[TRAIN][DAILY-PROB] n=2225 pos=518 (23.28%)
[TRAIN][DAILY-PROB] n=2250 pos=526 (23.38%)
[TRAIN][DAILY-PROB] n=2275 pos=530 (23.30%)
[TRAIN][DAILY-PROB] n=2300 pos=532 (23.13%)
[TRAIN][DAILY-PROB] n=2325 pos=538 (23.14%)
[TRAIN][DAILY-PROB] n=2350 pos=543 (23.11%)
[TRAIN][DAILY-PROB] n=2375 pos=544 (22.91%)
[TRAIN][DAILY-PROB] n=2400 pos=544 (22.67%)
[TRAIN][DAILY-PROB] n=2425 pos=547 (22.56%)
[TRAIN][DAILY-PROB] n=2450 pos=549 (22.41%)
[TRAIN][DAILY-PROB] n=2475 pos=557 (22.51%)
[TRAIN][DAILY-PROB] n=2500 pos=567 (22.68%)
[TRAIN][DAILY-PROB] n=2525 pos=571 (22.61%)
[TRAIN][DAILY-PROB] n=2550 pos=574 (22.51%)
[TRAIN][DAILY-PROB] n=2575 pos=581 (22.56%)
[TRAIN][DAILY-PROB] n=2600 pos=586 (22.54%)
[TRAIN][DAILY-PROB] n=2625 pos=592 (22.55%)
[TRAIN][DAILY-PROB] n=2650 pos=603 (22.75%)
[TRAIN][DAILY-PROB] n=2675 pos=611 (22.84%)
[TRAIN][DAILY-PROB] n=2700 pos=615 (22.78%)
[TRAIN][DAILY-PROB] n=2725 pos=616 (22.61%)
[TRAIN][DAILY-PROB] n=2750 pos=623 (22.65%)
[TRAIN][DAILY-PROB] n=2775 pos=624 (22.49%)
[TRAIN][DAILY-PROB] n=2800 pos=634 (22.64%)
[TRAIN][DAILY-PROB] n=2825 pos=637 (22.55%)
[TRAIN][DAILY-PROB] n=2850 pos=646 (22.67%)
[TRAIN][DAILY-PROB] n=2875 pos=650 (22.61%)
[TRAIN][DAILY-PROB] n=2900 pos=655 (22.59%)
[TRAIN][DAILY-PROB] n=2925 pos=656 (22.43%)
[TRAIN][5M] asof=2010-02-03 feats=69 buy=NO sell=YES rows=587
[TRAIN][5M] asof=2010-02-08 feats=69 buy=NO sell=YES rows=677
[TRAIN][5M] asof=2010-02-16 feats=69 buy=YES sell=YES rows=804
[TRAIN][5M] asof=2010-02-22 feats=69 buy=YES sell=YES rows=923
[TRAIN][5M] asof=2010-03-01 feats=69 buy=YES sell=YES rows=1091
[TRAIN][5M] asof=2010-03-08 feats=69 buy=YES sell=YES rows=1223
[TRAIN][5M] asof=2010-03-15 feats=69 buy=YES sell=YES rows=1368
[TRAIN][5M] asof=2010-03-22 feats=69 buy=YES sell=YES rows=1487
[TRAIN][5M] asof=2010-03-29 feats=69 buy=YES sell=YES rows=1573
[TRAIN][5M] asof=2010-04-05 feats=69 buy=YES sell=YES rows=1709
[TRAIN][5M] asof=2010-04-12 feats=69 buy=YES sell=YES rows=1845
[TRAIN][5M] asof=2010-04-19 feats=69 buy=YES sell=YES rows=1983
[TRAIN][5M] asof=2010-04-26 feats=69 buy=YES sell=YES rows=2105
[TRAIN][5M] asof=2010-05-03 feats=69 buy=YES sell=YES rows=2250
[TRAIN][5M] asof=2010-05-10 feats=69 buy=YES sell=YES rows=2348
[TRAIN][5M] asof=2010-05-17 feats=69 buy=YES sell=YES rows=2506
[TRAIN][5M] asof=2010-05-24 feats=69 buy=YES sell=YES rows=2723
[TRAIN][5M] asof=2010-06-01 feats=69 buy=YES sell=YES rows=2888
[TRAIN][5M] asof=2010-06-07 feats=69 buy=YES sell=YES rows=3027
[TRAIN][5M] asof=2010-06-14 feats=69 buy=YES sell=YES rows=3162
[TRAIN][5M] asof=2010-06-21 feats=69 buy=YES sell=YES rows=3227
[TRAIN][5M] asof=2010-06-28 feats=69 buy=YES sell=YES rows=3382
[TRAIN][5M] asof=2010-07-06 feats=69 buy=YES sell=YES rows=3547
[TRAIN][5M] asof=2010-07-12 feats=69 buy=YES sell=YES rows=3680
[TRAIN][5M] asof=2010-07-19 feats=69 buy=YES sell=YES rows=3845
[TRAIN][5M] asof=2010-07-26 feats=69 buy=YES sell=YES rows=4037
[TRAIN][5M] asof=2010-08-02 feats=69 buy=YES sell=YES rows=4139
[TRAIN][5M] asof=2010-08-09 feats=69 buy=YES sell=YES rows=4281
[TRAIN][5M] asof=2010-08-16 feats=69 buy=YES sell=YES rows=4446
[TRAIN][5M] asof=2010-08-23 feats=69 buy=YES sell=YES rows=4558
[TRAIN][5M] asof=2010-08-30 feats=69 buy=YES sell=YES rows=4713
[TRAIN][5M] asof=2010-09-07 feats=69 buy=YES sell=YES rows=4816
[TRAIN][5M] asof=2010-09-13 feats=69 buy=YES sell=YES rows=5014
[TRAIN][5M] asof=2010-09-20 feats=69 buy=YES sell=YES rows=5202
[TRAIN][5M] asof=2010-09-27 feats=69 buy=YES sell=YES rows=5324
[TRAIN][5M] asof=2010-10-04 feats=69 buy=YES sell=YES rows=5563
[TRAIN][5M] asof=2010-10-11 feats=69 buy=YES sell=YES rows=5693
[TRAIN][5M] asof=2010-10-18 feats=69 buy=YES sell=YES rows=5853
[TRAIN][5M] asof=2010-10-25 feats=69 buy=YES sell=YES rows=5992
[TRAIN][5M] asof=2010-11-01 feats=69 buy=YES sell=YES rows=6165
[TRAIN][5M] asof=2010-11-08 feats=69 buy=YES sell=YES rows=6288
[TRAIN][5M] asof=2010-11-15 feats=69 buy=YES sell=YES rows=6473
[TRAIN][5M] asof=2010-11-22 feats=69 buy=YES sell=YES rows=6586
[TRAIN][5M] asof=2010-11-29 feats=69 buy=YES sell=YES rows=6730
[TRAIN][5M] asof=2010-12-06 feats=69 buy=YES sell=YES rows=6915
[TRAIN][5M] asof=2010-12-13 feats=69 buy=YES sell=YES rows=7069
[TRAIN][5M] asof=2010-12-20 feats=69 buy=YES sell=YES rows=7250
[TRAIN][5M] asof=2010-12-27 feats=69 buy=YES sell=YES rows=7367
[TRAIN][5M] asof=2011-01-03 feats=69 buy=YES sell=YES rows=7473
[TRAIN][5M] asof=2011-01-10 feats=69 buy=YES sell=YES rows=7584
[TRAIN][5M] asof=2011-01-18 feats=69 buy=YES sell=YES rows=7743
[TRAIN][5M] asof=2011-01-24 feats=69 buy=YES sell=YES rows=7867
[TRAIN][5M] asof=2011-01-31 feats=69 buy=YES sell=YES rows=8067
[TRAIN][5M] asof=2011-02-07 feats=69 buy=YES sell=YES rows=8176
[TRAIN][5M] asof=2011-02-14 feats=69 buy=YES sell=YES rows=8329
[TRAIN][5M] asof=2011-02-22 feats=69 buy=YES sell=YES rows=8484
[TRAIN][5M] asof=2011-02-28 feats=69 buy=YES sell=YES rows=8650
[TRAIN][5M] asof=2011-03-07 feats=69 buy=YES sell=YES rows=8802
[TRAIN][5M] asof=2011-03-14 feats=69 buy=YES sell=YES rows=8948
[TRAIN][5M] asof=2011-03-21 feats=69 buy=YES sell=YES rows=9048
[TRAIN][5M] asof=2011-03-28 feats=69 buy=YES sell=YES rows=9222
[TRAIN][5M] asof=2011-04-04 feats=69 buy=YES sell=YES rows=9346
[TRAIN][5M] asof=2011-04-11 feats=69 buy=YES sell=YES rows=9488
[TRAIN][5M] asof=2011-04-18 feats=69 buy=YES sell=YES rows=9681
[TRAIN][5M] asof=2011-04-25 feats=69 buy=YES sell=YES rows=9828
[TRAIN][5M] asof=2011-05-02 feats=69 buy=YES sell=YES rows=10015
[TRAIN][5M] asof=2011-05-09 feats=69 buy=YES sell=YES rows=10197
[TRAIN][5M] asof=2011-05-16 feats=69 buy=YES sell=YES rows=10400
[TRAIN][5M] asof=2011-05-23 feats=69 buy=YES sell=YES rows=10568
[TRAIN][5M] asof=2011-05-31 feats=69 buy=YES sell=YES rows=10737
[TRAIN][5M] asof=2011-06-06 feats=69 buy=YES sell=YES rows=10844
[TRAIN][5M] asof=2011-06-13 feats=69 buy=YES sell=YES rows=11012
[TRAIN][5M] asof=2011-06-20 feats=69 buy=YES sell=YES rows=11194
[TRAIN][5M] asof=2011-06-27 feats=69 buy=YES sell=YES rows=11349
[TRAIN][5M] asof=2011-07-05 feats=69 buy=YES sell=YES rows=11515
[TRAIN][5M] asof=2011-07-11 feats=69 buy=YES sell=YES rows=11657
[TRAIN][5M] asof=2011-07-18 feats=69 buy=YES sell=YES rows=11849
[TRAIN][5M] asof=2011-07-25 feats=69 buy=YES sell=YES rows=11985
[TRAIN][5M] asof=2011-08-01 feats=69 buy=YES sell=YES rows=12157
[TRAIN][5M] asof=2011-08-08 feats=69 buy=YES sell=YES rows=12381
[TRAIN][5M] asof=2011-08-15 feats=69 buy=YES sell=YES rows=12573
[TRAIN][5M] asof=2011-08-22 feats=69 buy=YES sell=YES rows=12739
[TRAIN][5M] asof=2011-08-29 feats=69 buy=YES sell=YES rows=12909
[TRAIN][5M] asof=2011-09-06 feats=69 buy=YES sell=YES rows=13075
[TRAIN][5M] asof=2011-09-12 feats=69 buy=YES sell=YES rows=13208
[TRAIN][5M] asof=2011-09-19 feats=69 buy=YES sell=YES rows=13373
[TRAIN][5M] asof=2011-09-26 feats=69 buy=YES sell=YES rows=13551
[TRAIN][5M] asof=2011-10-03 feats=69 buy=YES sell=YES rows=13714
[TRAIN][5M] asof=2011-10-10 feats=69 buy=YES sell=YES rows=13825
[TRAIN][5M] asof=2011-10-17 feats=69 buy=YES sell=YES rows=14011
[TRAIN][5M] asof=2011-10-24 feats=69 buy=YES sell=YES rows=14173
[TRAIN][5M] asof=2011-10-31 feats=69 buy=YES sell=YES rows=14332
[TRAIN][5M] asof=2011-11-07 feats=69 buy=YES sell=YES rows=14422
[TRAIN][5M] asof=2011-11-14 feats=69 buy=YES sell=YES rows=14583
[TRAIN][5M] asof=2011-11-21 feats=69 buy=YES sell=YES rows=14743
[TRAIN][5M] asof=2011-11-28 feats=69 buy=YES sell=YES rows=14889
[TRAIN][5M] asof=2011-12-05 feats=69 buy=YES sell=YES rows=15070
[TRAIN][5M] asof=2011-12-12 feats=69 buy=YES sell=YES rows=15237
[TRAIN][5M] asof=2011-12-19 feats=69 buy=YES sell=YES rows=15369
[TRAIN][5M] asof=2011-12-27 feats=69 buy=YES sell=YES rows=15494
[TRAIN][5M] asof=2012-01-03 feats=69 buy=YES sell=YES rows=15563
[TRAIN][5M] asof=2012-01-09 feats=69 buy=YES sell=YES rows=15619
[TRAIN][5M] asof=2012-01-17 feats=69 buy=YES sell=YES rows=15794
[TRAIN][5M] asof=2012-01-23 feats=69 buy=YES sell=YES rows=15961
[TRAIN][5M] asof=2012-01-30 feats=69 buy=YES sell=YES rows=16144
[TRAIN][5M] asof=2012-02-06 feats=69 buy=YES sell=YES rows=16247
[TRAIN][5M] asof=2012-02-13 feats=69 buy=YES sell=YES rows=16349
[TRAIN][5M] asof=2012-02-21 feats=69 buy=YES sell=YES rows=16540
[TRAIN][5M] asof=2012-02-27 feats=69 buy=YES sell=YES rows=16670
[TRAIN][5M] asof=2012-03-05 feats=69 buy=YES sell=YES rows=16775
[TRAIN][5M] asof=2012-03-12 feats=69 buy=YES sell=YES rows=16869
[TRAIN][5M] asof=2012-03-19 feats=69 buy=YES sell=YES rows=17054
[TRAIN][5M] asof=2012-03-26 feats=69 buy=YES sell=YES rows=17260
[TRAIN][5M] asof=2012-04-02 feats=69 buy=YES sell=YES rows=17426
[TRAIN][5M] asof=2012-04-09 feats=69 buy=YES sell=YES rows=17521
[TRAIN][5M] asof=2012-04-16 feats=69 buy=YES sell=YES rows=17625
[TRAIN][5M] asof=2012-04-23 feats=69 buy=YES sell=YES rows=17737
[TRAIN][5M] asof=2012-04-30 feats=69 buy=YES sell=YES rows=17868
[TRAIN][5M] asof=2012-05-07 feats=69 buy=YES sell=YES rows=18047
[TRAIN][5M] asof=2012-05-14 feats=69 buy=YES sell=YES rows=18264
[TRAIN][5M] asof=2012-05-21 feats=69 buy=YES sell=YES rows=18442
[TRAIN][5M] asof=2012-05-29 feats=69 buy=YES sell=YES rows=18559
[TRAIN][5M] asof=2012-06-04 feats=69 buy=YES sell=YES rows=18674
[TRAIN][5M] asof=2012-06-11 feats=69 buy=YES sell=YES rows=18830
[TRAIN][5M] asof=2012-06-18 feats=69 buy=YES sell=YES rows=18989
[TRAIN][5M] asof=2012-06-25 feats=69 buy=YES sell=YES rows=19153
[TRAIN][5M] asof=2012-07-02 feats=69 buy=YES sell=YES rows=19268
[TRAIN][5M] asof=2012-07-09 feats=69 buy=YES sell=YES rows=19395
[TRAIN][5M] asof=2012-07-16 feats=69 buy=YES sell=YES rows=19508
[TRAIN][5M] asof=2012-07-23 feats=69 buy=YES sell=YES rows=19652
[TRAIN][5M] asof=2012-07-30 feats=69 buy=YES sell=YES rows=19752
[TRAIN][5M] asof=2012-08-06 feats=69 buy=YES sell=YES rows=19891
[TRAIN][5M] asof=2012-08-13 feats=69 buy=YES sell=YES rows=20074
[TRAIN][5M] asof=2012-08-20 feats=69 buy=YES sell=YES rows=20211
[TRAIN][5M] asof=2012-08-27 feats=69 buy=YES sell=YES rows=20367
[TRAIN][5M] asof=2012-09-04 feats=69 buy=YES sell=YES rows=20487
[TRAIN][5M] asof=2012-09-10 feats=69 buy=YES sell=YES rows=20636
[TRAIN][5M] asof=2012-09-17 feats=69 buy=YES sell=YES rows=20807
[TRAIN][5M] asof=2012-09-24 feats=69 buy=YES sell=YES rows=20919
[TRAIN][5M] asof=2012-10-01 feats=69 buy=YES sell=YES rows=21030
[TRAIN][5M] asof=2012-10-08 feats=69 buy=YES sell=YES rows=21163
[TRAIN][5M] asof=2012-10-15 feats=69 buy=YES sell=YES rows=21282
[TRAIN][5M] asof=2012-10-22 feats=69 buy=YES sell=YES rows=21399
[TRAIN][5M] asof=2012-10-31 feats=69 buy=YES sell=YES rows=21552
[TRAIN][5M] asof=2012-11-05 feats=69 buy=YES sell=YES rows=21673
[TRAIN][5M] asof=2012-11-12 feats=69 buy=YES sell=YES rows=21880
[TRAIN][5M] asof=2012-11-19 feats=69 buy=YES sell=YES rows=22049
[TRAIN][5M] asof=2012-11-26 feats=69 buy=YES sell=YES rows=22156
[TRAIN][5M] asof=2012-12-03 feats=69 buy=YES sell=YES rows=22306
[TRAIN][5M] asof=2012-12-10 feats=69 buy=YES sell=YES rows=22416
[TRAIN][5M] asof=2012-12-17 feats=69 buy=YES sell=YES rows=22546
[TRAIN][5M] asof=2012-12-24 feats=69 buy=YES sell=YES rows=22656
[TRAIN][5M] asof=2012-12-31 feats=69 buy=YES sell=YES rows=22773
[TRAIN][5M] asof=2013-01-07 feats=69 buy=YES sell=YES rows=22871
[TRAIN][5M] asof=2013-01-14 feats=69 buy=YES sell=YES rows=23094
[TRAIN][5M] asof=2013-01-22 feats=69 buy=YES sell=YES rows=23225
[TRAIN][5M] asof=2013-01-28 feats=69 buy=YES sell=YES rows=23353
[TRAIN][5M] asof=2013-02-04 feats=69 buy=YES sell=YES rows=23555
[TRAIN][5M] asof=2013-02-11 feats=69 buy=YES sell=YES rows=23696
[TRAIN][5M] asof=2013-02-19 feats=69 buy=YES sell=YES rows=23856
[TRAIN][5M] asof=2013-02-25 feats=69 buy=YES sell=YES rows=23976
[TRAIN][5M] asof=2013-03-04 feats=69 buy=YES sell=YES rows=24065
[TRAIN][5M] asof=2013-03-11 feats=69 buy=YES sell=YES rows=24249
[TRAIN][5M] asof=2013-03-18 feats=69 buy=YES sell=YES rows=24446
[TRAIN][5M] asof=2013-03-25 feats=69 buy=YES sell=YES rows=24604
[TRAIN][5M] asof=2013-04-01 feats=69 buy=YES sell=YES rows=24774
[TRAIN][5M] asof=2013-04-08 feats=69 buy=YES sell=YES rows=24958
[TRAIN][5M] asof=2013-04-15 feats=69 buy=YES sell=YES rows=25124
[TRAIN][5M] asof=2013-04-22 feats=69 buy=YES sell=YES rows=25274
[TRAIN][5M] asof=2013-04-29 feats=69 buy=YES sell=YES rows=25454
[TRAIN][5M] asof=2013-05-06 feats=69 buy=YES sell=YES rows=25575
[TRAIN][5M] asof=2013-05-13 feats=69 buy=YES sell=YES rows=25735
[TRAIN][5M] asof=2013-05-20 feats=69 buy=YES sell=YES rows=25838
[TRAIN][5M] asof=2013-05-28 feats=69 buy=YES sell=YES rows=26012
[TRAIN][5M] asof=2013-06-03 feats=69 buy=YES sell=YES rows=26173
[TRAIN][5M] asof=2013-06-10 feats=69 buy=YES sell=YES rows=26342
[TRAIN][5M] asof=2013-06-17 feats=69 buy=YES sell=YES rows=26518
[TRAIN][5M] asof=2013-06-24 feats=69 buy=YES sell=YES rows=26721
[TRAIN][5M] asof=2013-07-01 feats=69 buy=YES sell=YES rows=26921
[TRAIN][5M] asof=2013-07-08 feats=69 buy=YES sell=YES rows=27027
[TRAIN][5M] asof=2013-07-15 feats=69 buy=YES sell=YES rows=27170
[TRAIN][5M] asof=2013-07-22 feats=69 buy=YES sell=YES rows=27305
[TRAIN][5M] asof=2013-07-29 feats=69 buy=YES sell=YES rows=27509
[TRAIN][5M] asof=2013-08-05 feats=69 buy=YES sell=YES rows=27675
[TRAIN][5M] asof=2013-08-12 feats=69 buy=YES sell=YES rows=27877
[TRAIN][5M] asof=2013-08-19 feats=69 buy=YES sell=YES rows=28091
[TRAIN][5M] asof=2013-08-26 feats=69 buy=YES sell=YES rows=28220
[TRAIN][5M] asof=2013-09-03 feats=69 buy=YES sell=YES rows=28372
[TRAIN][5M] asof=2013-09-09 feats=69 buy=YES sell=YES rows=28468
[TRAIN][5M] asof=2013-09-16 feats=69 buy=YES sell=YES rows=28604
[TRAIN][5M] asof=2013-09-23 feats=69 buy=YES sell=YES rows=28767
[TRAIN][5M] asof=2013-09-30 feats=69 buy=YES sell=YES rows=28933
[TRAIN][5M] asof=2013-10-07 feats=69 buy=YES sell=YES rows=29089
[TRAIN][5M] asof=2013-10-14 feats=69 buy=YES sell=YES rows=29228
[TRAIN][5M] asof=2013-10-21 feats=69 buy=YES sell=YES rows=29377
[TRAIN][5M] asof=2013-10-28 feats=69 buy=YES sell=YES rows=29506
[TRAIN][5M] asof=2013-11-04 feats=69 buy=YES sell=YES rows=29679
[TRAIN][5M] asof=2013-11-11 feats=69 buy=YES sell=YES rows=29779
[TRAIN][5M] asof=2013-11-18 feats=69 buy=YES sell=YES rows=29945
[TRAIN][5M] asof=2013-11-25 feats=69 buy=YES sell=YES rows=30112
[TRAIN][5M] asof=2013-12-02 feats=69 buy=YES sell=YES rows=30204
[TRAIN][5M] asof=2013-12-09 feats=69 buy=YES sell=YES rows=30363
[TRAIN][5M] asof=2013-12-16 feats=69 buy=YES sell=YES rows=30545
[TRAIN][5M] asof=2013-12-23 feats=69 buy=YES sell=YES rows=30626
[TRAIN][5M] asof=2013-12-30 feats=69 buy=YES sell=YES rows=30760
[TRAIN][5M] asof=2014-01-06 feats=69 buy=YES sell=YES rows=30918
[TRAIN][5M] asof=2014-01-13 feats=69 buy=YES sell=YES rows=31119
[TRAIN][5M] asof=2014-01-21 feats=69 buy=YES sell=YES rows=31185
[TRAIN][5M] asof=2014-01-27 feats=69 buy=YES sell=YES rows=31329
[TRAIN][5M] asof=2014-02-03 feats=69 buy=YES sell=YES rows=31473
[TRAIN][5M] asof=2014-02-10 feats=69 buy=YES sell=YES rows=31623
[TRAIN][5M] asof=2014-02-18 feats=69 buy=YES sell=YES rows=31826
[TRAIN][5M] asof=2014-02-24 feats=69 buy=YES sell=YES rows=31954
[TRAIN][5M] asof=2014-03-03 feats=69 buy=YES sell=YES rows=32036
[TRAIN][5M] asof=2014-03-10 feats=69 buy=YES sell=YES rows=32177
[TRAIN][5M] asof=2014-03-17 feats=69 buy=YES sell=YES rows=32366
[TRAIN][5M] asof=2014-03-24 feats=69 buy=YES sell=YES rows=32502
[TRAIN][5M] asof=2014-03-31 feats=69 buy=YES sell=YES rows=32652
[TRAIN][5M] asof=2014-04-07 feats=69 buy=YES sell=YES rows=32803
[TRAIN][5M] asof=2014-04-14 feats=69 buy=YES sell=YES rows=33012
[TRAIN][5M] asof=2014-04-21 feats=69 buy=YES sell=YES rows=33137
[TRAIN][5M] asof=2014-04-28 feats=69 buy=YES sell=YES rows=33275
[TRAIN][5M] asof=2014-05-05 feats=69 buy=YES sell=YES rows=33374
[TRAIN][5M] asof=2014-05-12 feats=69 buy=YES sell=YES rows=33580
[TRAIN][5M] asof=2014-05-19 feats=69 buy=YES sell=YES rows=33769
[TRAIN][5M] asof=2014-05-27 feats=69 buy=YES sell=YES rows=33922
[TRAIN][5M] asof=2014-06-02 feats=69 buy=YES sell=YES rows=34036
[TRAIN][5M] asof=2014-06-09 feats=69 buy=YES sell=YES rows=34201
[TRAIN][5M] asof=2014-06-16 feats=69 buy=YES sell=YES rows=34403
[TRAIN][5M] asof=2014-06-23 feats=69 buy=YES sell=YES rows=34551
[TRAIN][5M] asof=2014-06-30 feats=69 buy=YES sell=YES rows=34674
[TRAIN][5M] asof=2014-07-07 feats=69 buy=YES sell=YES rows=34738
[TRAIN][5M] asof=2014-07-14 feats=69 buy=YES sell=YES rows=34863
[TRAIN][5M] asof=2014-07-21 feats=69 buy=YES sell=YES rows=35005

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
2510,2019-12-23,0.147412,0.155,0.18,FORCE_BUY,0.000031,0.000031,0.000031,0.000031,FORCE_BUY,5.100441e+07,321.35,1.25,1.95
2511,2019-12-24,0.136711,0.155,0.18,FORCE_BUY,-0.000715,-0.000715,-0.000715,-0.000715,FORCE_BUY,5.096792e+07,321.24,1.25,1.95
2512,2019-12-26,0.125245,0.155,0.18,FORCE_BUY,0.005754,0.000653,0.000653,0.005754,FORCE_BUY,5.126117e+07,323.39,1.50,-0.50
2513,2019-12-27,0.156382,0.155,0.18,FREE,-0.003770,-0.001997,-0.000031,-0.001997,FORCE_SELL,5.125958e+07,322.39,1.50,-0.50
2514,2019-12-30,0.191498,0.155,0.18,FORCE_SELL,-0.005354,0.002557,-0.000093,-0.000093,FREE,5.139065e+07,321.38,1.50,-0.50

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
2510,2019-12-23,389266.697318,0.000000,1,1.25,1.95,0.147412,FORCE_BUY,0.155,0.18
2511,2019-12-24,389133.449032,0.000000,1,1.50,-0.50,0.136711,FORCE_BUY,0.155,0.18
2512,2019-12-26,391737.847349,0.000000,1,1.50,-0.50,0.125245,FORCE_BUY,0.155,0.18
2513,2019-12-27,391221.655202,0.000000,1,1.50,-0.50,0.156382,FREE,0.155,0.18
2514,2019-12-30,392058.973178,392058.973178,0,1.50,-0.50,0.191498,FORCE_SELL,0.155,0.18

In [2]:
resume_res = run_adaptive_reward_from_snapshot(
    dp_lookback_override=252,
    snapshot_path=str(snapshot_path),
    end_time="2026-12-31",
    sim_start="2020-01-01",
    initial_capital=100000.0,
    fee_pct=0.0,
    output_dir="output_adaptive_reward_resumed_fresh_SPY_252days_at_2020",
    # Optional. If omitted, the code saves next to the source snapshot as
    # checkpoints/SPY_adaptive_reward_fresh_start__continued.joblib
    save_snapshot_path=None,
    verbose=True,
)

print("continued snapshot:", resume_res["continued_snapshot_path"])

display(resume_res["daily_reward_df"].tail())
display(resume_res["daily_log_df"].tail())
display(resume_res["trades_df"].head())

[TRAIN][DAILY-PROB] n=2963 pos=658 (22.21%)
[TRAIN][DAILY-PROB] n=2988 pos=668 (22.36%)
[TRAIN][DAILY-PROB] n=3013 pos=683 (22.67%)
[TRAIN][DAILY-PROB] n=3038 pos=690 (22.71%)
[TRAIN][DAILY-PROB] n=3063 pos=696 (22.72%)
[TRAIN][DAILY-PROB] n=3088 pos=697 (22.57%)
[TRAIN][DAILY-PROB] n=3113 pos=698 (22.42%)
[TRAIN][DAILY-PROB] n=3138 pos=704 (22.43%)
[TRAIN][DAILY-PROB] n=3163 pos=714 (22.57%)
[TRAIN][DAILY-PROB] n=3188 pos=715 (22.43%)
[TRAIN][DAILY-PROB] n=3213 pos=718 (22.35%)
[TRAIN][DAILY-PROB] n=3238 pos=725 (22.39%)
[TRAIN][DAILY-PROB] n=3263 pos=727 (22.28%)
[TRAIN][DAILY-PROB] n=3288 pos=730 (22.20%)
[TRAIN][DAILY-PROB] n=3313 pos=732 (22.09%)
[TRAIN][DAILY-PROB] n=3338 pos=733 (21.96%)
[TRAIN][DAILY-PROB] n=3363 pos=733 (21.80%)
[TRAIN][DAILY-PROB] n=3388 pos=747 (22.05%)
[TRAIN][DAILY-PROB] n=3413 pos=749 (21.95%)
[TRAIN][DAILY-PROB] n=3438 pos=753 (21.90%)
[TRAIN][DAILY-PROB] n=3463 pos=762 (22.00%)
[TRAIN][DAILY-PROB] n=3488 pos=770 (22.08%)
[TRAIN][DAILY-PROB] n=3513 pos=777 (22.12%)
[TRAIN][DAILY-PROB] n=3538 pos=777 (21.96%)
[TRAIN][DAILY-PROB] n=3563 pos=787 (22.09%)
[TRAIN][DAILY-PROB] n=3588 pos=795 (22.16%)
[TRAIN][DAILY-PROB] n=3613 pos=801 (22.17%)
[TRAIN][DAILY-PROB] n=3638 pos=809 (22.24%)
[TRAIN][DAILY-PROB] n=3663 pos=817 (22.30%)
[TRAIN][DAILY-PROB] n=3688 pos=823 (22.32%)
[TRAIN][DAILY-PROB] n=3713 pos=828 (22.30%)
[TRAIN][DAILY-PROB] n=3738 pos=835 (22.34%)
[TRAIN][DAILY-PROB] n=3763 pos=840 (22.32%)
[TRAIN][DAILY-PROB] n=3788 pos=847 (22.36%)
[TRAIN][DAILY-PROB] n=3813 pos=851 (22.32%)
[TRAIN][DAILY-PROB] n=3838 pos=859 (22.38%)
[TRAIN][DAILY-PROB] n=3863 pos=868 (22.47%)
[TRAIN][DAILY-PROB] n=3888 pos=875 (22.51%)
[TRAIN][DAILY-PROB] n=3913 pos=886 (22.64%)
[TRAIN][DAILY-PROB] n=3938 pos=886 (22.50%)
[TRAIN][DAILY-PROB] n=3963 pos=890 (22.46%)
[TRAIN][DAILY-PROB] n=3988 pos=891 (22.34%)
[TRAIN][DAILY-PROB] n=4013 pos=895 (22.30%)
[TRAIN][DAILY-PROB] n=4038 pos=901 (22.31%)
[TRAIN][DAILY-PROB] n=4063 pos=908 (22.35%)
[TRAIN][DAILY-PROB] n=4088 pos=912 (22.31%)
[TRAIN][DAILY-PROB] n=4113 pos=915 (22.25%)
[TRAIN][DAILY-PROB] n=4138 pos=920 (22.23%)
[TRAIN][DAILY-PROB] n=4163 pos=925 (22.22%)
[TRAIN][DAILY-PROB] n=4188 pos=931 (22.23%)
[TRAIN][DAILY-PROB] n=4213 pos=936 (22.22%)
[TRAIN][DAILY-PROB] n=4238 pos=943 (22.25%)
[TRAIN][DAILY-PROB] n=4263 pos=951 (22.31%)
[TRAIN][DAILY-PROB] n=4288 pos=959 (22.36%)
[TRAIN][DAILY-PROB] n=4313 pos=962 (22.30%)
[TRAIN][DAILY-PROB] n=4338 pos=963 (22.20%)
[TRAIN][DAILY-PROB] n=4363 pos=968 (22.19%)
[TRAIN][DAILY-PROB] n=4388 pos=979 (22.31%)
[TRAIN][DAILY-PROB] n=4413 pos=987 (22.37%)
[TRAIN][DAILY-PROB] n=4438 pos=995 (22.42%)
[TRAIN][DAILY-PROB] n=4463 pos=1004 (22.50%)
[TRAIN][DAILY-PROB] n=4488 pos=1011 (22.53%)
[TRAIN][DAILY-PROB] n=4513 pos=1022 (22.65%)
[TRAIN][5M] asof=2019-12-31 feats=69 buy=YES sell=YES rows=81935
[TRAIN][5M] asof=2020-01-06 feats=69 buy=YES sell=YES rows=82061
[TRAIN][5M] asof=2020-01-13 feats=69 buy=YES sell=YES rows=82265
[TRAIN][5M] asof=2020-01-21 feats=69 buy=YES sell=YES rows=82465
[TRAIN][5M] asof=2020-01-27 feats=69 buy=YES sell=YES rows=82607
[TRAIN][5M] asof=2020-02-03 feats=69 buy=YES sell=YES rows=82692
[TRAIN][5M] asof=2020-02-10 feats=69 buy=YES sell=YES rows=82896
[TRAIN][5M] asof=2020-02-18 feats=69 buy=YES sell=YES rows=83115
[TRAIN][5M] asof=2020-02-24 feats=69 buy=YES sell=YES rows=83271
[TRAIN][5M] asof=2020-03-02 feats=69 buy=YES sell=YES rows=83433
[TRAIN][5M] asof=2020-03-09 feats=69 buy=YES sell=YES rows=83600
[TRAIN][5M] asof=2020-03-16 feats=69 buy=YES sell=YES rows=83781
[TRAIN][5M] asof=2020-03-23 feats=69 buy=YES sell=YES rows=84031
[TRAIN][5M] asof=2020-03-30 feats=69 buy=YES sell=YES rows=84216
[TRAIN][5M] asof=2020-04-06 feats=69 buy=YES sell=YES rows=84384
[TRAIN][5M] asof=2020-04-13 feats=69 buy=YES sell=YES rows=84548
[TRAIN][5M] asof=2020-04-20 feats=69 buy=YES sell=YES rows=84697
[TRAIN][5M] asof=2020-04-27 feats=69 buy=YES sell=YES rows=84879
[TRAIN][5M] asof=2020-05-04 feats=69 buy=YES sell=YES rows=85030
[TRAIN][5M] asof=2020-05-11 feats=69 buy=YES sell=YES rows=85206
[TRAIN][5M] asof=2020-05-18 feats=69 buy=YES sell=YES rows=85404
[TRAIN][5M] asof=2020-05-26 feats=69 buy=YES sell=YES rows=85586
[TRAIN][5M] asof=2020-06-01 feats=69 buy=YES sell=YES rows=85750
[TRAIN][5M] asof=2020-06-08 feats=69 buy=YES sell=YES rows=85983
[TRAIN][5M] asof=2020-06-15 feats=69 buy=YES sell=YES rows=86173
[TRAIN][5M] asof=2020-06-22 feats=69 buy=YES sell=YES rows=86449
[TRAIN][5M] asof=2020-06-29 feats=69 buy=YES sell=YES rows=86609
[TRAIN][5M] asof=2020-07-06 feats=69 buy=YES sell=YES rows=86735
[TRAIN][5M] asof=2020-07-13 feats=69 buy=YES sell=YES rows=86920
[TRAIN][5M] asof=2020-07-20 feats=69 buy=YES sell=YES rows=87106
[TRAIN][5M] asof=2020-07-27 feats=69 buy=YES sell=YES rows=87294
[TRAIN][5M] asof=2020-08-03 feats=69 buy=YES sell=YES rows=87468
[TRAIN][5M] asof=2020-08-10 feats=69 buy=YES sell=YES rows=87613
[TRAIN][5M] asof=2020-08-17 feats=69 buy=YES sell=YES rows=87815
[TRAIN][5M] asof=2020-08-24 feats=69 buy=YES sell=YES rows=87979
[TRAIN][5M] asof=2020-08-31 feats=69 buy=YES sell=YES rows=88178
[TRAIN][5M] asof=2020-09-08 feats=69 buy=YES sell=YES rows=88411
[TRAIN][5M] asof=2020-09-14 feats=69 buy=YES sell=YES rows=88584
[TRAIN][5M] asof=2020-09-21 feats=69 buy=YES sell=YES rows=88771
[TRAIN][5M] asof=2020-09-28 feats=69 buy=YES sell=YES rows=88960
[TRAIN][5M] asof=2020-10-05 feats=69 buy=YES sell=YES rows=89160
[TRAIN][5M] asof=2020-10-12 feats=69 buy=YES sell=YES rows=89334
[TRAIN][5M] asof=2020-10-19 feats=69 buy=YES sell=YES rows=89562
[TRAIN][5M] asof=2020-10-26 feats=69 buy=YES sell=YES rows=89764
[TRAIN][5M] asof=2020-11-02 feats=69 buy=YES sell=YES rows=89983
[TRAIN][5M] asof=2020-11-09 feats=69 buy=YES sell=YES rows=90161
[TRAIN][5M] asof=2020-11-16 feats=69 buy=YES sell=YES rows=90308
[TRAIN][5M] asof=2020-11-23 feats=69 buy=YES sell=YES rows=90480
[TRAIN][5M] asof=2020-11-30 feats=69 buy=YES sell=YES rows=90642
[TRAIN][5M] asof=2020-12-07 feats=69 buy=YES sell=YES rows=90787
[TRAIN][5M] asof=2020-12-14 feats=69 buy=YES sell=YES rows=90980
[TRAIN][5M] asof=2020-12-21 feats=69 buy=YES sell=YES rows=91146
[TRAIN][5M] asof=2020-12-28 feats=69 buy=YES sell=YES rows=91322
[TRAIN][5M] asof=2021-01-04 feats=69 buy=YES sell=YES rows=91487
[TRAIN][5M] asof=2021-01-11 feats=69 buy=YES sell=YES rows=91655
[TRAIN][5M] asof=2021-01-19 feats=69 buy=YES sell=YES rows=91825
[TRAIN][5M] asof=2021-01-25 feats=69 buy=YES sell=YES rows=91996
[TRAIN][5M] asof=2021-02-01 feats=69 buy=YES sell=YES rows=92217
[TRAIN][5M] asof=2021-02-08 feats=69 buy=YES sell=YES rows=92425
[TRAIN][5M] asof=2021-02-16 feats=69 buy=YES sell=YES rows=92614
[TRAIN][5M] asof=2021-02-22 feats=69 buy=YES sell=YES rows=92713
[TRAIN][5M] asof=2021-03-01 feats=69 buy=YES sell=YES rows=92904
[TRAIN][5M] asof=2021-03-08 feats=69 buy=YES sell=YES rows=93159
[TRAIN][5M] asof=2021-03-15 feats=69 buy=YES sell=YES rows=93384
[TRAIN][5M] asof=2021-03-22 feats=69 buy=YES sell=YES rows=93572
[TRAIN][5M] asof=2021-03-29 feats=69 buy=YES sell=YES rows=93750
[TRAIN][5M] asof=2021-04-05 feats=69 buy=YES sell=YES rows=93925
[TRAIN][5M] asof=2021-04-12 feats=69 buy=YES sell=YES rows=94130
[TRAIN][5M] asof=2021-04-19 feats=69 buy=YES sell=YES rows=94243
[TRAIN][5M] asof=2021-04-26 feats=69 buy=YES sell=YES rows=94412
[TRAIN][5M] asof=2021-05-03 feats=69 buy=YES sell=YES rows=94577
[TRAIN][5M] asof=2021-05-10 feats=69 buy=YES sell=YES rows=94754
[TRAIN][5M] asof=2021-05-17 feats=69 buy=YES sell=YES rows=94927
[TRAIN][5M] asof=2021-05-24 feats=69 buy=YES sell=YES rows=95174
[TRAIN][5M] asof=2021-06-01 feats=69 buy=YES sell=YES rows=95373
[TRAIN][5M] asof=2021-06-07 feats=69 buy=YES sell=YES rows=95568
[TRAIN][5M] asof=2021-06-14 feats=69 buy=YES sell=YES rows=95777
[TRAIN][5M] asof=2021-06-21 feats=69 buy=YES sell=YES rows=95962
[TRAIN][5M] asof=2021-06-28 feats=69 buy=YES sell=YES rows=96159
[TRAIN][5M] asof=2021-07-06 feats=69 buy=YES sell=YES rows=96368
[TRAIN][5M] asof=2021-07-12 feats=69 buy=YES sell=YES rows=96482
[TRAIN][5M] asof=2021-07-19 feats=69 buy=YES sell=YES rows=96663
[TRAIN][5M] asof=2021-07-26 feats=69 buy=YES sell=YES rows=96872
[TRAIN][5M] asof=2021-08-02 feats=69 buy=YES sell=YES rows=97070
[TRAIN][5M] asof=2021-08-09 feats=69 buy=YES sell=YES rows=97204
[TRAIN][5M] asof=2021-08-16 feats=69 buy=YES sell=YES rows=97362
[TRAIN][5M] asof=2021-08-23 feats=69 buy=YES sell=YES rows=97582
[TRAIN][5M] asof=2021-08-30 feats=69 buy=YES sell=YES rows=97767
[TRAIN][5M] asof=2021-09-07 feats=69 buy=YES sell=YES rows=97939
[TRAIN][5M] asof=2021-09-13 feats=69 buy=YES sell=YES rows=98097
[TRAIN][5M] asof=2021-09-20 feats=69 buy=YES sell=YES rows=98327
[TRAIN][5M] asof=2021-09-27 feats=69 buy=YES sell=YES rows=98494
[TRAIN][5M] asof=2021-10-04 feats=69 buy=YES sell=YES rows=98686
[TRAIN][5M] asof=2021-10-11 feats=69 buy=YES sell=YES rows=98878
[TRAIN][5M] asof=2021-10-18 feats=69 buy=YES sell=YES rows=99046
[TRAIN][5M] asof=2021-10-25 feats=69 buy=YES sell=YES rows=99214
[TRAIN][5M] asof=2021-11-01 feats=69 buy=YES sell=YES rows=99406
[TRAIN][5M] asof=2021-11-08 feats=69 buy=YES sell=YES rows=99542
[TRAIN][5M] asof=2021-11-15 feats=69 buy=YES sell=YES rows=99747
[TRAIN][5M] asof=2021-11-22 feats=69 buy=YES sell=YES rows=99911
[TRAIN][5M] asof=2021-11-29 feats=69 buy=YES sell=YES rows=100088
[TRAIN][5M] asof=2021-12-06 feats=69 buy=YES sell=YES rows=100290
[TRAIN][5M] asof=2021-12-13 feats=69 buy=YES sell=YES rows=100513
[TRAIN][5M] asof=2021-12-20 feats=69 buy=YES sell=YES rows=100703
[TRAIN][5M] asof=2021-12-27 feats=69 buy=YES sell=YES rows=100879
[TRAIN][5M] asof=2022-01-03 feats=69 buy=YES sell=YES rows=101010
[TRAIN][5M] asof=2022-01-10 feats=69 buy=YES sell=YES rows=101232
[TRAIN][5M] asof=2022-01-18 feats=69 buy=YES sell=YES rows=101427
[TRAIN][5M] asof=2022-01-24 feats=69 buy=YES sell=YES rows=101613
[TRAIN][5M] asof=2022-01-31 feats=69 buy=YES sell=YES rows=101839
[TRAIN][5M] asof=2022-02-07 feats=69 buy=YES sell=YES rows=102024
[TRAIN][5M] asof=2022-02-14 feats=69 buy=YES sell=YES rows=102197
[TRAIN][5M] asof=2022-02-22 feats=69 buy=YES sell=YES rows=102342
[TRAIN][5M] asof=2022-02-28 feats=69 buy=YES sell=YES rows=102498
[TRAIN][5M] asof=2022-03-07 feats=69 buy=YES sell=YES rows=102685
[TRAIN][5M] asof=2022-03-14 feats=69 buy=YES sell=YES rows=102903
[TRAIN][5M] asof=2022-03-21 feats=69 buy=YES sell=YES rows=103097
[TRAIN][5M] asof=2022-03-28 feats=69 buy=YES sell=YES rows=103264
[TRAIN][5M] asof=2022-04-04 feats=69 buy=YES sell=YES rows=103453
[TRAIN][5M] asof=2022-04-11 feats=69 buy=YES sell=YES rows=103681
[TRAIN][5M] asof=2022-04-18 feats=69 buy=YES sell=YES rows=103851
[TRAIN][5M] asof=2022-04-25 feats=69 buy=YES sell=YES rows=104068
[TRAIN][5M] asof=2022-05-02 feats=69 buy=YES sell=YES rows=104307
[TRAIN][5M] asof=2022-05-09 feats=69 buy=YES sell=YES rows=104490
[TRAIN][5M] asof=2022-05-16 feats=69 buy=YES sell=YES rows=104699
[TRAIN][5M] asof=2022-05-23 feats=69 buy=YES sell=YES rows=104924
[TRAIN][5M] asof=2022-05-31 feats=69 buy=YES sell=YES rows=105143
[TRAIN][5M] asof=2022-06-06 feats=69 buy=YES sell=YES rows=105311
[TRAIN][5M] asof=2022-06-13 feats=69 buy=YES sell=YES rows=105519
[TRAIN][5M] asof=2022-06-21 feats=69 buy=YES sell=YES rows=105713
[TRAIN][5M] asof=2022-06-27 feats=69 buy=YES sell=YES rows=105844
[TRAIN][5M] asof=2022-07-05 feats=69 buy=YES sell=YES rows=106076
[TRAIN][5M] asof=2022-07-11 feats=69 buy=YES sell=YES rows=106195
[TRAIN][5M] asof=2022-07-18 feats=69 buy=YES sell=YES rows=106395
[TRAIN][5M] asof=2022-07-25 feats=69 buy=YES sell=YES rows=106564
[TRAIN][5M] asof=2022-08-01 feats=69 buy=YES sell=YES rows=106727
[TRAIN][5M] asof=2022-08-08 feats=69 buy=YES sell=YES rows=106934
[TRAIN][5M] asof=2022-08-15 feats=69 buy=YES sell=YES rows=107149
[TRAIN][5M] asof=2022-08-22 feats=69 buy=YES sell=YES rows=107387
[TRAIN][5M] asof=2022-08-29 feats=69 buy=YES sell=YES rows=107569
[TRAIN][5M] asof=2022-09-06 feats=69 buy=YES sell=YES rows=107784
[TRAIN][5M] asof=2022-09-12 feats=69 buy=YES sell=YES rows=107961
[TRAIN][5M] asof=2022-09-19 feats=69 buy=YES sell=YES rows=108191
[TRAIN][5M] asof=2022-09-26 feats=69 buy=YES sell=YES rows=108373
[TRAIN][5M] asof=2022-10-03 feats=69 buy=YES sell=YES rows=108545
[TRAIN][5M] asof=2022-10-10 feats=69 buy=YES sell=YES rows=108754
[TRAIN][5M] asof=2022-10-17 feats=69 buy=YES sell=YES rows=108945
[TRAIN][5M] asof=2022-10-24 feats=69 buy=YES sell=YES rows=109170
[TRAIN][5M] asof=2022-10-31 feats=69 buy=YES sell=YES rows=109399
[TRAIN][5M] asof=2022-11-07 feats=69 buy=YES sell=YES rows=109611
[TRAIN][5M] asof=2022-11-14 feats=69 buy=YES sell=YES rows=109816
[TRAIN][5M] asof=2022-11-21 feats=69 buy=YES sell=YES rows=110018
[TRAIN][5M] asof=2022-11-28 feats=69 buy=YES sell=YES rows=110199
[TRAIN][5M] asof=2022-12-05 feats=69 buy=YES sell=YES rows=110339
[TRAIN][5M] asof=2022-12-12 feats=69 buy=YES sell=YES rows=110497
[TRAIN][5M] asof=2022-12-19 feats=69 buy=YES sell=YES rows=110670
[TRAIN][5M] asof=2022-12-27 feats=69 buy=YES sell=YES rows=110888
[TRAIN][5M] asof=2023-01-03 feats=69 buy=YES sell=YES rows=111015
[TRAIN][5M] asof=2023-01-09 feats=69 buy=YES sell=YES rows=111167
[TRAIN][5M] asof=2023-01-17 feats=69 buy=YES sell=YES rows=111415
[TRAIN][5M] asof=2023-01-23 feats=69 buy=YES sell=YES rows=111594
[TRAIN][5M] asof=2023-01-30 feats=69 buy=YES sell=YES rows=111794
[TRAIN][5M] asof=2023-02-06 feats=69 buy=YES sell=YES rows=111965
[TRAIN][5M] asof=2023-02-13 feats=69 buy=YES sell=YES rows=112162
[TRAIN][5M] asof=2023-02-21 feats=69 buy=YES sell=YES rows=112336
[TRAIN][5M] asof=2023-02-27 feats=69 buy=YES sell=YES rows=112524
[TRAIN][5M] asof=2023-03-06 feats=69 buy=YES sell=YES rows=112734
[TRAIN][5M] asof=2023-03-13 feats=69 buy=YES sell=YES rows=112889
[TRAIN][5M] asof=2023-03-20 feats=69 buy=YES sell=YES rows=113077
[TRAIN][5M] asof=2023-03-27 feats=69 buy=YES sell=YES rows=113237
[TRAIN][5M] asof=2023-04-03 feats=69 buy=YES sell=YES rows=113449
[TRAIN][5M] asof=2023-04-10 feats=69 buy=YES sell=YES rows=113613
[TRAIN][5M] asof=2023-04-17 feats=69 buy=YES sell=YES rows=113808
[TRAIN][5M] asof=2023-04-24 feats=69 buy=YES sell=YES rows=113989
[TRAIN][5M] asof=2023-05-01 feats=69 buy=YES sell=YES rows=114161
[TRAIN][5M] asof=2023-05-08 feats=69 buy=YES sell=YES rows=114396
[TRAIN][5M] asof=2023-05-15 feats=69 buy=YES sell=YES rows=114571
[TRAIN][5M] asof=2023-05-22 feats=69 buy=YES sell=YES rows=114729
[TRAIN][5M] asof=2023-05-30 feats=69 buy=YES sell=YES rows=114919
[TRAIN][5M] asof=2023-06-05 feats=69 buy=YES sell=YES rows=115067
[TRAIN][5M] asof=2023-06-12 feats=69 buy=YES sell=YES rows=115256
[TRAIN][5M] asof=2023-06-20 feats=69 buy=YES sell=YES rows=115423
[TRAIN][5M] asof=2023-06-26 feats=69 buy=YES sell=YES rows=115610
[TRAIN][5M] asof=2023-07-03 feats=69 buy=YES sell=YES rows=115838
[TRAIN][5M] asof=2023-07-10 feats=69 buy=YES sell=YES rows=116007
[TRAIN][5M] asof=2023-07-17 feats=69 buy=YES sell=YES rows=116238
[TRAIN][5M] asof=2023-07-24 feats=69 buy=YES sell=YES rows=116438
[TRAIN][5M] asof=2023-07-31 feats=69 buy=YES sell=YES rows=116668
[TRAIN][5M] asof=2023-08-07 feats=69 buy=YES sell=YES rows=116870
[TRAIN][5M] asof=2023-08-14 feats=69 buy=YES sell=YES rows=117097
[TRAIN][5M] asof=2023-08-21 feats=69 buy=YES sell=YES rows=117295
[TRAIN][5M] asof=2023-08-28 feats=69 buy=YES sell=YES rows=117469
[TRAIN][5M] asof=2023-09-05 feats=69 buy=YES sell=YES rows=117677
[TRAIN][5M] asof=2023-09-11 feats=69 buy=YES sell=YES rows=117816
[TRAIN][5M] asof=2023-09-18 feats=69 buy=YES sell=YES rows=117978
[TRAIN][5M] asof=2023-09-25 feats=69 buy=YES sell=YES rows=118233
[TRAIN][5M] asof=2023-10-02 feats=69 buy=YES sell=YES rows=118410
[TRAIN][5M] asof=2023-10-09 feats=69 buy=YES sell=YES rows=118598
[TRAIN][5M] asof=2023-10-16 feats=69 buy=YES sell=YES rows=118830
[TRAIN][5M] asof=2023-10-23 feats=69 buy=YES sell=YES rows=119012
[TRAIN][5M] asof=2023-10-30 feats=69 buy=YES sell=YES rows=119198
[TRAIN][5M] asof=2023-11-06 feats=69 buy=YES sell=YES rows=119365
[TRAIN][5M] asof=2023-11-13 feats=69 buy=YES sell=YES rows=119532
[TRAIN][5M] asof=2023-11-20 feats=69 buy=YES sell=YES rows=119755
[TRAIN][5M] asof=2023-11-27 feats=69 buy=YES sell=YES rows=119839
[TRAIN][5M] asof=2023-12-04 feats=69 buy=YES sell=YES rows=120002
[TRAIN][5M] asof=2023-12-11 feats=69 buy=YES sell=YES rows=120217
[TRAIN][5M] asof=2023-12-18 feats=69 buy=YES sell=YES rows=120370
[TRAIN][5M] asof=2023-12-26 feats=69 buy=YES sell=YES rows=120543
[TRAIN][5M] asof=2024-01-02 feats=69 buy=YES sell=YES rows=120672
[TRAIN][5M] asof=2024-01-08 feats=69 buy=YES sell=YES rows=120822
[TRAIN][5M] asof=2024-01-16 feats=69 buy=YES sell=YES rows=120993
[TRAIN][5M] asof=2024-01-22 feats=69 buy=YES sell=YES rows=121093
[TRAIN][5M] asof=2024-01-29 feats=69 buy=YES sell=YES rows=121382
[TRAIN][5M] asof=2024-02-05 feats=69 buy=YES sell=YES rows=121535
[TRAIN][5M] asof=2024-02-12 feats=69 buy=YES sell=YES rows=121681
[TRAIN][5M] asof=2024-02-20 feats=69 buy=YES sell=YES rows=121888
[TRAIN][5M] asof=2024-02-26 feats=69 buy=YES sell=YES rows=122010
[TRAIN][5M] asof=2024-03-04 feats=69 buy=YES sell=YES rows=122214
[TRAIN][5M] asof=2024-03-11 feats=69 buy=YES sell=YES rows=122427
[TRAIN][5M] asof=2024-03-18 feats=69 buy=YES sell=YES rows=122607
[TRAIN][5M] asof=2024-03-25 feats=69 buy=YES sell=YES rows=122755
[TRAIN][5M] asof=2024-04-01 feats=69 buy=YES sell=YES rows=122841
[TRAIN][5M] asof=2024-04-08 feats=69 buy=YES sell=YES rows=122988
[TRAIN][5M] asof=2024-04-15 feats=69 buy=YES sell=YES rows=123156
[TRAIN][5M] asof=2024-04-22 feats=69 buy=YES sell=YES rows=123284
[TRAIN][5M] asof=2024-04-29 feats=69 buy=YES sell=YES rows=123468
[TRAIN][5M] asof=2024-05-06 feats=69 buy=YES sell=YES rows=123651
[TRAIN][5M] asof=2024-05-13 feats=69 buy=YES sell=YES rows=123860
[TRAIN][5M] asof=2024-05-20 feats=69 buy=YES sell=YES rows=124011
[TRAIN][5M] asof=2024-05-28 feats=69 buy=YES sell=YES rows=124210
[TRAIN][5M] asof=2024-06-03 feats=69 buy=YES sell=YES rows=124354
[TRAIN][5M] asof=2024-06-10 feats=69 buy=YES sell=YES rows=124590
[TRAIN][5M] asof=2024-06-17 feats=69 buy=YES sell=YES rows=124800
[TRAIN][5M] asof=2024-06-24 feats=69 buy=YES sell=YES rows=124921
[TRAIN][5M] asof=2024-07-01 feats=69 buy=YES sell=YES rows=125123
[TRAIN][5M] asof=2024-07-08 feats=69 buy=YES sell=YES rows=125252
[TRAIN][5M] asof=2024-07-15 feats=69 buy=YES sell=YES rows=125430
[TRAIN][5M] asof=2024-07-22 feats=69 buy=YES sell=YES rows=125655
[TRAIN][5M] asof=2024-07-29 feats=69 buy=YES sell=YES rows=125875
[TRAIN][5M] asof=2024-08-05 feats=69 buy=YES sell=YES rows=126091
[TRAIN][5M] asof=2024-08-12 feats=69 buy=YES sell=YES rows=126303
[TRAIN][5M] asof=2024-08-19 feats=69 buy=YES sell=YES rows=126508
[TRAIN][5M] asof=2024-08-26 feats=69 buy=YES sell=YES rows=126692
[TRAIN][5M] asof=2024-09-03 feats=69 buy=YES sell=YES rows=126882
[TRAIN][5M] asof=2024-09-09 feats=69 buy=YES sell=YES rows=127015
[TRAIN][5M] asof=2024-09-16 feats=69 buy=YES sell=YES rows=127172
[TRAIN][5M] asof=2024-09-23 feats=69 buy=YES sell=YES rows=127365
[TRAIN][5M] asof=2024-09-30 feats=69 buy=YES sell=YES rows=127543
[TRAIN][5M] asof=2024-10-07 feats=69 buy=YES sell=YES rows=127711
[TRAIN][5M] asof=2024-10-14 feats=69 buy=YES sell=YES rows=127899
[TRAIN][5M] asof=2024-10-21 feats=69 buy=YES sell=YES rows=128093
[TRAIN][5M] asof=2024-10-28 feats=69 buy=YES sell=YES rows=128320
[TRAIN][5M] asof=2024-11-04 feats=69 buy=YES sell=YES rows=128472
[TRAIN][5M] asof=2024-11-11 feats=69 buy=YES sell=YES rows=128662
[TRAIN][5M] asof=2024-11-18 feats=69 buy=YES sell=YES rows=128849
[TRAIN][5M] asof=2024-11-25 feats=69 buy=YES sell=YES rows=129057
[TRAIN][5M] asof=2024-12-02 feats=69 buy=YES sell=YES rows=129167
[TRAIN][5M] asof=2024-12-09 feats=69 buy=YES sell=YES rows=129342
[TRAIN][5M] asof=2024-12-16 feats=69 buy=YES sell=YES rows=129480
[TRAIN][5M] asof=2024-12-23 feats=69 buy=YES sell=YES rows=129698
[TRAIN][5M] asof=2024-12-30 feats=69 buy=YES sell=YES rows=129808

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
4094,2026-04-15,0.122837,0.155,0.315,FORCE_BUY,0.008710,-0.000604,-0.000604,0.008710,FORCE_BUY,3.626008e+07,700.65,-0.50,1.7
4095,2026-04-16,0.117469,0.155,0.315,FORCE_BUY,0.001812,0.001528,-0.000257,0.001812,FORCE_BUY,3.632578e+07,702.22,-0.50,1.7
4096,2026-04-17,0.136876,0.155,0.315,FORCE_BUY,0.011427,0.000668,-0.000014,0.011427,FORCE_BUY,3.674087e+07,710.75,1.15,-0.5
4097,2026-04-20,0.134608,0.155,0.315,FORCE_BUY,0.004147,0.004147,0.004147,0.004147,FORCE_BUY,3.689323e+07,709.49,1.15,-0.5
4098,2026-04-21,0.184940,0.155,0.315,FREE,-0.003720,0.001227,0.001860,0.001227,FORCE_SELL,3.696186e+07,707.00,1.15,-0.5

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
1579,2026-04-15,624999.137145,0.000000,1,-0.50,1.7,0.122837,FORCE_BUY,0.155,0.315
1580,2026-04-16,626399.620476,0.000000,1,1.15,-0.5,0.117469,FORCE_BUY,0.155,0.315
1581,2026-04-17,634008.615894,0.000000,1,1.15,-0.5,0.136876,FORCE_BUY,0.155,0.315
1582,2026-04-20,632884.661119,0.000000,1,1.15,-0.5,0.134608,FORCE_BUY,0.155,0.315
1583,2026-04-21,634469.654019,634469.654019,0,1.15,-0.5,0.184940,FREE,0.155,0.315

,side,seen_idx,exec_px,qty,fee,reason,ts,pred,th,gate,pnl,entry_px,entry_idx
0,buy,452961,320.23,312.275552,0.0,5m BUY signal,2020-01-06 04:00:00,0.306116,-0.5,FREE,NaN,NaN,NaN
1,sell,453104,323.66,312.275552,0.0,5m SELL signal,2020-01-06 15:55:00,4.976673,-0.5,FREE,1071.105143,320.23,452961.0
2,buy,453119,323.26,312.661960,0.0,5m BUY signal,2020-01-06 17:10:00,-0.414623,-0.5,FREE,NaN,NaN,NaN
3,sell,453130,323.44,312.661960,0.0,5m SELL signal,2020-01-06 18:10:00,4.249341,-0.5,FREE,56.279153,323.26,453119.0
4,buy,453136,323.23,312.865094,0.0,5m BUY signal,2020-01-06 18:45:00,-0.434716,-0.5,FREE,NaN,NaN,NaN

In [1]:

from pathlib import Path
import pandas as pd

from adaptive_reward_checkpoint_fresh import (
    build_adaptive_reward_snapshot,
    run_adaptive_reward_from_snapshot,
)
from adaptive_trade_extensions import RollingThresholdConfig, make_threshold_grid

snapshot_path = Path("checkpoints") / "TQQQ_adaptive_reward_fresh_start_252days_at_2020.joblib"

common_kwargs = dict(
    daily_csv_path="DataAPI/data/TQQQ_day.csv",
    k5m_csv_path="DataAPI/data/TQQQ_5M.csv",
    code="TQQQ",
    daily_chan_start="2010-02-11",
    accumulation_start="2012-02-11",
    N_confirm=5,
    min_labeled_days_to_train=200,
    retrain_every_new_labels=25,
    dp_lookback=5,
    lookahead_days_5m=2.0,
    retrain_every_days_5m=5,
    min_samples_total_5m=300,
    threshold_window_days=2.0,
    threshold_ret_grid=None,
    threshold_min_open_signals=10,
    initial_capital=100000.0,
    fee_pct=0.0,
    daily_chan_max_klines=500,
    five_chan_max_klines=500,
    macro_files={
        "vix_": "VIX.csv",
    },
    static_buy_level=0.20,
    static_sell_level=0.30,
    daily_threshold_config=RollingThresholdConfig(
        lookback_days=252,
        buy_grid=make_threshold_grid(0.05, 0.35, 0.005),
        sell_grid=make_threshold_grid(0.15, 0.60, 0.005),
        min_gap=0.02,
        min_obs=60,
        switch_penalty=0.0,
    ),
    verbose=True,
)

In [6]:
snapshot_res = build_adaptive_reward_snapshot(
    snapshot_path=str(snapshot_path),
    snapshot_end_time="2019-12-31",
    output_dir="output_adaptive_reward_snapshot_build_TQQQ_252days_at_2020",
    **common_kwargs,
)

print(snapshot_res["snapshot_path"])
display(snapshot_res["daily_reward_df"].tail())
display(snapshot_res["daily_log_df"].tail())

[TRAIN][DAILY-PROB] n=200 pos=49 (24.50%)
[TRAIN][DAILY-PROB] n=225 pos=52 (23.11%)
[TRAIN][DAILY-PROB] n=250 pos=61 (24.40%)
[TRAIN][DAILY-PROB] n=275 pos=65 (23.64%)
[TRAIN][DAILY-PROB] n=300 pos=76 (25.33%)
[TRAIN][DAILY-PROB] n=325 pos=76 (23.38%)
[TRAIN][DAILY-PROB] n=350 pos=76 (21.71%)
[TRAIN][DAILY-PROB] n=375 pos=79 (21.07%)
[TRAIN][DAILY-PROB] n=400 pos=84 (21.00%)
[TRAIN][DAILY-PROB] n=425 pos=91 (21.41%)
[TRAIN][DAILY-PROB] n=450 pos=96 (21.33%)
[TRAIN][DAILY-PROB] n=475 pos=99 (20.84%)
[TRAIN][DAILY-PROB] n=500 pos=104 (20.80%)
[TRAIN][DAILY-PROB] n=525 pos=114 (21.71%)
[TRAIN][DAILY-PROB] n=550 pos=118 (21.45%)
[TRAIN][DAILY-PROB] n=575 pos=120 (20.87%)
[TRAIN][DAILY-PROB] n=600 pos=128 (21.33%)
[TRAIN][DAILY-PROB] n=625 pos=137 (21.92%)
[TRAIN][DAILY-PROB] n=650 pos=142 (21.85%)
[TRAIN][DAILY-PROB] n=675 pos=150 (22.22%)
[TRAIN][DAILY-PROB] n=700 pos=152 (21.71%)
[TRAIN][DAILY-PROB] n=725 pos=155 (21.38%)
[TRAIN][DAILY-PROB] n=750 pos=160 (21.33%)
[TRAIN][DAILY-PROB] n=775 pos=161 (20.77%)
[TRAIN][DAILY-PROB] n=800 pos=164 (20.50%)
[TRAIN][DAILY-PROB] n=825 pos=170 (20.61%)
[TRAIN][DAILY-PROB] n=850 pos=172 (20.24%)
[TRAIN][DAILY-PROB] n=875 pos=182 (20.80%)
[TRAIN][DAILY-PROB] n=900 pos=188 (20.89%)
[TRAIN][DAILY-PROB] n=925 pos=188 (20.32%)
[TRAIN][DAILY-PROB] n=950 pos=190 (20.00%)
[TRAIN][DAILY-PROB] n=975 pos=197 (20.21%)
[TRAIN][DAILY-PROB] n=1000 pos=203 (20.30%)
[TRAIN][DAILY-PROB] n=1025 pos=208 (20.29%)
[TRAIN][DAILY-PROB] n=1050 pos=215 (20.48%)
[TRAIN][DAILY-PROB] n=1075 pos=220 (20.47%)
[TRAIN][DAILY-PROB] n=1100 pos=225 (20.45%)
[TRAIN][DAILY-PROB] n=1125 pos=230 (20.44%)
[TRAIN][DAILY-PROB] n=1150 pos=235 (20.43%)
[TRAIN][DAILY-PROB] n=1175 pos=241 (20.51%)
[TRAIN][DAILY-PROB] n=1200 pos=253 (21.08%)
[TRAIN][DAILY-PROB] n=1225 pos=259 (21.14%)
[TRAIN][DAILY-PROB] n=1250 pos=267 (21.36%)
[TRAIN][DAILY-PROB] n=1275 pos=275 (21.57%)
[TRAIN][DAILY-PROB] n=1300 pos=281 (21.62%)
[TRAIN][DAILY-PROB] n=1325 pos=287 (21.66%)
[TRAIN][DAILY-PROB] n=1350 pos=295 (21.85%)
[TRAIN][DAILY-PROB] n=1375 pos=303 (22.04%)
[TRAIN][DAILY-PROB] n=1400 pos=304 (21.71%)
[TRAIN][DAILY-PROB] n=1425 pos=311 (21.82%)
[TRAIN][DAILY-PROB] n=1450 pos=318 (21.93%)
[TRAIN][DAILY-PROB] n=1475 pos=321 (21.76%)
[TRAIN][DAILY-PROB] n=1500 pos=329 (21.93%)
[TRAIN][DAILY-PROB] n=1525 pos=337 (22.10%)
[TRAIN][DAILY-PROB] n=1550 pos=339 (21.87%)
[TRAIN][DAILY-PROB] n=1575 pos=341 (21.65%)
[TRAIN][DAILY-PROB] n=1600 pos=344 (21.50%)
[TRAIN][DAILY-PROB] n=1625 pos=346 (21.29%)
[TRAIN][DAILY-PROB] n=1650 pos=347 (21.03%)
[TRAIN][DAILY-PROB] n=1675 pos=349 (20.84%)
[TRAIN][DAILY-PROB] n=1700 pos=353 (20.76%)
[TRAIN][DAILY-PROB] n=1725 pos=358 (20.75%)
[TRAIN][DAILY-PROB] n=1750 pos=363 (20.74%)
[TRAIN][DAILY-PROB] n=1775 pos=365 (20.56%)
[TRAIN][DAILY-PROB] n=1800 pos=367 (20.39%)
[TRAIN][DAILY-PROB] n=1825 pos=371 (20.33%)
[TRAIN][DAILY-PROB] n=1850 pos=379 (20.49%)
[TRAIN][DAILY-PROB] n=1875 pos=388 (20.69%)
[TRAIN][DAILY-PROB] n=1900 pos=391 (20.58%)
[TRAIN][DAILY-PROB] n=1925 pos=392 (20.36%)
[TRAIN][DAILY-PROB] n=1950 pos=397 (20.36%)
[TRAIN][DAILY-PROB] n=1975 pos=402 (20.35%)
[TRAIN][DAILY-PROB] n=2000 pos=409 (20.45%)
[TRAIN][DAILY-PROB] n=2025 pos=416 (20.54%)
[TRAIN][DAILY-PROB] n=2050 pos=420 (20.49%)
[TRAIN][DAILY-PROB] n=2075 pos=425 (20.48%)
[TRAIN][DAILY-PROB] n=2100 pos=425 (20.24%)
[TRAIN][DAILY-PROB] n=2125 pos=433 (20.38%)
[TRAIN][DAILY-PROB] n=2150 pos=439 (20.42%)
[TRAIN][DAILY-PROB] n=2175 pos=445 (20.46%)
[TRAIN][DAILY-PROB] n=2200 pos=448 (20.36%)
[TRAIN][DAILY-PROB] n=2225 pos=455 (20.45%)
[TRAIN][DAILY-PROB] n=2250 pos=462 (20.53%)
[TRAIN][DAILY-PROB] n=2275 pos=467 (20.53%)
[TRAIN][DAILY-PROB] n=2300 pos=469 (20.39%)
[TRAIN][5M] asof=2012-03-15 feats=69 buy=NO sell=YES rows=552
[TRAIN][5M] asof=2012-03-20 feats=69 buy=NO sell=YES rows=635
[TRAIN][5M] asof=2012-03-26 feats=69 buy=NO sell=YES rows=744
[TRAIN][5M] asof=2012-04-02 feats=69 buy=NO sell=YES rows=856
[TRAIN][5M] asof=2012-04-09 feats=69 buy=NO sell=YES rows=947
[TRAIN][5M] asof=2012-04-16 feats=69 buy=NO sell=YES rows=1051
[TRAIN][5M] asof=2012-04-23 feats=69 buy=YES sell=YES rows=1192
[TRAIN][5M] asof=2012-04-30 feats=69 buy=YES sell=YES rows=1324
[TRAIN][5M] asof=2012-05-07 feats=69 buy=YES sell=YES rows=1442
[TRAIN][5M] asof=2012-05-14 feats=69 buy=YES sell=YES rows=1595
[TRAIN][5M] asof=2012-05-21 feats=69 buy=YES sell=YES rows=1761
[TRAIN][5M] asof=2012-05-29 feats=69 buy=YES sell=YES rows=1907
[TRAIN][5M] asof=2012-06-04 feats=69 buy=YES sell=YES rows=1971
[TRAIN][5M] asof=2012-06-11 feats=69 buy=YES sell=YES rows=2136
[TRAIN][5M] asof=2012-06-18 feats=69 buy=YES sell=YES rows=2259
[TRAIN][5M] asof=2012-06-25 feats=69 buy=YES sell=YES rows=2370
[TRAIN][5M] asof=2012-07-02 feats=69 buy=YES sell=YES rows=2466
[TRAIN][5M] asof=2012-07-09 feats=69 buy=YES sell=YES rows=2544
[TRAIN][5M] asof=2012-07-16 feats=69 buy=YES sell=YES rows=2643
[TRAIN][5M] asof=2012-07-23 feats=69 buy=YES sell=YES rows=2787
[TRAIN][5M] asof=2012-07-30 feats=69 buy=YES sell=YES rows=2884
[TRAIN][5M] asof=2012-08-06 feats=69 buy=YES sell=YES rows=3018
[TRAIN][5M] asof=2012-08-13 feats=69 buy=YES sell=YES rows=3144
[TRAIN][5M] asof=2012-08-20 feats=69 buy=YES sell=YES rows=3248
[TRAIN][5M] asof=2012-08-27 feats=69 buy=YES sell=YES rows=3376
[TRAIN][5M] asof=2012-09-04 feats=69 buy=YES sell=YES rows=3472
[TRAIN][5M] asof=2012-09-10 feats=69 buy=YES sell=YES rows=3563
[TRAIN][5M] asof=2012-09-17 feats=69 buy=YES sell=YES rows=3705
[TRAIN][5M] asof=2012-09-24 feats=69 buy=YES sell=YES rows=3829
[TRAIN][5M] asof=2012-10-01 feats=69 buy=YES sell=YES rows=3960
[TRAIN][5M] asof=2012-10-08 feats=69 buy=YES sell=YES rows=4089
[TRAIN][5M] asof=2012-10-15 feats=69 buy=YES sell=YES rows=4212
[TRAIN][5M] asof=2012-10-22 feats=69 buy=YES sell=YES rows=4343
[TRAIN][5M] asof=2012-10-31 feats=69 buy=YES sell=YES rows=4515
[TRAIN][5M] asof=2012-11-05 feats=69 buy=YES sell=YES rows=4595
[TRAIN][5M] asof=2012-11-12 feats=69 buy=YES sell=YES rows=4744
[TRAIN][5M] asof=2012-11-19 feats=69 buy=YES sell=YES rows=4909
[TRAIN][5M] asof=2012-11-26 feats=69 buy=YES sell=YES rows=5003
[TRAIN][5M] asof=2012-12-03 feats=69 buy=YES sell=YES rows=5090
[TRAIN][5M] asof=2012-12-10 feats=69 buy=YES sell=YES rows=5210
[TRAIN][5M] asof=2012-12-17 feats=69 buy=YES sell=YES rows=5363
[TRAIN][5M] asof=2012-12-24 feats=69 buy=YES sell=YES rows=5467
[TRAIN][5M] asof=2012-12-31 feats=69 buy=YES sell=YES rows=5567
[TRAIN][5M] asof=2013-01-07 feats=69 buy=YES sell=YES rows=5655
[TRAIN][5M] asof=2013-01-14 feats=69 buy=YES sell=YES rows=5776
[TRAIN][5M] asof=2013-01-22 feats=69 buy=YES sell=YES rows=5866
[TRAIN][5M] asof=2013-01-28 feats=69 buy=YES sell=YES rows=5998
[TRAIN][5M] asof=2013-02-04 feats=69 buy=YES sell=YES rows=6137
[TRAIN][5M] asof=2013-02-11 feats=69 buy=YES sell=YES rows=6249
[TRAIN][5M] asof=2013-02-19 feats=69 buy=YES sell=YES rows=6357
[TRAIN][5M] asof=2013-02-25 feats=69 buy=YES sell=YES rows=6478
[TRAIN][5M] asof=2013-03-04 feats=69 buy=YES sell=YES rows=6587
[TRAIN][5M] asof=2013-03-11 feats=69 buy=YES sell=YES rows=6737
[TRAIN][5M] asof=2013-03-18 feats=69 buy=YES sell=YES rows=6858
[TRAIN][5M] asof=2013-03-25 feats=69 buy=YES sell=YES rows=6990
[TRAIN][5M] asof=2013-04-01 feats=69 buy=YES sell=YES rows=7086
[TRAIN][5M] asof=2013-04-08 feats=69 buy=YES sell=YES rows=7197
[TRAIN][5M] asof=2013-04-15 feats=69 buy=YES sell=YES rows=7344
[TRAIN][5M] asof=2013-04-22 feats=69 buy=YES sell=YES rows=7462
[TRAIN][5M] asof=2013-04-29 feats=69 buy=YES sell=YES rows=7576
[TRAIN][5M] asof=2013-05-06 feats=69 buy=YES sell=YES rows=7693
[TRAIN][5M] asof=2013-05-13 feats=69 buy=YES sell=YES rows=7838
[TRAIN][5M] asof=2013-05-20 feats=69 buy=YES sell=YES rows=7944
[TRAIN][5M] asof=2013-05-28 feats=69 buy=YES sell=YES rows=8076
[TRAIN][5M] asof=2013-06-03 feats=69 buy=YES sell=YES rows=8185
[TRAIN][5M] asof=2013-06-10 feats=69 buy=YES sell=YES rows=8288
[TRAIN][5M] asof=2013-06-17 feats=69 buy=YES sell=YES rows=8372
[TRAIN][5M] asof=2013-06-24 feats=69 buy=YES sell=YES rows=8509
[TRAIN][5M] asof=2013-07-01 feats=69 buy=YES sell=YES rows=8668
[TRAIN][5M] asof=2013-07-08 feats=69 buy=YES sell=YES rows=8746
[TRAIN][5M] asof=2013-07-15 feats=69 buy=YES sell=YES rows=8846
[TRAIN][5M] asof=2013-07-22 feats=69 buy=YES sell=YES rows=8960
[TRAIN][5M] asof=2013-07-29 feats=69 buy=YES sell=YES rows=9113
[TRAIN][5M] asof=2013-08-05 feats=69 buy=YES sell=YES rows=9217
[TRAIN][5M] asof=2013-08-12 feats=69 buy=YES sell=YES rows=9331
[TRAIN][5M] asof=2013-08-19 feats=69 buy=YES sell=YES rows=9469
[TRAIN][5M] asof=2013-08-26 feats=69 buy=YES sell=YES rows=9587
[TRAIN][5M] asof=2013-09-03 feats=69 buy=YES sell=YES rows=9707
[TRAIN][5M] asof=2013-09-09 feats=69 buy=YES sell=YES rows=9776
[TRAIN][5M] asof=2013-09-16 feats=69 buy=YES sell=YES rows=9889
[TRAIN][5M] asof=2013-09-23 feats=69 buy=YES sell=YES rows=9961
[TRAIN][5M] asof=2013-09-30 feats=69 buy=YES sell=YES rows=10091
[TRAIN][5M] asof=2013-10-07 feats=69 buy=YES sell=YES rows=10176
[TRAIN][5M] asof=2013-10-14 feats=69 buy=YES sell=YES rows=10323
[TRAIN][5M] asof=2013-10-21 feats=69 buy=YES sell=YES rows=10451
[TRAIN][5M] asof=2013-10-28 feats=69 buy=YES sell=YES rows=10591
[TRAIN][5M] asof=2013-11-04 feats=69 buy=YES sell=YES rows=10733
[TRAIN][5M] asof=2013-11-11 feats=69 buy=YES sell=YES rows=10829
[TRAIN][5M] asof=2013-11-18 feats=69 buy=YES sell=YES rows=10931
[TRAIN][5M] asof=2013-11-25 feats=69 buy=YES sell=YES rows=11041
[TRAIN][5M] asof=2013-12-02 feats=69 buy=YES sell=YES rows=11136
[TRAIN][5M] asof=2013-12-09 feats=69 buy=YES sell=YES rows=11278
[TRAIN][5M] asof=2013-12-16 feats=69 buy=YES sell=YES rows=11425
[TRAIN][5M] asof=2013-12-23 feats=69 buy=YES sell=YES rows=11542
[TRAIN][5M] asof=2013-12-30 feats=69 buy=YES sell=YES rows=11608
[TRAIN][5M] asof=2014-01-06 feats=69 buy=YES sell=YES rows=11707
[TRAIN][5M] asof=2014-01-13 feats=69 buy=YES sell=YES rows=11807
[TRAIN][5M] asof=2014-01-21 feats=69 buy=YES sell=YES rows=11929
[TRAIN][5M] asof=2014-01-27 feats=69 buy=YES sell=YES rows=12036
[TRAIN][5M] asof=2014-02-03 feats=69 buy=YES sell=YES rows=12172
[TRAIN][5M] asof=2014-02-10 feats=69 buy=YES sell=YES rows=12337
[TRAIN][5M] asof=2014-02-18 feats=69 buy=YES sell=YES rows=12480
[TRAIN][5M] asof=2014-02-24 feats=69 buy=YES sell=YES rows=12563
[TRAIN][5M] asof=2014-03-03 feats=69 buy=YES sell=YES rows=12694
[TRAIN][5M] asof=2014-03-10 feats=69 buy=YES sell=YES rows=12804
[TRAIN][5M] asof=2014-03-17 feats=69 buy=YES sell=YES rows=12921
[TRAIN][5M] asof=2014-03-24 feats=69 buy=YES sell=YES rows=13031
[TRAIN][5M] asof=2014-03-31 feats=69 buy=YES sell=YES rows=13192
[TRAIN][5M] asof=2014-04-07 feats=69 buy=YES sell=YES rows=13330
[TRAIN][5M] asof=2014-04-14 feats=69 buy=YES sell=YES rows=13478
[TRAIN][5M] asof=2014-04-21 feats=69 buy=YES sell=YES rows=13598
[TRAIN][5M] asof=2014-04-28 feats=69 buy=YES sell=YES rows=13745
[TRAIN][5M] asof=2014-05-05 feats=69 buy=YES sell=YES rows=13871
[TRAIN][5M] asof=2014-05-12 feats=69 buy=YES sell=YES rows=14045
[TRAIN][5M] asof=2014-05-19 feats=69 buy=YES sell=YES rows=14192
[TRAIN][5M] asof=2014-05-27 feats=69 buy=YES sell=YES rows=14340
[TRAIN][5M] asof=2014-06-02 feats=69 buy=YES sell=YES rows=14430
[TRAIN][5M] asof=2014-06-09 feats=69 buy=YES sell=YES rows=14541
[TRAIN][5M] asof=2014-06-16 feats=69 buy=YES sell=YES rows=14679
[TRAIN][5M] asof=2014-06-23 feats=69 buy=YES sell=YES rows=14779
[TRAIN][5M] asof=2014-06-30 feats=69 buy=YES sell=YES rows=14869
[TRAIN][5M] asof=2014-07-07 feats=69 buy=YES sell=YES rows=14977
[TRAIN][5M] asof=2014-07-14 feats=69 buy=YES sell=YES rows=15082
[TRAIN][5M] asof=2014-07-21 feats=69 buy=YES sell=YES rows=15213
[TRAIN][5M] asof=2014-07-28 feats=69 buy=YES sell=YES rows=15330
[TRAIN][5M] asof=2014-08-04 feats=69 buy=YES sell=YES rows=15471
[TRAIN][5M] asof=2014-08-11 feats=69 buy=YES sell=YES rows=15616
[TRAIN][5M] asof=2014-08-18 feats=69 buy=YES sell=YES rows=15750
[TRAIN][5M] asof=2014-08-25 feats=69 buy=YES sell=YES rows=15858
[TRAIN][5M] asof=2014-09-02 feats=69 buy=YES sell=YES rows=15954
[TRAIN][5M] asof=2014-09-08 feats=69 buy=YES sell=YES rows=16072
[TRAIN][5M] asof=2014-09-15 feats=69 buy=YES sell=YES rows=16176
[TRAIN][5M] asof=2014-09-22 feats=69 buy=YES sell=YES rows=16302
[TRAIN][5M] asof=2014-09-29 feats=69 buy=YES sell=YES rows=16432
[TRAIN][5M] asof=2014-10-06 feats=69 buy=YES sell=YES rows=16554
[TRAIN][5M] asof=2014-10-13 feats=69 buy=YES sell=YES rows=16689
[TRAIN][5M] asof=2014-10-20 feats=69 buy=YES sell=YES rows=16875
[TRAIN][5M] asof=2014-10-27 feats=69 buy=YES sell=YES rows=16998
[TRAIN][5M] asof=2014-11-03 feats=69 buy=YES sell=YES rows=17136
[TRAIN][5M] asof=2014-11-10 feats=69 buy=YES sell=YES rows=17275
[TRAIN][5M] asof=2014-11-17 feats=69 buy=YES sell=YES rows=17390
[TRAIN][5M] asof=2014-11-24 feats=69 buy=YES sell=YES rows=17529
[TRAIN][5M] asof=2014-12-01 feats=69 buy=YES sell=YES rows=17579
[TRAIN][5M] asof=2014-12-08 feats=69 buy=YES sell=YES rows=17673
[TRAIN][5M] asof=2014-12-15 feats=69 buy=YES sell=YES rows=17792
[TRAIN][5M] asof=2014-12-22 feats=69 buy=YES sell=YES rows=17936
[TRAIN][5M] asof=2014-12-29 feats=69 buy=YES sell=YES rows=18050
[TRAIN][5M] asof=2015-01-05 feats=69 buy=YES sell=YES rows=18129
[TRAIN][5M] asof=2015-01-12 feats=69 buy=YES sell=YES rows=18246
[TRAIN][5M] asof=2015-01-20 feats=69 buy=YES sell=YES rows=18381
[TRAIN][5M] asof=2015-01-26 feats=69 buy=YES sell=YES rows=18491
[TRAIN][5M] asof=2015-02-02 feats=69 buy=YES sell=YES rows=18677
[TRAIN][5M] asof=2015-02-09 feats=69 buy=YES sell=YES rows=18797
[TRAIN][5M] asof=2015-02-17 feats=69 buy=YES sell=YES rows=18925
[TRAIN][5M] asof=2015-02-23 feats=69 buy=YES sell=YES rows=19013
[TRAIN][5M] asof=2015-03-02 feats=69 buy=YES sell=YES rows=19097
[TRAIN][5M] asof=2015-03-09 feats=69 buy=YES sell=YES rows=19229
[TRAIN][5M] asof=2015-03-16 feats=69 buy=YES sell=YES rows=19365
[TRAIN][5M] asof=2015-03-23 feats=69 buy=YES sell=YES rows=19492
[TRAIN][5M] asof=2015-03-30 feats=69 buy=YES sell=YES rows=19635
[TRAIN][5M] asof=2015-04-06 feats=69 buy=YES sell=YES rows=19741
[TRAIN][5M] asof=2015-04-13 feats=69 buy=YES sell=YES rows=19840
[TRAIN][5M] asof=2015-04-20 feats=69 buy=YES sell=YES rows=19944
[TRAIN][5M] asof=2015-04-27 feats=69 buy=YES sell=YES rows=20061
[TRAIN][5M] asof=2015-05-04 feats=69 buy=YES sell=YES rows=20211
[TRAIN][5M] asof=2015-05-11 feats=69 buy=YES sell=YES rows=20329
[TRAIN][5M] asof=2015-05-18 feats=69 buy=YES sell=YES rows=20457
[TRAIN][5M] asof=2015-05-26 feats=69 buy=YES sell=YES rows=20552
[TRAIN][5M] asof=2015-06-01 feats=69 buy=YES sell=YES rows=20666
[TRAIN][5M] asof=2015-06-08 feats=69 buy=YES sell=YES rows=20799
[TRAIN][5M] asof=2015-06-15 feats=69 buy=YES sell=YES rows=20915
[TRAIN][5M] asof=2015-06-22 feats=69 buy=YES sell=YES rows=21058
[TRAIN][5M] asof=2015-06-29 feats=69 buy=YES sell=YES rows=21209
[TRAIN][5M] asof=2015-07-06 feats=69 buy=YES sell=YES rows=21339
[TRAIN][5M] asof=2015-07-13 feats=69 buy=YES sell=YES rows=21488
[TRAIN][5M] asof=2015-07-20 feats=69 buy=YES sell=YES rows=21644
[TRAIN][5M] asof=2015-07-27 feats=69 buy=YES sell=YES rows=21799
[TRAIN][5M] asof=2015-08-03 feats=69 buy=YES sell=YES rows=21936
[TRAIN][5M] asof=2015-08-10 feats=69 buy=YES sell=YES rows=22098
[TRAIN][5M] asof=2015-08-17 feats=69 buy=YES sell=YES rows=22238
[TRAIN][5M] asof=2015-08-24 feats=69 buy=YES sell=YES rows=22382
[TRAIN][5M] asof=2015-08-31 feats=69 buy=YES sell=YES rows=22553
[TRAIN][5M] asof=2015-09-08 feats=69 buy=YES sell=YES rows=22692
[TRAIN][5M] asof=2015-09-14 feats=69 buy=YES sell=YES rows=22799
[TRAIN][5M] asof=2015-09-21 feats=69 buy=YES sell=YES rows=22957
[TRAIN][5M] asof=2015-09-28 feats=69 buy=YES sell=YES rows=23138
[TRAIN][5M] asof=2015-10-05 feats=69 buy=YES sell=YES rows=23303
[TRAIN][5M] asof=2015-10-12 feats=69 buy=YES sell=YES rows=23449
[TRAIN][5M] asof=2015-10-19 feats=69 buy=YES sell=YES rows=23621
[TRAIN][5M] asof=2015-10-26 feats=69 buy=YES sell=YES rows=23792
[TRAIN][5M] asof=2015-11-02 feats=69 buy=YES sell=YES rows=23930
[TRAIN][5M] asof=2015-11-09 feats=69 buy=YES sell=YES rows=24071
[TRAIN][5M] asof=2015-11-16 feats=69 buy=YES sell=YES rows=24245
[TRAIN][5M] asof=2015-11-23 feats=69 buy=YES sell=YES rows=24405
[TRAIN][5M] asof=2015-11-30 feats=69 buy=YES sell=YES rows=24504
[TRAIN][5M] asof=2015-12-07 feats=69 buy=YES sell=YES rows=24665
[TRAIN][5M] asof=2015-12-14 feats=69 buy=YES sell=YES rows=24833
[TRAIN][5M] asof=2015-12-21 feats=69 buy=YES sell=YES rows=24992
[TRAIN][5M] asof=2015-12-28 feats=69 buy=YES sell=YES rows=25090
[TRAIN][5M] asof=2016-01-04 feats=69 buy=YES sell=YES rows=25219
[TRAIN][5M] asof=2016-01-11 feats=69 buy=YES sell=YES rows=25415
[TRAIN][5M] asof=2016-01-19 feats=69 buy=YES sell=YES rows=25570
[TRAIN][5M] asof=2016-01-25 feats=69 buy=YES sell=YES rows=25693
[TRAIN][5M] asof=2016-02-01 feats=69 buy=YES sell=YES rows=25888
[TRAIN][5M] asof=2016-02-08 feats=69 buy=YES sell=YES rows=26065
[TRAIN][5M] asof=2016-02-16 feats=69 buy=YES sell=YES rows=26269
[TRAIN][5M] asof=2016-02-22 feats=69 buy=YES sell=YES rows=26395
[TRAIN][5M] asof=2016-02-29 feats=69 buy=YES sell=YES rows=26554
[TRAIN][5M] asof=2016-03-07 feats=69 buy=YES sell=YES rows=26724
[TRAIN][5M] asof=2016-03-14 feats=69 buy=YES sell=YES rows=26863
[TRAIN][5M] asof=2016-03-21 feats=69 buy=YES sell=YES rows=26966
[TRAIN][5M] asof=2016-03-28 feats=69 buy=YES sell=YES rows=27052
[TRAIN][5M] asof=2016-04-04 feats=69 buy=YES sell=YES rows=27179
[TRAIN][5M] asof=2016-04-11 feats=69 buy=YES sell=YES rows=27333
[TRAIN][5M] asof=2016-04-18 feats=69 buy=YES sell=YES rows=27461
[TRAIN][5M] asof=2016-04-25 feats=69 buy=YES sell=YES rows=27584
[TRAIN][5M] asof=2016-05-02 feats=69 buy=YES sell=YES rows=27772
[TRAIN][5M] asof=2016-05-09 feats=69 buy=YES sell=YES rows=27902
[TRAIN][5M] asof=2016-05-16 feats=69 buy=YES sell=YES rows=28024
[TRAIN][5M] asof=2016-05-23 feats=69 buy=YES sell=YES rows=28182
[TRAIN][5M] asof=2016-05-31 feats=69 buy=YES sell=YES rows=28334
[TRAIN][5M] asof=2016-06-06 feats=69 buy=YES sell=YES rows=28430
[TRAIN][5M] asof=2016-06-13 feats=69 buy=YES sell=YES rows=28542
[TRAIN][5M] asof=2016-06-20 feats=69 buy=YES sell=YES rows=28718
[TRAIN][5M] asof=2016-06-27 feats=69 buy=YES sell=YES rows=28900
[TRAIN][5M] asof=2016-07-05 feats=69 buy=YES sell=YES rows=29063
[TRAIN][5M] asof=2016-07-11 feats=69 buy=YES sell=YES rows=29178
[TRAIN][5M] asof=2016-07-18 feats=69 buy=YES sell=YES rows=29302
[TRAIN][5M] asof=2016-07-25 feats=69 buy=YES sell=YES rows=29428
[TRAIN][5M] asof=2016-08-01 feats=69 buy=YES sell=YES rows=29562
[TRAIN][5M] asof=2016-08-08 feats=69 buy=YES sell=YES rows=29687
[TRAIN][5M] asof=2016-08-15 feats=69 buy=YES sell=YES rows=29790
[TRAIN][5M] asof=2016-08-22 feats=69 buy=YES sell=YES rows=29912
[TRAIN][5M] asof=2016-08-29 feats=69 buy=YES sell=YES rows=30000
[TRAIN][5M] asof=2016-09-06 feats=69 buy=YES sell=YES rows=30125
[TRAIN][5M] asof=2016-09-12 feats=69 buy=YES sell=YES rows=30237
[TRAIN][5M] asof=2016-09-19 feats=69 buy=YES sell=YES rows=30352
[TRAIN][5M] asof=2016-09-26 feats=69 buy=YES sell=YES rows=30508
[TRAIN][5M] asof=2016-10-03 feats=69 buy=YES sell=YES rows=30647
[TRAIN][5M] asof=2016-10-10 feats=69 buy=YES sell=YES rows=30765
[TRAIN][5M] asof=2016-10-17 feats=69 buy=YES sell=YES rows=30871
[TRAIN][5M] asof=2016-10-24 feats=69 buy=YES sell=YES rows=30985
[TRAIN][5M] asof=2016-10-31 feats=69 buy=YES sell=YES rows=31087
[TRAIN][5M] asof=2016-11-07 feats=69 buy=YES sell=YES rows=31254
[TRAIN][5M] asof=2016-11-14 feats=69 buy=YES sell=YES rows=31399
[TRAIN][5M] asof=2016-11-21 feats=69 buy=YES sell=YES rows=31552
[TRAIN][5M] asof=2016-11-28 feats=69 buy=YES sell=YES rows=31637
[TRAIN][5M] asof=2016-12-05 feats=69 buy=YES sell=YES rows=31775
[TRAIN][5M] asof=2016-12-12 feats=69 buy=YES sell=YES rows=31924
[TRAIN][5M] asof=2016-12-19 feats=69 buy=YES sell=YES rows=32034
[TRAIN][5M] asof=2016-12-27 feats=69 buy=YES sell=YES rows=32198
[TRAIN][5M] asof=2017-01-03 feats=69 buy=YES sell=YES rows=32279

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
1978,2019-12-23,0.149304,0.205,0.230,FORCE_BUY,0.002572,0.004443,0.003161,0.002572,FREE,1.338595e+13,10.7212,-0.5,-0.50
1979,2019-12-24,0.140908,0.205,0.230,FORCE_BUY,0.000121,-0.000571,0.002106,0.000121,FORCE_SELL,1.341415e+13,10.7325,-0.5,-0.50
1980,2019-12-26,0.153845,0.205,0.230,FORCE_BUY,0.029743,0.006162,0.001980,0.029743,FORCE_BUY,1.381313e+13,11.0787,-0.5,1.95
1981,2019-12-27,0.201983,0.205,0.230,FORCE_BUY,-0.014070,0.000797,-0.000117,-0.014070,FREE,1.382413e+13,10.9525,-0.5,1.95
1982,2019-12-30,0.226911,0.190,0.215,FORCE_SELL,-0.021668,-0.029709,-0.027342,-0.027342,FORCE_BUY,1.352459e+13,10.7775,-0.5,1.95

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
1978,2019-12-23,3.109785e+07,0.000000e+00,1,-0.5,-0.50,0.149304,FORCE_BUY,0.205,0.230
1979,2019-12-24,3.113063e+07,0.000000e+00,1,-0.5,1.95,0.140908,FORCE_BUY,0.205,0.230
1980,2019-12-26,3.213481e+07,0.000000e+00,1,-0.5,1.95,0.153845,FORCE_BUY,0.205,0.230
1981,2019-12-27,3.176876e+07,0.000000e+00,1,-0.5,1.95,0.201983,FORCE_BUY,0.205,0.230
1982,2019-12-30,3.107987e+07,3.107987e+07,0,-0.5,1.95,0.226911,FORCE_SELL,0.190,0.215

In [2]:
resume_res = run_adaptive_reward_from_snapshot(
    dp_lookback_override=252,
    snapshot_path=str(snapshot_path),
    end_time="2026-12-31",
    sim_start="2020-01-01",
    initial_capital=100000.0,
    fee_pct=0.0,
    output_dir="output_adaptive_reward_resumed_fresh_TQQQ_252days_at_2020",
    # Optional. If omitted, the code saves next to the source snapshot as
    # checkpoints/TQQQ_adaptive_reward_fresh_start__continued.joblib
    save_snapshot_path="output_adaptive_reward_resumed_fresh_TQQQ_252days_at_2020/final_checkpoint.joblib",
    autosave_year_start_checkpoints=True,
    verbose=True,
)

print("continued snapshot:", resume_res["continued_snapshot_path"])

display(resume_res["daily_reward_df"].tail())
display(resume_res["daily_log_df"].tail())
display(resume_res["trades_df"].head())

[TRAIN][DAILY-PROB] n=2332 pos=470 (20.15%)
[TRAIN][DAILY-PROB] n=2357 pos=475 (20.15%)
[TRAIN][DAILY-PROB] n=2382 pos=477 (20.03%)
[TRAIN][DAILY-PROB] n=2407 pos=478 (19.86%)
[TRAIN][DAILY-PROB] n=2432 pos=480 (19.74%)
[TRAIN][DAILY-PROB] n=2457 pos=484 (19.70%)
[TRAIN][DAILY-PROB] n=2482 pos=487 (19.62%)
[TRAIN][DAILY-PROB] n=2507 pos=493 (19.66%)
[TRAIN][DAILY-PROB] n=2532 pos=504 (19.91%)
[TRAIN][DAILY-PROB] n=2557 pos=505 (19.75%)
[TRAIN][DAILY-PROB] n=2582 pos=508 (19.67%)
[TRAIN][DAILY-PROB] n=2607 pos=516 (19.79%)
[TRAIN][DAILY-PROB] n=2632 pos=519 (19.72%)
[TRAIN][DAILY-PROB] n=2657 pos=525 (19.76%)
[TRAIN][DAILY-PROB] n=2682 pos=525 (19.57%)
[TRAIN][DAILY-PROB] n=2707 pos=528 (19.50%)
[TRAIN][DAILY-PROB] n=2732 pos=531 (19.44%)
[TRAIN][DAILY-PROB] n=2757 pos=542 (19.66%)
[TRAIN][DAILY-PROB] n=2782 pos=545 (19.59%)
[TRAIN][DAILY-PROB] n=2807 pos=551 (19.63%)
[TRAIN][DAILY-PROB] n=2832 pos=557 (19.67%)
[TRAIN][DAILY-PROB] n=2857 pos=559 (19.57%)
[TRAIN][DAILY-PROB] n=2882 pos=569 (19.74%)
[TRAIN][DAILY-PROB] n=2907 pos=569 (19.57%)
[TRAIN][DAILY-PROB] n=2932 pos=580 (19.78%)
[TRAIN][DAILY-PROB] n=2957 pos=588 (19.89%)
[TRAIN][DAILY-PROB] n=2982 pos=596 (19.99%)
[TRAIN][DAILY-PROB] n=3007 pos=597 (19.85%)
[TRAIN][DAILY-PROB] n=3032 pos=601 (19.82%)
[TRAIN][DAILY-PROB] n=3057 pos=608 (19.89%)
[TRAIN][DAILY-PROB] n=3082 pos=614 (19.92%)
[TRAIN][DAILY-PROB] n=3107 pos=623 (20.05%)
[TRAIN][DAILY-PROB] n=3132 pos=627 (20.02%)
[TRAIN][DAILY-PROB] n=3157 pos=633 (20.05%)
[TRAIN][DAILY-PROB] n=3182 pos=633 (19.89%)
[TRAIN][DAILY-PROB] n=3207 pos=639 (19.93%)
[TRAIN][DAILY-PROB] n=3232 pos=647 (20.02%)
[TRAIN][DAILY-PROB] n=3257 pos=656 (20.14%)
[TRAIN][DAILY-PROB] n=3282 pos=666 (20.29%)
[TRAIN][DAILY-PROB] n=3307 pos=667 (20.17%)
[TRAIN][DAILY-PROB] n=3332 pos=675 (20.26%)
[TRAIN][DAILY-PROB] n=3357 pos=678 (20.20%)
[TRAIN][DAILY-PROB] n=3382 pos=684 (20.22%)
[TRAIN][DAILY-PROB] n=3407 pos=692 (20.31%)
[TRAIN][DAILY-PROB] n=3432 pos=694 (20.22%)
[TRAIN][DAILY-PROB] n=3457 pos=700 (20.25%)
[TRAIN][DAILY-PROB] n=3482 pos=709 (20.36%)
[TRAIN][DAILY-PROB] n=3507 pos=719 (20.50%)
[TRAIN][DAILY-PROB] n=3532 pos=723 (20.47%)
[TRAIN][DAILY-PROB] n=3557 pos=726 (20.41%)
[TRAIN][DAILY-PROB] n=3582 pos=732 (20.44%)
[TRAIN][DAILY-PROB] n=3607 pos=739 (20.49%)
[TRAIN][DAILY-PROB] n=3632 pos=741 (20.40%)
[TRAIN][DAILY-PROB] n=3657 pos=752 (20.56%)
[TRAIN][DAILY-PROB] n=3682 pos=759 (20.61%)
[TRAIN][DAILY-PROB] n=3707 pos=770 (20.77%)
[TRAIN][DAILY-PROB] n=3732 pos=782 (20.95%)
[TRAIN][DAILY-PROB] n=3757 pos=791 (21.05%)
[TRAIN][DAILY-PROB] n=3782 pos=796 (21.05%)
[TRAIN][DAILY-PROB] n=3807 pos=805 (21.15%)
[TRAIN][DAILY-PROB] n=3832 pos=809 (21.11%)
[TRAIN][DAILY-PROB] n=3857 pos=816 (21.16%)
[TRAIN][DAILY-PROB] n=3882 pos=822 (21.17%)
[TRAIN][DAILY-PROB] n=3907 pos=823 (21.06%)
[TRAIN][5M] asof=2019-12-31 feats=69 buy=YES sell=YES rows=57752
[TRAIN][5M] asof=2020-01-06 feats=69 buy=YES sell=YES rows=57885
[TRAIN][5M] asof=2020-01-13 feats=69 buy=YES sell=YES rows=58140
[TRAIN][5M] asof=2020-01-21 feats=69 buy=YES sell=YES rows=58318
[TRAIN][5M] asof=2020-01-27 feats=69 buy=YES sell=YES rows=58465
[TRAIN][5M] asof=2020-02-03 feats=69 buy=YES sell=YES rows=58676
[TRAIN][5M] asof=2020-02-10 feats=69 buy=YES sell=YES rows=58878
[TRAIN][5M] asof=2020-02-18 feats=69 buy=YES sell=YES rows=59038
[TRAIN][5M] asof=2020-02-24 feats=69 buy=YES sell=YES rows=59189
[TRAIN][5M] asof=2020-03-02 feats=69 buy=YES sell=YES rows=59426
[TRAIN][5M] asof=2020-03-09 feats=69 buy=YES sell=YES rows=59631
[TRAIN][5M] asof=2020-03-16 feats=69 buy=YES sell=YES rows=59895
[TRAIN][5M] asof=2020-03-23 feats=69 buy=YES sell=YES rows=60104
[TRAIN][5M] asof=2020-03-30 feats=69 buy=YES sell=YES rows=60283
[TRAIN][5M] asof=2020-04-06 feats=69 buy=YES sell=YES rows=60488
[TRAIN][5M] asof=2020-04-13 feats=69 buy=YES sell=YES rows=60680
[TRAIN][5M] asof=2020-04-20 feats=69 buy=YES sell=YES rows=60889
[TRAIN][5M] asof=2020-04-27 feats=69 buy=YES sell=YES rows=61132
[TRAIN][5M] asof=2020-05-04 feats=69 buy=YES sell=YES rows=61326
[TRAIN][5M] asof=2020-05-11 feats=69 buy=YES sell=YES rows=61523
[TRAIN][5M] asof=2020-05-18 feats=69 buy=YES sell=YES rows=61722
[TRAIN][5M] asof=2020-05-26 feats=69 buy=YES sell=YES rows=61882
[TRAIN][5M] asof=2020-06-01 feats=69 buy=YES sell=YES rows=62064
[TRAIN][5M] asof=2020-06-08 feats=69 buy=YES sell=YES rows=62273
[TRAIN][5M] asof=2020-06-15 feats=69 buy=YES sell=YES rows=62461
[TRAIN][5M] asof=2020-06-22 feats=69 buy=YES sell=YES rows=62696
[TRAIN][5M] asof=2020-06-29 feats=69 buy=YES sell=YES rows=62865
[TRAIN][5M] asof=2020-07-06 feats=69 buy=YES sell=YES rows=63041
[TRAIN][5M] asof=2020-07-13 feats=69 buy=YES sell=YES rows=63271
[TRAIN][5M] asof=2020-07-20 feats=69 buy=YES sell=YES rows=63430
[TRAIN][5M] asof=2020-07-27 feats=69 buy=YES sell=YES rows=63607
[TRAIN][5M] asof=2020-08-03 feats=69 buy=YES sell=YES rows=63794
[TRAIN][5M] asof=2020-08-10 feats=69 buy=YES sell=YES rows=63978
[TRAIN][5M] asof=2020-08-17 feats=69 buy=YES sell=YES rows=64228
[TRAIN][5M] asof=2020-08-24 feats=69 buy=YES sell=YES rows=64426
[TRAIN][5M] asof=2020-08-31 feats=69 buy=YES sell=YES rows=64640
[TRAIN][5M] asof=2020-09-08 feats=69 buy=YES sell=YES rows=64838
[TRAIN][5M] asof=2020-09-14 feats=69 buy=YES sell=YES rows=65025
[TRAIN][5M] asof=2020-09-21 feats=69 buy=YES sell=YES rows=65242
[TRAIN][5M] asof=2020-09-28 feats=69 buy=YES sell=YES rows=65496
[TRAIN][5M] asof=2020-10-05 feats=69 buy=YES sell=YES rows=65709
[TRAIN][5M] asof=2020-10-12 feats=69 buy=YES sell=YES rows=65909
[TRAIN][5M] asof=2020-10-19 feats=69 buy=YES sell=YES rows=66119
[TRAIN][5M] asof=2020-10-26 feats=69 buy=YES sell=YES rows=66290
[TRAIN][5M] asof=2020-11-02 feats=69 buy=YES sell=YES rows=66483
[TRAIN][5M] asof=2020-11-09 feats=69 buy=YES sell=YES rows=66675
[TRAIN][5M] asof=2020-11-16 feats=69 buy=YES sell=YES rows=66844
[TRAIN][5M] asof=2020-11-23 feats=69 buy=YES sell=YES rows=67028
[TRAIN][5M] asof=2020-11-30 feats=69 buy=YES sell=YES rows=67183
[TRAIN][5M] asof=2020-12-07 feats=69 buy=YES sell=YES rows=67391
[TRAIN][5M] asof=2020-12-14 feats=69 buy=YES sell=YES rows=67546
[TRAIN][5M] asof=2020-12-21 feats=69 buy=YES sell=YES rows=67741
[TRAIN][5M] asof=2020-12-28 feats=69 buy=YES sell=YES rows=67912
[TRAIN][5M] asof=2021-01-04 feats=69 buy=YES sell=YES rows=68055
[TRAIN][5M] asof=2021-01-11 feats=69 buy=YES sell=YES rows=68241
[TRAIN][5M] asof=2021-01-19 feats=69 buy=YES sell=YES rows=68460
[TRAIN][5M] asof=2021-01-25 feats=69 buy=YES sell=YES rows=68623
[TRAIN][5M] asof=2021-02-01 feats=69 buy=YES sell=YES rows=68817
[TRAIN][5M] asof=2021-02-08 feats=69 buy=YES sell=YES rows=68988
[TRAIN][5M] asof=2021-02-16 feats=69 buy=YES sell=YES rows=69143
[TRAIN][5M] asof=2021-02-22 feats=69 buy=YES sell=YES rows=69307
[TRAIN][5M] asof=2021-03-01 feats=69 buy=YES sell=YES rows=69510
[TRAIN][5M] asof=2021-03-08 feats=69 buy=YES sell=YES rows=69763
[TRAIN][5M] asof=2021-03-15 feats=69 buy=YES sell=YES rows=69961
[TRAIN][5M] asof=2021-03-22 feats=69 buy=YES sell=YES rows=70114
[TRAIN][5M] asof=2021-03-29 feats=69 buy=YES sell=YES rows=70323
[TRAIN][5M] asof=2021-04-05 feats=69 buy=YES sell=YES rows=70511
[TRAIN][5M] asof=2021-04-12 feats=69 buy=YES sell=YES rows=70734
[TRAIN][5M] asof=2021-04-19 feats=69 buy=YES sell=YES rows=70922
[TRAIN][5M] asof=2021-04-26 feats=69 buy=YES sell=YES rows=71116
[TRAIN][5M] asof=2021-05-03 feats=69 buy=YES sell=YES rows=71323
[TRAIN][5M] asof=2021-05-10 feats=69 buy=YES sell=YES rows=71515
[TRAIN][5M] asof=2021-05-17 feats=69 buy=YES sell=YES rows=71711
[TRAIN][5M] asof=2021-05-24 feats=69 buy=YES sell=YES rows=71906
[TRAIN][5M] asof=2021-06-01 feats=69 buy=YES sell=YES rows=72070
[TRAIN][5M] asof=2021-06-07 feats=69 buy=YES sell=YES rows=72244
[TRAIN][5M] asof=2021-06-14 feats=69 buy=YES sell=YES rows=72467
[TRAIN][5M] asof=2021-06-21 feats=69 buy=YES sell=YES rows=72677
[TRAIN][5M] asof=2021-06-28 feats=69 buy=YES sell=YES rows=72821
[TRAIN][5M] asof=2021-07-06 feats=69 buy=YES sell=YES rows=73034
[TRAIN][5M] asof=2021-07-12 feats=69 buy=YES sell=YES rows=73179
[TRAIN][5M] asof=2021-07-19 feats=69 buy=YES sell=YES rows=73372
[TRAIN][5M] asof=2021-07-26 feats=69 buy=YES sell=YES rows=73555
[TRAIN][5M] asof=2021-08-02 feats=69 buy=YES sell=YES rows=73718
[TRAIN][5M] asof=2021-08-09 feats=69 buy=YES sell=YES rows=73880
[TRAIN][5M] asof=2021-08-16 feats=69 buy=YES sell=YES rows=74050
[TRAIN][5M] asof=2021-08-23 feats=69 buy=YES sell=YES rows=74268
[TRAIN][5M] asof=2021-08-30 feats=69 buy=YES sell=YES rows=74414
[TRAIN][5M] asof=2021-09-07 feats=69 buy=YES sell=YES rows=74603
[TRAIN][5M] asof=2021-09-13 feats=69 buy=YES sell=YES rows=74723
[TRAIN][5M] asof=2021-09-20 feats=69 buy=YES sell=YES rows=74939
[TRAIN][5M] asof=2021-09-27 feats=69 buy=YES sell=YES rows=75104
[TRAIN][5M] asof=2021-10-04 feats=69 buy=YES sell=YES rows=75313
[TRAIN][5M] asof=2021-10-11 feats=69 buy=YES sell=YES rows=75515
[TRAIN][5M] asof=2021-10-18 feats=69 buy=YES sell=YES rows=75705
[TRAIN][5M] asof=2021-10-25 feats=69 buy=YES sell=YES rows=75912
[TRAIN][5M] asof=2021-11-01 feats=69 buy=YES sell=YES rows=76105
[TRAIN][5M] asof=2021-11-08 feats=69 buy=YES sell=YES rows=76298
[TRAIN][5M] asof=2021-11-15 feats=69 buy=YES sell=YES rows=76496
[TRAIN][5M] asof=2021-11-22 feats=69 buy=YES sell=YES rows=76643
[TRAIN][5M] asof=2021-11-29 feats=69 buy=YES sell=YES rows=76801
[TRAIN][5M] asof=2021-12-06 feats=69 buy=YES sell=YES rows=77007
[TRAIN][5M] asof=2021-12-13 feats=69 buy=YES sell=YES rows=77177
[TRAIN][5M] asof=2021-12-20 feats=69 buy=YES sell=YES rows=77308
[TRAIN][5M] asof=2021-12-27 feats=69 buy=YES sell=YES rows=77490
[TRAIN][5M] asof=2022-01-03 feats=69 buy=YES sell=YES rows=77675
[TRAIN][5M] asof=2022-01-10 feats=69 buy=YES sell=YES rows=77870
[TRAIN][5M] asof=2022-01-18 feats=69 buy=YES sell=YES rows=78109
[TRAIN][5M] asof=2022-01-24 feats=69 buy=YES sell=YES rows=78284
[TRAIN][5M] asof=2022-01-31 feats=69 buy=YES sell=YES rows=78528
[TRAIN][5M] asof=2022-02-07 feats=69 buy=YES sell=YES rows=78736
[TRAIN][5M] asof=2022-02-14 feats=69 buy=YES sell=YES rows=78888
[TRAIN][5M] asof=2022-02-22 feats=69 buy=YES sell=YES rows=79046
[TRAIN][5M] asof=2022-02-28 feats=69 buy=YES sell=YES rows=79261
[TRAIN][5M] asof=2022-03-07 feats=69 buy=YES sell=YES rows=79466
[TRAIN][5M] asof=2022-03-14 feats=69 buy=YES sell=YES rows=79627
[TRAIN][5M] asof=2022-03-21 feats=69 buy=YES sell=YES rows=79847
[TRAIN][5M] asof=2022-03-28 feats=69 buy=YES sell=YES rows=80054
[TRAIN][5M] asof=2022-04-04 feats=69 buy=YES sell=YES rows=80234
[TRAIN][5M] asof=2022-04-11 feats=69 buy=YES sell=YES rows=80462
[TRAIN][5M] asof=2022-04-18 feats=69 buy=YES sell=YES rows=80661
[TRAIN][5M] asof=2022-04-25 feats=69 buy=YES sell=YES rows=80893
[TRAIN][5M] asof=2022-05-02 feats=69 buy=YES sell=YES rows=81113
[TRAIN][5M] asof=2022-05-09 feats=69 buy=YES sell=YES rows=81299
[TRAIN][5M] asof=2022-05-16 feats=69 buy=YES sell=YES rows=81497
[TRAIN][5M] asof=2022-05-23 feats=69 buy=YES sell=YES rows=81762
[TRAIN][5M] asof=2022-05-31 feats=69 buy=YES sell=YES rows=82025
[TRAIN][5M] asof=2022-06-06 feats=69 buy=YES sell=YES rows=82191
[TRAIN][5M] asof=2022-06-13 feats=69 buy=YES sell=YES rows=82438
[TRAIN][5M] asof=2022-06-21 feats=69 buy=YES sell=YES rows=82634
[TRAIN][5M] asof=2022-06-27 feats=69 buy=YES sell=YES rows=82782
[TRAIN][5M] asof=2022-07-05 feats=69 buy=YES sell=YES rows=82930
[TRAIN][5M] asof=2022-07-11 feats=69 buy=YES sell=YES rows=83067
[TRAIN][5M] asof=2022-07-18 feats=69 buy=YES sell=YES rows=83153
[TRAIN][5M] asof=2022-07-25 feats=69 buy=YES sell=YES rows=83369
[TRAIN][5M] asof=2022-08-01 feats=69 buy=YES sell=YES rows=83526
[TRAIN][5M] asof=2022-08-08 feats=69 buy=YES sell=YES rows=83755
[TRAIN][5M] asof=2022-08-15 feats=69 buy=YES sell=YES rows=83937
[TRAIN][5M] asof=2022-08-22 feats=69 buy=YES sell=YES rows=84212
[TRAIN][5M] asof=2022-08-29 feats=69 buy=YES sell=YES rows=84431
[TRAIN][5M] asof=2022-09-06 feats=69 buy=YES sell=YES rows=84620
[TRAIN][5M] asof=2022-09-12 feats=69 buy=YES sell=YES rows=84805
[TRAIN][5M] asof=2022-09-19 feats=69 buy=YES sell=YES rows=85037
[TRAIN][5M] asof=2022-09-26 feats=69 buy=YES sell=YES rows=85250
[TRAIN][5M] asof=2022-10-03 feats=69 buy=YES sell=YES rows=85458
[TRAIN][5M] asof=2022-10-10 feats=69 buy=YES sell=YES rows=85650
[TRAIN][5M] asof=2022-10-17 feats=69 buy=YES sell=YES rows=85842
[TRAIN][5M] asof=2022-10-24 feats=69 buy=YES sell=YES rows=86088
[TRAIN][5M] asof=2022-10-31 feats=69 buy=YES sell=YES rows=86305
[TRAIN][5M] asof=2022-11-07 feats=69 buy=YES sell=YES rows=86509
[TRAIN][5M] asof=2022-11-14 feats=69 buy=YES sell=YES rows=86718
[TRAIN][5M] asof=2022-11-21 feats=69 buy=YES sell=YES rows=86929
[TRAIN][5M] asof=2022-11-28 feats=69 buy=YES sell=YES rows=87128
[TRAIN][5M] asof=2022-12-05 feats=69 buy=YES sell=YES rows=87234
[TRAIN][5M] asof=2022-12-12 feats=69 buy=YES sell=YES rows=87324
[TRAIN][5M] asof=2022-12-19 feats=69 buy=YES sell=YES rows=87486
[TRAIN][5M] asof=2022-12-27 feats=69 buy=YES sell=YES rows=87679
[TRAIN][5M] asof=2023-01-03 feats=69 buy=YES sell=YES rows=87844
[TRAIN][5M] asof=2023-01-09 feats=69 buy=YES sell=YES rows=87979
[TRAIN][5M] asof=2023-01-17 feats=69 buy=YES sell=YES rows=88133
[TRAIN][5M] asof=2023-01-23 feats=69 buy=YES sell=YES rows=88332
[TRAIN][5M] asof=2023-01-30 feats=69 buy=YES sell=YES rows=88507
[TRAIN][5M] asof=2023-02-06 feats=69 buy=YES sell=YES rows=88727
[TRAIN][5M] asof=2023-02-13 feats=69 buy=YES sell=YES rows=88942
[TRAIN][5M] asof=2023-02-21 feats=69 buy=YES sell=YES rows=89134
[TRAIN][5M] asof=2023-02-27 feats=69 buy=YES sell=YES rows=89291
[TRAIN][5M] asof=2023-03-06 feats=69 buy=YES sell=YES rows=89505
[TRAIN][5M] asof=2023-03-13 feats=69 buy=YES sell=YES rows=89678
[TRAIN][5M] asof=2023-03-20 feats=69 buy=YES sell=YES rows=89888
[TRAIN][5M] asof=2023-03-27 feats=69 buy=YES sell=YES rows=90083
[TRAIN][5M] asof=2023-04-03 feats=69 buy=YES sell=YES rows=90319
[TRAIN][5M] asof=2023-04-10 feats=69 buy=YES sell=YES rows=90507
[TRAIN][5M] asof=2023-04-17 feats=69 buy=YES sell=YES rows=90699
[TRAIN][5M] asof=2023-04-24 feats=69 buy=YES sell=YES rows=90900
[TRAIN][5M] asof=2023-05-01 feats=69 buy=YES sell=YES rows=91078
[TRAIN][5M] asof=2023-05-08 feats=69 buy=YES sell=YES rows=91288
[TRAIN][5M] asof=2023-05-15 feats=69 buy=YES sell=YES rows=91460
[TRAIN][5M] asof=2023-05-22 feats=69 buy=YES sell=YES rows=91604
[TRAIN][5M] asof=2023-05-30 feats=69 buy=YES sell=YES rows=91841
[TRAIN][5M] asof=2023-06-05 feats=69 buy=YES sell=YES rows=91985
[TRAIN][5M] asof=2023-06-12 feats=69 buy=YES sell=YES rows=92169
[TRAIN][5M] asof=2023-06-20 feats=69 buy=YES sell=YES rows=92390
[TRAIN][5M] asof=2023-06-26 feats=69 buy=YES sell=YES rows=92548
[TRAIN][5M] asof=2023-07-03 feats=69 buy=YES sell=YES rows=92780
[TRAIN][5M] asof=2023-07-10 feats=69 buy=YES sell=YES rows=92914
[TRAIN][5M] asof=2023-07-17 feats=69 buy=YES sell=YES rows=93132
[TRAIN][5M] asof=2023-07-24 feats=69 buy=YES sell=YES rows=93268
[TRAIN][5M] asof=2023-07-31 feats=69 buy=YES sell=YES rows=93483
[TRAIN][5M] asof=2023-08-07 feats=69 buy=YES sell=YES rows=93682
[TRAIN][5M] asof=2023-08-14 feats=69 buy=YES sell=YES rows=93913
[TRAIN][5M] asof=2023-08-21 feats=69 buy=YES sell=YES rows=94149
[TRAIN][5M] asof=2023-08-28 feats=69 buy=YES sell=YES rows=94364
[TRAIN][5M] asof=2023-09-05 feats=69 buy=YES sell=YES rows=94532
[TRAIN][5M] asof=2023-09-11 feats=69 buy=YES sell=YES rows=94683
[TRAIN][5M] asof=2023-09-18 feats=69 buy=YES sell=YES rows=94904
[TRAIN][5M] asof=2023-09-25 feats=69 buy=YES sell=YES rows=95116
[TRAIN][5M] asof=2023-10-02 feats=69 buy=YES sell=YES rows=95296
[TRAIN][5M] asof=2023-10-09 feats=69 buy=YES sell=YES rows=95509
[TRAIN][5M] asof=2023-10-16 feats=69 buy=YES sell=YES rows=95709
[TRAIN][5M] asof=2023-10-23 feats=69 buy=YES sell=YES rows=95935
[TRAIN][5M] asof=2023-10-30 feats=69 buy=YES sell=YES rows=96150
[TRAIN][5M] asof=2023-11-06 feats=69 buy=YES sell=YES rows=96314
[TRAIN][5M] asof=2023-11-13 feats=69 buy=YES sell=YES rows=96537
[TRAIN][5M] asof=2023-11-20 feats=69 buy=YES sell=YES rows=96717
[TRAIN][5M] asof=2023-11-27 feats=69 buy=YES sell=YES rows=96870
[TRAIN][5M] asof=2023-12-04 feats=69 buy=YES sell=YES rows=97136
[TRAIN][5M] asof=2023-12-11 feats=69 buy=YES sell=YES rows=97354
[TRAIN][5M] asof=2023-12-18 feats=69 buy=YES sell=YES rows=97573
[TRAIN][5M] asof=2023-12-26 feats=69 buy=YES sell=YES rows=97762
[TRAIN][5M] asof=2024-01-02 feats=69 buy=YES sell=YES rows=97865
[TRAIN][5M] asof=2024-01-08 feats=69 buy=YES sell=YES rows=98014
[TRAIN][5M] asof=2024-01-16 feats=69 buy=YES sell=YES rows=98284
[TRAIN][5M] asof=2024-01-22 feats=69 buy=YES sell=YES rows=98478
[TRAIN][5M] asof=2024-01-29 feats=69 buy=YES sell=YES rows=98672
[TRAIN][5M] asof=2024-02-05 feats=69 buy=YES sell=YES rows=98872
[TRAIN][5M] asof=2024-02-12 feats=69 buy=YES sell=YES rows=99027
[TRAIN][5M] asof=2024-02-20 feats=69 buy=YES sell=YES rows=99196
[TRAIN][5M] asof=2024-02-26 feats=69 buy=YES sell=YES rows=99358
[TRAIN][5M] asof=2024-03-04 feats=69 buy=YES sell=YES rows=99526
[TRAIN][5M] asof=2024-03-11 feats=69 buy=YES sell=YES rows=99779
[TRAIN][5M] asof=2024-03-18 feats=69 buy=YES sell=YES rows=99986
[TRAIN][5M] asof=2024-03-25 feats=69 buy=YES sell=YES rows=100250
[TRAIN][5M] asof=2024-04-01 feats=69 buy=YES sell=YES rows=100366
[TRAIN][5M] asof=2024-04-08 feats=69 buy=YES sell=YES rows=100505
[TRAIN][5M] asof=2024-04-15 feats=69 buy=YES sell=YES rows=100700
[TRAIN][5M] asof=2024-04-22 feats=69 buy=YES sell=YES rows=100851
[TRAIN][5M] asof=2024-04-29 feats=69 buy=YES sell=YES rows=101043
[TRAIN][5M] asof=2024-05-06 feats=69 buy=YES sell=YES rows=101180
[TRAIN][5M] asof=2024-05-13 feats=69 buy=YES sell=YES rows=101339
[TRAIN][5M] asof=2024-05-20 feats=69 buy=YES sell=YES rows=101510
[TRAIN][5M] asof=2024-05-28 feats=69 buy=YES sell=YES rows=101734
[TRAIN][5M] asof=2024-06-03 feats=69 buy=YES sell=YES rows=101910
[TRAIN][5M] asof=2024-06-10 feats=69 buy=YES sell=YES rows=102096
[TRAIN][5M] asof=2024-06-17 feats=69 buy=YES sell=YES rows=102281
[TRAIN][5M] asof=2024-06-24 feats=69 buy=YES sell=YES rows=102413
[TRAIN][5M] asof=2024-07-01 feats=69 buy=YES sell=YES rows=102578
[TRAIN][5M] asof=2024-07-08 feats=69 buy=YES sell=YES rows=102745
[TRAIN][5M] asof=2024-07-15 feats=69 buy=YES sell=YES rows=102924
[TRAIN][5M] asof=2024-07-22 feats=69 buy=YES sell=YES rows=103160
[TRAIN][5M] asof=2024-07-29 feats=69 buy=YES sell=YES rows=103419
[TRAIN][5M] asof=2024-08-05 feats=69 buy=YES sell=YES rows=103627
[TRAIN][5M] asof=2024-08-12 feats=69 buy=YES sell=YES rows=103810
[TRAIN][5M] asof=2024-08-19 feats=69 buy=YES sell=YES rows=103977
[TRAIN][5M] asof=2024-08-26 feats=69 buy=YES sell=YES rows=104175
[TRAIN][5M] asof=2024-09-03 feats=69 buy=YES sell=YES rows=104363
[TRAIN][5M] asof=2024-09-09 feats=69 buy=YES sell=YES rows=104533
[TRAIN][5M] asof=2024-09-16 feats=69 buy=YES sell=YES rows=104723
[TRAIN][5M] asof=2024-09-23 feats=69 buy=YES sell=YES rows=104937
[TRAIN][5M] asof=2024-09-30 feats=69 buy=YES sell=YES rows=105100
[TRAIN][5M] asof=2024-10-07 feats=69 buy=YES sell=YES rows=105249
[TRAIN][5M] asof=2024-10-14 feats=69 buy=YES sell=YES rows=105407
[TRAIN][5M] asof=2024-10-21 feats=69 buy=YES sell=YES rows=105586
[TRAIN][5M] asof=2024-10-28 feats=69 buy=YES sell=YES rows=105790
[TRAIN][5M] asof=2024-11-04 feats=69 buy=YES sell=YES rows=105968
[TRAIN][5M] asof=2024-11-11 feats=69 buy=YES sell=YES rows=106142
[TRAIN][5M] asof=2024-11-18 feats=69 buy=YES sell=YES rows=106352
[TRAIN][5M] asof=2024-11-25 feats=69 buy=YES sell=YES rows=106589
[TRAIN][5M] asof=2024-12-02 feats=69 buy=YES sell=YES rows=106734
[TRAIN][5M] asof=2024-12-09 feats=69 buy=YES sell=YES rows=106932
[TRAIN][5M] asof=2024-12-16 feats=69 buy=YES sell=YES rows=107156
[TRAIN][5M] asof=2024-12-23 feats=69 buy=YES sell=YES rows=107322
[TRAIN][5M] asof=2024-12-30 feats=69 buy=YES sell=YES rows=107492
[TRAIN][5M] asof=2025-01-06 feats=69 buy=YES sell=YES rows=107674

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
3585,2026-05-18,0.259901,0.24,0.26,FREE,0.002692,0.046294,0.013190,0.046294,FREE,4.418697e+16,74.50,-0.5,-0.5
3586,2026-05-19,0.222622,0.24,0.26,FORCE_BUY,-0.015875,-0.023606,-0.014933,-0.015875,FORCE_SELL,4.352711e+16,73.15,-0.5,-0.5
3587,2026-05-20,0.201810,0.24,0.26,FORCE_BUY,0.017227,0.006506,0.004069,0.017227,FORCE_BUY,4.427696e+16,74.99,-0.5,-0.5
3588,2026-05-21,0.216030,0.24,0.26,FORCE_BUY,0.022632,0.029939,0.002500,0.022632,FREE,4.560255e+16,77.72,-0.5,-0.5
3589,2026-05-22,0.241934,0.24,0.26,FREE,-0.009860,0.002904,0.000768,0.002904,FREE,4.573496e+16,77.32,-0.5,-0.5

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
1602,2026-05-18,1.163219e+09,0.000000e+00,1,-0.5,-0.5,0.259901,FREE,0.24,0.26
1603,2026-05-19,1.142140e+09,0.000000e+00,1,-0.5,-0.5,0.222622,FORCE_BUY,0.24,0.26
1604,2026-05-20,1.170869e+09,0.000000e+00,1,-0.5,-0.5,0.201810,FORCE_BUY,0.24,0.26
1605,2026-05-21,1.213495e+09,0.000000e+00,1,-0.5,-0.5,0.216030,FORCE_BUY,0.24,0.26
1606,2026-05-22,1.222812e+09,1.222812e+09,0,-0.5,-0.5,0.241934,FREE,0.24,0.26

,side,seen_idx,exec_px,qty,fee,reason,ts,pred,th,gate,pnl,entry_px,entry_idx
0,buy,253880,11.2613,8879.969453,0.0,ADAPTIVE_FORCE_BUY->first acceptable 5m signal,2020-01-07 08:30:00,2.143581,-0.5,FORCE_BUY,NaN,NaN,NaN
1,sell,254029,11.2100,8879.969453,0.0,5m SELL signal,2020-01-08 05:15:00,26.507231,-0.5,FREE,-455.542433,11.2613,253880.0
2,buy,254050,11.2625,8838.575589,0.0,5m BUY signal,2020-01-08 07:00:00,0.846646,-0.5,FREE,NaN,NaN,NaN
3,sell,254065,11.3375,8838.575589,0.0,5m SELL signal,2020-01-08 08:15:00,23.341526,-0.5,FREE,662.893169,11.2625,254050.0
4,buy,254070,11.2875,8877.727640,0.0,5m BUY signal,2020-01-08 08:40:00,2.161747,-0.5,FREE,NaN,NaN,NaN

In [1]:

from pathlib import Path
import pandas as pd

from adaptive_reward_checkpoint_fresh import (
    build_adaptive_reward_snapshot,
    run_adaptive_reward_from_snapshot,
)
from adaptive_trade_extensions import RollingThresholdConfig, make_threshold_grid

snapshot_path = Path("checkpoints") / "SOXL_adaptive_reward_fresh_start_252days_at_2020.joblib"

common_kwargs = dict(
    daily_csv_path="DataAPI/data/SOXL_day.csv",
    k5m_csv_path="DataAPI/data/SOXL_5M.csv",
    code="SOXL",
    daily_chan_start="2010-02-11",
    accumulation_start="2012-02-11",
    N_confirm=5,
    min_labeled_days_to_train=200,
    retrain_every_new_labels=25,
    dp_lookback=5,
    lookahead_days_5m=2.0,
    retrain_every_days_5m=5,
    min_samples_total_5m=300,
    threshold_window_days=2.0,
    threshold_ret_grid=None,
    threshold_min_open_signals=10,
    initial_capital=100000.0,
    fee_pct=0.0,
    daily_chan_max_klines=500,
    five_chan_max_klines=500,
    macro_files={
        "vix_": "VIX.csv",
    },
    static_buy_level=0.20,
    static_sell_level=0.30,
    daily_threshold_config=RollingThresholdConfig(
        lookback_days=252,
        buy_grid=make_threshold_grid(0.05, 0.35, 0.005),
        sell_grid=make_threshold_grid(0.15, 0.60, 0.005),
        min_gap=0.02,
        min_obs=60,
        switch_penalty=0.0,
    ),
    verbose=True,
)

In [2]:
snapshot_res = build_adaptive_reward_snapshot(
    snapshot_path=str(snapshot_path),
    snapshot_end_time="2019-12-31",
    output_dir="output_adaptive_reward_snapshot_build_TQQQ_252days_at_2020",
    **common_kwargs,
)

print("base snapshot:", snapshot_res["snapshot_path"])
print("year-start build checkpoints:")
for p in snapshot_res["year_start_checkpoint_paths"]:
    print(" ", p)

display(snapshot_res["daily_reward_df"].tail())
display(snapshot_res["daily_log_df"].tail())

[TRAIN][DAILY-PROB] n=200 pos=43 (21.50%)
[TRAIN][DAILY-PROB] n=225 pos=51 (22.67%)
[TRAIN][DAILY-PROB] n=250 pos=54 (21.60%)
[TRAIN][DAILY-PROB] n=275 pos=61 (22.18%)
[TRAIN][DAILY-PROB] n=300 pos=66 (22.00%)
[TRAIN][DAILY-PROB] n=325 pos=72 (22.15%)
[TRAIN][DAILY-PROB] n=350 pos=80 (22.86%)
[TRAIN][DAILY-PROB] n=375 pos=92 (24.53%)
[TRAIN][DAILY-PROB] n=400 pos=96 (24.00%)
[TRAIN][DAILY-PROB] n=425 pos=107 (25.18%)
[TRAIN][DAILY-PROB] n=450 pos=112 (24.89%)
[TRAIN][DAILY-PROB] n=475 pos=119 (25.05%)
[TRAIN][DAILY-PROB] n=500 pos=131 (26.20%)
[TRAIN][DAILY-PROB] n=525 pos=133 (25.33%)
[TRAIN][DAILY-PROB] n=550 pos=135 (24.55%)
[TRAIN][DAILY-PROB] n=575 pos=136 (23.65%)
[TRAIN][DAILY-PROB] n=600 pos=145 (24.17%)
[TRAIN][DAILY-PROB] n=625 pos=149 (23.84%)
[TRAIN][DAILY-PROB] n=650 pos=153 (23.54%)
[TRAIN][DAILY-PROB] n=675 pos=158 (23.41%)
[TRAIN][DAILY-PROB] n=700 pos=161 (23.00%)
[TRAIN][DAILY-PROB] n=725 pos=168 (23.17%)
[TRAIN][DAILY-PROB] n=750 pos=175 (23.33%)
[TRAIN][DAILY-PROB] n=775 pos=180 (23.23%)
[TRAIN][DAILY-PROB] n=800 pos=185 (23.12%)
[TRAIN][DAILY-PROB] n=825 pos=185 (22.42%)
[TRAIN][DAILY-PROB] n=850 pos=188 (22.12%)
[TRAIN][DAILY-PROB] n=875 pos=191 (21.83%)
[TRAIN][DAILY-PROB] n=900 pos=191 (21.22%)
[TRAIN][DAILY-PROB] n=925 pos=199 (21.51%)
[TRAIN][DAILY-PROB] n=950 pos=200 (21.05%)
[TRAIN][DAILY-PROB] n=975 pos=213 (21.85%)
[TRAIN][DAILY-PROB] n=1000 pos=216 (21.60%)
[TRAIN][DAILY-PROB] n=1025 pos=220 (21.46%)
[TRAIN][DAILY-PROB] n=1050 pos=227 (21.62%)
[TRAIN][DAILY-PROB] n=1075 pos=232 (21.58%)
[TRAIN][DAILY-PROB] n=1100 pos=239 (21.73%)
[TRAIN][DAILY-PROB] n=1125 pos=245 (21.78%)
[TRAIN][DAILY-PROB] n=1150 pos=256 (22.26%)
[TRAIN][DAILY-PROB] n=1175 pos=264 (22.47%)
[TRAIN][DAILY-PROB] n=1200 pos=268 (22.33%)
[TRAIN][DAILY-PROB] n=1225 pos=277 (22.61%)
[TRAIN][DAILY-PROB] n=1250 pos=284 (22.72%)
[TRAIN][DAILY-PROB] n=1275 pos=291 (22.82%)
[TRAIN][DAILY-PROB] n=1300 pos=297 (22.85%)
[TRAIN][DAILY-PROB] n=1325 pos=306 (23.09%)
[TRAIN][DAILY-PROB] n=1350 pos=311 (23.04%)
[TRAIN][DAILY-PROB] n=1375 pos=314 (22.84%)
[TRAIN][DAILY-PROB] n=1400 pos=324 (23.14%)
[TRAIN][DAILY-PROB] n=1425 pos=328 (23.02%)
[TRAIN][DAILY-PROB] n=1450 pos=333 (22.97%)
[TRAIN][DAILY-PROB] n=1475 pos=336 (22.78%)
[TRAIN][DAILY-PROB] n=1500 pos=340 (22.67%)
[TRAIN][DAILY-PROB] n=1525 pos=344 (22.56%)
[TRAIN][DAILY-PROB] n=1550 pos=347 (22.39%)
[TRAIN][DAILY-PROB] n=1575 pos=350 (22.22%)
[TRAIN][DAILY-PROB] n=1600 pos=354 (22.12%)
[TRAIN][DAILY-PROB] n=1625 pos=360 (22.15%)
[TRAIN][DAILY-PROB] n=1650 pos=364 (22.06%)
[TRAIN][DAILY-PROB] n=1675 pos=368 (21.97%)
[TRAIN][DAILY-PROB] n=1700 pos=373 (21.94%)
[TRAIN][DAILY-PROB] n=1725 pos=376 (21.80%)
[TRAIN][DAILY-PROB] n=1750 pos=376 (21.49%)
[TRAIN][DAILY-PROB] n=1775 pos=385 (21.69%)
[TRAIN][DAILY-PROB] n=1800 pos=387 (21.50%)
[TRAIN][DAILY-PROB] n=1825 pos=393 (21.53%)
[TRAIN][DAILY-PROB] n=1850 pos=401 (21.68%)
[TRAIN][DAILY-PROB] n=1875 pos=407 (21.71%)
[TRAIN][DAILY-PROB] n=1900 pos=412 (21.68%)
[TRAIN][DAILY-PROB] n=1925 pos=419 (21.77%)
[TRAIN][DAILY-PROB] n=1950 pos=428 (21.95%)
[TRAIN][DAILY-PROB] n=1975 pos=434 (21.97%)
[TRAIN][DAILY-PROB] n=2000 pos=440 (22.00%)
[TRAIN][DAILY-PROB] n=2025 pos=446 (22.02%)
[TRAIN][DAILY-PROB] n=2050 pos=457 (22.29%)
[TRAIN][DAILY-PROB] n=2075 pos=471 (22.70%)
[TRAIN][DAILY-PROB] n=2100 pos=480 (22.86%)
[TRAIN][DAILY-PROB] n=2125 pos=486 (22.87%)
[TRAIN][DAILY-PROB] n=2150 pos=490 (22.79%)
[TRAIN][DAILY-PROB] n=2175 pos=495 (22.76%)
[TRAIN][DAILY-PROB] n=2200 pos=504 (22.91%)
[TRAIN][DAILY-PROB] n=2225 pos=509 (22.88%)
[TRAIN][DAILY-PROB] n=2250 pos=512 (22.76%)
[TRAIN][DAILY-PROB] n=2275 pos=522 (22.95%)
[TRAIN][5M] asof=2012-04-03 feats=69 buy=NO sell=YES rows=658
[TRAIN][5M] asof=2012-04-09 feats=69 buy=NO sell=YES rows=712
[TRAIN][5M] asof=2012-04-16 feats=69 buy=NO sell=YES rows=800
[TRAIN][5M] asof=2012-04-23 feats=69 buy=YES sell=YES rows=932
[TRAIN][5M] asof=2012-04-30 feats=69 buy=YES sell=YES rows=979
[TRAIN][5M] asof=2012-05-07 feats=69 buy=YES sell=YES rows=1085
[TRAIN][5M] asof=2012-05-14 feats=69 buy=YES sell=YES rows=1175
[TRAIN][5M] asof=2012-05-21 feats=69 buy=YES sell=YES rows=1307
[TRAIN][5M] asof=2012-05-29 feats=69 buy=YES sell=YES rows=1387
[TRAIN][5M] asof=2012-06-04 feats=69 buy=YES sell=YES rows=1451
[TRAIN][5M] asof=2012-06-11 feats=69 buy=YES sell=YES rows=1573
[TRAIN][5M] asof=2012-06-18 feats=69 buy=YES sell=YES rows=1682
[TRAIN][5M] asof=2012-06-25 feats=69 buy=YES sell=YES rows=1780
[TRAIN][5M] asof=2012-07-02 feats=69 buy=YES sell=YES rows=1863
[TRAIN][5M] asof=2012-07-09 feats=69 buy=YES sell=YES rows=1952
[TRAIN][5M] asof=2012-07-16 feats=69 buy=YES sell=YES rows=2026
[TRAIN][5M] asof=2012-07-23 feats=69 buy=YES sell=YES rows=2153
[TRAIN][5M] asof=2012-07-30 feats=69 buy=YES sell=YES rows=2237
[TRAIN][5M] asof=2012-08-06 feats=69 buy=YES sell=YES rows=2323
[TRAIN][5M] asof=2012-08-13 feats=69 buy=YES sell=YES rows=2418
[TRAIN][5M] asof=2012-08-20 feats=69 buy=YES sell=YES rows=2506
[TRAIN][5M] asof=2012-08-27 feats=69 buy=YES sell=YES rows=2613
[TRAIN][5M] asof=2012-09-04 feats=69 buy=YES sell=YES rows=2728
[TRAIN][5M] asof=2012-09-10 feats=69 buy=YES sell=YES rows=2795
[TRAIN][5M] asof=2012-09-17 feats=69 buy=YES sell=YES rows=2890
[TRAIN][5M] asof=2012-09-24 feats=69 buy=YES sell=YES rows=2970
[TRAIN][5M] asof=2012-10-01 feats=69 buy=YES sell=YES rows=3068
[TRAIN][5M] asof=2012-10-08 feats=69 buy=YES sell=YES rows=3118
[TRAIN][5M] asof=2012-10-15 feats=69 buy=YES sell=YES rows=3205
[TRAIN][5M] asof=2012-10-22 feats=69 buy=YES sell=YES rows=3301
[TRAIN][5M] asof=2012-10-31 feats=69 buy=YES sell=YES rows=3368
[TRAIN][5M] asof=2012-11-05 feats=69 buy=YES sell=YES rows=3470
[TRAIN][5M] asof=2012-11-12 feats=69 buy=YES sell=YES rows=3575
[TRAIN][5M] asof=2012-11-19 feats=69 buy=YES sell=YES rows=3688
[TRAIN][5M] asof=2012-11-26 feats=69 buy=YES sell=YES rows=3744
[TRAIN][5M] asof=2012-12-03 feats=69 buy=YES sell=YES rows=3793
[TRAIN][5M] asof=2012-12-10 feats=69 buy=YES sell=YES rows=3864
[TRAIN][5M] asof=2012-12-17 feats=69 buy=YES sell=YES rows=3937
[TRAIN][5M] asof=2012-12-24 feats=69 buy=YES sell=YES rows=3975
[TRAIN][5M] asof=2012-12-31 feats=69 buy=YES sell=YES rows=4045
[TRAIN][5M] asof=2013-01-07 feats=69 buy=YES sell=YES rows=4105
[TRAIN][5M] asof=2013-01-14 feats=69 buy=YES sell=YES rows=4199
[TRAIN][5M] asof=2013-01-22 feats=69 buy=YES sell=YES rows=4291
[TRAIN][5M] asof=2013-01-28 feats=69 buy=YES sell=YES rows=4368
[TRAIN][5M] asof=2013-02-04 feats=69 buy=YES sell=YES rows=4435
[TRAIN][5M] asof=2013-02-11 feats=69 buy=YES sell=YES rows=4494
[TRAIN][5M] asof=2013-02-19 feats=69 buy=YES sell=YES rows=4596
[TRAIN][5M] asof=2013-02-25 feats=69 buy=YES sell=YES rows=4687
[TRAIN][5M] asof=2013-03-04 feats=69 buy=YES sell=YES rows=4734
[TRAIN][5M] asof=2013-03-11 feats=69 buy=YES sell=YES rows=4839
[TRAIN][5M] asof=2013-03-18 feats=69 buy=YES sell=YES rows=4869
[TRAIN][5M] asof=2013-03-25 feats=69 buy=YES sell=YES rows=4964
[TRAIN][5M] asof=2013-04-01 feats=69 buy=YES sell=YES rows=5013
[TRAIN][5M] asof=2013-04-08 feats=69 buy=YES sell=YES rows=5144
[TRAIN][5M] asof=2013-04-15 feats=69 buy=YES sell=YES rows=5238
[TRAIN][5M] asof=2013-04-22 feats=69 buy=YES sell=YES rows=5321
[TRAIN][5M] asof=2013-04-29 feats=69 buy=YES sell=YES rows=5428
[TRAIN][5M] asof=2013-05-06 feats=69 buy=YES sell=YES rows=5500
[TRAIN][5M] asof=2013-05-13 feats=69 buy=YES sell=YES rows=5590
[TRAIN][5M] asof=2013-05-20 feats=69 buy=YES sell=YES rows=5665
[TRAIN][5M] asof=2013-05-28 feats=69 buy=YES sell=YES rows=5724
[TRAIN][5M] asof=2013-06-03 feats=69 buy=YES sell=YES rows=5793
[TRAIN][5M] asof=2013-06-10 feats=69 buy=YES sell=YES rows=5855
[TRAIN][5M] asof=2013-06-17 feats=69 buy=YES sell=YES rows=5916
[TRAIN][5M] asof=2013-06-24 feats=69 buy=YES sell=YES rows=5980
[TRAIN][5M] asof=2013-07-01 feats=69 buy=YES sell=YES rows=6040
[TRAIN][5M] asof=2013-07-08 feats=69 buy=YES sell=YES rows=6101
[TRAIN][5M] asof=2013-07-15 feats=69 buy=YES sell=YES rows=6164
[TRAIN][5M] asof=2013-07-22 feats=69 buy=YES sell=YES rows=6243
[TRAIN][5M] asof=2013-07-29 feats=69 buy=YES sell=YES rows=6323
[TRAIN][5M] asof=2013-08-05 feats=69 buy=YES sell=YES rows=6401
[TRAIN][5M] asof=2013-08-12 feats=69 buy=YES sell=YES rows=6487
[TRAIN][5M] asof=2013-08-19 feats=69 buy=YES sell=YES rows=6588
[TRAIN][5M] asof=2013-08-26 feats=69 buy=YES sell=YES rows=6641
[TRAIN][5M] asof=2013-09-03 feats=69 buy=YES sell=YES rows=6742
[TRAIN][5M] asof=2013-09-09 feats=69 buy=YES sell=YES rows=6811
[TRAIN][5M] asof=2013-09-16 feats=69 buy=YES sell=YES rows=6865
[TRAIN][5M] asof=2013-09-23 feats=69 buy=YES sell=YES rows=6919
[TRAIN][5M] asof=2013-09-30 feats=69 buy=YES sell=YES rows=6988
[TRAIN][5M] asof=2013-10-07 feats=69 buy=YES sell=YES rows=7049
[TRAIN][5M] asof=2013-10-14 feats=69 buy=YES sell=YES rows=7130
[TRAIN][5M] asof=2013-10-21 feats=69 buy=YES sell=YES rows=7188
[TRAIN][5M] asof=2013-10-28 feats=69 buy=YES sell=YES rows=7248
[TRAIN][5M] asof=2013-11-04 feats=69 buy=YES sell=YES rows=7294
[TRAIN][5M] asof=2013-11-11 feats=69 buy=YES sell=YES rows=7340
[TRAIN][5M] asof=2013-11-18 feats=69 buy=YES sell=YES rows=7410
[TRAIN][5M] asof=2013-11-25 feats=69 buy=YES sell=YES rows=7468
[TRAIN][5M] asof=2013-12-02 feats=69 buy=YES sell=YES rows=7535
[TRAIN][5M] asof=2013-12-09 feats=69 buy=YES sell=YES rows=7600
[TRAIN][5M] asof=2013-12-16 feats=69 buy=YES sell=YES rows=7656
[TRAIN][5M] asof=2013-12-23 feats=69 buy=YES sell=YES rows=7740
[TRAIN][5M] asof=2013-12-30 feats=69 buy=YES sell=YES rows=7764
[TRAIN][5M] asof=2014-01-06 feats=69 buy=YES sell=YES rows=7817
[TRAIN][5M] asof=2014-01-13 feats=69 buy=YES sell=YES rows=7888
[TRAIN][5M] asof=2014-01-21 feats=69 buy=YES sell=YES rows=7933
[TRAIN][5M] asof=2014-01-27 feats=69 buy=YES sell=YES rows=8008
[TRAIN][5M] asof=2014-02-03 feats=69 buy=YES sell=YES rows=8039
[TRAIN][5M] asof=2014-02-10 feats=69 buy=YES sell=YES rows=8122
[TRAIN][5M] asof=2014-02-18 feats=69 buy=YES sell=YES rows=8208
[TRAIN][5M] asof=2014-02-24 feats=69 buy=YES sell=YES rows=8265
[TRAIN][5M] asof=2014-03-03 feats=69 buy=YES sell=YES rows=8318
[TRAIN][5M] asof=2014-03-10 feats=69 buy=YES sell=YES rows=8370
[TRAIN][5M] asof=2014-03-17 feats=69 buy=YES sell=YES rows=8428
[TRAIN][5M] asof=2014-03-24 feats=69 buy=YES sell=YES rows=8499
[TRAIN][5M] asof=2014-03-31 feats=69 buy=YES sell=YES rows=8587
[TRAIN][5M] asof=2014-04-07 feats=69 buy=YES sell=YES rows=8681
[TRAIN][5M] asof=2014-04-14 feats=69 buy=YES sell=YES rows=8777
[TRAIN][5M] asof=2014-04-21 feats=69 buy=YES sell=YES rows=8875
[TRAIN][5M] asof=2014-04-28 feats=69 buy=YES sell=YES rows=8957
[TRAIN][5M] asof=2014-05-05 feats=69 buy=YES sell=YES rows=9020
[TRAIN][5M] asof=2014-05-12 feats=69 buy=YES sell=YES rows=9126
[TRAIN][5M] asof=2014-05-19 feats=69 buy=YES sell=YES rows=9166
[TRAIN][5M] asof=2014-05-27 feats=69 buy=YES sell=YES rows=9256
[TRAIN][5M] asof=2014-06-02 feats=69 buy=YES sell=YES rows=9287
[TRAIN][5M] asof=2014-06-09 feats=69 buy=YES sell=YES rows=9347
[TRAIN][5M] asof=2014-06-16 feats=69 buy=YES sell=YES rows=9436
[TRAIN][5M] asof=2014-06-23 feats=69 buy=YES sell=YES rows=9518
[TRAIN][5M] asof=2014-06-30 feats=69 buy=YES sell=YES rows=9569
[TRAIN][5M] asof=2014-07-07 feats=69 buy=YES sell=YES rows=9628
[TRAIN][5M] asof=2014-07-14 feats=69 buy=YES sell=YES rows=9720
[TRAIN][5M] asof=2014-07-21 feats=69 buy=YES sell=YES rows=9801
[TRAIN][5M] asof=2014-07-28 feats=69 buy=YES sell=YES rows=9882
[TRAIN][5M] asof=2014-08-04 feats=69 buy=YES sell=YES rows=9949
[TRAIN][5M] asof=2014-08-11 feats=69 buy=YES sell=YES rows=10027
[TRAIN][5M] asof=2014-08-18 feats=69 buy=YES sell=YES rows=10103
[TRAIN][5M] asof=2014-08-25 feats=69 buy=YES sell=YES rows=10152
[TRAIN][5M] asof=2014-09-02 feats=69 buy=YES sell=YES rows=10201
[TRAIN][5M] asof=2014-09-08 feats=69 buy=YES sell=YES rows=10255
[TRAIN][5M] asof=2014-09-15 feats=69 buy=YES sell=YES rows=10304
[TRAIN][5M] asof=2014-09-22 feats=69 buy=YES sell=YES rows=10375
[TRAIN][5M] asof=2014-09-29 feats=69 buy=YES sell=YES rows=10433
[TRAIN][5M] asof=2014-10-06 feats=69 buy=YES sell=YES rows=10545
[TRAIN][5M] asof=2014-10-13 feats=69 buy=YES sell=YES rows=10682
[TRAIN][5M] asof=2014-10-20 feats=69 buy=YES sell=YES rows=10772
[TRAIN][5M] asof=2014-10-27 feats=69 buy=YES sell=YES rows=10885
[TRAIN][5M] asof=2014-11-03 feats=69 buy=YES sell=YES rows=10965
[TRAIN][5M] asof=2014-11-10 feats=69 buy=YES sell=YES rows=11054
[TRAIN][5M] asof=2014-11-17 feats=69 buy=YES sell=YES rows=11129
[TRAIN][5M] asof=2014-11-24 feats=69 buy=YES sell=YES rows=11208
[TRAIN][5M] asof=2014-12-01 feats=69 buy=YES sell=YES rows=11268
[TRAIN][5M] asof=2014-12-08 feats=69 buy=YES sell=YES rows=11331
[TRAIN][5M] asof=2014-12-15 feats=69 buy=YES sell=YES rows=11408
[TRAIN][5M] asof=2014-12-22 feats=69 buy=YES sell=YES rows=11503
[TRAIN][5M] asof=2014-12-29 feats=69 buy=YES sell=YES rows=11565
[TRAIN][5M] asof=2015-01-05 feats=69 buy=YES sell=YES rows=11606
[TRAIN][5M] asof=2015-01-12 feats=69 buy=YES sell=YES rows=11686
[TRAIN][5M] asof=2015-01-20 feats=69 buy=YES sell=YES rows=11768
[TRAIN][5M] asof=2015-01-26 feats=69 buy=YES sell=YES rows=11830
[TRAIN][5M] asof=2015-02-02 feats=69 buy=YES sell=YES rows=11940
[TRAIN][5M] asof=2015-02-09 feats=69 buy=YES sell=YES rows=12026
[TRAIN][5M] asof=2015-02-17 feats=69 buy=YES sell=YES rows=12119
[TRAIN][5M] asof=2015-02-23 feats=69 buy=YES sell=YES rows=12170
[TRAIN][5M] asof=2015-03-02 feats=69 buy=YES sell=YES rows=12251
[TRAIN][5M] asof=2015-03-09 feats=69 buy=YES sell=YES rows=12315
[TRAIN][5M] asof=2015-03-16 feats=69 buy=YES sell=YES rows=12419
[TRAIN][5M] asof=2015-03-23 feats=69 buy=YES sell=YES rows=12510
[TRAIN][5M] asof=2015-03-30 feats=69 buy=YES sell=YES rows=12599
[TRAIN][5M] asof=2015-04-06 feats=69 buy=YES sell=YES rows=12659
[TRAIN][5M] asof=2015-04-13 feats=69 buy=YES sell=YES rows=12707
[TRAIN][5M] asof=2015-04-20 feats=69 buy=YES sell=YES rows=12770
[TRAIN][5M] asof=2015-04-27 feats=69 buy=YES sell=YES rows=12847
[TRAIN][5M] asof=2015-05-04 feats=69 buy=YES sell=YES rows=12940
[TRAIN][5M] asof=2015-05-11 feats=69 buy=YES sell=YES rows=13018
[TRAIN][5M] asof=2015-05-18 feats=69 buy=YES sell=YES rows=13088
[TRAIN][5M] asof=2015-05-26 feats=69 buy=YES sell=YES rows=13166
[TRAIN][5M] asof=2015-06-01 feats=69 buy=YES sell=YES rows=13221
[TRAIN][5M] asof=2015-06-08 feats=69 buy=YES sell=YES rows=13309
[TRAIN][5M] asof=2015-06-15 feats=69 buy=YES sell=YES rows=13370
[TRAIN][5M] asof=2015-06-22 feats=69 buy=YES sell=YES rows=13464
[TRAIN][5M] asof=2015-06-29 feats=69 buy=YES sell=YES rows=13587
[TRAIN][5M] asof=2015-07-06 feats=69 buy=YES sell=YES rows=13683
[TRAIN][5M] asof=2015-07-13 feats=69 buy=YES sell=YES rows=13749
[TRAIN][5M] asof=2015-07-20 feats=69 buy=YES sell=YES rows=13810
[TRAIN][5M] asof=2015-07-27 feats=69 buy=YES sell=YES rows=13916
[TRAIN][5M] asof=2015-08-03 feats=69 buy=YES sell=YES rows=14001
[TRAIN][5M] asof=2015-08-10 feats=69 buy=YES sell=YES rows=14088
[TRAIN][5M] asof=2015-08-17 feats=69 buy=YES sell=YES rows=14175
[TRAIN][5M] asof=2015-08-24 feats=69 buy=YES sell=YES rows=14295
[TRAIN][5M] asof=2015-08-31 feats=69 buy=YES sell=YES rows=14370
[TRAIN][5M] asof=2015-09-08 feats=69 buy=YES sell=YES rows=14458
[TRAIN][5M] asof=2015-09-14 feats=69 buy=YES sell=YES rows=14535
[TRAIN][5M] asof=2015-09-21 feats=69 buy=YES sell=YES rows=14655
[TRAIN][5M] asof=2015-09-28 feats=69 buy=YES sell=YES rows=14753
[TRAIN][5M] asof=2015-10-05 feats=69 buy=YES sell=YES rows=14886
[TRAIN][5M] asof=2015-10-12 feats=69 buy=YES sell=YES rows=14970
[TRAIN][5M] asof=2015-10-19 feats=69 buy=YES sell=YES rows=15002
[TRAIN][5M] asof=2015-10-26 feats=69 buy=YES sell=YES rows=15079
[TRAIN][5M] asof=2015-11-02 feats=69 buy=YES sell=YES rows=15183
[TRAIN][5M] asof=2015-11-09 feats=69 buy=YES sell=YES rows=15248
[TRAIN][5M] asof=2015-11-16 feats=69 buy=YES sell=YES rows=15321
[TRAIN][5M] asof=2015-11-23 feats=69 buy=YES sell=YES rows=15390
[TRAIN][5M] asof=2015-11-30 feats=69 buy=YES sell=YES rows=15403
[TRAIN][5M] asof=2015-12-07 feats=69 buy=YES sell=YES rows=15523
[TRAIN][5M] asof=2015-12-14 feats=69 buy=YES sell=YES rows=15629
[TRAIN][5M] asof=2015-12-21 feats=69 buy=YES sell=YES rows=15703
[TRAIN][5M] asof=2015-12-28 feats=69 buy=YES sell=YES rows=15759
[TRAIN][5M] asof=2016-01-04 feats=69 buy=YES sell=YES rows=15820
[TRAIN][5M] asof=2016-01-11 feats=69 buy=YES sell=YES rows=15913
[TRAIN][5M] asof=2016-01-19 feats=69 buy=YES sell=YES rows=16018
[TRAIN][5M] asof=2016-01-25 feats=69 buy=YES sell=YES rows=16071
[TRAIN][5M] asof=2016-02-01 feats=69 buy=YES sell=YES rows=16180
[TRAIN][5M] asof=2016-02-08 feats=69 buy=YES sell=YES rows=16296
[TRAIN][5M] asof=2016-02-16 feats=69 buy=YES sell=YES rows=16434
[TRAIN][5M] asof=2016-02-22 feats=69 buy=YES sell=YES rows=16522
[TRAIN][5M] asof=2016-02-29 feats=69 buy=YES sell=YES rows=16598
[TRAIN][5M] asof=2016-03-07 feats=69 buy=YES sell=YES rows=16713
[TRAIN][5M] asof=2016-03-14 feats=69 buy=YES sell=YES rows=16802
[TRAIN][5M] asof=2016-03-21 feats=69 buy=YES sell=YES rows=16895
[TRAIN][5M] asof=2016-03-28 feats=69 buy=YES sell=YES rows=16950
[TRAIN][5M] asof=2016-04-04 feats=69 buy=YES sell=YES rows=17065
[TRAIN][5M] asof=2016-04-11 feats=69 buy=YES sell=YES rows=17203
[TRAIN][5M] asof=2016-04-18 feats=69 buy=YES sell=YES rows=17303
[TRAIN][5M] asof=2016-04-25 feats=69 buy=YES sell=YES rows=17398
[TRAIN][5M] asof=2016-05-02 feats=69 buy=YES sell=YES rows=17501
[TRAIN][5M] asof=2016-05-09 feats=69 buy=YES sell=YES rows=17585
[TRAIN][5M] asof=2016-05-16 feats=69 buy=YES sell=YES rows=17654
[TRAIN][5M] asof=2016-05-23 feats=69 buy=YES sell=YES rows=17768
[TRAIN][5M] asof=2016-05-31 feats=69 buy=YES sell=YES rows=17848
[TRAIN][5M] asof=2016-06-06 feats=69 buy=YES sell=YES rows=17894
[TRAIN][5M] asof=2016-06-13 feats=69 buy=YES sell=YES rows=17984
[TRAIN][5M] asof=2016-06-20 feats=69 buy=YES sell=YES rows=18042
[TRAIN][5M] asof=2016-06-27 feats=69 buy=YES sell=YES rows=18125
[TRAIN][5M] asof=2016-07-05 feats=69 buy=YES sell=YES rows=18227
[TRAIN][5M] asof=2016-07-11 feats=69 buy=YES sell=YES rows=18289
[TRAIN][5M] asof=2016-07-18 feats=69 buy=YES sell=YES rows=18334
[TRAIN][5M] asof=2016-07-25 feats=69 buy=YES sell=YES rows=18425
[TRAIN][5M] asof=2016-08-01 feats=69 buy=YES sell=YES rows=18502
[TRAIN][5M] asof=2016-08-08 feats=69 buy=YES sell=YES rows=18570
[TRAIN][5M] asof=2016-08-15 feats=69 buy=YES sell=YES rows=18660
[TRAIN][5M] asof=2016-08-22 feats=69 buy=YES sell=YES rows=18727
[TRAIN][5M] asof=2016-08-29 feats=69 buy=YES sell=YES rows=18810
[TRAIN][5M] asof=2016-09-06 feats=69 buy=YES sell=YES rows=18885
[TRAIN][5M] asof=2016-09-12 feats=69 buy=YES sell=YES rows=18964
[TRAIN][5M] asof=2016-09-19 feats=69 buy=YES sell=YES rows=19078
[TRAIN][5M] asof=2016-09-26 feats=69 buy=YES sell=YES rows=19162
[TRAIN][5M] asof=2016-10-03 feats=69 buy=YES sell=YES rows=19258
[TRAIN][5M] asof=2016-10-10 feats=69 buy=YES sell=YES rows=19327
[TRAIN][5M] asof=2016-10-17 feats=69 buy=YES sell=YES rows=19414
[TRAIN][5M] asof=2016-10-24 feats=69 buy=YES sell=YES rows=19449
[TRAIN][5M] asof=2016-10-31 feats=69 buy=YES sell=YES rows=19543
[TRAIN][5M] asof=2016-11-07 feats=69 buy=YES sell=YES rows=19650
[TRAIN][5M] asof=2016-11-14 feats=69 buy=YES sell=YES rows=19730
[TRAIN][5M] asof=2016-11-21 feats=69 buy=YES sell=YES rows=19808
[TRAIN][5M] asof=2016-11-28 feats=69 buy=YES sell=YES rows=19839
[TRAIN][5M] asof=2016-12-05 feats=69 buy=YES sell=YES rows=19918
[TRAIN][5M] asof=2016-12-12 feats=69 buy=YES sell=YES rows=20005
[TRAIN][5M] asof=2016-12-19 feats=69 buy=YES sell=YES rows=20078
[TRAIN][5M] asof=2016-12-27 feats=69 buy=YES sell=YES rows=20138
[TRAIN][5M] asof=2017-01-03 feats=69 buy=YES sell=YES rows=20210
[TRAIN][5M] asof=2017-01-09 feats=69 buy=YES sell=YES rows=20260
[TRAIN][5M] asof=2017-01-17 feats=69 buy=YES sell=YES rows=20307
[TRAIN][5M] asof=2017-01-23 feats=69 buy=YES sell=YES rows=20379
[TRAIN][5M] asof=2017-01-30 feats=69 buy=YES sell=YES rows=20464

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
1978,2019-12-23,0.231515,0.255,0.275,FORCE_BUY,-0.002679,-0.002679,-0.002679,-0.002679,FORCE_BUY,1.094626e+13,18.6167,-0.5,-0.5
1979,2019-12-24,0.194711,0.255,0.275,FORCE_BUY,0.003075,0.003075,0.003075,0.003075,FORCE_BUY,1.097992e+13,18.7241,-0.5,-0.5
1980,2019-12-26,0.202051,0.255,0.275,FORCE_BUY,0.003874,0.003874,0.003874,0.003874,FORCE_BUY,1.102246e+13,18.8400,-0.5,-0.5
1981,2019-12-27,0.222002,0.255,0.275,FORCE_BUY,-0.022254,-0.002908,0.006008,-0.022254,FORCE_SELL,1.108869e+13,18.4533,-0.5,-0.5
1982,2019-12-30,0.231132,0.255,0.275,FORCE_BUY,-0.015162,0.026836,0.005415,-0.015162,FREE,1.138627e+13,18.1867,-0.5,-0.5

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
1978,2019-12-23,4.715208e+06,0.0,1,-0.5,-0.5,0.231515,FORCE_BUY,0.255,0.275
1979,2019-12-24,4.742410e+06,0.0,1,-0.5,-0.5,0.194711,FORCE_BUY,0.255,0.275
1980,2019-12-26,4.771765e+06,0.0,1,-0.5,-0.5,0.202051,FORCE_BUY,0.255,0.275
1981,2019-12-27,4.673823e+06,0.0,1,-0.5,-0.5,0.222002,FORCE_BUY,0.255,0.275
1982,2019-12-30,4.606299e+06,0.0,1,-0.5,-0.5,0.231132,FORCE_BUY,0.255,0.275

In [ ]:
resume_res = run_adaptive_reward_from_snapshot(
    snapshot_path=str(snapshot_path),
    end_time="2026-12-31",
    sim_start="2020-01-01",
    initial_capital=100000.0,
    fee_pct=0.0,
    output_dir="output_adaptive_reward_resumed_fresh_TQQQ_252days_at_2020",
    save_snapshot_path=None,
    autosave_year_start_checkpoints=True,
    verbose=True,
)

print("continued snapshot:", resume_res["continued_snapshot_path"])
print("year-start resume checkpoints:")
for p in resume_res["year_start_checkpoint_paths"]:
    print(" ", p)

display(resume_res["daily_reward_df"].tail())
display(resume_res["daily_log_df"].tail())
display(resume_res["trades_df"].head())

[TRAIN][DAILY-PROB] n=2310 pos=525 (22.73%)
[TRAIN][DAILY-PROB] n=2335 pos=535 (22.91%)
[TRAIN][DAILY-PROB] n=2360 pos=542 (22.97%)
[TRAIN][DAILY-PROB] n=2385 pos=545 (22.85%)
[TRAIN][DAILY-PROB] n=2410 pos=548 (22.74%)
[TRAIN][DAILY-PROB] n=2435 pos=550 (22.59%)
[TRAIN][DAILY-PROB] n=2460 pos=551 (22.40%)
[TRAIN][DAILY-PROB] n=2485 pos=555 (22.33%)
[TRAIN][DAILY-PROB] n=2510 pos=565 (22.51%)
[TRAIN][DAILY-PROB] n=2535 pos=569 (22.45%)
[TRAIN][DAILY-PROB] n=2560 pos=574 (22.42%)
[TRAIN][DAILY-PROB] n=2585 pos=582 (22.51%)
[TRAIN][DAILY-PROB] n=2610 pos=587 (22.49%)
[TRAIN][DAILY-PROB] n=2635 pos=597 (22.66%)
[TRAIN][DAILY-PROB] n=2660 pos=602 (22.63%)
[TRAIN][DAILY-PROB] n=2685 pos=610 (22.72%)
[TRAIN][DAILY-PROB] n=2710 pos=620 (22.88%)
[TRAIN][DAILY-PROB] n=2735 pos=629 (23.00%)
[TRAIN][DAILY-PROB] n=2760 pos=630 (22.83%)
[TRAIN][DAILY-PROB] n=2785 pos=635 (22.80%)
[TRAIN][DAILY-PROB] n=2810 pos=643 (22.88%)
[TRAIN][DAILY-PROB] n=2835 pos=648 (22.86%)
[TRAIN][DAILY-PROB] n=2860 pos=657 (22.97%)
[TRAIN][DAILY-PROB] n=2885 pos=661 (22.91%)
[TRAIN][DAILY-PROB] n=2910 pos=666 (22.89%)
[TRAIN][DAILY-PROB] n=2935 pos=674 (22.96%)
[TRAIN][DAILY-PROB] n=2960 pos=681 (23.01%)
[TRAIN][DAILY-PROB] n=2985 pos=683 (22.88%)
[TRAIN][DAILY-PROB] n=3010 pos=692 (22.99%)
[TRAIN][DAILY-PROB] n=3035 pos=696 (22.93%)
[TRAIN][DAILY-PROB] n=3060 pos=704 (23.01%)
[TRAIN][DAILY-PROB] n=3085 pos=711 (23.05%)
[TRAIN][DAILY-PROB] n=3110 pos=716 (23.02%)
[TRAIN][DAILY-PROB] n=3135 pos=722 (23.03%)
[TRAIN][DAILY-PROB] n=3160 pos=724 (22.91%)
[TRAIN][DAILY-PROB] n=3185 pos=735 (23.08%)
[TRAIN][DAILY-PROB] n=3210 pos=743 (23.15%)
[TRAIN][DAILY-PROB] n=3235 pos=750 (23.18%)
[TRAIN][DAILY-PROB] n=3260 pos=761 (23.34%)
[TRAIN][DAILY-PROB] n=3285 pos=767 (23.35%)
[TRAIN][DAILY-PROB] n=3310 pos=771 (23.29%)
[TRAIN][DAILY-PROB] n=3335 pos=774 (23.21%)
[TRAIN][DAILY-PROB] n=3360 pos=779 (23.18%)
[TRAIN][DAILY-PROB] n=3385 pos=787 (23.25%)
[TRAIN][DAILY-PROB] n=3410 pos=788 (23.11%)
[TRAIN][DAILY-PROB] n=3435 pos=801 (23.32%)
[TRAIN][DAILY-PROB] n=3460 pos=809 (23.38%)
[TRAIN][DAILY-PROB] n=3485 pos=819 (23.50%)
[TRAIN][DAILY-PROB] n=3510 pos=828 (23.59%)
[TRAIN][DAILY-PROB] n=3535 pos=832 (23.54%)
[TRAIN][DAILY-PROB] n=3560 pos=839 (23.57%)
[TRAIN][DAILY-PROB] n=3585 pos=846 (23.60%)
[TRAIN][DAILY-PROB] n=3610 pos=848 (23.49%)
[TRAIN][DAILY-PROB] n=3635 pos=858 (23.60%)
[TRAIN][DAILY-PROB] n=3660 pos=868 (23.72%)
[TRAIN][DAILY-PROB] n=3685 pos=869 (23.58%)
[TRAIN][DAILY-PROB] n=3710 pos=874 (23.56%)
[TRAIN][DAILY-PROB] n=3735 pos=875 (23.43%)
[TRAIN][DAILY-PROB] n=3760 pos=882 (23.46%)
[TRAIN][DAILY-PROB] n=3785 pos=890 (23.51%)
[TRAIN][DAILY-PROB] n=3810 pos=891 (23.39%)
[TRAIN][DAILY-PROB] n=3835 pos=896 (23.36%)
[TRAIN][DAILY-PROB] n=3860 pos=903 (23.39%)
[TRAIN][DAILY-PROB] n=3885 pos=903 (23.24%)
[TRAIN][5M] asof=2019-12-31 feats=69 buy=YES sell=YES rows=36303
[TRAIN][5M] asof=2020-01-06 feats=69 buy=YES sell=YES rows=36383
[TRAIN][5M] asof=2020-01-13 feats=69 buy=YES sell=YES rows=36513
[TRAIN][5M] asof=2020-01-21 feats=69 buy=YES sell=YES rows=36657
[TRAIN][5M] asof=2020-01-27 feats=69 buy=YES sell=YES rows=36772
[TRAIN][5M] asof=2020-02-03 feats=69 buy=YES sell=YES rows=36930
[TRAIN][5M] asof=2020-02-10 feats=69 buy=YES sell=YES rows=37074
[TRAIN][5M] asof=2020-02-18 feats=69 buy=YES sell=YES rows=37225
[TRAIN][5M] asof=2020-02-24 feats=69 buy=YES sell=YES rows=37344
[TRAIN][5M] asof=2020-03-02 feats=69 buy=YES sell=YES rows=37535
[TRAIN][5M] asof=2020-03-09 feats=69 buy=YES sell=YES rows=37699
[TRAIN][5M] asof=2020-03-16 feats=69 buy=YES sell=YES rows=37870
[TRAIN][5M] asof=2020-03-23 feats=69 buy=YES sell=YES rows=38066
[TRAIN][5M] asof=2020-03-30 feats=69 buy=YES sell=YES rows=38240
[TRAIN][5M] asof=2020-04-06 feats=69 buy=YES sell=YES rows=38404
[TRAIN][5M] asof=2020-04-13 feats=69 buy=YES sell=YES rows=38557
[TRAIN][5M] asof=2020-04-20 feats=69 buy=YES sell=YES rows=38686
[TRAIN][5M] asof=2020-04-27 feats=69 buy=YES sell=YES rows=38878
[TRAIN][5M] asof=2020-05-04 feats=69 buy=YES sell=YES rows=39048
[TRAIN][5M] asof=2020-05-11 feats=69 buy=YES sell=YES rows=39203
[TRAIN][5M] asof=2020-05-18 feats=69 buy=YES sell=YES rows=39392
[TRAIN][5M] asof=2020-05-26 feats=69 buy=YES sell=YES rows=39507
[TRAIN][5M] asof=2020-06-01 feats=69 buy=YES sell=YES rows=39625
[TRAIN][5M] asof=2020-06-08 feats=69 buy=YES sell=YES rows=39770
[TRAIN][5M] asof=2020-06-15 feats=69 buy=YES sell=YES rows=39934
[TRAIN][5M] asof=2020-06-22 feats=69 buy=YES sell=YES rows=40085
[TRAIN][5M] asof=2020-06-29 feats=69 buy=YES sell=YES rows=40236
[TRAIN][5M] asof=2020-07-06 feats=69 buy=YES sell=YES rows=40333
[TRAIN][5M] asof=2020-07-13 feats=69 buy=YES sell=YES rows=40492
[TRAIN][5M] asof=2020-07-20 feats=69 buy=YES sell=YES rows=40571
[TRAIN][5M] asof=2020-07-27 feats=69 buy=YES sell=YES rows=40719
[TRAIN][5M] asof=2020-08-03 feats=69 buy=YES sell=YES rows=40832
[TRAIN][5M] asof=2020-08-10 feats=69 buy=YES sell=YES rows=40933
[TRAIN][5M] asof=2020-08-17 feats=69 buy=YES sell=YES rows=41078
[TRAIN][5M] asof=2020-08-24 feats=69 buy=YES sell=YES rows=41181
[TRAIN][5M] asof=2020-08-31 feats=69 buy=YES sell=YES rows=41272
[TRAIN][5M] asof=2020-09-08 feats=69 buy=YES sell=YES rows=41428
[TRAIN][5M] asof=2020-09-14 feats=69 buy=YES sell=YES rows=41529
[TRAIN][5M] asof=2020-09-21 feats=69 buy=YES sell=YES rows=41689
[TRAIN][5M] asof=2020-09-28 feats=69 buy=YES sell=YES rows=41876
[TRAIN][5M] asof=2020-10-05 feats=69 buy=YES sell=YES rows=42013
[TRAIN][5M] asof=2020-10-12 feats=69 buy=YES sell=YES rows=42154
[TRAIN][5M] asof=2020-10-19 feats=69 buy=YES sell=YES rows=42300
[TRAIN][5M] asof=2020-10-26 feats=69 buy=YES sell=YES rows=42383
[TRAIN][5M] asof=2020-11-02 feats=69 buy=YES sell=YES rows=42555
[TRAIN][5M] asof=2020-11-09 feats=69 buy=YES sell=YES rows=42691
[TRAIN][5M] asof=2020-11-16 feats=69 buy=YES sell=YES rows=42807
[TRAIN][5M] asof=2020-11-23 feats=69 buy=YES sell=YES rows=42941
[TRAIN][5M] asof=2020-11-30 feats=69 buy=YES sell=YES rows=43030
[TRAIN][5M] asof=2020-12-07 feats=69 buy=YES sell=YES rows=43133
[TRAIN][5M] asof=2020-12-14 feats=69 buy=YES sell=YES rows=43270
[TRAIN][5M] asof=2020-12-21 feats=69 buy=YES sell=YES rows=43355
[TRAIN][5M] asof=2020-12-28 feats=69 buy=YES sell=YES rows=43441
[TRAIN][5M] asof=2021-01-04 feats=69 buy=YES sell=YES rows=43533
[TRAIN][5M] asof=2021-01-11 feats=69 buy=YES sell=YES rows=43607
[TRAIN][5M] asof=2021-01-19 feats=69 buy=YES sell=YES rows=43716
[TRAIN][5M] asof=2021-01-25 feats=69 buy=YES sell=YES rows=43820
[TRAIN][5M] asof=2021-02-01 feats=69 buy=YES sell=YES rows=43981
[TRAIN][5M] asof=2021-02-08 feats=69 buy=YES sell=YES rows=44097
[TRAIN][5M] asof=2021-02-16 feats=69 buy=YES sell=YES rows=44225
[TRAIN][5M] asof=2021-02-22 feats=69 buy=YES sell=YES rows=44329
[TRAIN][5M] asof=2021-03-01 feats=69 buy=YES sell=YES rows=44531
[TRAIN][5M] asof=2021-03-08 feats=69 buy=YES sell=YES rows=44766
[TRAIN][5M] asof=2021-03-15 feats=69 buy=YES sell=YES rows=44871
[TRAIN][5M] asof=2021-03-22 feats=69 buy=YES sell=YES rows=45068
[TRAIN][5M] asof=2021-03-29 feats=69 buy=YES sell=YES rows=45279
[TRAIN][5M] asof=2021-04-05 feats=69 buy=YES sell=YES rows=45448
[TRAIN][5M] asof=2021-04-12 feats=69 buy=YES sell=YES rows=45632
[TRAIN][5M] asof=2021-04-19 feats=69 buy=YES sell=YES rows=45801
[TRAIN][5M] asof=2021-04-26 feats=69 buy=YES sell=YES rows=45977
[TRAIN][5M] asof=2021-05-03 feats=69 buy=YES sell=YES rows=46119
[TRAIN][5M] asof=2021-05-10 feats=69 buy=YES sell=YES rows=46319
[TRAIN][5M] asof=2021-05-17 feats=69 buy=YES sell=YES rows=46559
[TRAIN][5M] asof=2021-05-24 feats=69 buy=YES sell=YES rows=46737
[TRAIN][5M] asof=2021-06-01 feats=69 buy=YES sell=YES rows=46891
[TRAIN][5M] asof=2021-06-07 feats=69 buy=YES sell=YES rows=47015
[TRAIN][5M] asof=2021-06-14 feats=69 buy=YES sell=YES rows=47204
[TRAIN][5M] asof=2021-06-21 feats=69 buy=YES sell=YES rows=47427
[TRAIN][5M] asof=2021-06-28 feats=69 buy=YES sell=YES rows=47591
[TRAIN][5M] asof=2021-07-06 feats=69 buy=YES sell=YES rows=47763
[TRAIN][5M] asof=2021-07-12 feats=69 buy=YES sell=YES rows=47923
[TRAIN][5M] asof=2021-07-19 feats=69 buy=YES sell=YES rows=48102
[TRAIN][5M] asof=2021-07-26 feats=69 buy=YES sell=YES rows=48287
[TRAIN][5M] asof=2021-08-02 feats=69 buy=YES sell=YES rows=48497
[TRAIN][5M] asof=2021-08-09 feats=69 buy=YES sell=YES rows=48646
[TRAIN][5M] asof=2021-08-16 feats=69 buy=YES sell=YES rows=48808
[TRAIN][5M] asof=2021-08-23 feats=69 buy=YES sell=YES rows=49018
[TRAIN][5M] asof=2021-08-30 feats=69 buy=YES sell=YES rows=49183
[TRAIN][5M] asof=2021-09-07 feats=69 buy=YES sell=YES rows=49392
[TRAIN][5M] asof=2021-09-13 feats=69 buy=YES sell=YES rows=49574
[TRAIN][5M] asof=2021-09-20 feats=69 buy=YES sell=YES rows=49756
[TRAIN][5M] asof=2021-09-27 feats=69 buy=YES sell=YES rows=49968
[TRAIN][5M] asof=2021-10-04 feats=69 buy=YES sell=YES rows=50110
[TRAIN][5M] asof=2021-10-11 feats=69 buy=YES sell=YES rows=50323
[TRAIN][5M] asof=2021-10-18 feats=69 buy=YES sell=YES rows=50487
[TRAIN][5M] asof=2021-10-25 feats=69 buy=YES sell=YES rows=50677
[TRAIN][5M] asof=2021-11-01 feats=69 buy=YES sell=YES rows=50823
[TRAIN][5M] asof=2021-11-08 feats=69 buy=YES sell=YES rows=50992
[TRAIN][5M] asof=2021-11-15 feats=69 buy=YES sell=YES rows=51168
[TRAIN][5M] asof=2021-11-22 feats=69 buy=YES sell=YES rows=51306
[TRAIN][5M] asof=2021-11-29 feats=69 buy=YES sell=YES rows=51421
[TRAIN][5M] asof=2021-12-06 feats=69 buy=YES sell=YES rows=51603
[TRAIN][5M] asof=2021-12-13 feats=69 buy=YES sell=YES rows=51760
[TRAIN][5M] asof=2021-12-20 feats=69 buy=YES sell=YES rows=51902
[TRAIN][5M] asof=2021-12-27 feats=69 buy=YES sell=YES rows=52054
[TRAIN][5M] asof=2022-01-03 feats=69 buy=YES sell=YES rows=52185
[TRAIN][5M] asof=2022-01-10 feats=69 buy=YES sell=YES rows=52365
[TRAIN][5M] asof=2022-01-18 feats=69 buy=YES sell=YES rows=52573
[TRAIN][5M] asof=2022-01-24 feats=69 buy=YES sell=YES rows=52712
[TRAIN][5M] asof=2022-01-31 feats=69 buy=YES sell=YES rows=52941
[TRAIN][5M] asof=2022-02-07 feats=69 buy=YES sell=YES rows=53134
[TRAIN][5M] asof=2022-02-14 feats=69 buy=YES sell=YES rows=53359
[TRAIN][5M] asof=2022-02-22 feats=69 buy=YES sell=YES rows=53537
[TRAIN][5M] asof=2022-02-28 feats=69 buy=YES sell=YES rows=53754
[TRAIN][5M] asof=2022-03-07 feats=69 buy=YES sell=YES rows=53973
[TRAIN][5M] asof=2022-03-14 feats=69 buy=YES sell=YES rows=54158
[TRAIN][5M] asof=2022-03-21 feats=69 buy=YES sell=YES rows=54381
[TRAIN][5M] asof=2022-03-28 feats=69 buy=YES sell=YES rows=54541
[TRAIN][5M] asof=2022-04-04 feats=69 buy=YES sell=YES rows=54761
[TRAIN][5M] asof=2022-04-11 feats=69 buy=YES sell=YES rows=54959
[TRAIN][5M] asof=2022-04-18 feats=69 buy=YES sell=YES rows=55134
[TRAIN][5M] asof=2022-04-25 feats=69 buy=YES sell=YES rows=55339
[TRAIN][5M] asof=2022-05-02 feats=69 buy=YES sell=YES rows=55511
[TRAIN][5M] asof=2022-05-09 feats=69 buy=YES sell=YES rows=55705
[TRAIN][5M] asof=2022-05-16 feats=69 buy=YES sell=YES rows=55878
[TRAIN][5M] asof=2022-05-23 feats=69 buy=YES sell=YES rows=56108
[TRAIN][5M] asof=2022-05-31 feats=69 buy=YES sell=YES rows=56291
[TRAIN][5M] asof=2022-06-06 feats=69 buy=YES sell=YES rows=56431
[TRAIN][5M] asof=2022-06-13 feats=69 buy=YES sell=YES rows=56660
[TRAIN][5M] asof=2022-06-21 feats=69 buy=YES sell=YES rows=56822
[TRAIN][5M] asof=2022-06-27 feats=69 buy=YES sell=YES rows=56929
[TRAIN][5M] asof=2022-07-05 feats=69 buy=YES sell=YES rows=57110
[TRAIN][5M] asof=2022-07-11 feats=69 buy=YES sell=YES rows=57246
[TRAIN][5M] asof=2022-07-18 feats=69 buy=YES sell=YES rows=57386
[TRAIN][5M] asof=2022-07-25 feats=69 buy=YES sell=YES rows=57660
[TRAIN][5M] asof=2022-08-01 feats=69 buy=YES sell=YES rows=57851
[TRAIN][5M] asof=2022-08-08 feats=69 buy=YES sell=YES rows=58077
[TRAIN][5M] asof=2022-08-15 feats=69 buy=YES sell=YES rows=58217
[TRAIN][5M] asof=2022-08-22 feats=69 buy=YES sell=YES rows=58431
[TRAIN][5M] asof=2022-08-29 feats=69 buy=YES sell=YES rows=58622
[TRAIN][5M] asof=2022-09-06 feats=69 buy=YES sell=YES rows=58821
[TRAIN][5M] asof=2022-09-12 feats=69 buy=YES sell=YES rows=59010
[TRAIN][5M] asof=2022-09-19 feats=69 buy=YES sell=YES rows=59192
[TRAIN][5M] asof=2022-09-26 feats=69 buy=YES sell=YES rows=59421
[TRAIN][5M] asof=2022-10-03 feats=69 buy=YES sell=YES rows=59573
[TRAIN][5M] asof=2022-10-10 feats=69 buy=YES sell=YES rows=59793
[TRAIN][5M] asof=2022-10-17 feats=69 buy=YES sell=YES rows=60032
[TRAIN][5M] asof=2022-10-24 feats=69 buy=YES sell=YES rows=60243
[TRAIN][5M] asof=2022-10-31 feats=69 buy=YES sell=YES rows=60428
[TRAIN][5M] asof=2022-11-07 feats=69 buy=YES sell=YES rows=60603
[TRAIN][5M] asof=2022-11-14 feats=69 buy=YES sell=YES rows=60819
[TRAIN][5M] asof=2022-11-21 feats=69 buy=YES sell=YES rows=60971
[TRAIN][5M] asof=2022-11-28 feats=69 buy=YES sell=YES rows=61076
[TRAIN][5M] asof=2022-12-05 feats=69 buy=YES sell=YES rows=61187
[TRAIN][5M] asof=2022-12-12 feats=69 buy=YES sell=YES rows=61321
[TRAIN][5M] asof=2022-12-19 feats=69 buy=YES sell=YES rows=61462
[TRAIN][5M] asof=2022-12-27 feats=69 buy=YES sell=YES rows=61638
[TRAIN][5M] asof=2023-01-03 feats=69 buy=YES sell=YES rows=61786
[TRAIN][5M] asof=2023-01-09 feats=69 buy=YES sell=YES rows=61911
[TRAIN][5M] asof=2023-01-17 feats=69 buy=YES sell=YES rows=62100
[TRAIN][5M] asof=2023-01-23 feats=69 buy=YES sell=YES rows=62268
[TRAIN][5M] asof=2023-01-30 feats=69 buy=YES sell=YES rows=62469
[TRAIN][5M] asof=2023-02-06 feats=69 buy=YES sell=YES rows=62657
[TRAIN][5M] asof=2023-02-13 feats=69 buy=YES sell=YES rows=62866
[TRAIN][5M] asof=2023-02-21 feats=69 buy=YES sell=YES rows=63022
[TRAIN][5M] asof=2023-02-27 feats=69 buy=YES sell=YES rows=63140
[TRAIN][5M] asof=2023-03-06 feats=69 buy=YES sell=YES rows=63358
[TRAIN][5M] asof=2023-03-13 feats=69 buy=YES sell=YES rows=63537
[TRAIN][5M] asof=2023-03-20 feats=69 buy=YES sell=YES rows=63768
[TRAIN][5M] asof=2023-03-27 feats=69 buy=YES sell=YES rows=63922
[TRAIN][5M] asof=2023-04-03 feats=69 buy=YES sell=YES rows=64098
[TRAIN][5M] asof=2023-04-10 feats=69 buy=YES sell=YES rows=64266
[TRAIN][5M] asof=2023-04-17 feats=69 buy=YES sell=YES rows=64511
[TRAIN][5M] asof=2023-04-24 feats=69 buy=YES sell=YES rows=64731
[TRAIN][5M] asof=2023-05-01 feats=69 buy=YES sell=YES rows=64914
[TRAIN][5M] asof=2023-05-08 feats=69 buy=YES sell=YES rows=65136
[TRAIN][5M] asof=2023-05-15 feats=69 buy=YES sell=YES rows=65326
[TRAIN][5M] asof=2023-05-22 feats=69 buy=YES sell=YES rows=65548
[TRAIN][5M] asof=2023-05-30 feats=69 buy=YES sell=YES rows=65800
[TRAIN][5M] asof=2023-06-05 feats=69 buy=YES sell=YES rows=65972
[TRAIN][5M] asof=2023-06-12 feats=69 buy=YES sell=YES rows=66161
[TRAIN][5M] asof=2023-06-20 feats=69 buy=YES sell=YES rows=66423
[TRAIN][5M] asof=2023-06-26 feats=69 buy=YES sell=YES rows=66600
[TRAIN][5M] asof=2023-07-03 feats=69 buy=YES sell=YES rows=66768
[TRAIN][5M] asof=2023-07-10 feats=69 buy=YES sell=YES rows=66891
[TRAIN][5M] asof=2023-07-17 feats=69 buy=YES sell=YES rows=67146
[TRAIN][5M] asof=2023-07-24 feats=69 buy=YES sell=YES rows=67330
[TRAIN][5M] asof=2023-07-31 feats=69 buy=YES sell=YES rows=67541
[TRAIN][5M] asof=2023-08-07 feats=69 buy=YES sell=YES rows=67781
[TRAIN][5M] asof=2023-08-14 feats=69 buy=YES sell=YES rows=67967
[TRAIN][5M] asof=2023-08-21 feats=69 buy=YES sell=YES rows=68178
[TRAIN][5M] asof=2023-08-28 feats=69 buy=YES sell=YES rows=68389
[TRAIN][5M] asof=2023-09-05 feats=69 buy=YES sell=YES rows=68520
[TRAIN][5M] asof=2023-09-11 feats=69 buy=YES sell=YES rows=68704
[TRAIN][5M] asof=2023-09-18 feats=69 buy=YES sell=YES rows=68968
[TRAIN][5M] asof=2023-09-25 feats=69 buy=YES sell=YES rows=69172
[TRAIN][5M] asof=2023-10-02 feats=69 buy=YES sell=YES rows=69342
[TRAIN][5M] asof=2023-10-09 feats=69 buy=YES sell=YES rows=69532
[TRAIN][5M] asof=2023-10-16 feats=69 buy=YES sell=YES rows=69722
[TRAIN][5M] asof=2023-10-23 feats=69 buy=YES sell=YES rows=69899
[TRAIN][5M] asof=2023-10-30 feats=69 buy=YES sell=YES rows=70095
[TRAIN][5M] asof=2023-11-06 feats=69 buy=YES sell=YES rows=70283
[TRAIN][5M] asof=2023-11-13 feats=69 buy=YES sell=YES rows=70543
[TRAIN][5M] asof=2023-11-20 feats=69 buy=YES sell=YES rows=70794
[TRAIN][5M] asof=2023-11-27 feats=69 buy=YES sell=YES rows=70944
[TRAIN][5M] asof=2023-12-04 feats=69 buy=YES sell=YES rows=71182
[TRAIN][5M] asof=2023-12-11 feats=69 buy=YES sell=YES rows=71400
[TRAIN][5M] asof=2023-12-18 feats=69 buy=YES sell=YES rows=71654
[TRAIN][5M] asof=2023-12-26 feats=69 buy=YES sell=YES rows=71808
[TRAIN][5M] asof=2024-01-02 feats=69 buy=YES sell=YES rows=71993
[TRAIN][5M] asof=2024-01-08 feats=69 buy=YES sell=YES rows=72159
[TRAIN][5M] asof=2024-01-16 feats=69 buy=YES sell=YES rows=72369
[TRAIN][5M] asof=2024-01-22 feats=69 buy=YES sell=YES rows=72497
[TRAIN][5M] asof=2024-01-29 feats=69 buy=YES sell=YES rows=72731
[TRAIN][5M] asof=2024-02-05 feats=69 buy=YES sell=YES rows=72846
[TRAIN][5M] asof=2024-02-12 feats=69 buy=YES sell=YES rows=73107
[TRAIN][5M] asof=2024-02-20 feats=69 buy=YES sell=YES rows=73299
[TRAIN][5M] asof=2024-02-26 feats=69 buy=YES sell=YES rows=73426
[TRAIN][5M] asof=2024-03-04 feats=69 buy=YES sell=YES rows=73645
[TRAIN][5M] asof=2024-03-11 feats=69 buy=YES sell=YES rows=73855
[TRAIN][5M] asof=2024-03-18 feats=69 buy=YES sell=YES rows=74035
[TRAIN][5M] asof=2024-03-25 feats=69 buy=YES sell=YES rows=74288
[TRAIN][5M] asof=2024-04-01 feats=69 buy=YES sell=YES rows=74459
[TRAIN][5M] asof=2024-04-08 feats=69 buy=YES sell=YES rows=74625
[TRAIN][5M] asof=2024-04-15 feats=69 buy=YES sell=YES rows=74845
[TRAIN][5M] asof=2024-04-22 feats=69 buy=YES sell=YES rows=75004
[TRAIN][5M] asof=2024-04-29 feats=69 buy=YES sell=YES rows=75245
[TRAIN][5M] asof=2024-05-06 feats=69 buy=YES sell=YES rows=75427
[TRAIN][5M] asof=2024-05-13 feats=69 buy=YES sell=YES rows=75572
[TRAIN][5M] asof=2024-05-20 feats=69 buy=YES sell=YES rows=75743
[TRAIN][5M] asof=2024-05-28 feats=69 buy=YES sell=YES rows=75947
[TRAIN][5M] asof=2024-06-03 feats=69 buy=YES sell=YES rows=76116
[TRAIN][5M] asof=2024-06-10 feats=69 buy=YES sell=YES rows=76314
[TRAIN][5M] asof=2024-06-17 feats=69 buy=YES sell=YES rows=76556
[TRAIN][5M] asof=2024-06-24 feats=69 buy=YES sell=YES rows=76698
[TRAIN][5M] asof=2024-07-01 feats=69 buy=YES sell=YES rows=76902
[TRAIN][5M] asof=2024-07-08 feats=69 buy=YES sell=YES rows=77000
[TRAIN][5M] asof=2024-07-15 feats=69 buy=YES sell=YES rows=77209
[TRAIN][5M] asof=2024-07-22 feats=69 buy=YES sell=YES rows=77404
[TRAIN][5M] asof=2024-07-29 feats=69 buy=YES sell=YES rows=77677
[TRAIN][5M] asof=2024-08-05 feats=69 buy=YES sell=YES rows=77848
[TRAIN][5M] asof=2024-08-12 feats=69 buy=YES sell=YES rows=78054
[TRAIN][5M] asof=2024-08-19 feats=69 buy=YES sell=YES rows=78217
[TRAIN][5M] asof=2024-08-26 feats=69 buy=YES sell=YES rows=78369
[TRAIN][5M] asof=2024-09-03 feats=69 buy=YES sell=YES rows=78610
[TRAIN][5M] asof=2024-09-09 feats=69 buy=YES sell=YES rows=78778
[TRAIN][5M] asof=2024-09-16 feats=69 buy=YES sell=YES rows=78929
[TRAIN][5M] asof=2024-09-23 feats=69 buy=YES sell=YES rows=79117
[TRAIN][5M] asof=2024-09-30 feats=69 buy=YES sell=YES rows=79318
[TRAIN][5M] asof=2024-10-07 feats=69 buy=YES sell=YES rows=79508
[TRAIN][5M] asof=2024-10-14 feats=69 buy=YES sell=YES rows=79700
[TRAIN][5M] asof=2024-10-21 feats=69 buy=YES sell=YES rows=79834
[TRAIN][5M] asof=2024-10-28 feats=69 buy=YES sell=YES rows=80032
[TRAIN][5M] asof=2024-11-04 feats=69 buy=YES sell=YES rows=80217
[TRAIN][5M] asof=2024-11-11 feats=69 buy=YES sell=YES rows=80398
[TRAIN][5M] asof=2024-11-18 feats=69 buy=YES sell=YES rows=80585
[TRAIN][5M] asof=2024-11-25 feats=69 buy=YES sell=YES rows=80829
[TRAIN][5M] asof=2024-12-02 feats=69 buy=YES sell=YES rows=80967
[TRAIN][5M] asof=2024-12-09 feats=69 buy=YES sell=YES rows=81115
[TRAIN][5M] asof=2024-12-16 feats=69 buy=YES sell=YES rows=81293
[TRAIN][5M] asof=2024-12-23 feats=69 buy=YES sell=YES rows=81458
[TRAIN][5M] asof=2024-12-30 feats=69 buy=YES sell=YES rows=81625
[TRAIN][5M] asof=2025-01-06 feats=69 buy=YES sell=YES rows=81760
[TRAIN][5M] asof=2025-01-13 feats=69 buy=YES sell=YES rows=81886

,date,p_day,buy_level,sell_level,chosen_action,reward_force_buy,reward_free,reward_force_sell,chosen_reward,best_action_ex_post,oracle_equity,close,buy_th_5m,sell_th_5m
3578,2026-05-07,0.434549,0.305,0.33,FORCE_SELL,-0.051580,0.001741,0.0,0.0,FREE,1.141265e+20,152.4300,-0.5,-0.5
3579,2026-05-08,0.407557,0.305,0.33,FORCE_SELL,0.113694,-0.004800,0.0,0.0,FORCE_BUY,1.271020e+20,178.6700,-0.5,-0.5
3580,2026-05-11,0.430346,0.305,0.33,FORCE_SELL,0.097270,0.082189,0.0,0.0,FORCE_BUY,1.394652e+20,190.5300,-0.5,-0.5
3581,2026-05-12,0.554729,0.305,0.33,FORCE_SELL,-0.068091,-0.005622,0.0,0.0,FORCE_SELL,1.394652e+20,167.6505,-0.5,-0.5
3582,2026-05-13,0.502656,0.305,0.33,FORCE_SELL,0.028616,0.089799,0.0,0.0,FREE,1.519891e+20,188.0000,-0.5,-0.5

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
1595,2026-05-07,3.629903e+08,3.629903e+08,0,-0.5,-0.5,0.434549,FORCE_SELL,0.305,0.33
1596,2026-05-08,3.629903e+08,3.629903e+08,0,-0.5,-0.5,0.407557,FORCE_SELL,0.305,0.33
1597,2026-05-11,3.629903e+08,3.629903e+08,0,-0.5,-0.5,0.430346,FORCE_SELL,0.305,0.33
1598,2026-05-12,3.629903e+08,3.629903e+08,0,-0.5,-0.5,0.554729,FORCE_SELL,0.305,0.33
1599,2026-05-13,3.629903e+08,3.629903e+08,0,-0.5,-0.5,0.502656,FORCE_SELL,0.305,0.33

,side,seen_idx,exec_px,qty,fee,reason,ts,pred,th,gate,pnl,entry_px,entry_idx
0,buy,163608,18.7813,5324.445060,0.0,5m BUY signal,2020-01-07 15:50:00,2.407178,-0.50,FREE,NaN,NaN,NaN
1,sell,163638,18.7847,5324.445060,0.0,5m SELL signal,2020-01-08 06:25:00,27.777378,-0.50,FREE,18.103113,18.7813,163608.0
2,buy,163733,18.7980,5320.677897,0.0,5m BUY signal,2020-01-08 15:45:00,2.382491,1.85,FREE,NaN,NaN,NaN
3,sell,163744,18.9267,5320.677897,0.0,5m SELL signal,2020-01-08 19:10:00,20.199308,-0.50,FREE,684.771245,18.7980,163733.0
4,buy,163772,19.4660,5173.270028,0.0,ADAPTIVE_FORCE_BUY->first acceptable 5m signal,2020-01-09 09:25:00,2.685045,-0.05,FORCE_BUY,NaN,NaN,NaN

In [1]:
from adaptive_reward_checkpoint_fresh import run_adaptive_reward_realtime_from_checkpoint

realtime_res = run_adaptive_reward_realtime_from_checkpoint(
    checkpoint_path="output_adaptive_reward_resumed_fresh_TQQQ_252days_at_2020/final_checkpoint.joblib",
    output_dir="output_adaptive_reward_realtime_TQQQ",
    end_time=None,  # None = now
    initial_capital=100000.0,
    fee_pct=0.0,
    save_snapshot_path="output_adaptive_reward_realtime_TQQQ/final_checkpoint.joblib",
    refresh_data=True,
    verbose=True,
)

print("new checkpoint:", realtime_res["continued_snapshot_path"])
display(realtime_res["trades_df"].tail())
display(realtime_res["daily_log_df"].tail())

[SAVED] output_adaptive_reward_realtime_TQQQ\trades.csv
[SAVED] output_adaptive_reward_realtime_TQQQ\daily_log.csv
[SAVED] output_adaptive_reward_realtime_TQQQ\daily_reward_log.csv
[SAVED] output_adaptive_reward_realtime_TQQQ\equity_vs_buyhold.png
[SAVED] output_adaptive_reward_realtime_TQQQ\price_with_trades.png
[SAVED] output_adaptive_reward_realtime_TQQQ\p_day.png
[CHECKPOINT] saved continued snapshot -> output_adaptive_reward_realtime_TQQQ/final_checkpoint.joblib
new checkpoint: output_adaptive_reward_realtime_TQQQ/final_checkpoint.joblib

Empty DataFrame
Columns: []
Index: []

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
0,2026-05-26,100000.0,100000.0,0,-0.5,-0.5,0.200764,FORCE_BUY,0.24,0.26

In [1]:
from importlib import reload
import adaptive_reward_checkpoint_fresh
reload(adaptive_reward_checkpoint_fresh)

from adaptive_reward_checkpoint_fresh import run_adaptive_reward_yfinance_intraday_loop

live_res = run_adaptive_reward_yfinance_intraday_loop(
    checkpoint_path="output_adaptive_reward_resumed_fresh_TQQQ_252days_at_2020/final_checkpoint.joblib",
    output_dir="output_adaptive_reward_live_TQQQ",
    initial_capital=100000.0,
    fee_pct=0.0,
    save_snapshot_path="output_adaptive_reward_live_TQQQ/live_checkpoint.joblib",
    poll_seconds=60,
    market_close_time="16:00",
    timezone="America/New_York",
    verbose=True,
)

print("latest checkpoint:", live_res["latest_checkpoint_path"])
display(live_res["trades_df"].tail())
display(live_res["daily_log_df"].tail())

[LIVE] advancing through 2026-05-29 16:00:00 EDT
[TRAIN][5M] asof=2026-05-26 feats=69 buy=YES sell=YES rows=121233
[SAVED] output_adaptive_reward_live_TQQQ\trades.csv
[SAVED] output_adaptive_reward_live_TQQQ\daily_log.csv
[SAVED] output_adaptive_reward_live_TQQQ\daily_reward_log.csv
[SAVED] output_adaptive_reward_live_TQQQ\equity_vs_buyhold.png
[SAVED] output_adaptive_reward_live_TQQQ\price_with_trades.png
[SAVED] output_adaptive_reward_live_TQQQ\p_day.png
[CHECKPOINT] saved continued snapshot -> output_adaptive_reward_live_TQQQ/live_checkpoint.joblib
[LIVE] checkpoint -> output_adaptive_reward_live_TQQQ/live_checkpoint.joblib
[LIVE STATUS]
  today's decision: date=2026-05-29 00:00:00 daily_action=FORCE_BUY p_day=0.22061903632875482 buy_level=0.24 sell_level=0.26
  account: date=2026-05-29 00:00:00 equity=100000.0 cash=100000.0 pos=0
  5m model: buy_th=-0.5 sell_th=-0.5
  last trading decision: None
[LIVE] reached market close 2026-05-29 16:00:00 EDT
latest checkpoint: output_adaptive_reward_live_TQQQ/live_checkpoint.joblib

Empty DataFrame
Columns: []
Index: []

,date,equity,cash,pos,buy_th,sell_th,p_day,daily_action,daily_buy_level,daily_sell_level
0,2026-05-26,100000.0,100000.0,0,-0.5,-0.5,0.200764,FORCE_BUY,0.24,0.26
1,2026-05-27,100000.0,100000.0,0,-0.5,-0.5,0.215126,FORCE_BUY,0.24,0.26
2,2026-05-28,100000.0,100000.0,0,-0.5,-0.5,0.209231,FORCE_BUY,0.24,0.26
3,2026-05-29,100000.0,100000.0,0,-0.5,-0.5,0.220619,FORCE_BUY,0.24,0.26